'use client';

import { SafeImage } from '@/components/ui/safe-image';
import type { FormEvent } from 'react';
import { useState, useMemo, useCallback } from 'react';
import { Button } from './button';
import { Textarea } from './textarea';
import { cn } from '@/lib/utils';
import {
  Search,
  Plus,
  Trash2,
  Edit3,
  X,
  BookOpen,
  CheckCircle2,
  Circle,
  Download,
} from 'lucide-react';
import { CorkboardInvestigationBoard } from './journal/corkboard-investigation-board';
import { DiscoveriesView } from './journal/discoveries-view';
import { InspectionLightboxModal } from '../dialogs/inspection-lightbox-modal';
import { EvidenceNode, EvidenceRelation, InvestigatorBoardState, BoardViewport } from '@/types/investigator-board';
import { convertEntriesToBoardNodes } from '@/lib/journal/convert-entries';
import type { JournalEntry, JournalEventType, Character } from '@/lib/types';

// Ponieważ w nowym dzienniku PoE używamy szerszych typów zakładek
export type JournalEntryType =
  | 'board'
  | 'quest'
  | 'journal'
  | 'location'
  | 'npc'
  | 'item'
  | 'note';

export interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  dateCompleted?: string;
  gameDay?: number;
  gameHour?: number;
}

// Rozszerzenie typu JournalEntry na potrzeby nowego systemu misji i zakładek
export interface ExtendedJournalEntry extends Omit<
  JournalEntry,
  'type' | 'isBookmarked' | 'timestamp'
> {
  timestamp?: Date;
  type: JournalEntryType | JournalEventType;
  category?: string;
  isAutoGenerated?: boolean;
  isBookmarked?: boolean;
  questStatus?: 'active' | 'completed' | 'failed';
  objectives?: QuestObjective[];
  gameDay?: number;
  gameHour?: number;
}

interface SessionJournalProps {
  character: Character;
  onUpdateCharacter: (character: Character) => void;
  onClose: () => void;
  currentInGameDate?: string;
  sharedJournal?: JournalEntry[];
  onUpdateSharedJournal?: (journal: JournalEntry[]) => void;
  participantNames?: string[];
}

const categories = [
  'Wydarzenia',
  'Odkrycia',
  'Spotkania',
  'Walka',
  'Badania',
  'Sny',
  'Wizje',
  'Notatki',
  'Inne',
];

const defaultTags = [
  'Cthulhu',
  'Kult',
  'Koszmary',
  'Badania',
  'Walka',
  'Tajemnice',
  'NPC',
  'Lokalizacje',
  'Artefakty',
  'Zaklęcia',
];

export function SessionJournal({
  character,
  onUpdateCharacter,
  onClose,
  currentInGameDate,
  sharedJournal,
  onUpdateSharedJournal,
  participantNames = [],
}: SessionJournalProps) {
  const [activeTab, setActiveTab] = useState<JournalEntryType>('board');
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingEntry, setEditingEntry] = useState<ExtendedJournalEntry | null>(
    null
  );
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedQuestId, setSelectedQuestId] = useState<string | null>(null);
  const [encyclopediaSubTab, setEncyclopediaSubTab] = useState<
    'location' | 'character' | 'item'
  >('character');

  // Stan Tablicy Badacza z automatycznym odtworzeniem z postaci / sharedJournal
  const savedBoardState = character.investigatorBoard;

  const initialNodes = useMemo(() => {
    if (savedBoardState?.nodes && savedBoardState.nodes.length > 0) {
      return savedBoardState.nodes;
    }
    // Domyślnie pusta tablica - gracz sam przypina poszlaki ze Szuflady.
    return [];
  }, [savedBoardState]);

  const [boardNodes, setBoardNodes] = useState<EvidenceNode[]>(initialNodes);
  const [boardRelations, setBoardRelations] = useState<EvidenceRelation[]>(
    savedBoardState?.relations || []
  );
  const [boardViewport, setBoardViewport] = useState<BoardViewport>(
    savedBoardState?.viewport || { zoom: 1, panX: 0, panY: 0 }
  );
  const [inspectedNode, setInspectedNode] = useState<EvidenceNode | null>(null);

  // Funkcja pomocnicza zapisująca zaktualizowaną tablicę badacza do postaci
  const syncInvestigatorBoard = useCallback(
    (nodes: EvidenceNode[], relations: EvidenceRelation[]) => {
      const updatedBoardState: InvestigatorBoardState = {
        characterId: character.id,
        nodes,
        relations,
        lastUpdated: new Date().toISOString(),
      };

      onUpdateCharacter({
        ...character,
        investigatorBoard: updatedBoardState,
      });
    },
    [character, onUpdateCharacter]
  );

  const handleUpdateNodes = useCallback(
    (nodes: EvidenceNode[]) => {
      setBoardNodes(nodes);
      syncInvestigatorBoard(nodes, boardRelations);
    },
    [boardRelations, syncInvestigatorBoard]
  );

  const handleUpdateRelations = useCallback(
    (relations: EvidenceRelation[]) => {
      setBoardRelations(relations);
      syncInvestigatorBoard(boardNodes, relations);
    },
    [boardNodes, syncInvestigatorBoard]
  );

  const isShared = sharedJournal !== undefined;

  // Duet czyta scalony dziennik przygody, solo zachowuje dziennik postaci.
  const entries = useMemo(() => {
    const rawEntries = (sharedJournal ??
      character.journal ??
      []) as unknown as ExtendedJournalEntry[];
    return rawEntries.map((entry) => ({
      ...entry,
      type: entry.type || 'journal', // Domyślnie starsze wpisy stają się częścią kroniki
    })) as ExtendedJournalEntry[];
  }, [character.journal, sharedJournal]);

  const updateCharacterJournal = useCallback(
    (newEntries: ExtendedJournalEntry[]) => {
      if (onUpdateSharedJournal) {
        onUpdateSharedJournal(newEntries as unknown as JournalEntry[]);
        return;
      }
      onUpdateCharacter({
        ...character,
        journal: newEntries as unknown as JournalEntry[],
      });
    },
    [character, onUpdateCharacter, onUpdateSharedJournal]
  );

  const addEntry = (entry: Omit<ExtendedJournalEntry, 'id' | 'timestamp'>) => {
    const newEntry: ExtendedJournalEntry = {
      ...entry,
      id: `journal_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`,
      timestamp: new Date(),
      inGameDate: entry.inGameDate || currentInGameDate,
    };
    const updatedEntries = [newEntry, ...entries];
    updateCharacterJournal(updatedEntries);
    setShowAddForm(false);
  };

  const updateEntry = (updatedEntry: ExtendedJournalEntry) => {
    const updatedEntries = entries.map((entry) =>
      entry.id === updatedEntry.id
        ? { ...updatedEntry, updatedAt: new Date() }
        : entry
    );
    updateCharacterJournal(updatedEntries);
    setEditingEntry(null);
  };

  const deleteEntry = (id: string) => {
    if (!confirm('Czy na pewno chcesz usunąć ten wpis z księgi przygód?'))
      return;
    const updatedEntries = entries.filter((entry) => entry.id !== id);
    updateCharacterJournal(updatedEntries);
    if (selectedQuestId === id) {
      setSelectedQuestId(null);
    }
  };

  // Śledzenie nieprzeczytanych wpisów w konkretnych zakładkach
  const journalSeenKey = isShared
    ? `unseen_journal_detail_${[...participantNames].sort().join('_')}`
    : character
      ? `unseen_detail_${character.id}`
      : null;

  const unseenCounts = useMemo(() => {
    if (!journalSeenKey) return { quest: 0, journal: 0, encyclopedia: 0, note: 0 };
    const stored = localStorage.getItem(journalSeenKey);
    const seenData = stored ? JSON.parse(stored) : { quest: 0, journal: 0, encyclopedia: 0, note: 0 };
    
    // Liczymy wpisy każdego typu
    const questCount = entries.filter(e => e.type === 'quest').length;
    const journalCount = entries.filter(e => e.type === 'journal').length;
    const encyclopediaCount = entries.filter(e => 
      ['npc', 'location', 'item'].includes(e.type)
    ).length;
    const noteCount = entries.filter(e => e.type === 'note').length;

    return {
      quest: Math.max(0, questCount - (seenData.quest || 0)),
      journal: Math.max(0, journalCount - (seenData.journal || 0)),
      encyclopedia: Math.max(0, encyclopediaCount - (seenData.encyclopedia || 0)),
      note: Math.max(0, noteCount - (seenData.note || 0)),
    };
  }, [entries, journalSeenKey]);

  // Resetowanie powiadomień dla danej zakładki po jej aktywacji
  const markTabAsSeen = useCallback((tab: JournalEntryType) => {
    if (!journalSeenKey) return;
    const stored = localStorage.getItem(journalSeenKey);
    const seenData = stored ? JSON.parse(stored) : { quest: 0, journal: 0, encyclopedia: 0, note: 0 };
    
    const questCount = entries.filter(e => e.type === 'quest').length;
    const journalCount = entries.filter(e => e.type === 'journal').length;
    const encyclopediaCount = entries.filter(e => 
      ['npc', 'location', 'item'].includes(e.type)
    ).length;
    const noteCount = entries.filter(e => e.type === 'note').length;

    if (tab === 'quest') seenData.quest = questCount;
    else if (tab === 'journal') seenData.journal = journalCount;
    else if (tab === 'npc' || tab === 'location' || tab === 'item') {
      seenData.encyclopedia = encyclopediaCount;
    }
    else if (tab === 'note') seenData.note = noteCount;

    localStorage.setItem(journalSeenKey, JSON.stringify(seenData));
  }, [entries, journalSeenKey]);

  // Uruchomienie resetu dla domyślnej zakładki przy otwarciu
  useState(() => {
    markTabAsSeen(activeTab);
  });

  const handleTabChange = (tab: JournalEntryType) => {
    setActiveTab(tab);
    markTabAsSeen(tab);
    if (tab === 'quest') {
      setSelectedQuestId(null);
    }
  };

  // Filtrowanie wpisów według wyszukiwania i typu
  const filteredEntries = useMemo(() => {
    return entries.filter((entry) => {
      // Dopasowanie do zakładki
      if (activeTab === 'quest' && entry.type !== 'quest') return false;
      if (activeTab === 'journal' && entry.type !== 'journal') return false;
      if (activeTab === 'note' && entry.type !== 'note') return false;
      if (activeTab === 'npc') {
        if (
          entry.type !== 'npc' &&
          entry.type !== 'location' &&
          entry.type !== 'item'
        ) {
          return false;
        }

        // Sprawdzamy podzakładkę encyklopedii
        if (
          encyclopediaSubTab === 'character' &&
          entry.type !== 'npc'
        )
          return false;
        if (
          encyclopediaSubTab === 'location' &&
          entry.type !== 'location'
        )
          return false;
        if (encyclopediaSubTab === 'item' && entry.type !== 'item')
          return false;
      }

      // Dopasowanie do wyszukiwania
      if (!searchQuery) return true;
      const query = searchQuery.toLowerCase();
      return (
        entry.title.toLowerCase().includes(query) ||
        entry.content.toLowerCase().includes(query) ||
        (entry.tags &&
          entry.tags.some((tag) => tag.toLowerCase().includes(query)))
      );
    });
  }, [entries, activeTab, encyclopediaSubTab, searchQuery]);

  const activeQuests = useMemo(
    () =>
      filteredEntries.filter(
        (e) => e.questStatus === 'active' || !e.questStatus
      ),
    [filteredEntries]
  );
  const completedQuests = useMemo(
    () => filteredEntries.filter((e) => e.questStatus === 'completed'),
    [filteredEntries]
  );
  const failedQuests = useMemo(
    () => filteredEntries.filter((e) => e.questStatus === 'failed'),
    [filteredEntries]
  );

  const selectedQuest = useMemo(() => {
    return (
      filteredEntries.find((e) => e.id === selectedQuestId) ||
      filteredEntries[0]
    );
  }, [filteredEntries, selectedQuestId]);

  // Eksport Dziennika do pliku Markdown (Pure Helper / Local Download)
  const exportToMarkdown = useCallback(() => {
    const owner = isShared ? participantNames.join(' i ') : character.name;
    let md = `# 📖 Dziennik Przygody${owner ? `: ${owner}` : ''}\n\n`;
    md += `*Eksport: ${new Date().toLocaleString('pl-PL')}*\n\n---\n\n`;

    const quests = entries.filter((e) => e.type === 'quest');
    if (quests.length > 0) {
      md += `## ⚔️ Misje i Zadania\n\n`;
      quests.forEach((q) => {
        const status =
          q.questStatus === 'completed'
            ? '🟢 UKOŃCZONE'
            : q.questStatus === 'failed'
              ? '🔴 NIEUDANE'
              : '🟡 AKTYWNE';
        md += `### ${q.title} [${status}]\n`;
        if (q.inGameDate)
          md += `*Czas w grze: ${q.inGameDate} (Dzień ${q.gameDay || 1}, godz. ${q.gameHour || 12})*\n\n`;
        md += `${q.content}\n\n`;
        if (q.objectives && q.objectives.length > 0) {
          md += `**Cele:**\n`;
          q.objectives.forEach((obj) => {
            md += `- [${obj.completed ? 'x' : ' '}] ${obj.description}${obj.completed && obj.dateCompleted ? ` (Ukończono: ${obj.dateCompleted})` : ''}\n`;
          });
          md += `\n`;
        }
        md += `---\n\n`;
      });
    }

    const journalEntries = entries.filter((e) => e.type === 'journal');
    if (journalEntries.length > 0) {
      md += `## 📔 Kronika Wydarzeń\n\n`;
      journalEntries.forEach((e) => {
        md += `### ${e.title}\n`;
        const formattedDate = e.inGameDate || (e.timestamp ? new Date(e.timestamp).toLocaleDateString('pl-PL') : '');
        md += `*Data: ${formattedDate}*\n\n`;
        md += `${e.content}\n\n`;
        if (e.tags && e.tags.length > 0) {
          md += `*Tagi: ${e.tags.map((t) => `#${t}`).join(', ')}*\n\n`;
        }
        md += `---\n\n`;
      });
    }

    const encProps = entries.filter((e) =>
      [
        'npc',
        'location',
        'item',
      ].includes(e.type)
    );
    if (encProps.length > 0) {
      md += `## 📚 Encyklopedia Wiedzy\n\n`;
      encProps.forEach((e) => {
        const typeLabel =
          e.type === 'npc'
            ? 'Postać'
            : e.type === 'location'
              ? 'Lokacja'
              : 'Przedmiot';
        md += `### ${e.title} [${typeLabel}]\n\n`;
        md += `${e.content}\n\n`;
        md += `---\n\n`;
      });
    }

    const notes = entries.filter((e) => e.type === 'note');
    if (notes.length > 0) {
      md += `## 📝 Notatki i Teorie\n\n`;
      notes.forEach((e) => {
        md += `### ${e.title}\n`;
        const formattedNoteDate = e.timestamp ? new Date(e.timestamp).toLocaleDateString('pl-PL') : '';
        md += `*Zapisano: ${formattedNoteDate}*\n\n`;
        md += `${e.content}\n\n`;
        md += `---\n\n`;
      });
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute(
      'download',
      isShared
        ? 'dziennik_przygody_duet.md'
        : `dziennik_sesji_${character.name.replace(/\s+/g, '_').toLowerCase()}.md`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [character.name, entries, isShared, participantNames]);

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-md flex items-center justify-center z-50 p-4">
      {/* RPG-styled Container */}
      <div className="bg-zinc-950/90 backdrop-blur-xl border-4 border-emerald-900/40 rounded-xl shadow-2xl w-[85vw] max-w-[85vw] h-[85vh] flex flex-col overflow-hidden text-zinc-300">
        {/* Nagłówek i Główne Zakładki */}
        <div className="bg-zinc-900/80 border-b-2 border-emerald-900/50 px-6 py-3 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-3">
            <BookOpen className="h-7 w-7 text-emerald-400" />
            <div>
              <h2 className="font-display-decorative font-black text-2xl tracking-[0.12em] text-emerald-500 drop-shadow-md">
                DZIENNIK SESJI
              </h2>
              {isShared && participantNames.length > 0 && (
                <p className="text-xs font-special-elite tracking-wider text-emerald-400">
                  Wspólny dla: {participantNames.join(' i ')}
                </p>
              )}
            </div>
          </div>

          {/* Zakładki na górze - Styl Akt / Segregatora */}
          <div className="flex gap-1 self-end translate-y-[2px] mt-2 md:mt-0">
            <button
              onClick={() => handleTabChange('board')}
              className={cn(
                'px-5 py-2 text-sm font-serif font-bold rounded-t-lg transition-all relative flex items-center gap-2 border-x-2 border-t-2',
                activeTab === 'board'
                  ? 'bg-zinc-950 text-emerald-500 border-emerald-900/50 border-b-transparent z-10 pt-3 shadow-[0_-4px_10px_rgba(0,0,0,0.5)]'
                  : 'bg-zinc-900/80 text-muted-foreground/60 border-emerald-900/50 border-b-emerald-900/50 hover:text-emerald-500 hover:bg-emerald-500/5'
              )}
            >
              📌 Tablica Badacza
            </button>
            <button
              onClick={() => handleTabChange('npc')}
              className={cn(
                'px-5 py-2 text-sm font-serif font-bold rounded-t-lg transition-all relative flex items-center gap-2 border-x-2 border-t-2',
                (activeTab === 'npc' || activeTab === 'location' || activeTab === 'item' || activeTab === 'quest')
                  ? 'bg-zinc-950 text-emerald-500 border-emerald-900/50 border-b-transparent z-10 pt-3 shadow-[0_-4px_10px_rgba(0,0,0,0.5)]'
                  : 'bg-zinc-900/80 text-muted-foreground/60 border-emerald-900/50 border-b-emerald-900/50 hover:text-emerald-500 hover:bg-emerald-500/5'
              )}
            >
              🔍 Odkrycia
              {(unseenCounts.encyclopedia + unseenCounts.quest) > 0 && (
                <span className="bg-red-500 text-white text-[10px] font-bold rounded-full w-4 h-4 flex items-center justify-center">
                  {unseenCounts.encyclopedia + unseenCounts.quest}
                </span>
              )}
            </button>
            <button
              onClick={() => handleTabChange('journal')}
              className={cn(
                'px-5 py-2 text-sm font-serif font-bold rounded-t-lg transition-all relative flex items-center gap-2 border-x-2 border-t-2',
                activeTab === 'journal'
                  ? 'bg-zinc-950 text-emerald-500 border-emerald-900/50 border-b-transparent z-10 pt-3 shadow-[0_-4px_10px_rgba(0,0,0,0.5)]'
                  : 'bg-zinc-900/80 text-muted-foreground/60 border-emerald-900/50 border-b-emerald-900/50 hover:text-emerald-500 hover:bg-emerald-500/5'
              )}
            >
              Kronika
              {unseenCounts.journal > 0 && (
                <span className="bg-red-500 text-white text-[10px] font-bold rounded-full w-4 h-4 flex items-center justify-center">
                  {unseenCounts.journal}
                </span>
              )}
            </button>
            <button
              onClick={() => handleTabChange('note')}
              className={cn(
                'px-5 py-2 text-sm font-serif font-bold rounded-t-lg transition-all relative flex items-center gap-2 border-x-2 border-t-2',
                activeTab === 'note'
                  ? 'bg-zinc-950 text-emerald-500 border-emerald-900/50 border-b-transparent z-10 pt-3 shadow-[0_-4px_10px_rgba(0,0,0,0.5)]'
                  : 'bg-zinc-900/80 text-muted-foreground/60 border-emerald-900/50 border-b-emerald-900/50 hover:text-emerald-500 hover:bg-emerald-500/5'
              )}
            >
              Notatki
              {unseenCounts.note > 0 && (
                <span className="bg-red-500 text-white text-[10px] font-bold rounded-full w-4 h-4 flex items-center justify-center">
                  {unseenCounts.note}
                </span>
              )}
            </button>
          </div>

          {/* Narzędzia i Przyciski */}
          <div className="flex gap-2 items-center">
            <Button
              onClick={() => setShowAddForm(true)}
              className="bg-emerald-900/50 hover:bg-emerald-800/60 text-emerald-100 border border-emerald-500/40 font-serif"
            >
              <Plus className="h-4 w-4 mr-1" /> Dodaj notatkę
            </Button>
            <Button
              onClick={() => {
                import('@/lib/test-journal-data').then(({ MOCK_JOURNAL_ENTRIES, MOCK_BOARD_NODES, MOCK_BOARD_RELATIONS }) => {
                  updateCharacterJournal([...MOCK_JOURNAL_ENTRIES, ...entries]);
                  setBoardNodes(MOCK_BOARD_NODES);
                  setBoardRelations(MOCK_BOARD_RELATIONS);
                });
              }}
              className="bg-emerald-900/60 hover:bg-emerald-800/70 text-emerald-400 border border-emerald-500/40 font-serif text-xs"
              title="Wypełnij dziennik przykładowymi wpisami testowymi"
            >
              🧪 Wypełnij testowo
            </Button>
            <Button
              onClick={exportToMarkdown}
              className="bg-emerald-800/80 hover:bg-emerald-700/80 text-emerald-100 border border-emerald-500/40 font-serif"
            >
              <Download className="h-4 w-4 mr-1" /> Eksport MD
            </Button>
            {onClose && (
              <button
                onClick={onClose}
                className="ml-3 p-2 bg-[#4a1c1c] hover:bg-[#632525] rounded-md border border-[#942c2c] text-emerald-100 transition-colors"
                title="Zamknij dziennik"
              >
                <X className="h-5 w-5" />
              </button>
            )}
          </div>
        </div>

        {/* Wyszukiwarka */}
        <div className="bg-[#18100b] border-b border-emerald-900/30 px-6 py-2.5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center bg-zinc-950 rounded-md px-3 py-1.5 w-full sm:max-w-md border border-emerald-900/30">
            <Search className="h-4 w-4 text-[#8a7667] mr-2" />
            <input
              type="text"
              placeholder="Wyszukaj frazę..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-transparent text-sm w-full outline-none text-zinc-300 placeholder-emerald-900/60"
            />
          </div>
        </div>

        <div className="flex-1 flex overflow-hidden relative bg-gradient-to-br from-[#1a1610] to-[#100d09] text-zinc-300 journal-scroll">
          {/* 0. SEKCJA TABLICY BADACZA */}
          {activeTab === 'board' && (
            <div className="flex-1 flex flex-col overflow-hidden journal-scroll">
              <CorkboardInvestigationBoard
                nodes={boardNodes}
                relations={boardRelations}
                onUpdateNodes={handleUpdateNodes}
                onUpdateRelations={handleUpdateRelations}
                viewport={boardViewport}
                onUpdateViewport={(v) => {
                  setBoardViewport(v);
                  syncInvestigatorBoard(boardNodes, boardRelations);
                }}
                journalEntries={entries.map((e) => ({
                  id: e.id,
                  title: e.title,
                  content: e.content,
                  type: e.type,
                  imageUrl: (e as unknown as Record<string, string>).imageUrl,
                }))}
                equipmentItems={(character.equipment ?? []).map((e) => ({
                  id: e.id,
                  name: e.name,
                  description: e.description || '',
                  imageUrl: e.imageUrl,
                }))}
                onInspectNode={(node) => setInspectedNode(node)}
              />
            </div>
          )}

          {/* Inspection Lightbox Modal */}
          {inspectedNode && (
            <InspectionLightboxModal
              node={inspectedNode}
              onClose={() => setInspectedNode(null)}
              onUpdateNode={(updatedNode) => {
                const updatedNodes = boardNodes.map((n) => n.id === updatedNode.id ? updatedNode : n);
                handleUpdateNodes(updatedNodes);
                setInspectedNode(updatedNode);
              }}
              onDeleteNode={(nodeId) => {
                handleUpdateNodes(boardNodes.filter((n) => n.id !== nodeId));
                handleUpdateRelations(boardRelations.filter((r) => r.fromNodeId !== nodeId && r.toNodeId !== nodeId));
                setInspectedNode(null);
              }}
            />
          )}

          {/* 1. SEKCJA ODKRYĆ (dawne Misje + Encyklopedia) */}
          {(activeTab === 'quest' || activeTab === 'npc' || activeTab === 'location' || activeTab === 'item') && (
            <DiscoveriesView
              entries={(entries as unknown as Array<{ id: string; title: string; content: string; type: string; tags?: string[]; imageUrl?: string; imageStatus?: string; inGameDate?: string; timestamp?: number; questStatus?: 'active' | 'completed' | 'failed'; objectives?: Array<{ id: string; description: string; completed?: boolean; dateCompleted?: string }> }>).filter(
                (e) => ['quest', 'npc', 'location', 'item'].includes(e.type)
              )}
              onEditEntry={(entry) => setEditingEntry(entry as unknown as ExtendedJournalEntry)}
              onDeleteEntry={deleteEntry}
              searchQuery={searchQuery}
            />
          )}

          {/* 2. SEKCJA KRONIKI */}
          {activeTab === 'journal' && (
            <div className="flex-1 overflow-y-auto journal-scroll p-6 bg-[#18120c] space-y-6">
              <div className="max-w-4xl mx-auto space-y-4">
                <div className="flex justify-between items-center border-b border-emerald-900/30 pb-2">
                  <h3 className="text-xl font-serif font-bold text-emerald-100">
                    Chronologia Wydarzeń
                  </h3>
                  <span className="text-sm text-[#8a7667]">
                    {filteredEntries.length} wpisów
                  </span>
                </div>

                <div className="relative border-l-2 border-emerald-500/40 pl-6 ml-4 space-y-6">
                  {filteredEntries.map((entry) => (
                    <div key={entry.id} className="relative">
                      {/* Oś czasu */}
                      <span className="absolute -left-[31px] top-1 bg-[#bfa15f] border-4 border-zinc-950 rounded-full h-4 w-4"></span>

                      <div className="bg-[#120905] border border-emerald-900/30 rounded-lg p-4 shadow-sm hover:shadow-md transition-all">
                        <div className="flex justify-between items-start">
                          <div>
                            <h4 className="text-lg font-serif font-bold text-emerald-100 flex items-center gap-2">
                              {entry.title}
                              {entry.isAutoGenerated && (
                                <span className="text-[10px] bg-emerald-900/70 text-emerald-100 border border-emerald-500/30 px-1.5 py-0.5 rounded uppercase font-sans">
                                  Auto
                                </span>
                              )}
                            </h4>
                            <div className="text-xs text-[#8a7667] mt-0.5 flex gap-3">
                              <span>
                                📅{' '}
                                {entry.inGameDate ||
                                  (entry.timestamp
                                    ? new Date(entry.timestamp).toLocaleDateString('pl-PL')
                                    : '')}
                              </span>
                              {entry.gameDay && (
                                <span>⏳ Dzień {entry.gameDay}</span>
                              )}
                              {entry.category && (
                                <span>📁 Kategoria: {entry.category}</span>
                              )}
                            </div>
                          </div>

                          <div className="flex gap-1">
                            <button
                              onClick={() => setEditingEntry(entry)}
                              className="p-1 text-emerald-100 hover:bg-emerald-900/60 rounded transition-colors"
                            >
                              <Edit3 className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => deleteEntry(entry.id)}
                              className="p-1 text-[#ff6b6b] hover:bg-[#2b1010] rounded transition-colors"
                            >
                              <Trash2 className="h-4 w-4" />
                            </button>
                          </div>
                        </div>

                        {entry.imageStatus === 'pending' ? (
                          <div className="mt-3 my-2 h-44 rounded border border-emerald-500/30 bg-zinc-950 p-4 flex flex-col items-center justify-center gap-2 text-emerald-400">
                            <div className="w-6 h-6 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
                            <span className="text-xs font-serif italic">Malowanie ilustracji...</span>
                          </div>
                        ) : entry.imageUrl ? (
                          <div className="mt-3 my-2 max-h-48 overflow-hidden rounded border border-emerald-500/30 bg-zinc-950 p-1">
                            <SafeImage
                              src={entry.imageUrl}
                              alt={entry.title}
                              className="w-full h-44 object-cover rounded"
                            />
                          </div>
                        ) : null}
                        <p className="text-sm mt-2 whitespace-pre-wrap font-serif text-zinc-300">
                          {entry.content}
                        </p>

                        {entry.tags && entry.tags.length > 0 && (
                          <div className="flex gap-1 mt-2.5 flex-wrap">
                            {entry.tags.map((tag) => (
                              <span
                                key={tag}
                                className="text-[11px] bg-emerald-900/60 text-emerald-100 px-2 py-0.5 rounded border border-emerald-500/30"
                              >
                                #{tag}
                              </span>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}

                  {filteredEntries.length === 0 && (
                    <div className="text-center py-12 text-[#8a7667] italic font-serif">
                      Kronika jest pusta. Wpisy z przygód pojawią się tutaj
                      chronologicznie.
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* 4. SEKCJA NOTATEK */}
          {activeTab === 'note' && (
            <div className="flex-1 overflow-y-auto journal-scroll p-6 bg-[#18120c]">
              <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                {filteredEntries.map((entry) => (
                  <div
                    key={entry.id}
                    className="bg-[#f0e6d2] border-[8px] border-[#f0e6d2] border-b-[24px] hover:scale-[1.02] hover:-rotate-1 transition-transform shadow-xl rounded-sm p-0 flex flex-col justify-between min-h-[220px] group relative text-[#2a1b12]"
                    style={{ transform: `rotate(${Math.random() * 4 - 2}deg)` }}
                  >
                    {/* Przypinka */}
                    <div className="absolute -top-[16px] left-1/2 -translate-x-1/2 w-4 h-4 rounded-full bg-[#8a1c1c] shadow-[inset_-2px_-2px_4px_rgba(0,0,0,0.5),2px_2px_4px_rgba(0,0,0,0.4)] z-10 border border-[#4a0c0c]">
                      <div className="absolute top-[2px] left-[2px] w-1.5 h-1.5 rounded-full bg-white/40"></div>
                    </div>
                    
                    <div className="h-full flex flex-col">
                      {entry.imageStatus === 'pending' ? (
                        <div className="h-40 bg-[#d8cbb5] p-4 flex flex-col items-center justify-center gap-2 text-[#5c4a3d] border border-[#d8cbb5] shadow-inner mb-3">
                          <div className="w-5 h-5 border-2 border-[#5c4a3d] border-t-transparent rounded-full animate-spin"></div>
                          <span className="text-xs font-serif italic">Wywyoływanie...</span>
                        </div>
                      ) : entry.imageUrl ? (
                        <div className="h-40 overflow-hidden bg-[#111] mb-3 relative shadow-[inset_0_0_10px_rgba(0,0,0,0.5)]">
                          <SafeImage
                            src={entry.imageUrl}
                            alt={entry.title}
                            className="w-full h-full object-cover mix-blend-multiply sepia-[0.3]"
                          />
                        </div>
                      ) : (
                        <div className="h-4 bg-[#e6d9c3] mb-3 shadow-inner opacity-50"></div>
                      )}
                      
                      <div className="px-2 flex-1 flex flex-col">
                        <div className="flex justify-between items-start pb-1 mb-2">
                          <h4 className="font-serif font-bold text-lg text-[#2a1b12] leading-snug underline decoration-1 underline-offset-4 decoration-[#8a7667]/40">
                            {entry.title}
                          </h4>
                          <div className="flex gap-1 flex-none ml-2 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button
                              onClick={() => setEditingEntry(entry)}
                              className="p-1 text-[#5c4a3d] hover:text-[#2a1b12] hover:bg-[#d8cbb5] rounded transition-colors"
                              title="Edytuj notatkę"
                            >
                              <Edit3 className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => deleteEntry(entry.id)}
                              className="p-1 text-[#8a1c1c]/70 hover:text-[#8a1c1c] hover:bg-[#ffcccc] rounded transition-colors"
                              title="Usuń notatkę"
                            >
                              <Trash2 className="h-4 w-4" />
                            </button>
                          </div>
                        </div>
                        
                        <p className="text-sm font-serif italic leading-relaxed text-[#4a3525] whitespace-pre-wrap flex-1 pb-2">
                          {entry.content}
                        </p>

                        <div className="text-[10px] text-[#5c4a3d]/80 pt-2 flex justify-between items-end font-special-elite absolute bottom-[-18px] left-2 right-2">
                          <span>
                            {entry.inGameDate ||
                              (entry.timestamp
                                ? new Date(entry.timestamp).toLocaleDateString('pl-PL')
                                : '')}
                          </span>
                          {entry.tags && entry.tags.length > 0 && (
                            <div className="flex gap-1 flex-wrap justify-end">
                              {entry.tags.slice(0, 2).map((tag) => (
                                <span
                                  key={tag}
                                  className="text-[9px] uppercase tracking-wider"
                                >
                                  #{tag}
                                </span>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}

                {filteredEntries.length === 0 && (
                  <div className="col-span-full text-center py-16 text-[#8a7667] italic font-serif">
                    Brak własnych zapisków. Dodaj nową notatkę.
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Formularze dialogowe */}
      {showAddForm && (
        <AddEntryForm
          onAdd={addEntry}
          onCancel={() => setShowAddForm(false)}
          categories={categories}
          defaultTags={defaultTags}
          initialType={activeTab}
        />
      )}

      {editingEntry && (
        <EditEntryForm
          entry={editingEntry}
          onUpdate={updateEntry}
          onCancel={() => setEditingEntry(null)}
        />
      )}
    </div>
  );
}

// ============================================================================
// FORMULARZE POMOCNICZE
// ============================================================================

interface AddEntryFormProps {
  onAdd: (entry: Omit<ExtendedJournalEntry, 'id' | 'timestamp'>) => void;
  onCancel: () => void;
  categories: string[];
  defaultTags: string[];
  initialType: JournalEntryType;
}

function AddEntryForm({
  onAdd,
  onCancel,
  categories,
  defaultTags,
  initialType,
}: AddEntryFormProps) {
  const [formData, setFormData] = useState({
    title: '',
    content: '',
    category: categories[0],
    tags: [] as string[],
    isAutoGenerated: false,
    type: (['quest', 'journal', 'npc', 'location', 'item', 'note'].includes(initialType)
      ? initialType
      : 'note') as JournalEntryType,
    gameDay: 1,
    gameHour: 12,
    questStatus: 'active' as 'active' | 'completed' | 'failed',
    objectives: [] as QuestObjective[],
  });
  const [newTag, setNewTag] = useState('');
  const [newObjective, setNewObjective] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (formData.title.trim() && formData.content.trim()) {
      onAdd(formData);
    }
  };

  const addTag = (tag: string) => {
    if (tag.trim() && !formData.tags.includes(tag.trim())) {
      setFormData({ ...formData, tags: [...formData.tags, tag.trim()] });
      setNewTag('');
    }
  };

  const removeTag = (tagToRemove: string) => {
    setFormData({
      ...formData,
      tags: formData.tags.filter((tag) => tag !== tagToRemove),
    });
  };

  const addObjective = () => {
    if (newObjective.trim()) {
      const obj: QuestObjective = {
        id: Date.now().toString() + Math.random().toString(36).substring(2, 5),
        description: newObjective.trim(),
        completed: false,
        gameDay: formData.gameDay,
        gameHour: formData.gameHour,
      };
      setFormData({ ...formData, objectives: [...formData.objectives, obj] });
      setNewObjective('');
    }
  };

  const removeObjective = (id: string) => {
    setFormData({
      ...formData,
      objectives: formData.objectives.filter((o) => o.id !== id),
    });
  };

  return (
    <div className="fixed inset-0 bg-black/85 flex items-center justify-center z-[60] p-4">
      <div className="bg-[#1c120c] border-4 border-emerald-900/30 rounded-xl p-6 w-[90vw] max-w-[800px] max-h-[90vh] overflow-y-auto journal-scroll text-zinc-300 font-serif shadow-2xl">
        <div className="flex justify-between items-center border-b border-emerald-900/30 pb-3 mb-5">
          <h3 className="text-xl font-bold text-emerald-100">
            Dodaj nowy wpis do księgi przygód
          </h3>
          <button
            onClick={onCancel}
            className="text-[#a29182] hover:text-emerald-100"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Typ wpisu
            </label>
            <select
              value={formData.type}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  type: e.target.value as JournalEntryType,
                })
              }
              className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
            >
              <option value="quest">Misja (Quest)</option>
              <option value="journal">Wpis do Dziennika (Kronika)</option>
              <option value="npc">
                Encyklopedia - Postać / Byt
              </option>
              <option value="location">
                Encyklopedia - Lokacja
              </option>
              <option value="item">
                Encyklopedia - Przedmiot
              </option>
              <option value="note">Własna notatka / Teoria</option>
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Dzień kampanii
              </label>
              <input
                type="number"
                min="1"
                value={formData.gameDay}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    gameDay: parseInt(e.target.value) || 1,
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Godzina
              </label>
              <input
                type="number"
                min="0"
                max="23"
                value={formData.gameHour}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    gameHour: parseInt(e.target.value) || 0,
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              />
            </div>
          </div>

          {formData.type === 'quest' && (
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Status misji
              </label>
              <select
                value={formData.questStatus}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    questStatus: e.target.value as
                      | 'active'
                      | 'completed'
                      | 'failed',
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              >
                <option value="active">Aktywna</option>
                <option value="completed">Ukończona</option>
                <option value="failed">Nieudana</option>
              </select>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Tytuł wpisu
            </label>
            <input
              type="text"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none placeholder-emerald-900/60"
              placeholder="np. Śledztwo w Domu Corbitów"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Treść / Opis
            </label>
            <Textarea
              value={formData.content}
              onChange={(e) =>
                setFormData({ ...formData, content: e.target.value })
              }
              className="min-h-32 bg-zinc-950 text-zinc-300 border-emerald-900/30 focus-visible:ring-[#bfa15f] placeholder-emerald-900/60"
              placeholder="Zapisz szczegóły przygody lub informacje o postaci/przedmiocie..."
              required
            />
          </div>

          {formData.type === 'quest' && (
            <div className="border border-emerald-900/30 p-4 rounded-md bg-zinc-950/40 space-y-3">
              <label className="block text-sm font-serif font-bold text-emerald-100 border-b border-emerald-900/30 pb-1">
                Cele zadania
              </label>
              <div className="space-y-2">
                {formData.objectives.map((obj, i) => (
                  <div
                    key={obj.id}
                    className="flex justify-between items-center bg-zinc-950 p-2 rounded border border-emerald-900/30 text-sm"
                  >
                    <span className="truncate">
                      {i + 1}. {obj.description}
                    </span>
                    <button
                      type="button"
                      onClick={() => removeObjective(obj.id)}
                      className="text-[#942c2c] hover:text-red-400"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newObjective}
                  onChange={(e) => setNewObjective(e.target.value)}
                  placeholder="Nowy cel misji..."
                  className="flex-1 p-2 bg-zinc-950 border border-emerald-900/30 rounded-md text-sm text-zinc-300 outline-none focus:border-emerald-500"
                  onKeyDown={(e) =>
                    e.key === 'Enter' && (e.preventDefault(), addObjective())
                  }
                />
                <Button
                  type="button"
                  onClick={addObjective}
                  className="bg-emerald-900/60 hover:bg-emerald-800/70 text-emerald-100"
                >
                  Dodaj cel
                </Button>
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Tagi
            </label>
            <div className="flex flex-wrap gap-1.5 mb-2">
              {formData.tags.map((tag) => (
                <span
                  key={tag}
                  className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-emerald-900/50/60 text-emerald-100 border border-emerald-500/25"
                >
                  #{tag}
                  <button
                    type="button"
                    onClick={() => removeTag(tag)}
                    className="ml-1 text-[#a29182] hover:text-red-400"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                className="flex-1 p-2 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none placeholder-emerald-900/60"
                placeholder="Dodaj własny tag..."
                onKeyDown={(e) =>
                  e.key === 'Enter' && (e.preventDefault(), addTag(newTag))
                }
              />
              <Button
                type="button"
                onClick={() => addTag(newTag)}
                className="bg-emerald-900/60 hover:bg-emerald-800/70 text-emerald-100"
              >
                +
              </Button>
            </div>
            <div className="flex flex-wrap gap-1 mt-2">
              {defaultTags.map((tag) => (
                <button
                  key={tag}
                  type="button"
                  onClick={() => addTag(tag)}
                  className="px-2 py-0.5 text-xs bg-zinc-950 hover:bg-[#1a110a] text-[#8a7667] rounded border border-emerald-900/30"
                >
                  {tag}
                </button>
              ))}
            </div>
          </div>

          <div className="flex gap-3 pt-3 border-t border-emerald-900/30">
            <Button
              type="submit"
              className="flex-1 py-3 bg-emerald-900/50 hover:bg-emerald-800/60 text-emerald-100 border border-emerald-500/40"
              disabled={!formData.title.trim() || !formData.content.trim()}
            >
              Zapisz wpis
            </Button>
            <Button
              type="button"
              onClick={onCancel}
              className="flex-1 py-3 bg-[#38261c] hover:bg-[#4d3527] text-[#a29182]"
            >
              Anuluj
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}

interface EditEntryFormProps {
  entry: ExtendedJournalEntry;
  onUpdate: (entry: ExtendedJournalEntry) => void;
  onCancel: () => void;
}

function EditEntryForm({ entry, onUpdate, onCancel }: EditEntryFormProps) {
  const [formData, setFormData] = useState(entry);
  const [newTag, setNewTag] = useState('');
  const [newObjective, setNewObjective] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (formData.title.trim() && formData.content.trim()) {
      onUpdate(formData);
    }
  };

  const addTag = (tag: string) => {
    if (tag.trim() && !formData.tags.includes(tag.trim())) {
      setFormData({ ...formData, tags: [...formData.tags, tag.trim()] });
      setNewTag('');
    }
  };

  const removeTag = (tagToRemove: string) => {
    setFormData({
      ...formData,
      tags: formData.tags.filter((tag) => tag !== tagToRemove),
    });
  };

  const addObjective = () => {
    if (newObjective.trim()) {
      const obj: QuestObjective = {
        id: Date.now().toString() + Math.random().toString(36).substring(2, 5),
        description: newObjective.trim(),
        completed: false,
        gameDay: formData.gameDay,
        gameHour: formData.gameHour,
      };
      setFormData({
        ...formData,
        objectives: [...(formData.objectives || []), obj],
      });
      setNewObjective('');
    }
  };

  const removeObjective = (id: string) => {
    setFormData({
      ...formData,
      objectives: (formData.objectives || []).filter((o) => o.id !== id),
    });
  };

  return (
    <div className="fixed inset-0 bg-black/85 flex items-center justify-center z-[60] p-4">
      <div className="bg-[#1c120c] border-4 border-emerald-900/30 rounded-xl p-6 w-[90vw] max-w-[800px] max-h-[90vh] overflow-y-auto journal-scroll text-zinc-300 font-serif shadow-2xl">
        <div className="flex justify-between items-center border-b border-emerald-900/30 pb-3 mb-5">
          <h3 className="text-xl font-bold text-emerald-100">
            Edytuj wpis w księdze przygód
          </h3>
          <button
            onClick={onCancel}
            className="text-[#a29182] hover:text-emerald-100"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Typ wpisu
            </label>
            <select
              value={formData.type}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  type: e.target.value as JournalEntryType,
                })
              }
              className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
            >
              <option value="quest">Misja (Quest)</option>
              <option value="journal">Wpis do Dziennika (Kronika)</option>
              <option value="npc">
                Encyklopedia - Postać / Byt
              </option>
              <option value="location">
                Encyklopedia - Lokacja
              </option>
              <option value="item">
                Encyklopedia - Przedmiot
              </option>
              <option value="note">Własna notatka / Teoria</option>
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Dzień kampanii
              </label>
              <input
                type="number"
                min="1"
                value={formData.gameDay || 1}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    gameDay: parseInt(e.target.value) || 1,
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Godzina
              </label>
              <input
                type="number"
                min="0"
                max="23"
                value={formData.gameHour || 0}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    gameHour: parseInt(e.target.value) || 0,
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              />
            </div>
          </div>

          {formData.type === 'quest' && (
            <div>
              <label className="block text-sm font-medium mb-1.5 text-emerald-100">
                Status misji
              </label>
              <select
                value={formData.questStatus || 'active'}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    questStatus: e.target.value as
                      | 'active'
                      | 'completed'
                      | 'failed',
                  })
                }
                className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              >
                <option value="active">Aktywna</option>
                <option value="completed">Ukończona</option>
                <option value="failed">Nieudana</option>
              </select>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Tytuł wpisu
            </label>
            <input
              type="text"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              className="w-full p-2.5 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Treść / Opis
            </label>
            <Textarea
              value={formData.content}
              onChange={(e) =>
                setFormData({ ...formData, content: e.target.value })
              }
              className="min-h-32 bg-zinc-950 text-zinc-300 border-emerald-900/30 focus-visible:ring-[#bfa15f]"
              required
            />
          </div>

          {formData.type === 'quest' && (
            <div className="border border-emerald-900/30 p-4 rounded-md bg-zinc-950/40 space-y-3">
              <label className="block text-sm font-serif font-bold text-emerald-100 border-b border-emerald-900/30 pb-1">
                Cele zadania
              </label>
              <div className="space-y-2">
                {(formData.objectives || []).map((obj, i) => (
                  <div
                    key={obj.id}
                    className="flex justify-between items-center bg-zinc-950 p-2 rounded border border-emerald-900/30 text-sm"
                  >
                    <span className="truncate">
                      {i + 1}. {obj.description}
                    </span>
                    <button
                      type="button"
                      onClick={() => removeObjective(obj.id)}
                      className="text-[#942c2c] hover:text-red-400"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newObjective}
                  onChange={(e) => setNewObjective(e.target.value)}
                  placeholder="Nowy cel misji..."
                  className="flex-1 p-2 bg-zinc-950 border border-emerald-900/30 rounded-md text-sm text-zinc-300 outline-none"
                  onKeyDown={(e) =>
                    e.key === 'Enter' && (e.preventDefault(), addObjective())
                  }
                />
                <Button
                  type="button"
                  onClick={addObjective}
                  className="bg-emerald-900/60 hover:bg-emerald-800/70 text-emerald-100"
                >
                  Dodaj
                </Button>
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium mb-1.5 text-emerald-100">
              Tagi
            </label>
            <div className="flex flex-wrap gap-1.5 mb-2">
              {formData.tags.map((tag) => (
                <span
                  key={tag}
                  className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-emerald-900/50/60 text-emerald-100 border border-emerald-500/25"
                >
                  #{tag}
                  <button
                    type="button"
                    onClick={() => removeTag(tag)}
                    className="ml-1 text-[#a29182] hover:text-red-400"
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                className="flex-1 p-2 bg-zinc-950 border border-emerald-900/30 rounded-md text-zinc-300 focus:border-emerald-500 focus:outline-none"
                placeholder="Dodaj własny tag..."
                onKeyDown={(e) =>
                  e.key === 'Enter' && (e.preventDefault(), addTag(newTag))
                }
              />
              <Button
                type="button"
                onClick={() => addTag(newTag)}
                className="bg-emerald-900/60 hover:bg-emerald-800/70 text-emerald-100"
              >
                +
              </Button>
            </div>
          </div>

          <div className="flex gap-3 pt-3 border-t border-emerald-900/30">
            <Button
              type="submit"
              className="flex-1 py-3 bg-emerald-900/50 hover:bg-emerald-800/60 text-emerald-100 border border-emerald-500/40"
              disabled={!formData.title.trim() || !formData.content.trim()}
            >
              Zapisz zmiany
            </Button>
            <Button
              type="button"
              onClick={onCancel}
              className="flex-1 py-3 bg-[#38261c] hover:bg-[#4d3527] text-[#a29182]"
            >
              Anuluj
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
