'use client';

import { useState, useMemo, useEffect } from 'react';
import { useTranslations } from 'next-intl';
import {
  BookOpen,
  X,
  MessageSquare,
  Users,
  Scroll,
  Search,
  Compass,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { filterPlotItems, isPlotRelevantItem } from '@/lib/journal/item-filter';
import type { JournalEntry, JournalEventType, Character, SceneCaseCard } from '@/lib/types';

export type JournalEntryType =
  | 'case'
  | 'quest'
  | 'journal'
  | 'location'
  | 'npc'
  | 'item'
  | 'note'
  | 'scene';

export interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  dateCompleted?: string;
  gameDay?: number;
  gameHour?: number;
}

export interface ExtendedJournalEntry extends Omit<
  JournalEntry,
  'type' | 'isBookmarked' | 'timestamp'
> {
  timestamp?: Date;
  type: JournalEntryType | JournalEventType;
  category?: string;
  isAutoGenerated?: boolean;
  isBookmarked?: boolean;
  questStatus?: 'active' | 'completed' | 'failed';
  objectives?: QuestObjective[];
  gameDay?: number;
  gameHour?: number;
}

export interface SessionJournalProps {
  character: Character;
  onUpdateCharacter?: (character: Character) => void;
  onClose?: () => void;
  currentInGameDate?: string;
  sharedJournal?: JournalEntry[];
  onUpdateSharedJournal?: (journal: JournalEntry[]) => void;
  participantNames?: string[];
  /** Callback cytowania poszlaki/tekstu do pola czatu (Quote-to-Input) */
  onQuoteToInput?: (text: string) => void;
}

export interface SealedScene {
  id: string;
  sceneNumber: number;
  location: string;
  title: string;
  inGameDate?: string;
  timestamp?: string | Date;
  people: string[];
  findings: string[];
  keyTakeaways: string[];
  nextStep?: string;
}

export function SessionJournal({
  character,
  onClose,
  currentInGameDate,
  sharedJournal,
  participantNames = [],
  onQuoteToInput,
}: SessionJournalProps) {
  const t = useTranslations('SessionJournal');

  // Obsługa klawisza Escape do zamykania Dziennika
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose?.();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  const isShared = sharedJournal !== undefined;

  // Pobranie wpisów dziennika (duet lub solo)
  const entries = useMemo(() => {
    return (sharedJournal ?? character.journal ?? []) as unknown as ExtendedJournalEntry[];
  }, [character.journal, sharedJournal]);

  // Ekstrakcja i deduplikacja zapieczętowanych kart scen
  const sealedScenes = useMemo<SealedScene[]>(() => {
    const map = new Map<string, SealedScene>();

    // 1. Karty scen z character.sceneCards
    if (Array.isArray(character.sceneCards)) {
      character.sceneCards.forEach((sc: SceneCaseCard, idx: number) => {
        if (sc.isSealed === false) return;
        const id = sc.id || `sc-card-${sc.sceneNumber ?? idx + 1}`;
        map.set(id, {
          id,
          sceneNumber: sc.sceneNumber ?? idx + 1,
          location: sc.location || 'Nieznana lokacja',
          title: sc.title || `Scena #${sc.sceneNumber ?? idx + 1}`,
          inGameDate: sc.inGameDate,
          timestamp: sc.timestamp,
          people: Array.isArray(sc.people) ? sc.people : [],
          findings: Array.isArray(sc.findings) ? sc.findings : [],
          keyTakeaways: Array.isArray(sc.keyTakeaways) ? sc.keyTakeaways : [],
          nextStep: sc.nextStep,
        });
      });
    }

    // 2. Karty ze scalonego dziennika przygody
    entries.forEach((entry, idx) => {
      if (entry.sceneData) {
        if (entry.sceneData.isSealed === false) return;
        const sd = entry.sceneData;
        const id = sd.id || entry.id;
        if (!map.has(id)) {
          map.set(id, {
            id,
            sceneNumber: sd.sceneNumber ?? idx + 1,
            location: sd.location || 'Nieznana lokacja',
            title: sd.title || entry.title || `Scena #${sd.sceneNumber ?? idx + 1}`,
            inGameDate: sd.inGameDate || entry.inGameDate,
            timestamp: sd.timestamp || entry.timestamp,
            people: Array.isArray(sd.people) ? sd.people : [],
            findings: Array.isArray(sd.findings) ? sd.findings : [],
            keyTakeaways: Array.isArray(sd.keyTakeaways)
              ? sd.keyTakeaways
              : entry.content
                ? [entry.content]
                : [],
            nextStep: sd.nextStep,
          });
        }
      } else if (entry.type === 'scene') {
        const id = entry.id;
        if (!map.has(id)) {
          const takeaways = entry.content
            ? entry.content.split('\n').map((s) => s.trim()).filter(Boolean)
            : [];
          map.set(id, {
            id,
            sceneNumber: map.size + 1,
            location: entry.metadata?.locationName || entry.title || 'Nieznana lokacja',
            title: entry.title,
            inGameDate: entry.inGameDate,
            timestamp: entry.timestamp,
            people: entry.metadata?.npcName ? [entry.metadata.npcName] : [],
            findings: [],
            keyTakeaways: takeaways,
            nextStep: undefined,
          });
        }
      }
    });

    const list = Array.from(map.values());
    // Chronologicznie od najnowszej na samej górze
    list.sort((a, b) => {
      if (b.sceneNumber !== a.sceneNumber) {
        return b.sceneNumber - a.sceneNumber;
      }
      const timeA = a.timestamp ? new Date(a.timestamp).getTime() : 0;
      const timeB = b.timestamp ? new Date(b.timestamp).getTime() : 0;
      return timeB - timeA;
    });

    return list;
  }, [character.sceneCards, entries]);

  // Ekstrakcja i synteza trwającej sceny w toku (Issue #471)
  const ongoingSceneCard = useMemo<SealedScene | null>(() => {
    const as = character.activeScene;
    if (!as) {
      return null;
    }

    const keyTakeaways: string[] = [];
    const seenTakeaways = new Set<string>();

    const addTakeaway = (text?: string | null) => {
      if (!text) return;
      const clean = text.trim();
      if (!clean || seenTakeaways.has(clean.toLowerCase())) return;
      seenTakeaways.add(clean.toLowerCase());
      keyTakeaways.push(clean);
    };

    if (Array.isArray(as.notes)) {
      as.notes.forEach(addTakeaway);
    }
    if (Array.isArray(as.findings)) {
      as.findings.forEach((f) => {
        if (isPlotRelevantItem(f)) {
          addTakeaway(f);
        }
      });
    }

    entries.forEach((e) => {
      if (e.type === 'scene') return;
      const isRelatedLocation = Boolean(
        as.location &&
        as.location !== 'Aktualna lokacja' &&
        (
          e.metadata?.locationName?.toLowerCase() === as.location.toLowerCase() ||
          e.title?.toLowerCase().includes(as.location.toLowerCase())
        )
      );

      if (isRelatedLocation || e.type === 'clue' || e.type === 'discovery' || e.type === 'note') {
        const text = e.content || e.title;
        addTakeaway(text);
      }
    });

    let nextStep: string | undefined;
    if (Array.isArray(as.notes)) {
      const explicitNext = as.notes.find((n) =>
        /^(?:cel|zadanie|kolejny krok|następny krok|next step):/i.test(n)
      );
      if (explicitNext) {
        nextStep = explicitNext
          .replace(/^(?:cel|zadanie|kolejny krok|następny krok|next step):\s*/i, '')
          .trim();
      }
    }
    if (!nextStep) {
      nextStep =
        as.location && as.location !== 'Aktualna lokacja'
          ? `Kontynuuj badanie lokacji: ${as.location}`
          : t('ongoingNextStepDefault');
    }

    const allFindings = [...(Array.isArray(as.findings) ? as.findings : [])];
    entries.forEach((e) => {
      if (e.type === 'item' && e.title && !allFindings.includes(e.title)) {
        allFindings.push(e.title);
      }
    });

    return {
      id: 'active-ongoing-scene',
      sceneNumber: as.sceneNumber || sealedScenes.length + 1,
      location: as.location || 'Aktualna lokacja',
      title: as.title || t('activeSceneHeader'),
      inGameDate: as.inGameDate || currentInGameDate,
      timestamp: as.startedAt || new Date().toISOString(),
      people: Array.isArray(as.people) ? as.people : [],
      findings: allFindings,
      keyTakeaways,
      nextStep,
    };
  }, [character.activeScene, currentInGameDate, entries, sealedScenes.length, t]);

  // Pusty stan ("Dziennik śledztwa milczy") pojawia się TYLKO wtedy, gdy nie ma ani zapieczętowanych scen, ani żadnych wpisów/ustaleń w aktywnej scenie
  const hasActiveSceneContent = Boolean(
    ongoingSceneCard &&
    (
      ongoingSceneCard.findings.length > 0 ||
      ongoingSceneCard.people.length > 0 ||
      ongoingSceneCard.keyTakeaways.length > 0 ||
      (ongoingSceneCard.location &&
        ongoingSceneCard.location.trim() !== '' &&
        ongoingSceneCard.location !== 'Aktualna lokacja')
    )
  );

  const isEmpty = sealedScenes.length === 0 && !hasActiveSceneContent;

  // Domyślnie wybrana jest bieżąca scena (lub najnowsza zapieczętowana, jeśli brak aktywnej)
  const [selectedSceneId, setSelectedSceneId] = useState<string | null>(null);

  const activeSceneCard = useMemo(() => {
    if (selectedSceneId) {
      if (ongoingSceneCard && selectedSceneId === ongoingSceneCard.id) {
        return ongoingSceneCard;
      }
      const found = sealedScenes.find((s) => s.id === selectedSceneId);
      if (found) return found;
    }
    if (ongoingSceneCard) {
      return ongoingSceneCard;
    }
    return sealedScenes[0] || null;
  }, [ongoingSceneCard, sealedScenes, selectedSceneId]);

  // Cytowanie do czatu
  const handleQuoteToInput = (text: string) => {
    if (onQuoteToInput) {
      onQuoteToInput(text);
    } else {
      window.dispatchEvent(
        new CustomEvent('straznik:quote-to-input', {
          detail: { text },
        })
      );
    }
    onClose?.();
  };

  // Trwająca aktywna scena do paska statusu
  const ongoingLocation =
    character.activeScene?.location ||
    (sealedScenes.length > 0 ? sealedScenes[0].location : null);

  return (
    <div
      data-testid="session-journal"
      className="fixed inset-0 w-full h-full z-50 flex flex-col bg-[#0b0805] text-[#e8dfcf] select-none overflow-hidden"
    >
      {/* Narożniki ozdobne Dark Art Déco */}
      <span className="pointer-events-none absolute left-3 top-3 h-5 w-5 border-l-2 border-t-2 border-brass/60 z-30" />
      <span className="pointer-events-none absolute right-3 top-3 h-5 w-5 border-r-2 border-t-2 border-brass/60 z-30" />
      <span className="pointer-events-none absolute bottom-3 left-3 h-5 w-5 border-l-2 border-b-2 border-brass/60 z-30" />
      <span className="pointer-events-none absolute bottom-3 right-3 h-5 w-5 border-r-2 border-b-2 border-brass/60 z-30" />

      {/* 1. Czysty Nagłówek (Header) */}
      <header className="bg-gradient-to-r from-[#140e09] via-[#1a130c] to-[#140e09] border-b border-brass/30 px-6 py-3 flex items-center justify-between gap-4 shrink-0 shadow-md relative z-10">
        <div className="flex items-center gap-3">
          <BookOpen className="h-6 w-6 text-brass shrink-0" />
          <div>
            <div className="font-special-elite text-[10px] uppercase tracking-[0.22em] text-brass/80">
              {t('titleEyebrow')}
            </div>
            <h1 className="font-display uppercase tracking-[0.14em] text-lg lg:text-xl text-foreground drop-shadow-sm whitespace-nowrap">
              {t('titleFull')}
            </h1>
            <div className="text-xs font-serif text-muted-foreground flex items-center gap-2">
              <span>{t('investigatorLabel', { name: character.name })}</span>
              {(currentInGameDate || character.activeScene?.inGameDate) && (
                <>
                  <span className="text-brass/40">•</span>
                  <span className="text-brass/75">
                    {currentInGameDate || character.activeScene?.inGameDate}
                  </span>
                </>
              )}
              {isShared && participantNames.length > 0 && (
                <>
                  <span className="text-brass/40">•</span>
                  <span className="text-emerald-400/90 font-mono text-[11px]">
                    {t('sharedWith', { names: participantNames.join(' i ') })}
                  </span>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Przycisk zamknięcia X (z obsługą Esc) */}
        {onClose && (
          <button
            type="button"
            onClick={onClose}
            className="flex h-9 w-9 items-center justify-center rounded-full border border-brass/40 bg-[#120f0c] text-muted-foreground transition-all hover:border-brass/80 hover:text-brass hover:scale-105 shrink-0"
            title={t('closeTooltip')}
            aria-label={t('closeAriaLabel')}
          >
            <X className="h-5 w-5" />
          </button>
        )}
      </header>

      {/* 2. Dyskretny pasek statusu trwającej sceny */}
      <div className="bg-[#0e0a07] border-b border-brass/20 px-6 py-2 flex items-center justify-between gap-4 text-xs shrink-0">
        <div className="flex items-center gap-2.5">
          <span className="relative flex h-2.5 w-2.5">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500"></span>
          </span>
          <span className="font-mono uppercase tracking-wider text-brass/90">
            {ongoingLocation
              ? t('currentLocationStatus', { location: ongoingLocation })
              : t('statusInvestigationOngoing')}
          </span>
        </div>
        {character.activeScene && (
          <span className="text-[11px] font-mono text-muted-foreground hidden sm:inline">
            Scena #{character.activeScene.sceneNumber} {t('activeSceneBadge')}
          </span>
        )}
      </div>

      {/* 3. Główna przestrzeń: Układ Kroniki Scen (100% wysokości i szerokości) */}
      <main className="flex-1 flex flex-col md:flex-row overflow-hidden relative">
        {isEmpty ? (
          /* Empty State - Dziennik milczy */
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center bg-gradient-to-b from-[#140e09] via-[#0d0906] to-[#070503]">
            <div className="w-16 h-16 rounded-full border border-brass/40 bg-brass/10 flex items-center justify-center mb-4 text-brass shadow-[0_0_20px_rgba(191,161,95,0.15)]">
              <Compass className="h-8 w-8" />
            </div>
            <h2 className="font-display text-xl uppercase tracking-[0.16em] text-foreground mb-2">
              {t('emptyScenesTitle')}
            </h2>
            <p className="font-serif italic text-muted-foreground max-w-lg leading-relaxed text-sm">
              {t('emptyScenesDescription')}
            </p>
          </div>
        ) : (
          /* Dwukolumnowy układ Kroniki Scen */
          <>
            {/* Lewa kolumna: Lista Scen (najnowsza u góry) */}
            <aside className="w-full md:w-80 lg:w-96 shrink-0 border-b md:border-b-0 md:border-r border-brass/25 bg-[#0e0a07] flex flex-col max-h-48 md:max-h-none overflow-hidden">
              <div className="px-4 py-3 border-b border-brass/15 bg-[#140f0a] flex items-center justify-between shrink-0">
                <span className="font-display text-xs uppercase tracking-[0.18em] text-brass/90 font-bold">
                  {t('sceneListTitle')} ({sealedScenes.length + (ongoingSceneCard ? 1 : 0)})
                </span>
                <span className="text-[10px] font-mono text-muted-foreground uppercase">
                  Najnowsze na górze
                </span>
              </div>

              <div className="flex-1 overflow-y-auto journal-scroll p-3 space-y-2">
                {/* 1. Bieżąca scena (W toku) na samej górze listy scen */}
                {ongoingSceneCard && (
                  <div
                    key={ongoingSceneCard.id}
                    role="button"
                    tabIndex={0}
                    onClick={() => setSelectedSceneId(ongoingSceneCard.id)}
                    onMouseEnter={() => setSelectedSceneId(ongoingSceneCard.id)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        setSelectedSceneId(ongoingSceneCard.id);
                      }
                    }}
                    className={cn(
                      'p-3.5 rounded-sm border cursor-pointer transition-all duration-200 text-left relative group',
                      activeSceneCard?.id === ongoingSceneCard.id
                        ? 'bg-gradient-to-r from-emerald-950/40 via-brass/15 to-transparent border-emerald-500/80 shadow-[inset_0_0_12px_rgba(16,185,129,0.15),0_0_10px_rgba(16,185,129,0.1)] text-[#f4ebd0]'
                        : 'bg-[#140f0b]/70 border-emerald-500/30 hover:border-emerald-500/60 hover:bg-emerald-950/20 hover:shadow-[0_0_12px_rgba(16,185,129,0.15)] text-[#d4c8b8]'
                    )}
                  >
                    <div className="flex items-center justify-between gap-2 mb-1.5">
                      <div className="flex items-center gap-2">
                        <span className="relative flex h-2.5 w-2.5 shrink-0">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500"></span>
                        </span>
                        <span className="text-[11px] bg-emerald-950/60 text-emerald-400 font-mono uppercase px-2 py-0.5 rounded border border-emerald-500/40 shrink-0 font-bold">
                          Scena #{ongoingSceneCard.sceneNumber}
                        </span>
                      </div>
                      <span className="text-[10px] bg-emerald-500/20 text-emerald-300 font-mono uppercase px-1.5 py-0.5 rounded border border-emerald-500/30 shrink-0 tracking-wider font-bold">
                        {t('ongoingBadge')}
                      </span>
                    </div>

                    <h3 className="font-serif font-bold text-sm leading-snug line-clamp-2 text-foreground group-hover:text-emerald-300 transition-colors">
                      {ongoingSceneCard.title}
                    </h3>

                    <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1.5">
                      <span className="shrink-0">📍</span>
                      <span className="truncate text-brass/90">{ongoingSceneCard.location}</span>
                    </div>
                  </div>
                )}

                {/* 2. Zapieczętowane sceny chronologicznie */}
                {sealedScenes.map((scene) => {
                  const isSelected = activeSceneCard?.id === scene.id;
                  return (
                    <div
                      key={scene.id}
                      role="button"
                      tabIndex={0}
                      onClick={() => setSelectedSceneId(scene.id)}
                      onMouseEnter={() => setSelectedSceneId(scene.id)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' || e.key === ' ') {
                          setSelectedSceneId(scene.id);
                        }
                      }}
                      className={cn(
                        'p-3.5 rounded-sm border cursor-pointer transition-all duration-200 text-left relative group',
                        isSelected
                          ? 'bg-gradient-to-r from-brass/20 via-brass/15 to-transparent border-brass/80 shadow-[inset_0_0_12px_rgba(191,161,95,0.15),0_0_10px_rgba(191,161,95,0.1)] text-[#f4ebd0]'
                          : 'bg-[#140f0b]/70 border-brass/15 hover:border-brass/50 hover:bg-brass/10 hover:shadow-[0_0_12px_rgba(191,161,95,0.15)] text-[#d4c8b8]'
                      )}
                    >
                      <div className="flex items-center justify-between gap-2 mb-1.5">
                        <span className="text-[11px] bg-brass/20 text-brass font-mono uppercase px-2 py-0.5 rounded border border-brass/40 shrink-0">
                          Scena #{scene.sceneNumber}
                        </span>
                        {scene.inGameDate && (
                          <span className="text-[11px] text-brass/70 font-mono shrink-0">
                            📅 {scene.inGameDate}
                          </span>
                        )}
                      </div>

                      <h3 className="font-serif font-bold text-sm leading-snug line-clamp-2 text-foreground group-hover:text-brass transition-colors">
                        {scene.title}
                      </h3>

                      <div className="text-xs text-muted-foreground mt-1 flex items-center gap-1.5">
                        <span className="shrink-0">📍</span>
                        <span className="truncate">{scene.location}</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </aside>

            {/* Prawa strona: Karta Sceny w 4 czystych blokach */}
            {activeSceneCard && (
              <section className="flex-1 overflow-y-auto journal-scroll p-6 lg:p-8 bg-[#110d09] flex flex-col space-y-6">
                {/* Nagłówek wybranej karty */}
                <div className="border-b border-brass/25 pb-4">
                  <div className="flex items-center gap-2 mb-2">
                    {activeSceneCard.id === ongoingSceneCard?.id ? (
                      <span className="text-xs bg-emerald-950/60 text-emerald-300 font-mono uppercase px-2.5 py-0.5 rounded border border-emerald-500/50 font-bold flex items-center gap-1.5">
                        <span className="relative flex h-2 w-2">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                        </span>
                        Scena #{activeSceneCard.sceneNumber} • {t('ongoingBadge')}
                      </span>
                    ) : (
                      <span className="text-xs bg-brass/25 text-brass font-mono uppercase px-2.5 py-0.5 rounded border border-brass/50 font-bold">
                        Scena #{activeSceneCard.sceneNumber}
                      </span>
                    )}
                    <span className="text-xs text-brass/80 font-mono flex items-center gap-1">
                      <span>📍</span> {activeSceneCard.location}
                    </span>
                    {activeSceneCard.inGameDate && (
                      <span className="text-xs text-brass/80 font-mono flex items-center gap-1">
                        <span>📅</span> {activeSceneCard.inGameDate}
                      </span>
                    )}
                  </div>
                  <h2 className="font-display text-xl lg:text-2xl text-foreground uppercase tracking-wide">
                    {activeSceneCard.title}
                  </h2>
                </div>

                {/* BLOK 1: Przebieg i kluczowe ustalenia */}
                <div className="bg-[#16100b] border border-brass/30 rounded-sm p-4 lg:p-5 shadow-sm">
                  <div className="flex items-center gap-2 text-brass font-display text-xs uppercase tracking-[0.14em] mb-3 pb-2 border-b border-brass/20">
                    <Scroll className="h-4 w-4" />
                    <span>{t('blockEventsAndFindings')}</span>
                  </div>
                  {activeSceneCard.keyTakeaways.length > 0 ? (
                    <ul className="space-y-2 font-serif text-sm text-[#e8dfcf] leading-relaxed list-disc list-inside">
                      {activeSceneCard.keyTakeaways.map((item, idx) => (
                        <li key={idx} className="leading-relaxed">
                          {item}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-sm font-serif italic text-muted-foreground">
                      {activeSceneCard.id === ongoingSceneCard?.id
                        ? t('ongoingEmptyFindings')
                        : 'Brak szczegółowych ustaleń dla tej sceny.'}
                    </p>
                  )}
                </div>

                {/* BLOK 2: Spotkane osoby */}
                <div className="bg-[#16100b] border border-brass/30 rounded-sm p-4 lg:p-5 shadow-sm">
                  <div className="flex items-center gap-2 text-brass font-display text-xs uppercase tracking-[0.14em] mb-3 pb-2 border-b border-brass/20">
                    <Users className="h-4 w-4" />
                    <span>{t('blockPeople')}</span>
                  </div>
                  {activeSceneCard.people.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {activeSceneCard.people.map((person, idx) => (
                        <span
                          key={idx}
                          className="bg-black/50 border border-brass/30 text-brass/90 text-xs px-2.5 py-1 rounded-sm font-serif"
                        >
                          {person}
                        </span>
                      ))}
                    </div>
                  ) : (
                    <p className="text-sm font-serif italic text-muted-foreground">
                      {t('sceneCardEmptyPeople')}
                    </p>
                  )}
                </div>

                {/* BLOK 3: Zdobyte kluczowe przedmioty i poszlaki (filtrowane przez item-filter) */}
                {(() => {
                  const filteredFindings = filterPlotItems(activeSceneCard.findings);
                  return (
                    <div className="bg-[#16100b] border border-brass/30 rounded-sm p-4 lg:p-5 shadow-sm">
                      <div className="flex items-center gap-2 text-brass font-display text-xs uppercase tracking-[0.14em] mb-3 pb-2 border-b border-brass/20">
                        <Search className="h-4 w-4" />
                        <span>{t('blockKeyItemsAndClues')}</span>
                      </div>
                      {filteredFindings.length > 0 ? (
                        <div className="flex flex-wrap gap-2">
                          {filteredFindings.map((item, idx) => (
                            <span
                              key={idx}
                              className="bg-emerald-950/40 border border-emerald-500/40 text-emerald-200 text-xs px-2.5 py-1 rounded-sm font-mono tracking-wide"
                            >
                              🔍 {item}
                            </span>
                          ))}
                        </div>
                      ) : (
                        <p className="text-sm font-serif italic text-muted-foreground">
                          {t('sceneCardEmptyFindings')}
                        </p>
                      )}
                    </div>
                  );
                })()}

                {/* BLOK 4: Cel / Następny krok śledztwa */}
                <div className="bg-gradient-to-r from-brass/15 via-brass/10 to-transparent border border-brass/40 rounded-sm p-4 lg:p-5 shadow-sm">
                  <div className="flex items-center gap-2 text-brass font-display text-xs uppercase tracking-[0.14em] mb-2">
                    <span>🎯</span>
                    <span>{t('blockNextStep')}</span>
                  </div>
                  {activeSceneCard.nextStep ? (
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mt-2">
                      <p className="font-serif italic text-sm text-[#f4ebd0] leading-relaxed flex-1">
                        {activeSceneCard.nextStep}
                      </p>
                      <button
                        type="button"
                        onClick={() => handleQuoteToInput(activeSceneCard.nextStep!)}
                        className="bg-[#241a10] hover:bg-brass hover:text-black text-brass border border-brass/50 font-special-elite text-xs uppercase tracking-wider px-3.5 py-2 rounded-sm flex items-center gap-2 shrink-0 transition-all shadow-sm"
                        title={t('quoteToChatTitle')}
                      >
                        <MessageSquare className="h-4 w-4" />
                        <span>{t('quoteToChatButton')}</span>
                      </button>
                    </div>
                  ) : (
                    <p className="text-sm font-serif italic text-muted-foreground">
                      {t('noNextStep')}
                    </p>
                  )}
                </div>
              </section>
            )}
          </>
        )}
      </main>
    </div>
  );
}
