'use client';

import { useState, useMemo, useEffect, useRef } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import {
  BookOpen,
  X,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import type { JournalEntry, JournalEventType, Character, SceneCaseCard } from '@/lib/types';

export type JournalEntryType =
  | 'case'
  | 'quest'
  | 'journal'
  | 'location'
  | 'npc'
  | 'item'
  | 'note'
  | 'scene'
  | 'act_report';

export interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  dateCompleted?: string;
  gameDay?: number;
  gameHour?: number;
}

export interface ExtendedJournalEntry extends Omit<
  JournalEntry,
  'type' | 'isBookmarked' | 'timestamp'
> {
  timestamp?: Date;
  type: JournalEntryType | JournalEventType;
  category?: string;
  isAutoGenerated?: boolean;
  isBookmarked?: boolean;
  questStatus?: 'active' | 'completed' | 'failed';
  objectives?: QuestObjective[];
  gameDay?: number;
  gameHour?: number;
}

export interface SessionJournalProps {
  character: Character;
  onUpdateCharacter?: (character: Character) => void;
  onClose?: () => void;
  currentInGameDate?: string;
  sharedJournal?: JournalEntry[];
  onUpdateSharedJournal?: (journal: JournalEntry[]) => void;
  participantNames?: string[];
  /** Callback cytowania poszlaki/tekstu do pola czatu (Quote-to-Input) */
  onQuoteToInput?: (text: string) => void;
  /** Szacunkowa całkowita liczba wskazówek w scenariuszu (Mechanika 1) */
  totalCluesEstimated?: number;
}

export interface SealedScene {
  id: string;
  sceneNumber: number;
  location: string;
  title: string;
  inGameDate?: string;
  timestamp?: string | Date;
  people: string[];
  findings: string[];
  keyTakeaways: string[];
  chronicleSummary?: string;
  chroniclePending?: boolean;
  nextStep?: string;
}

interface ReadingEntry {
  id: string;
  title: string;
  sceneNumber?: number;
  location?: string;
  inGameDate?: string;
  timestamp?: string | Date;
  people: string[];
  findings: string[];
  content: string;
  pending: boolean;
  legacy: boolean;
}

export function SessionJournal({
  character,
  onClose,
  currentInGameDate,
  sharedJournal,
  participantNames = [],
}: SessionJournalProps) {
  const t = useTranslations('SessionJournal');
  const locale = useLocale() === 'en' ? 'en' : 'pl';
  const dialogRef = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose);
  closeRef.current = onClose;
  const articleRefs = useRef(new Map<string, HTMLElement>());
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const entries = useMemo<ReadingEntry[]>(() => {
    const map = new Map<string, ReadingEntry>();
    const addScene = (scene: SceneCaseCard) => {
      if (scene.isSealed === false) return;
      const summary = scene.chronicleSummaryByLocale?.[locale];
      const content = typeof summary === 'string' ? summary.trim() : '';
      const existing = map.get(scene.id);
      if (existing) {
        if (!content) return;
        if (!existing.pending && !existing.legacy) {
          const existingTime = existing.timestamp ? new Date(existing.timestamp).getTime() : NaN;
          const candidateTime = new Date(scene.timestamp).getTime();
          if (!Number.isFinite(candidateTime) || !Number.isFinite(existingTime) || candidateTime <= existingTime) return;
        }
      }
      const pending = Boolean(scene.endMessageId) && !content;
      map.set(scene.id, {
        id: scene.id,
        title: scene.title || scene.location || t('sceneNumber', { number: scene.sceneNumber }),
        sceneNumber: scene.sceneNumber,
        location: scene.location,
        inGameDate: scene.inGameDate,
        timestamp: scene.timestamp,
        people: Array.isArray(scene.people) ? scene.people : [],
        findings: !pending && !content && Array.isArray(scene.findings) ? scene.findings : [],
        content: content || (!pending && Array.isArray(scene.keyTakeaways) ? scene.keyTakeaways.join('\n') : ''),
        pending,
        legacy: !content && !pending,
      });
    };
    // Shared entries may contain a later recap than a character's snapshot.
    const journal = sharedJournal ?? character.journal ?? [];
    journal.forEach((entry) => { if (entry.sceneData) addScene(entry.sceneData); });
    (character.sceneCards ?? []).forEach(addScene);
    journal.forEach((entry) => {
      if (entry.sceneData || entry.type === 'act_report' || map.has(entry.id)) return;
      if (!entry.content?.trim()) return;
      map.set(entry.id, {
        id: entry.id, title: entry.title, inGameDate: entry.inGameDate,
        timestamp: entry.timestamp,
        location: entry.metadata?.locationName,
        people: entry.metadata?.npcName ? [entry.metadata.npcName] : [],
        findings: [], content: entry.content, pending: false, legacy: true,
      });
    });
    return Array.from(map.values()).sort((a, b) => {
      const timeA = a.timestamp ? new Date(a.timestamp).getTime() : NaN;
      const timeB = b.timestamp ? new Date(b.timestamp).getTime() : NaN;
      if (Number.isFinite(timeA) && Number.isFinite(timeB) && timeA !== timeB) return timeA - timeB;
      return (a.sceneNumber ?? 0) - (b.sceneNumber ?? 0);
    });
  }, [character.sceneCards, character.journal, sharedJournal, locale, t]);

  const latestId = entries[entries.length - 1]?.id;
  useEffect(() => {
    if (latestId) articleRefs.current.get(latestId)?.scrollIntoView?.({ block: 'start' });
  }, [latestId]);

  useEffect(() => {
    const previouslyFocused = document.activeElement;
    dialogRef.current?.focus({ preventScroll: true });
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeRef.current?.();
      if (event.key !== 'Tab') return;
      const buttons = dialogRef.current?.querySelectorAll<HTMLButtonElement>('button:not([disabled])');
      if (!buttons?.length) return;
      const first = buttons[0];
      const last = buttons[buttons.length - 1];
      const active = document.activeElement;
      if (event.shiftKey && (active === first || active === dialogRef.current || active?.tagName === 'ARTICLE')) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && (active === last || active?.tagName === 'ARTICLE')) {
        event.preventDefault();
        first.focus();
      }
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => {
      window.removeEventListener('keydown', closeOnEscape);
      if (previouslyFocused instanceof HTMLElement && previouslyFocused.isConnected) previouslyFocused.focus({ preventScroll: true });
    };
  }, []);

  const navigate = (id: string) => {
    setSelectedId(id);
    const article = articleRefs.current.get(id);
    article?.scrollIntoView?.({ block: 'start', behavior: 'smooth' });
    article?.focus({ preventScroll: true });
  };

  return (
    <div ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="journal-reader-title"
      data-testid="session-journal"
      className="fixed inset-0 z-50 flex flex-col overflow-hidden bg-[#0c0b09] text-[#e8dfcf]">
      <header className="flex shrink-0 items-start justify-between gap-4 border-b border-brass/25 px-5 py-4 md:px-8 md:py-5">
        <div className="min-w-0">
          <p className="mb-2 font-special-elite text-[10px] uppercase tracking-[0.24em] text-brass">{t('readerEyebrow')}</p>
          <h1 id="journal-reader-title" className="flex items-center gap-3 font-display text-xl md:text-2xl">
            <BookOpen aria-hidden="true" className="h-5 w-5 shrink-0 text-brass" />{t('readerTitle')}
          </h1>
          <p className="mt-2 font-serif text-sm text-[#bbb09d]">
            {sharedJournal !== undefined && participantNames.length > 0
              ? t('readerParty', { names: participantNames.join(', ') })
              : t('readerInvestigator', { name: character.name })}
            {currentInGameDate ? <span className="ml-3">{currentInGameDate}</span> : null}
          </p>
        </div>
        {onClose && <button type="button" onClick={onClose} aria-label={t('closeAriaLabel')}
          className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-brass/30 text-brass hover:bg-brass/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brass">
          <X aria-hidden="true" className="h-5 w-5" />
        </button>}
      </header>

      {entries.length === 0 ? (
        <main className="flex flex-1 items-center justify-center overflow-auto p-8">
          <div className="max-w-lg text-center">
            <BookOpen aria-hidden="true" className="mx-auto mb-5 h-10 w-10 text-brass/60" />
            <h2 className="font-display text-xl">{t('readerEmptyTitle')}</h2>
            <p className="mt-4 font-serif leading-relaxed text-[#bbb09d]">{t('readerEmptyDescription')}</p>
            {character.activeScene?.location && <p className="mt-6 font-serif text-sm">{t('readerCurrentLocation', { location: character.activeScene.location })}</p>}
          </div>
        </main>
      ) : (
        <div className="flex min-h-0 flex-1 flex-col md:flex-row">
          <nav aria-label={t('readerContents')} data-testid="journal-contents"
            className="min-w-0 shrink-0 border-b border-brass/20 bg-[#11100d] md:w-64 md:overflow-y-auto md:border-b-0 md:border-r lg:w-72">
            <h2 className="px-5 pt-4 font-special-elite text-xs uppercase tracking-[0.16em] text-brass">{t('readerContents')}</h2>
            <ol className="flex gap-2 overflow-x-auto p-3 md:flex-col md:gap-1">
              {entries.map((entry) => (
                <li key={entry.id} className="shrink-0 md:shrink">
                  <button type="button" onClick={() => navigate(entry.id)}
                    aria-current={(selectedId ?? latestId) === entry.id ? 'location' : undefined}
                    className={cn('w-full max-w-56 rounded-sm border border-transparent px-3 py-3 text-left hover:bg-brass/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brass md:max-w-none',
                      (selectedId ?? latestId) === entry.id && 'border-brass/30 bg-brass/10')}>
                    <span className="block font-special-elite text-[10px] uppercase tracking-wider text-brass">{entry.sceneNumber !== undefined ? t('sceneNumber', { number: entry.sceneNumber }) : t('readerEarlierEntry')}</span>
                    <span className="mt-1 block truncate font-serif text-sm">{entry.title}</span>
                    {entry.inGameDate && <span className="mt-1 block text-xs text-[#aaa08e]">{entry.inGameDate}</span>}
                  </button>
                </li>
              ))}
            </ol>
          </nav>

          <main data-testid="journal-reader" aria-label={t('readerTitle')}
            className="min-h-0 min-w-0 flex-1 overflow-y-auto scroll-smooth">
            <div className="mx-auto max-w-3xl px-5 py-8 md:px-10 md:py-12">
              <p className="mb-10 border-l border-brass/40 pl-4 font-serif text-sm italic leading-relaxed text-[#bbb09d]">{t('readerIntroduction')}</p>
              {entries.map((entry) => (
                <article key={entry.id} tabIndex={-1} data-testid="journal-entry"
                  ref={(element) => { if (element) articleRefs.current.set(entry.id, element); else articleRefs.current.delete(entry.id); }}
                  aria-labelledby={`journal-entry-${encodeURIComponent(entry.id)}`}
                  className="mb-10 scroll-mt-8 border-b border-brass/20 pb-10 outline-none last:mb-0 focus-visible:ring-1 focus-visible:ring-brass/40">
                  <p className="mb-3 font-special-elite text-xs uppercase tracking-[0.16em] text-brass">
                    {entry.sceneNumber !== undefined ? t('sceneNumber', { number: entry.sceneNumber }) : t('readerEarlierEntry')}
                    {entry.inGameDate && <span className="ml-3 normal-case tracking-normal text-[#bbb09d]">{entry.inGameDate}</span>}
                  </p>
                  <h2 id={`journal-entry-${encodeURIComponent(entry.id)}`} className="font-display text-2xl leading-snug md:text-3xl">{entry.title}</h2>
                  {entry.location && entry.location !== entry.title && <p className="mt-2 font-serif text-sm text-[#bbb09d]">{entry.location}</p>}
                  {entry.people.length > 0 && <p className="mt-3 font-serif text-sm leading-relaxed text-[#bbb09d]">
                    <span className="text-brass">{t('readerPeople')}: </span>{entry.people.join(', ')}
                  </p>}
                  {entry.pending ? <p className="mt-6 font-serif italic leading-relaxed text-[#bbb09d]">{t('chroniclePending')}</p>
                    : <div data-testid={entry.legacy ? 'journal-legacy-record' : 'scene-chronicle-summary'} className="mt-6 whitespace-pre-line font-serif text-base leading-8 text-[#e8dfcf]">
                      {entry.content || t('readerNoRecord')}
                    </div>}
                  {entry.findings.length > 0 && <p className="mt-5 font-serif text-sm leading-relaxed text-[#bbb09d]">
                    <span className="text-brass">{t('readerFindings')}: </span>{entry.findings.join(', ')}
                  </p>}
                </article>
              ))}
              {character.activeScene?.location && <section data-testid="journal-current-scene" className="mt-10 font-serif text-sm leading-relaxed text-[#bbb09d]">
                <h2 className="mb-2 font-special-elite text-xs uppercase tracking-wider text-brass">{t('readerCurrentLocation', { location: character.activeScene.location })}</h2>
                <p>{t('readerCurrentDescription')}</p>
              </section>}
            </div>
          </main>
        </div>
      )}
    </div>
  );
}
