import { Character } from '@/lib/types';
import { buildPredefinedEquipment } from './predefined-equipment';

export type PredefinedCharacterEra = 'gaslight' | 'classic' | 'modern';
export type PredefinedCharacterArchetype =
  | 'investigator'
  | 'scholar'
  | 'action'
  | 'healer'
  | 'mystic';

export interface PredefinedCharacter extends Character {
  era: PredefinedCharacterEra;
  archetype: PredefinedCharacterArchetype;
}

// Baza 30 predefiniowanych postaci zbalansowanych pod mechanike CoC 7e (3 ery x 5 archetypow x 2 plcie = 30 postaci)
const BASE_PREDEFINED_CHARACTERS: PredefinedCharacter[] = [
  // ==========================================================================
  // ERA: LATA 90. XIX WIEKU (1890s / Gaslight) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDÇZY (Investigator) ---
  {
    id: 'pref_arthur_pendleton_1890s',
    era: 'gaslight',
    archetype: 'investigator',
    name: 'Arthur Pendleton',
    occupation: 'Dziennikarz',
    age: 42,
    gender: 'male',
    portraitUrl: '/portraits/predefined/arthur-pendleton.webp',
    str: 55,
    dex: 60,
    con: 55,
    app: 50,
    pow: 65,
    edu: 75,
    siz: 60,
    int: 70,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Urodzony w Londynie reporter piszący dla "The Pall Mall Gazette". Zawsze z notesem w dłoni, bada tajemnice mglistych uliczek East Endu. Wierzy, że prawda jest silniejsza od jakiegokolwiek przesądu.',
    birthplace: 'Londyn, Anglia',
    residence: 'Londyn, dzielnica Chelsea',
    characterConcept: 'Dociekliwy reporter tropiący to, o czym inni boją się pisać.',
    ideology: 'Prawda i fakty są jedyną bronią przeciwko ciemnocie i zabobonom.',
    significantPerson: 'Redaktor naczelny Pall Mall Gazette, który wielokrotnie ratował go przed procesami o zniesławienie.',
    meaningfulLocation: 'Ciasna redakcja pełna dymu tytoniowego i zapachu zecerki.',
    treasuredPossession: 'Mosiężny zegarek kieszonkowy po ojcu, odliczający sekundy podczas nocnych czuwań.',
    traits: ['Dociekliwy', 'Sceptyczny', 'Uparty'],
    description: 'Mężczyzna średniego wzrostu, z gęstym wąsem i wiecznie przybrudzonymi atramentem palcami. Nosi lekko sfatygowany tweedowy garnitur.',
    backstory: 'Arthur spędził ostatnie piętnaście lat na spisywaniu historii z najuboższych dzielnic Londynu. Ostatnio jednak jego reportaże zaczęły dotykać spraw, których nie potrafi wyjaśnić racjonalnym intelektem.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wnikliwy obserwator, świetny w wywiadach i zbieraniu plotek.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 65,
      Psychologia: 60,
      'Korzystanie z Bibliotek': 60,
      Perswazja: 55,
      Historia: 50,
      'Język Ojczysty (Angielski)': 75,
      Nasłuchiwanie: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_arthur_notebook',
        name: 'Skórzany notatnik i pióro',
        category: 'tool',
      },
      {
        id: 'eq_arthur_lamp',
        name: 'Lampa naftowa kieszonkowa',
        category: 'tool',
      },
      {
        id: 'eq_arthur_card',
        name: 'Legitymacja prasowa gazety',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_beatrice_vance_1890s',
    era: 'gaslight',
    archetype: 'investigator',
    name: 'Beatrice Vance',
    occupation: 'Prywatna Detektyw',
    age: 31,
    gender: 'female',
    portraitUrl: '/portraits/predefined/beatrice-vance.webp',
    str: 50,
    dex: 65,
    con: 60,
    app: 60,
    pow: 70,
    edu: 65,
    siz: 55,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Jedna z nielicznych kobiet prowadzących własną agencję śledczą w wiktoriańskim Londynie. Oficjalnie zajmuje się sprawami rodzinnymi, nieoficjalnie tropi podejrzane stowarzyszenia.',
    birthplace: 'Bristol, Anglia',
    residence: 'Londyn, Soho',
    characterConcept: 'Niezależna śledcza działająca w cieniu patriarchalnego społeczeństwa.',
    ideology: 'Każdy sekret, nieważne jak głęboko zakopany, ostatecznie wychodzi na jaw.',
    significantPerson: 'Jej zaginiony brat, którego poszukiwania pchnęły ją do otwarcia agencji.',
    meaningfulLocation: 'Jej małe biuro w Soho, z którego widać zatłoczoną ulicę.',
    treasuredPossession: 'Srebrny medalion ze zdjęciem brata.',
    traits: ['S spostrzegawcza', 'Dyskretna', 'Zdecydowana'],
    description: 'Szczupła kobieta o bystrym spojrzeniu, zazwyczaj ubrana w ciemną, praktyczną garsonkę i kapelusz z gęstym welonem.',
    backstory: 'Po tajemniczym zaginięciu brata, który badał sprawę pewnego elitarnego klubu dżentelmenów, Beatrice założyła własne biuro. Odkryła, że pod powierzchnią Londynu kryją się sekty czczące prastare byty.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Doskonała w ukrywaniu się, śledzeniu celów i otwieraniu zamków.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Skradanie: 70,
      Spostrzegawczość: 65,
      Ślusarstwo: 60,
      Psychologia: 55,
      'Walka Wręcz': 50,
      'Broń Palna (Krótka)': 45,
      'Szybkie Czytanie': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_beatrice_derringer',
        name: 'Mały pistolet Derringer .41',
        category: 'weapon',
        description: 'Kieszonkowy pistolet dwustrzałowy.',
        modifiers: { damage: '1d10', range: '5 yards' },
      },
      {
        id: 'eq_beatrice_lockpicks',
        name: 'Zestaw wytrychów w etui',
        category: 'tool',
      },
      {
        id: 'eq_beatrice_veil',
        name: 'Czarny welon i kapelusz maskujący',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_archibald_blackwood_1890s',
    era: 'gaslight',
    archetype: 'scholar',
    name: 'Prof. Archibald Blackwood',
    occupation: 'Profesor',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/archibald-blackwood.webp',
    str: 45,
    dex: 50,
    con: 50,
    app: 50,
    pow: 75,
    edu: 90,
    siz: 50,
    int: 80,
    luck: 50,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Wykładowca historii starożytnej na Uniwersytecie Oxfordzkim. Spędził dekady badając zapomniane cywilizacje Mezopotamii. Szanowany badacz, który wierzy, że przeszłość kryje klucze do zrozumienia każdego koszmaru.',
    birthplace: 'Oxford, Anglia',
    residence: 'Oxford',
    characterConcept: 'Klasyczny naukowiec szukający racjonalnych wyjaśnień w starożytnych pismach.',
    ideology: 'Wiedza zgromadzona przez przodków chroni nas przed szaleństwem teraźniejszości.',
    significantPerson: 'Jego dawny profesor i mentor, który zmarł w tajemniczych okolicznościach po powrocie z Egiptu.',
    meaningfulLocation: 'Ciche, zakurzone biblioteki Oxfordu.',
    treasuredPossession: 'Mosiężna lupa, której używał podczas pierwszych wykopalisk w Ur.',
    traits: ['Erudyta', 'Rozważny', 'Sceptyczny'],
    description: 'Starszy mężczyzna o siwiejących skroniach, noszący okulary w okrągłych oprawkach i tradycyjny tweedowy garnitur z kamizelką.',
    backstory: 'Spędziwszy życie w murach uniwersytetu, prof. Blackwood uważał magię i mity za zwykłe alegorie starożytnych. Zmieniło się to, gdy odziedziczył notatnik swojego mentora z zapiskami na temat płaskowyżu Leng.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Chodząca encyklopedia. Zna martwe języki i stare księgi.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 80,
      Historia: 75,
      'Język Obcy (Łacina)': 60,
      'Język Obcy (Egipskie Hieronimy)': 50,
      Archeologia: 65,
      Spostrzegawczość: 50,
      Psychologia: 50,
      'Nauka (Astronomia)': 40,
      Okultyzm: 45,
      Unik: 25,
    },
    equipment: [
      {
        id: 'eq_arch_briefcase',
        name: 'Skórzana aktówka',
        category: 'tool',
        description: 'Pełna notatek i wycinków prasowych.',
      },
      {
        id: 'eq_arch_magnifier',
        name: 'Lupa w mosiężnej oprawie',
        category: 'tool',
      },
      {
        id: 'eq_arch_journal',
        name: 'Dziennik wykopalisk',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_cordelia_ashford_1890s',
    era: 'gaslight',
    archetype: 'scholar',
    name: 'Cordelia Ashford',
    occupation: 'Antykwariusz',
    age: 34,
    gender: 'female',
    portraitUrl: '/portraits/predefined/cordelia-ashford.webp',
    str: 50,
    dex: 60,
    con: 55,
    app: 60,
    pow: 70,
    edu: 80,
    siz: 50,
    int: 75,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Właścicielka małego antykwariatu w Londynie. Specjalizuje się w średniowiecznych manuskryptach oraz rzadkich dziełach okultystycznych. Posiada niezwykły zmysł do wykrywania fałszerstw.',
    birthplace: 'Bath, Anglia',
    residence: 'Londyn, Kensington',
    characterConcept: 'Konserwatorka ksiąg o niezwykłej intuicji do zakazanej wiedzy.',
    ideology: 'Księgi nie kłamią; to ludzie interpretują je w zły sposób.',
    significantPerson: 'Jej stały klient, ekscentryczny lord, który zleca jej poszukiwania najdziwniejszych tomów.',
    meaningfulLocation: 'Cichy tył jej antykwariatu, pachnący starym papierem i woskiem pszczelim.',
    treasuredPossession: 'Unikalny pęk kluczy do szuflad ze szczególnymi starodrukami.',
    traits: ['Skrupulatna', 'Dociekliwa', 'Spokojna'],
    description: 'Kobieta o inteligentnym spojrzeniu, z włosami spiętymi w wysoki kok. Zawsze nosi fartuch rzemieślniczy podczas pracy z manuskryptami.',
    backstory: 'Cordelia przejęła antykwariat po wuju. Szybko zorientowała się, że niektóre z woluminów w jego prywatnej kolekcji nie powinny nigdy zostać otwarte przez osoby postronne. Zaczęła je badać w tajemnicy.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Potrafi odczytać najstarsze pisma i ocenić każdy artefakt.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 75,
      Wycena: 70,
      Historia: 65,
      'Język Obcy (Sanskryt)': 50,
      Spostrzegawczość: 60,
      'Sztuka/Rzemiosło (Konserwacja Ksiąg)': 55,
      Perswazja: 50,
      Okultyzm: 50,
      Nasłuchiwanie: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_cord_glasses',
        name: 'Okulary do czytania',
        category: 'personal',
      },
      {
        id: 'eq_cord_monograph',
        name: 'Monografia o demonologii',
        category: 'document',
      },
      {
        id: 'eq_cord_keys',
        name: 'Pęk starych kluczy do archiwum',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_ronald_shaw_1890s',
    era: 'gaslight',
    archetype: 'action',
    name: 'Capt. Ronald Shaw',
    occupation: 'Wojskowy',
    age: 45,
    gender: 'male',
    portraitUrl: '/portraits/predefined/ronald-shaw.webp',
    str: 70,
    dex: 55,
    con: 65,
    app: 50,
    pow: 60,
    edu: 60,
    siz: 65,
    int: 65,
    luck: 50,
    hp: 13,
    maxHp: 13,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Kapitan piechoty w stanie spoczynku. Służył w Indiach i Afganistanie. Doskonały strzelec, wyznawca wojskowej dyscypliny, stawiający czoła niebezpieczeństwom z zimną krwią.',
    birthplace: 'York, Anglia',
    residence: 'Londyn',
    characterConcept: 'Zdyscyplinowany oficer zmagający się z demonami przeszłości.',
    ideology: 'Honor i lojalność wobec towarzyszy broni stoją ponad wszystkim.',
    significantPerson: 'Jego dawny ordynans, który zginął, osłaniając go w przełęczy Khyber.',
    meaningfulLocation: 'Klub oficerski, w którym szuka ciszy.',
    treasuredPossession: 'Srebrna piersiówka z wygrawerowanym godłem pułku.',
    traits: ['Szorstki', 'Opanowany', 'Honorowy'],
    description: 'Wysoki, postawny mężczyzna o nienagannej postawie. Posiada kilka blizn na twarzy i chłodne, stalowe spojrzenie.',
    backstory: 'Ronald Shaw spędził większość życia na rubieżach Imperium Brytyjskiego. Po przejściu na emeryturę nie potrafił odnaleźć się w dymie Londynu, dopóki dawny przyjaciel nie poprosił go o pomoc w zbadaniu zagadkowej śmierci wspólnego znajomego.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Mistrz broni palnej długiej, odporny psychicznie.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Długa)': 75,
      Zastraszanie: 60,
      'Walka Wręcz': 55,
      Jeździectwo: 50,
      Spostrzegawczość: 50,
      'Pierwsza Pomoc': 45,
      Nasłuchiwanie: 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_ronald_rifle',
        name: 'Karabin Lee-Metford .303',
        category: 'weapon',
        description: 'Celny karabin powtarzalny.',
        modifiers: { damage: '2d6+4', range: '100 yards' },
      },
      {
        id: 'eq_ronald_flask',
        name: 'Srebrna piersiówka z brandy',
        category: 'personal',
      },
      {
        id: 'eq_ronald_compass',
        name: 'Wojskowy kompas mosiężny',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_alexandra_croft_1890s',
    era: 'gaslight',
    archetype: 'action',
    name: 'Lady Alexandra Croft',
    occupation: 'Podróżnik',
    age: 28,
    gender: 'female',
    portraitUrl: '/portraits/predefined/alexandra-croft.webp',
    str: 60,
    dex: 70,
    con: 65,
    app: 60,
    pow: 65,
    edu: 70,
    siz: 55,
    int: 70,
    luck: 60,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Córka arystokraty, która odrzuciła salonowe życie na rzecz ekspedycji do Afryki i Ameryki Południowej. Znakomita sportsmenka, wspinacz i badaczka terenowa.',
    birthplace: 'Surrey, Anglia',
    residence: 'Londyn / W podróży',
    characterConcept: 'Arystokratka poszukująca przygód w najdzikszych zakątkach świata.',
    ideology: 'Życie nabiera smaku tylko wtedy, gdy igramy z niebezpieczeństwem.',
    significantPerson: 'Jej ojciec, lord Croft, który finansuje jej eskapady mimo sprzeciwu reszty rodziny.',
    meaningfulLocation: 'Szczyty Andów lub gęsta dżungla Kongo.',
    treasuredPossession: 'Notatnik podróżnika oprawiony w skórę pytona.',
    traits: ['Odważna', 'Niezależna', 'Porywcza'],
    description: 'Młoda kobieta o wysportowanej sylwetce, o smagłej od słońca skórze. Często nosi męski strój podróżny zamiast sukni.',
    backstory: 'Odrzuciwszy propozycje zamążpójścia, Alexandra poświęciła się eksploracji ruin. Podczas ostatniej wyprawy do Ameryki Południowej natknęła się na płaskorzeźby przedstawiające dziwne, uskrzydlone istoty, co obudziło jej głód prawdy.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo zwinna, świetna w nawigacji i wspinaczce.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Wspinaczka: 70,
      Nawigacja: 60,
      Spostrzegawczość: 60,
      'Broń Palna (Krótka)': 55,
      Archeologia: 50,
      Jeździectwo: 50,
      Przetrwanie: 50,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_alexandra_webley',
        name: 'Rewolwer Webley .455',
        category: 'weapon',
        description: 'Mocny brytyjski rewolwer służbowy.',
        modifiers: { damage: '1d10+2', range: '15 yards' },
      },
      { id: 'eq_alexandra_whip', name: 'Skórzany bicz', category: 'tool' },
      {
        id: 'eq_alexandra_journal',
        name: 'Notatnik podróżnika',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_alistair_sterling_1890s',
    era: 'gaslight',
    archetype: 'healer',
    name: 'Dr Alistair Sterling',
    occupation: 'Lekarz',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/alistair-sterling.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 50,
    pow: 70,
    edu: 85,
    siz: 55,
    int: 75,
    luck: 50,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Uznany londyński patolog i toksykolog. Często konsultuje nietypowe przypadki zgonów dla Scotland Yardu. Posiada chłodny umysł i głęboką wiedzę o chemii.',
    birthplace: 'Edynburg, Szkocja',
    residence: 'Londyn, Marylebone',
    characterConcept: 'Analityczny patolog badający granice życia i śmierci.',
    ideology: 'Ludzkie ciało to maszyna; każda śmierć ma swoją fizyczną i logiczną przyczynę.',
    significantPerson: 'Inspektor Scotland Yardu, który regularnie zleca mu sekcje zwłok z niewyjaśnionych spraw.',
    meaningfulLocation: 'Chłodne, oświetlone gazowymi lampami prosektorium.',
    treasuredPossession: 'Złoty zegarek kieszonkowy z wygrawerowaną przysięgą Hipokratesa.',
    traits: ['Analityczny', 'Chłodny', 'Sceptyczny'],
    description: 'Poważny mężczyzna w średnim wieku, o schludnie przystrzyżonej brodzie i uważnym, klinicznym spojrzeniu.',
    backstory: 'Dr Sterling badał setki ciał w Londynie. Jednak seria niedawnych autopsji ofiar znalezionych w pobliżu Tamizy ujawniła zmiany anatomiczne, które przeczą znanej biologii i toksykologii.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Ekspert od medycyny, biologii i identyfikacji trucizn.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 70,
      'Nauka (Chemia)': 65,
      'Nauka (Biologia)': 60,
      Psychologia: 55,
      Spostrzegawczość: 50,
      'Korzystanie z Bibliotek': 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_alistair_kit',
        name: 'Wiktoriańska torba lekarska',
        category: 'medical',
        description: 'Komplet narzędzi chirurgicznych i odtrutek.',
      },
      {
        id: 'eq_alistair_laudanum',
        name: 'Buteleczka z laudanum',
        category: 'medical',
      },
      {
        id: 'eq_alistair_ledger',
        name: 'Dziennik sekcji zwłok',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_edith_cavell_1890s',
    era: 'gaslight',
    archetype: 'healer',
    name: 'Edith Cavell',
    occupation: 'Pielęgniarka',
    age: 32,
    gender: 'female',
    portraitUrl: '/portraits/predefined/edith-cavell.webp',
    str: 55,
    dex: 60,
    con: 60,
    app: 60,
    pow: 75,
    edu: 70,
    siz: 50,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Doświadczona pielęgniarka pracująca w londyńskich szpitalach ubogich. Poświęciła życie niesieniu pomocy chorym. Cechuje ją bezgraniczna cierpliwość oraz stalowe nerwy.',
    birthplace: 'Norfolk, Anglia',
    residence: 'Londyn, East End',
    characterConcept: 'Oddana pielęgniarka o niezłomnej woli walki o ludzkie życie.',
    ideology: 'Pomoc należy się każdemu człowiekowi, niezależnie od jego statusu czy występków.',
    significantPerson: 'Jej matka, która zaszczepiła w niej wiarę w powołanie.',
    meaningfulLocation: 'Ciasny, duszny szpital polowy lub hospicjum.',
    treasuredPossession: 'Srebrny krzyżyk pielęgniarki przypięty do fartucha.',
    traits: ['Empatyczna', 'Niezłomna', 'Cierpliwa'],
    description: 'Kobieta o łagodnych rysach twarzy i spokojnym głosie. Zawsze nosi nienagannie czysty czepek i fartuch pielęgniarski.',
    backstory: 'Pracując w najuboższych i najbardziej niebezpiecznych rejonach Londynu, Edith widziała najgorsze ludzkie cierpienia. Jednak ostatnio niektórzy z jej pacjentów zaczęli zapadać na chorobę psychiczną objawiającą się przerażającymi wizjami morskich głębin.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezastąpiona w pierwszej pomocy i podnoszeniu morali zespołu.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Pierwsza Pomoc': 80,
      Medycyna: 55,
      Psychologia: 65,
      Nasłuchiwanie: 60,
      Spostrzegawczość: 55,
      Perswazja: 50,
      Skradanie: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_edith_bandages',
        name: 'Rolki bandaży i antyseptyk',
        category: 'medical',
      },
      {
        id: 'eq_edith_pills',
        name: 'Sole trzeźwiące i toniki',
        category: 'medical',
      },
      {
        id: 'eq_edith_cross',
        name: 'Srebrny krzyżyk pielęgniarki',
        category: 'personal',
      },
    ],
  },

  // ==========================================================================
  // ERA: LATA 20. XX WIEKU (1920s / Classic) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDÇZY (Investigator) ---
  {
    id: 'pref_tommy_obrien_1920s',
    era: 'classic',
    archetype: 'investigator',
    name: 'Thomas "Tommy" O\'Brien',
    occupation: 'Prywatny Detektyw',
    age: 38,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tommy-obrien.webp',
    str: 65,
    dex: 65,
    con: 60,
    app: 55,
    pow: 65,
    edu: 60,
    siz: 65,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Były detektyw bostońskiej policji, który odszedł ze służby po odkryciu korupcji na najwyższych szczeblach. Teraz prowadzi jednoosobowe biuro śledcze, przyjmując sprawy, którymi nikt inny nie chce się zająć.',
    birthplace: 'Boston, USA',
    residence: 'Boston, North End',
    characterConcept: 'Prywatny detektyw w stylu noir, trzymający się twardych zasad.',
    ideology: 'Prawo rzadko oznacza sprawiedliwość, ale ktoś musi stać po stronie słabszych.',
    significantPerson: 'Jego dawny partner z policji, jedyny gliniarz w Bostonie, któremu wciąż ufa.',
    meaningfulLocation: 'Biuro z zakurzonymi żaluzjami, pachnące tanią kawą i bourbonem.',
    treasuredPossession: 'Zniszczona odznaka policyjna ukryta w szufladzie.',
    traits: ['Cyniczny', 'Uparty', 'Lojalny'],
    description: 'Szorstki mężczyzna w średnim wieku, noszący szary prochowiec i kapelusz z rondem opuszczonym na oczy.',
    backstory: 'Tommy odszedł z bostońskiej policji po tym, jak jego śledztwo w sprawie zniknięcia lokalnego dokera zostało zablokowane przez wpływowego sędziego. Od tamtej pory drąży ten temat na własną rękę.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Klimat noir. Szorstki w obyciu, ale ma miękkie serce do sprawiedliwości.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 70,
      Psychologia: 60,
      'Broń Palna (Krótka)': 65,
      Zastraszanie: 55,
      Prawo: 40,
      Skradanie: 50,
      'Prowadzenie Samochodu': 50,
      'Walka Wręcz': 55,
      Nasłuchiwanie: 55,
      'Korzystanie z Bibliotek': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_tommy_gun',
        name: 'Rewolwer Colt .38',
        category: 'weapon',
        description: 'Niezawodny rewolwer detektywistyczny.',
        modifiers: { damage: '1d10', range: '15 yards' },
      },
      {
        id: 'eq_tommy_badge',
        name: 'Zniszczona odznaka',
        category: 'personal',
        description: 'Pamiątka z czasów pracy w policji.',
      },
      {
        id: 'eq_tommy_trench',
        name: 'Prochowiec i kapelusz',
        category: 'personal',
      },
    ],
  },
  {
    id: 'pref_margaret_sullivan_1920s',
    era: 'classic',
    archetype: 'investigator',
    name: 'Margaret Sullivan',
    occupation: 'Dziennikarka',
    age: 28,
    gender: 'female',
    portraitUrl: '/portraits/predefined/margaret-sullivan.webp',
    str: 50,
    dex: 65,
    con: 55,
    app: 65,
    pow: 70,
    edu: 70,
    siz: 55,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Reporterka śledcza pisząca dla „Arkham Advertiser”. Specjalizuje się w tropieniu powiązań lokalnych polityków z przestępczym podziemiem. Dociekliwa i nieustraszona, wierzy w uzdrawiającą moc prawdy.',
    birthplace: 'Arkham, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Dociekliwa i odważna dziennikarka śledcza.',
    ideology: 'Wolna prasa to jedyna zapora przed tyranią i złem.',
    significantPerson: 'Jej brat, redaktor naczelny, który drukuje jej ryzykowne artykuły.',
    meaningfulLocation: 'Głośna zecernia gazety z zapachami ołowiu i papieru.',
    treasuredPossession: 'Mały aparat Kodak podarowany przez mentora dziennikarstwa.',
    traits: ['Odważna', 'Bystra', 'Elokwentna'],
    description: 'Bystrooka kobieta o modnym, krótkim cięciu włosów. Nosi ze sobą ciężką skórzaną torbę z przyborami do pisania i aparatem.',
    backstory: 'Margaret napisała głośną serię artykułów o nielegalnym handlu alkoholem w Arkham. Ostatnio bada doniesienia o tajemniczym kulcie spotykającym się w lasach wokół Billingsgate.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wyśmienita w rozmowach i badaniu starych archiwów.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Perswazja: 65,
      'Urok Osobisty': 60,
      'Sztuka/Rzemiosło (Pisanie)': 65,
      Spostrzegawczość: 60,
      'Korzystanie z Bibliotek': 65,
      Psychologia: 55,
      Historia: 50,
      Nasłuchiwanie: 50,
      'Broń Palna (Krótka)': 30,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_margaret_notebook',
        name: 'Notatnik i ołówek',
        category: 'tool',
        description: 'Zapisane setkami wywiadów.',
      },
      {
        id: 'eq_margaret_camera',
        name: 'Aparat małoobrazkowy Kodak',
        category: 'tool',
      },
      {
        id: 'eq_margaret_press',
        name: 'Legitymacja prasowa',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_william_dyer_1920s',
    era: 'classic',
    archetype: 'scholar',
    name: 'Prof. William Dyer',
    occupation: 'Geolog',
    age: 46,
    gender: 'male',
    portraitUrl: '/portraits/predefined/william-dyer.webp',
    str: 55,
    dex: 55,
    con: 60,
    app: 50,
    pow: 65,
    edu: 85,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Ceniony profesor geologii na Uniwersytecie Miskatonic w Arkham. Weteran wypraw badawczych, w tym ekspedycji na Alaskę. Rzeczowy naukowiec, przyzwyczajony do analizy faktów i przetrwania w dziczy.',
    birthplace: 'Providence, USA',
    residence: 'Arkham, dzielnica uniwersytecka',
    characterConcept: 'Doświadczony geolog o wybitnym intelekcie i zamiłowaniu do natury.',
    ideology: 'Ziemia opowiada historię dłuższą i bardziej niezwykłą niż cała ludzkość.',
    significantPerson: 'Profesor Danforth, z którym dzielił trudy wypraw arktycznych.',
    meaningfulLocation: 'Uniwersyteckie laboratorium geologiczne pełne rzadkich okazów.',
    treasuredPossession: 'Kompas geologiczny używany na Alasce.',
    traits: ['Spokojny', 'Dociekliwy', 'Odporny'],
    description: 'Mężczyzna o siwiejących włosach i twarzy pooranej zmarszczkami od mroźnego wiatru. Zwykle zamyślony.',
    backstory: 'William Dyer badał próbki skał na całym świecie. Ostatnia partia minerałów przysłana z dziwnej jaskini w Nowej Anglii wykazuje jednak właściwości strukturalne, które nie pasują do żadnego znanego okresu geologicznego.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Szeroka wiedza akademicka, geologiczna i umiejętności przetrwania.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Nauka (Geologia)': 75,
      'Korzystanie z Bibliotek': 65,
      Nawigacja: 60,
      Przetrwanie: 55,
      Spostrzegawczość: 50,
      Historia: 45,
      'Język Obcy (Niemiecki)': 40,
      Unik: 27,
    },
    equipment: [
      { id: 'eq_william_pick', name: 'Młotek geologiczny', category: 'tool' },
      {
        id: 'eq_william_compass',
        name: 'Kompas geologiczny Bruntona',
        category: 'tool',
      },
      {
        id: 'eq_william_charts',
        name: 'Mapy topograficzne Nowej Anglii',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_dorothy_updike_1920s',
    era: 'classic',
    archetype: 'scholar',
    name: 'Dr Dorothy Updike',
    occupation: 'Bibliotekarka',
    age: 35,
    gender: 'female',
    portraitUrl: '/portraits/predefined/dorothy-updike.webp',
    str: 45,
    dex: 60,
    con: 50,
    app: 60,
    pow: 75,
    edu: 80,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Starsza archiwistka w bibliotece Uniwersytetu Miskatonic. Posiada klucze do działu ksiąg zakazanych i rzadkich manuskryptów. Cicha i spostrzegawcza, wie dokładnie, gdzie szukać zapomnianej wiedzy.',
    birthplace: 'Ipswich, USA',
    residence: 'Arkham, Northside',
    characterConcept: 'Dyskretna archiwistka posiadająca dostęp do najmroczniejszych sekretów historii.',
    ideology: 'Niektóre prawdy są tak potężne, że powinny pozostać ukryte w cieniu bibliotek.',
    significantPerson: 'Jej schorowany ojciec, dawny profesor filologii klasycznej, który przekazał jej pasję do ksiąg.',
    meaningfulLocation: 'Mroczny, chłodny dział starodruków w Bibliotece Orne.',
    treasuredPossession: 'Zeszyt z odręcznymi, poufnymi tłumaczeniami zakazanych fragmentów.',
    traits: ['Skupiona', 'Cicha', 'Ciekawska'],
    description: 'Elegancka kobieta w okularach, nosząca długie, wełniane spódnice. Porusza się z niezwykłą gracją i niemal bezszelestnie.',
    backstory: 'Dorothy spędziła dziesięć lat w archiwach. Podczas inwentaryzacji spuścizny po zmarłym w tajemniczych okolicznościach okultyście, znalazła dziwny, nieujęty w katalogu rękopis, który wywołał u niej powracające koszmary.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezrównana w researchu, znajomości historii i starych języków.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 85,
      Historia: 70,
      'Język Obcy (Łacina)': 60,
      'Język Obcy (Greka Starożytna)': 50,
      Okultyzm: 55,
      Spostrzegawczość: 50,
      Wycena: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_dorothy_magnifier',
        name: 'Lupa kieszonkowa',
        category: 'tool',
      },
      {
        id: 'eq_dorothy_notes',
        name: 'Zeszyt z odręcznymi tłumaczeniami',
        category: 'document',
      },
      {
        id: 'eq_dorothy_flashlight',
        name: 'Lampa elektryczna (latarka)',
        category: 'tool',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_gerald_grant_1920s',
    era: 'classic',
    archetype: 'action',
    name: 'Gerald Grant',
    occupation: 'Wojskowy',
    age: 32,
    gender: 'male',
    portraitUrl: '/portraits/predefined/gerald-grant.webp',
    str: 75,
    dex: 65,
    con: 70,
    app: 50,
    pow: 60,
    edu: 55,
    siz: 70,
    int: 60,
    luck: 50,
    hp: 14,
    maxHp: 14,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Weteran I Wojny Światowej, który walczył we Francji. Po powrocie do kraju nie potrafił odnaleźć się w cywilnym życiu. Pracuje jako ochroniarz oraz instruktor strzelectwa, wciąż prześladowany przez wspomnienia z frontu.',
    birthplace: 'Chicago, USA',
    residence: 'Arkham, Downtown',
    characterConcept: 'Weteran wojenny szukający ukojenia i celu w obronie innych.',
    ideology: 'Tylko siła i dyscyplina zapobiegają kompletnemu chaosowi.',
    significantPerson: 'Młodsza siostra, dla której stara się zachować resztki normalności.',
    meaningfulLocation: 'Zimna, zamglona strzelnica na obrzeżach miasta.',
    treasuredPossession: 'Stara apteczka polowa z frontu we Francji.',
    traits: ['Milczący', 'Zdyscyplinowany', 'Napięty'],
    description: 'Szeroki w barach mężczyzna o krótkich wojskowych włosach i uważnym, czujnym spojrzeniu.',
    backstory: 'Po powrocie z okopów Argonnów Gerald zmagał się z wojenną traumą. Zaciągnął się do ochrony transportów kolejowych w Arkham, gdzie niedawno był świadkiem napadu na pociąg, w którym napastnicy używali nieludzkiej siły i dziwnej broni.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Doskonały w walce, posługiwaniu się bronią palną i przetrwaniu w trudnych warunkach.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Długa)': 70,
      'Broń Palna (Krótka)': 60,
      'Walka Wręcz': 65,
      Przetrwanie: 60,
      'Pierwsza Pomoc': 50,
      Zastraszanie: 55,
      Spostrzegawczość: 50,
      Wspinaczka: 45,
      Skradanie: 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_gerald_rifle',
        name: 'Karabin Springfield M1903',
        category: 'weapon',
        description: 'Karabin wojskowy z czasów wojny.',
        modifiers: { damage: '2d6+4', range: '110 yards' },
      },
      { id: 'eq_gerald_canteen', name: 'Manierka wojskowa', category: 'tool' },
      { id: 'eq_gerald_medkit', name: 'Apteczka polowa', category: 'medical' },
    ],
  },
  {
    id: 'pref_agnes_mason_1920s',
    era: 'classic',
    archetype: 'action',
    name: 'Agnes Mason',
    occupation: 'Pilot',
    age: 26,
    gender: 'female',
    portraitUrl: '/portraits/predefined/agnes-mason.webp',
    str: 60,
    dex: 75,
    con: 65,
    app: 60,
    pow: 65,
    edu: 60,
    siz: 55,
    int: 65,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Jedna z pierwszych kobiet-pilotów w Nowej Anglii. Prowadzi firmę wykonującą loty pocztowe i transportowe. Kocha adrenalinę i otwarte przestrzenie. Nigdy nie odmawia podjęcia ryzykownego zlecenia.',
    birthplace: 'Gloucester, USA',
    residence: 'Arkham / Lotnisko',
    characterConcept: 'Niezależna pionierka lotnictwa o wielkiej odwadze.',
    ideology: 'Z góry świat wydaje się prosty i czysty; na ziemi wszystko jest skomplikowane.',
    significantPerson: 'Jej mechanik pokładowy, wierny stary wyjadacz, z którym naprawia samolot.',
    meaningfulLocation: 'Otwarty kokpit jej dwupłatowca wysoko w chmurach.',
    treasuredPossession: 'Ciężki klucz francuski z wygrawerowanym jej imieniem.',
    traits: ['Śmiała', 'Zaradna', 'Niecierpliwa'],
    description: 'Niska, energiczna kobieta w skórzanej kurtce lotniczej i goglach. Pachnie smarem i benzyną.',
    backstory: 'Agnes latała z pocztą w najgorsze burze. Jednak podczas nocnego lotu nad bagnami w pobliżu Innsmouth widziała z wysokości dziwne, fosforyzujące światła pod powierzchnią wody, które układały się w nienaturalne geometryczne wzory.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezwykle zręczna, zna się na maszynach i nawigacji.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Pilotowanie (Samoloty)': 70,
      Mechanika: 60,
      Nawigacja: 55,
      Spostrzegawczość: 60,
      Elektryka: 45,
      Strzelanie: 40,
      'Prowadzenie Samochodu': 50,
      'Walka Wręcz': 40,
      Unik: 37,
    },
    equipment: [
      {
        id: 'eq_agnes_goggles',
        name: 'Gogle i skórzana pilotka',
        category: 'personal',
      },
      {
        id: 'eq_agnes_wrench',
        name: 'Klucz francuski',
        category: 'tool',
        description: 'Ciężkie narzędzie, może służyć jako broń improwizowana.',
      },
      {
        id: 'eq_agnes_map',
        name: 'Mapy lotnicze regionu',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_henry_whitman_1920s',
    era: 'classic',
    archetype: 'healer',
    name: 'Dr Henry Whitman',
    occupation: 'Lekarz',
    age: 41,
    gender: 'male',
    portraitUrl: '/portraits/predefined/henry-whitman.webp',
    str: 50,
    dex: 60,
    con: 60,
    app: 60,
    pow: 65,
    edu: 85,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Uznany chirurg ogólny pracujący w szpitalu w Arkham. W czasie wojny służył w szpitalach polowych, gdzie nauczył się operować pod presją czasu i pod ostrzałem. Zawsze opanowany i profesjonalny.',
    birthplace: 'Philadelphia, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Opanowany chirurg ratujący życie w najtrudniejszych warunkach.',
    ideology: 'Zadaniem lekarza jest walka ze śmiercią, bez względu na okoliczności.',
    significantPerson: 'Ordynator szpitala w Arkham, który ufa jego nerwom w trudnych przypadkach.',
    meaningfulLocation: 'Sterylna, choć duszna sala operacyjna.',
    treasuredPossession: 'Mosiężna torba lekarska, która przeszła z nim przez okopy.',
    traits: ['Opanowany', 'Precyzyzyjny', 'Sceptyczny'],
    description: 'Postawny mężczyzna o gładko ogolonej twarzy i zmęczonym, lecz pewnym wzroku. Nosi dobrze skrojony garnitur pod lekarskim fartuchem.',
    backstory: 'Dr Whitman operował rannych pod Somą. W szpitalu w Arkham spotkał pacjenta, z którego ran wyciągnął tkankę przypominającą koralowiec - tkankę, która pulsowała życiem jeszcze przez godzinę po usunięciu.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Najlepszy specjalista od leczenia ran fizycznych i znajomości biologii.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 75,
      'Nauka (Biologia)': 65,
      'Nauka (Farmacja)': 55,
      Psychologia: 55,
      Spostrzegawczość: 60,
      'Język Obcy (Łacina)': 50,
      Perswazja: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_henry_bag',
        name: 'Torba lekarska',
        category: 'medical',
        description: 'Zawiera stetoskop, skalpele i podstawowe leki.',
      },
      {
        id: 'eq_henry_morphine',
        name: 'Ampułki z morfiną',
        category: 'medical',
        description: 'Do łagodzenia silnego bólu.',
      },
      {
        id: 'eq_henry_bandages',
        name: 'Zestaw sterylnych bandaży',
        category: 'medical',
      },
    ],
  },
  {
    id: 'pref_evelyn_sterling_1920s',
    era: 'classic',
    archetype: 'healer',
    name: 'Dr Evelyn Sterling',
    occupation: 'Lekarz',
    age: 36,
    gender: 'female',
    portraitUrl: '/portraits/predefined/evelyn-sterling.webp',
    str: 45,
    dex: 55,
    con: 55,
    app: 65,
    pow: 70,
    edu: 80,
    siz: 50,
    int: 75,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Psychiatra pracująca w azylu Arkham Sanitarium. Bada przypadki ciężkich psychoz i nietypowych urojeń. Interesuje się nowatorskimi metodami psychoanalizy, starając się zrozumieć najgłębsze zakamarki ludzkiego umysłu.',
    birthplace: 'Boston, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Psychoanalityczka zgłębiająca sekrety ludzkiego umysłu i obłędu.',
    ideology: 'Szaleństwo nie jest chaosem; to tylko inny język, który musimy nauczyć się rozumieć.',
    significantPerson: 'Jej były pacjent, który przed ucieczką z azylu narysował na ścianie skomplikowane mapy gwiezdne.',
    meaningfulLocation: 'Cichy, wyciszony gabinet terapeutyczny w Arkham Sanitarium.',
    treasuredPossession: 'Notes z zapiskami snów pacjentów.',
    traits: ['Cierpliwa', 'Uważna', 'Wnikliwa'],
    description: 'Spokojna kobieta o badawczym spojrzeniu i chłodnym głosie. Zawsze ma przy sobie notes i ołówek do spisywania reakcji rozmówców.',
    backstory: 'Evelyn Sterling bada przypadki nagłych załamań nerwowych u mieszkańców Arkham. Odkryła, że wielu pacjentów bez kontaktu ze sobą powtarza te same słowa w nieznanym języku (F\'thagn) i rysuje tę samą geometryczną figurę.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Kluczowa postać do leczenia utraty Poczytalności (SAN) i analizowania zachowań.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Psychoanaliza: 75,
      Psychologia: 70,
      Medycyna: 60,
      'Pierwsza Pomoc': 55,
      'Nauka (Medycyna Sądowa)': 50,
      Spostrzegawczość: 55,
      'Urok Osobisty': 50,
      'Korzystanie z Bibliotek': 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_evelyn_records',
        name: 'Akta pacjentów',
        category: 'document',
        description: 'Notatki dotyczące nietypowych przypadków schizofrenii.',
      },
      {
        id: 'eq_evelyn_sedatives',
        name: 'Środki uspokajające',
        category: 'medical',
      },
      {
        id: 'eq_evelyn_journal',
        name: 'Notes z zapiskami snów',
        category: 'document',
      },
    ],
  },

  // ==========================================================================
  // ERA: WSPÓŁCZESNOŚĆ (Modern) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDÇZY (Investigator) ---
  {
    id: 'pref_david_miller_modern',
    era: 'modern',
    archetype: 'investigator',
    name: 'David Miller',
    occupation: 'Dziennikarz',
    age: 34,
    gender: 'male',
    portraitUrl: '/portraits/predefined/david-miller.webp',
    str: 55,
    dex: 60,
    con: 55,
    app: 60,
    pow: 65,
    edu: 70,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Niezależny dziennikarz i twórca popularnego podcastu o niewyjaśnionych zagadkach i zjawiskach paranormalnych. Bardzo aktywny w sieci, dociera do informacji ukrywanych przez urzędników.',
    birthplace: 'Nowy Jork, USA',
    residence: 'Boston, Back Bay',
    characterConcept: 'Nowoczesny podcaster śledczy szukający prawdy o zjawiskach nadprzyrodzonych.',
    ideology: 'Internet pozwala nam obejść cenzurę i dotrzeć do prawdy, którą inni chcą ukryć.',
    significantPerson: 'Jego wierny słuchacz i patron, który podsyła mu najciekawsze i najbardziej niebezpieczne tematy.',
    meaningfulLocation: 'Dźwiękoszczelny domowy kącik studyjny z mikrofonami.',
    treasuredPossession: 'Smartfon z unikalną bazą kontaktów i nagrań audio.',
    traits: ['Komunikatywny', 'Ciekawski', 'Sceptyczny'],
    description: 'Młody mężczyzna w okularach, o luźnym stylu ubioru (t-shirt i jeansowa kurtka). Zawsze ma przy sobie smartfon i słuchawki.',
    backstory: 'David Miller założył podcast „Poza Granicą Prawdy” po tym, jak jego dawny artykuł o zniknięciach ludzi w lasach Maine został usunięty z ogólnokrajowego portalu informacyjnego bez podania przyczyny.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Świetny w technologiach cyfrowych, pozyskiwaniu informacji i wywiadach.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 65,
      Komputery: 60,
      Perswazja: 60,
      Psychologia: 55,
      'Korzystanie z Bibliotek': 55,
      'Sztuka/Rzemiosło (Podcast)': 50,
      Nasłuchiwanie: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_david_smartphone',
        name: 'Najnowszy smartfon',
        category: 'tool',
        description: 'Służy do nagrywania, kontaktu i GPS.',
      },
      {
        id: 'eq_david_laptop',
        name: 'Laptop ze stacją audio',
        category: 'tool',
      },
      {
        id: 'eq_david_recorder',
        name: 'Mikrofon kierunkowy',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_chloe_vance_modern',
    era: 'modern',
    archetype: 'investigator',
    name: 'Chloe Vance',
    occupation: 'Prywatna Detektyw',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/chloe-vance.webp',
    str: 50,
    dex: 70,
    con: 55,
    app: 65,
    pow: 70,
    edu: 65,
    siz: 50,
    int: 75,
    luck: 65,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Była analityczka agencji wywiadowczej, obecnie pracująca na własny rachunek jako prywatny detektyw. Specjalizuje się w cyber-bezpieczeństwie oraz tropieniu zaginionych ludzi.',
    birthplace: 'Washington D.C., USA',
    residence: 'Boston, South End',
    characterConcept: 'Analityczna detektyw łącząca biały wywiad (OSINT) z działaniem w terenie.',
    ideology: 'Cyfrowy ślad nigdy nie kłamie; każdy zostawia po sobie jakieś okruszki danych.',
    significantPerson: 'Jej dawny mentor z agencji wywiadowczej, który ostrzega ją przed niebezpiecznymi zapytaniami sieciowymi.',
    meaningfulLocation: 'Ciemny pokój rozświetlony blaskiem kilku monitorów.',
    treasuredPossession: 'Zabezpieczony, szyfrowany ultrabook o potężnej mocy obliczeniowej.',
    traits: ['Analityczna', 'Dyskretna', 'Zdecydowana'],
    description: 'Kobieta o chłodnym spojrzeniu, z włosami spiętymi w krótki kucyk. Nosi ciemne ubrania taktyczne i sportowe buty.',
    backstory: 'Chloe odeszła z agencji rządowej, gdy jej analizy aktywności podejrzanych serwerów w tak zwanej ciemnej sieci (dark web) zaczęły wskazywać na finansowanie dziwnych rytuałów przez globalne korporacje.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Mistrzyni hakowania, dyskrecji oraz walki wręcz obronnej.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Komputery: 70,
      Skradanie: 65,
      Spostrzegawczość: 60,
      'Broń Palna (Krótka)': 55,
      Psychologia: 55,
      'Walka Wręcz': 50,
      Ślusarstwo: 45,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_chloe_glock',
        name: 'Pistolet Glock 19',
        category: 'weapon',
        description: 'Niezawodny pistolet 9mm.',
        modifiers: { damage: '1d10', range: '15 yards' },
      },
      {
        id: 'eq_chloe_laptop',
        name: 'Zabezpieczony Ultrabook',
        category: 'tool',
      },
      { id: 'eq_chloe_kit', name: 'Zestaw cyber-śledczy', category: 'tool' },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_eric_carter_modern',
    era: 'modern',
    archetype: 'scholar',
    name: 'Prof. Eric Carter',
    occupation: 'Archeolog',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/eric-carter.webp',
    str: 55,
    dex: 55,
    con: 60,
    app: 50,
    pow: 65,
    edu: 80,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Profesor archeologii cyfrowej na Uniwersytecie Harvarda. Łączy wykopaliska terenowe z modelowaniem 3D i fotogrametrią. Odkrył kilka niewyjaśnionych dotąd ruin w Ameryce Południowej.',
    birthplace: 'Boston, USA',
    residence: 'Cambridge, USA',
    characterConcept: 'Nowoczesny naukowiec badający przeszłość za pomocą skanowania laserowego LiDAR.',
    ideology: 'Ziemia i dawne ruiny kryją prawdę o pochodzeniu ludzkości, której nie ma w podręcznikach.',
    significantPerson: 'Jego student i asystent terenowy, który wspiera go przy skomplikowanym sprzęcie.',
    meaningfulLocation: 'Zapomniane, porośnięte mchem ruiny w sercu peruwiańskich Andów.',
    treasuredPossession: 'Specjalistyczny tablet z wbudowanym skanerem LiDAR.',
    traits: ['Cierpliwy', 'Dociekliwy', 'Skrupulatny'],
    description: 'Mężczyzna o siwiejących włosach i przyjaznym wyrazie twarzy. Zwykle nosi ubrania trekkingowe i ma przy sobie torbę ze sprzętem pomiarowym.',
    backstory: 'Eric Carter podczas skanowania laserowego dżungli w Gwatemali odkrył podziemną strukturę, której układ geometryczny i wielkość nie pasują do architektury Majów ani żadnej znanej cywilizacji prekolumbijskiej.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Zna się na archeologii, historii i technologiach skanowania 3D.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Archeologia: 75,
      Historia: 65,
      Komputery: 60,
      Nawigacja: 55,
      'Nauka (Fizyka)': 50,
      'Korzystanie z Bibliotek': 50,
      'Język Obcy (Hiszpański)': 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_eric_tablet',
        name: 'Wstrząsoodporny tablet ze skanerem LiDAR',
        category: 'tool',
      },
      {
        id: 'eq_eric_gps',
        name: 'Odbiornik GPS satelitarny',
        category: 'tool',
      },
      { id: 'eq_eric_tool', name: 'Multitool Leatherman', category: 'tool' },
    ],
  },
  {
    id: 'pref_elena_rostova_modern',
    era: 'modern',
    archetype: 'scholar',
    name: 'Dr Elena Rostova',
    occupation: 'Lingwistka',
    age: 37,
    gender: 'female',
    portraitUrl: '/portraits/predefined/elena-rostova.webp',
    str: 45,
    dex: 60,
    con: 50,
    app: 60,
    pow: 75,
    edu: 85,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Światowej sławy lingwistka i kryptolog pracująca na MIT. Specjalizuje się w deszyfrowaniu wymarłych języków oraz nieznanych kodów starożytności. Współpracowała z rządami przy łamaniu trudnych szyfrów.',
    birthplace: 'Petersburg, Rosja',
    residence: 'Boston, USA',
    characterConcept: 'Genialna kryptolog i lingwistka potrafiąca złamać każdy kod.',
    ideology: 'Język to klucz do ludzkiego myślenia; bez względu na to, jak stary czy obcy jest zapis, da się go odczytać.',
    significantPerson: 'Jej brat, który pracuje w dziale bezpieczeństwa sieciowego i pomaga jej przy analizach cyfrowych.',
    meaningfulLocation: 'Jej gabinet akademicki na MIT, zastawiony tablicami pokrytymi wzorami i symbolami.',
    treasuredPossession: 'Unikalny zestaw rzadkich słowników lingwistycznych.',
    traits: ['Genialna', 'Spokojna', 'Skupiona'],
    description: 'Kobieta o bystrych oczach za okularami. Porusza się z elegancją i mówi z lekkim, wschodnioeuropejskim akcentem.',
    backstory: 'Elena Rostova pracowała nad łamaniem kodów wojskowych. Jednak gdy otrzymała od anonimowego nadawcy skan prastarego, nieznanego zwoju znalezionego w jaskiniach na Bliskim Wschodzie, odkryła powtarzający się wzór, który wywołuje u niej stany lękowe.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Geniusz lingwistyczny i analityczny, odczytuje najtrudniejsze kody.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Język Obcy (Sumeryjski)': 70,
      'Język Obcy (Łacina)': 60,
      Kryptografia: 75,
      Komputery: 60,
      'Korzystanie z Bibliotek': 70,
      Historia: 55,
      Spostrzegawczość: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_elena_device',
        name: 'Zaszyfrowany pendrive i dysk zewnętrzny',
        category: 'tool',
      },
      {
        id: 'eq_elena_dictionary',
        name: 'Rzadkie słowniki lingwistyczne',
        category: 'document',
      },
      {
        id: 'eq_elena_glasses',
        name: 'Okulary z filtrem światła niebieskiego',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_marcus_vance_modern',
    era: 'modern',
    archetype: 'action',
    name: 'Marcus Vance',
    occupation: 'Wojskowy',
    age: 35,
    gender: 'male',
    portraitUrl: '/portraits/predefined/marcus-vance.webp',
    str: 75,
    dex: 70,
    con: 70,
    app: 50,
    pow: 60,
    edu: 60,
    siz: 70,
    int: 65,
    luck: 50,
    hp: 14,
    maxHp: 14,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Były komandos sił specjalnych, obecnie pracujący jako prywatny doradca do spraw bezpieczeństwa w strefach wysokiego ryzyka. Niezwykle opanowany pod ostrzałem.',
    birthplace: 'San Diego, USA',
    residence: 'Dallas / W podróży',
    characterConcept: 'Profesjonalny najemnik i komandos o wybitnych zmysłach taktycznych.',
    ideology: 'Na polu bitwy nie ma miejsca na wahanie; liczy się tylko wykonanie zadania i przeżycie.',
    significantPerson: 'Dawny dowódca, który nauczył go wszystkiego o przetrwaniu.',
    meaningfulLocation: 'Piaszczyste poligony lub duszne strefy konfliktów.',
    treasuredPossession: 'Kamizelka taktyczna, która ocaliła mu życie podczas misji w Iraku.',
    traits: ['Opanowany', 'Czujny', 'Twardy'],
    description: 'Silnie zbudowany mężczyzna o krótkich włosach i surowych rysach twarzy. Porusza się z precyzyjną, drapieżną sprawnością.',
    backstory: 'Marcus spędził dziesięć lat w jednostkach specjalnych. Po odejściu ze służby założył firmę ochroniarską. Ostatnio jego zespół ochraniał transport korporacyjny w Afryce, który został zaatakowany przez istoty niebędące ludźmi.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Najwyższa sprawność bojowa, ekspert od broni palnej, taktyki i przetrwania.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Krótka)': 75,
      'Broń Palna (Długa)': 70,
      'Walka Wręcz': 70,
      Przetrwanie: 60,
      'Pierwsza Pomoc': 55,
      Spostrzegawczość: 55,
      Zastraszanie: 50,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_marcus_hk',
        name: 'Karabinek H&K 416',
        category: 'weapon',
        description: 'Karabin szturmowy kalibru 5.56mm.',
        modifiers: { damage: '2d6', range: '100 yards' },
      },
      {
        id: 'eq_marcus_vest',
        name: 'Kamizelka taktyczna',
        category: 'personal',
      },
      {
        id: 'eq_marcus_radio',
        name: 'Zabezpieczone radio satelitarne',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_jessica_cross_modern',
    era: 'modern',
    archetype: 'action',
    name: 'Jessica Cross',
    occupation: 'Fotoreporter',
    age: 30,
    gender: 'female',
    portraitUrl: '/portraits/predefined/jessica-cross.webp',
    str: 60,
    dex: 75,
    con: 65,
    app: 60,
    pow: 65,
    edu: 65,
    siz: 55,
    int: 70,
    luck: 60,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Fotoreporterka wojenna i wspinaczka ekstremalna. Relacjonowała konflikty na całym świecie. Posiada niezwykły zmysł orientacji w terenie i kocha ryzyko.',
    birthplace: 'Denver, USA',
    residence: 'Seattle, USA',
    characterConcept: 'Odważna fotografka wojenna i sportsmenka uwielbiająca adrenalinę.',
    ideology: 'Zdjęcie mówi więcej niż tysiąc słów; moim celem jest pokazanie prawdziwego oblicza świata.',
    significantPerson: 'Jej brat, alpinista, z którym zdobywała najtrudniejsze szczyty.',
    meaningfulLocation: 'Góry Skaliste lub zniszczone przez wojnę ulice miast Bliskiego Wschodu.',
    treasuredPossession: 'Wstrząsoodporny plecak turystyczny pełen cennego sprzętu fotograficznego.',
    traits: ['Odważna', 'Energiczna', 'Spostrzegawcza'],
    description: 'Sprawna kobieta o wysportowanej sylwetce, z aparatem fotograficznym przewieszonym przez ramię. Nosi sportowe ubrania trekkingowe.',
    backstory: 'Jessica pracowała w rejonach wojennych. Podczas ostatniej wyprawy w wysokie góry Tybetu sfotografowała w zaśnieżonej rozpadlinie wejście do jaskini o nienaturalnie gładkich ścianach oraz ogromne, trójpalczaste ślady na śniegu.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Wyjątkowo sprawna fizycznie, doskonała w robieniu zdjęć i wspinaczce.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Sztuka/Rzemiosło (Fotografia)': 75,
      Wspinaczka: 70,
      Spostrzegawczość: 65,
      Nawigacja: 60,
      Nasłuchiwanie: 55,
      Przetrwanie: 50,
      Skradanie: 50,
      Unik: 37,
    },
    equipment: [
      {
        id: 'eq_jessica_camera',
        name: 'Aparat cyfrowy Sony Alpha z zoomem',
        category: 'tool',
      },
      {
        id: 'eq_jessica_rope',
        name: 'Lina wspinaczkowa i karabinki',
        category: 'tool',
      },
      {
        id: 'eq_jessica_backpack',
        name: 'Wstrząsoodporny plecak turystyczny',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_christian_cole_modern',
    era: 'modern',
    archetype: 'healer',
    name: 'Dr Christian Cole',
    occupation: 'Lekarz',
    age: 43,
    gender: 'male',
    portraitUrl: '/portraits/predefined/christian-cole.webp',
    str: 50,
    dex: 60,
    con: 60,
    app: 55,
    pow: 65,
    edu: 85,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Lekarz medycyny ratunkowej pracujący w szpitalu urazowym w Chicago. Doświadczony w ratowaniu życia w skrajnych warunkach i pod ogromną presją czasu. Zawsze opanowany.',
    birthplace: 'Chicago, USA',
    residence: 'Chicago, USA',
    characterConcept: 'Lekarz urazowy potrafiący zachować absolutny spokój w obliczu tragedii.',
    ideology: 'Życie ludzkie to najwyższa wartość; każda sekunda opóźnienia to strata.',
    significantPerson: 'Jego mentor, wybitny chirurg polowy z czasów jego rezydentury.',
    meaningfulLocation: 'Przepełniony i głośny Szpitalny Oddział Ratunkowy (SOR) w piątkową noc.',
    treasuredPossession: 'Zaawansowana torba reanimacyjna z profesjonalnym sprzętem.',
    traits: ['Opanowany', 'Zaradny', 'Precyzyjny'],
    description: 'Mężczyzna o bystrym i zdecydowanym spojrzeniu, o silnych dłoniach chirurga. Zwykle ubrany w zielony strój medyczny i lekki fartuch.',
    backstory: 'Christian Cole uratował tysiące istnień. Tydzień temu przyjął na SOR pacjenta z ranami szarpanymi, którego krew miała ciemnozieloną barwę i dziwny zapach ozonu. Zanim pacjent zmarł, wyszeptał mu ostrzeżenie przed "tymi z głębin".',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Genialny chirurg, najlepszy w opatrywaniu najcięższych ran fizycznych.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 80,
      'Nauka (Farmacja)': 60,
    background:
      'Psycholog kliniczna i neurobiolog zajmująca się badaniem głębokiej traumy i zaburzeń percepcji. Prowadzi badania nad wpływem silnego szoku na mózg człowieka.',
    birthplace: 'Londyn, Anglia',
    residence: 'Boston, USA',
    characterConcept: 'Neurolog i psychoterapeutka badająca granice percepcji i stany traumatyczne.',
    ideology: 'Nauka potrafi uzdrowić nawet najbardziej okaleczony umysł, o ile zrozumiemy źródło jego lęku.',
    significantPerson: 'Jej brat, naukowiec pracujący w laboratorium biochemicznym, który wspiera ją w badaniach.',
    meaningfulLocation: 'Cichy, jasny gabinet z wygodną leżanką terapeutyczną.',
    treasuredPossession: 'Tablet zawierający unikalne bazy danych o snach pacjentów.',
    traits: ['Wnikliwa', 'Empatyczna', 'Opanowana'],
    description: 'Kobieta o łagodnych rysach twarzy, ciemnych, spiętych włosach i spokojnym, kojącym głosie.',
    backstory: 'Dr Patel badała ofiary masowej paniki w metrze. Odkryła u wszystkich badanych pacjentów niemal identyczne anomalie w obszarze płata skroniowego oraz powtarzające się koszmary przedstawiające geometryczne miasto o nienaturalnej architekturze.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Kluczowa badaczka do stabilizowania zdrowia psychicznego (Poczytalności) zespołu.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Psychoanaliza: 75,
      Psychologia: 70,
      Medycyna: 60,
      'Pierwsza Pomoc': 50,
      'Nauka (Neurobiologia)': 65,
      Spostrzegawczość: 55,
      'Korzystanie z Bibliotek': 50,
      Komputery: 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_maya_tablet',
        name: 'Tablet z dokumentacją pacjentów',
        category: 'tool',
      },
      {
        id: 'eq_maya_drugs',
        name: 'Przenośna apteczka z lekami psychotropowymi',
        category: 'medical',
      },
      {
        id: 'eq_maya_glass',
        name: 'Dziennik analiz snów pacjentów',
        category: 'document',
      },
    ],
  },

  // ==========================================================================
  // ARCHETYP: MISTYK (Mystic) - 6 POSTACI (2 na epoke)
  // ==========================================================================

  // --- GASLIGHT MYSTIC ---
  {
    id: 'pref_silas_thorne_gaslight',
    era: 'gaslight',
    archetype: 'mystic',
    name: 'Silas Thorne',
    occupation: 'Okultysta',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/silas-thorne.webp',
    str: 45,
    dex: 50,
    con: 50,
    app: 40,
    pow: 85,
    edu: 70,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 10,
    maxHp: 10,
    san: 65,
    maxSan: 99,
    mp: 17,
    maxMp: 17,
    background:
      'Dawny profesor filozofii, ktory po serii niepokojacych odkryc w bibliotece Uniwersytetu Londynskiego poswiecil zycie badaniu granic miedzy swiatem widzialnym a tym, co kryje sie poza zaslona. Jego gabinet pelny jest starozytnych zwojow i osobliwych artefaktow.',
    birthplace: 'Londyn, Anglia',
    residence: 'Londyn, Bloomsbury',
    characterConcept: 'Dawny filozof, który porzucił akademicki racjonalizm na rzecz badania magii i okultyzmu.',
    ideology: 'Nasz świat to tylko cienka zasłona skrywająca potężniejsze, mroczne siły.',
    significantPerson: 'Dawny wuj, ekscentryczny badacz kabały, który zapisał mu swoją bibliotekę.',
    meaningfulLocation: 'Ciemny gabinet zastawiony szafami pełnymi dziwnych zwojów i słojów.',
    treasuredPossession: 'Oprawny w skórę grimuar pełen unikalnych notatek rytualnych.',
    traits: ['Tajemniczy', 'Dociekliwy', 'Ekscentryczny'],
    description: 'Starszy mężczyzna o chudej sylwetce, z długą, szpakowatą brodą i przenikliwym spojrzeniu czarnych oczu.',
    backstory: 'Silas Thorne odkrył w archiwach uniwersyteckich fragmenty tekstu opisujące istoty żyjące w wymiarach poza czasem. Od tamtej pory prowadzi prywatne badania mające na celu ochronę przed tym, co nadchodzi.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo wysoka MOC. Ekspert od okultyzmu i starozytnych jezykow.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 75,
      'Korzystanie z Bibliotek': 65,
      'Jezyk Obcy (Lacina)': 55,
      'Jezyk Obcy (Greka)': 40,
      Historia: 60,
      Spostrzegawczosc: 55,
      Psychologia: 45,
      Nasluchiwanie: 50,
      Unik: 25,
    },
    equipment: [
      {
        id: 'eq_silas_grimoire',
        name: 'Oprawny w skore grimuar',
        category: 'occult',
        description: 'Pelny odrecznie zapisanych not i rysunkow pentagramow.',
      },
      {
        id: 'eq_silas_pendant',
        name: 'Srebrny amulet z siglem',
        category: 'occult',
        description: 'Odziedziczony po mistrzu - daje poczucie ochrony.',
      },
      { id: 'eq_silas_candles', name: 'Zestaw rytualnych swiec', category: 'occult' },
    ],
  },
  {
    id: 'pref_vivienne_moreau_gaslight',
    era: 'gaslight',
    archetype: 'mystic',
    name: 'Vivienne Moreau',
    occupation: 'Medium spirytystyczne',
    age: 34,
    gender: 'female',
    portraitUrl: '/portraits/predefined/vivienne-moreau.webp',
    str: 40,
    dex: 60,
    con: 50,
    app: 65,
    pow: 80,
    edu: 55,
    siz: 45,
    int: 75,
    luck: 70,
    hp: 9,
    maxHp: 9,
    san: 70,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Popularna medium na londynskich salonach. Wielu uwaza ja za szarlatanke, lecz niektore z jej seansow spirytystycznych przyniosly informacje, ktorych nie mogla poznac w zaden racjonalny sposob. Sama nie jest pewna natury swojego daru.',
    birthplace: 'Paryż, Francja',
    residence: 'Londyn',
    characterConcept: 'Towarzyskie medium o autentycznym, choć przerażającym darze kontaktu z zaświatami.',
    ideology: 'Granica między życiem a śmiercią jest niezwykle płynna.',
    significantPerson: 'Duch małej dziewczynki, który nawiedza ją od dzieciństwa i ostrzega przed niebezpieczeństwem.',
    meaningfulLocation: 'Czerwony pokój seansów oświetlony blaskiem świec.',
    treasuredPossession: 'Talia kart Tarota o nietypowych symbolach na rewersach.',
    traits: ['Intuicyjna', 'Urocza', 'Wrażliwa'],
    description: 'Elegancka kobieta o bladoszarych oczach i melancholijnym uśmiechu. Nosi bogato zdobione suknie i koronkowy welon.',
    backstory: 'Vivienne zaczynała jako modne medium dla rozrywki arystokracji. Podczas jednego z seansów przemówił przez nią byt, który podał szczegóły morderstwa popełnionego w zapomnianym doku, co sprowadziło na nią uwagę niebezpiecznych ludzi.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wysoka MOC i Szczescie. Perswazja i intuicja.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 60,
      Perswazja: 65,
      Psychologia: 60,
      Spostrzegawczosc: 55,
      Nasluchiwanie: 60,
      'Urok Osobisty': 55,
      'Korzystanie z Bibliotek': 40,
      Historia: 35,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_viv_cards',
        name: 'Talia kart Tarota',
        category: 'occult',
        description: 'Recznie malowana talia z nieznanymi symbolami na rewersach.',
      },
      {
        id: 'eq_viv_crystal',
        name: 'Kula krysztalowa',
        category: 'occult',
        description: 'Uzywana podczas seansow spirytystycznych.',
      },
      { id: 'eq_viv_veil', name: 'Czarny welon', category: 'personal' },
    ],
  },

  // --- CLASSIC MYSTIC ---
  {
    id: 'pref_nathaniel_ward_classic',
    era: 'classic',
    archetype: 'mystic',
    name: 'Nathaniel Ward',
    occupation: 'Antykwariusz / Badacz okultyzmu',
    age: 43,
    gender: 'male',
    portraitUrl: '/portraits/predefined/nathaniel-ward.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 45,
    pow: 80,
    edu: 75,
    siz: 50,
    int: 80,
    luck: 55,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Wlasciciel antykwariatu w Arkham specjalizujacego sie w rzadkich tomach i okultystycznych pamietkach. Lata kontaktu z zakazanymi tekstami daly mu wiedze, ktora wielu uznaloby za niebezpieczna. Utrzymuje kontakty z Uniwersytetem Miskatonic.',
    birthplace: 'Providence, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Antykwariusz i badacz okultyzmu skrywający niebezpieczną wiedzę.',
    ideology: 'To, co nazywamy mitami, to wspomnienia o siłach, które rządziły Ziemią przed nami.',
    significantPerson: 'Profesor Armitage z Uniwersytetu Miskatonic, z którym konsultuje najcięższe przypadki.',
    meaningfulLocation: 'Ciemne zaplecze antykwariatu oświetlone lampą naftową.',
    treasuredPossession: 'Łaciński zwój z XIV wieku zawierający fragmenty traktatu o istotach z zaświatów.',
    traits: ['Poważny', 'Wnikliwy', 'Skryty'],
    description: 'Mężczyzna w średnim wieku o bystrym, badawczym spojrzeniu. Zwykle ubrany w stary, wełniany garnitur.',
    backstory: 'Nathaniel Ward spędził lata na gromadzeniu dzieł okultystycznych. Analizując stare księgi, odkrył zbieżność między datami zaginięć mieszkańców Nowej Anglii a szczególnym układem gwiazd opisującym nadejście Yog-Sothotha.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Silna wola i szerokie wyksztalcenie. Ekspert od rzadkich ksiag.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 70,
      'Korzystanie z Bibliotek': 70,
      Wycena: 65,
      Historia: 55,
      'Jezyk Obcy (Lacina)': 50,
      Spostrzegawczosc: 55,
      Psychologia: 45,
      Nasluchiwanie: 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_nath_tome',
        name: 'Lacinski zwoj z XIV wieku',
        category: 'occult',
        description: 'Fragment traktatu o istotach z zaswiatow.',
      },
      {
        id: 'eq_nath_loupe',
        name: 'Lupa jubilerska',
        category: 'tool',
        description: 'Do odczytywania drobnych inskrypcji.',
      },
      { id: 'eq_nath_journal', name: 'Dziennik badan', category: 'document' },
    ],
  },
  {
    id: 'pref_iris_blackwell_classic',
    era: 'classic',
    archetype: 'mystic',
    name: 'Iris Blackwell',
    occupation: 'Wrozka / Jasnowidz',
    age: 26,
    gender: 'female',
    portraitUrl: '/portraits/predefined/iris-blackwell.webp',
    str: 40,
    dex: 60,
    con: 50,
    app: 70,
    pow: 75,
    edu: 55,
    siz: 45,
    int: 75,
    luck: 75,
    hp: 9,
    maxHp: 9,
    san: 70,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Mloda kobieta z cyganskim rodowodem, prowadzaca salon wrozbiarski w dzielnicy portowej. Ma niezwykla zdolnosc wyczuwania emocji i niebezpieczenstwa. Jej babka przekazala jej starozytne runy i wiedzę o tym, co kryje sie w ciemnosciach.',
    birthplace: 'Salem, USA',
    residence: 'Arkham, Dzielnica Portowa',
    characterConcept: 'Młoda jasnowidzka o cygańskich korzeniach i wielkim szczęściu.',
    ideology: 'Los rozmawia z nami przez symbole; trzeba tylko umieć go słuchać.',
    significantPerson: 'Jej babka, która nauczyła ją odczytywania znaczeń z run i snów.',
    meaningfulLocation: 'Mały, kolorowy namiot lub naczepa wozu wędrownego.',
    treasuredPossession: 'Zestaw kamiennych run ochronnych po babce.',
    traits: ['Intuicyjna', 'Tajemnicza', 'Sprytna'],
    description: 'Młoda kobieta o gęstych, ciemnych włosach i dużych, wyrazistych oczach. Często nosi wzorzyste szale i wiszące kolczyki.',
    backstory: 'Iris Blackwell zarabia na życie wróżeniem marynarzom w porcie. Jednak ostatnio jej sny zdominował obraz olbrzymiej, mrocznej sylwetki wyłaniającej się z wody, co skłoniło ją do poszukiwania kogoś, kto pomoże jej zrozumieć to ostrzeżenie.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo wysokie Szczescie (75). Intuicyjna i spostrzegawcza.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 55,
      Psychologia: 65,
      Spostrzegawczosc: 60,
      Nasluchiwanie: 55,
      'Urok Osobisty': 60,
      Perswazja: 50,
      'Sztuka/Rzemioslo (Kartomancja)': 70,
      Historia: 35,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_iris_runes',
        name: 'Zestaw starozytnych run',
        category: 'occult',
        description: 'Kamienne runy przekazane przez babke.',
      },
      {
        id: 'eq_iris_shawl',
        name: 'Haftowany szal',
        category: 'personal',
        description: 'Z tajemniczymi symbolami wplecionymi w wzor.',
      },
      { id: 'eq_iris_herbs', name: 'Woreczek ziol ochronnych', category: 'occult' },
    ],
  },

  // --- MODERN MYSTIC ---
  {
    id: 'pref_victor_crowley_modern',
    era: 'modern',
    archetype: 'mystic',
    name: 'Victor Crowley',
    occupation: 'Parapsychologist',
    age: 44,
    gender: 'male',
    portraitUrl: '/portraits/predefined/victor-crowley.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 50,
    pow: 80,
    edu: 75,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 80,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Prywatny badacz zjawisk paranormalnych. Autor kilku książek o nawiedzonych miejscach. Choć sceptyczny wobec tanich sztuczek spirytystycznych, wielokrotnie natknął się na zjawiska, których nauka nie potrafi wyjaśnić.',
    birthplace: 'Nowy Orlean, USA',
    residence: 'Boston, USA',
    characterConcept: 'Sceptyczny badacz zjawisk paranormalnych o potężnej sile woli.',
    ideology: 'Większość to oszustwa, ale to, co pozostaje po odrzuceniu kłamstw, jest prawdziwe i przerażające.',
    significantPerson: 'Jego zmarła żona, której obietnica kontaktu z zaświatów pchnęła go do tych badań.',
    meaningfulLocation: 'Opuszczone, rzekomo nawiedzone wille o bogatej historii.',
    treasuredPossession: 'Cenny miernik pola elektromagnetycznego (EMF) z autografem pioniera parapsychologii.',
    traits: ['Sceptyczny', 'Niezłomny', 'Analityczny'],
    description: 'Poważny mężczyzna o krótkich, szpakowatych włosach, zazwyczaj noszący ciemny golf i sportową marynarkę.',
    backstory: 'Victor Crowley napisał bestseller o nawiedzeniach w Nowej Anglii. Podczas badania starej kaplicy w Dunwich zarejestrował anomalie temperaturowe i dźwiękowe, które nie pasują do żadnego znanego zjawiska fizycznego.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezwykle silna wola. Wiedza o okultyzmie i badaniach terenowych.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 70,
      Psychologia: 60,
      'Nauka (Fizyka)': 45,
      Spostrzegawczość: 60,
      'Korzystanie z Bibliotek': 60,
      Nasłuchiwanie: 55,
      Fotografia: 50,
      Perswazja: 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_victor_emf',
        name: 'Miernik pola elektromagnetycznego',
        category: 'tool',
        description: 'Wykrywa anomalie magnetyczne.',
      },
      { id: 'eq_victor_recorder', name: 'Dyktafon cyfrowy', category: 'tool' },
      {
        id: 'eq_victor_camera',
        name: 'Lustrzanka z fleszem',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_seraphina_marsh_modern',
    era: 'modern',
    archetype: 'mystic',
    name: 'Seraphina Marsh',
    occupation: 'Artysta',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/seraphina-marsh.webp',
    str: 45,
    dex: 65,
    con: 50,
    app: 65,
    pow: 75,
    edu: 60,
    siz: 50,
    int: 75,
    luck: 70,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Malarka mieszkająca w klimatycznej dzielnicy bohemy. Twierdzi, że jej surrealistyczne obrazy są inspirowane snami oraz szeptami z innego wymiaru. Posiada niezwykle czułą intuicję i wrażliwość na atmosferę miejsc.',
    birthplace: 'Innsmouth, USA',
    residence: 'Boston, North End',
    characterConcept: 'Wrażliwa artystka malująca obrazy inspirowane szeptami z koszmarów.',
    ideology: 'Sztuka to jedyny sposób, by ludzki umysł mógł wyrazić prawdy zbyt straszne dla języka.',
    significantPerson: 'Jej marszand, który sprzedaje jej dzieła, choć sam boi się na nie patrzeć.',
    meaningfulLocation: 'Jasne atelier pełne płócien, pachnące terpentyną i farbami.',
    treasuredPossession: 'Szkicownik węglowy wypełniony surrealistycznymi rysunkami.',
    traits: ['Wrażliwa', 'Intuicyjna', 'Melancholijna'],
    description: 'Młoda kobieta o artystycznym nieładzie we włosach i farbie na dłoniach. Ubiera się w luźne swetry i chusty.',
    backstory: 'Seraphina opuściła rodzinne Innsmouth jako nastolatka. Od tamtej pory maluje obrazy przedstawiające podwodne miasta i rybie hybrydy, twierdząc, że to tylko sny. Ostatnio jednak zaczęła słyszeć te same szepty na jawie.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wysokie Szczęście. Intuicyjna i spostrzegawcza.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Sztuka/Rzemiosło (Malarstwo)': 75,
      Spostrzegawczość: 65,
      Psychologia: 60,
      Nasłuchiwanie: 55,
      Okultyzm: 50,
      'Urok Osobisty': 55,
      Historia: 40,
      'Język Obcy (Francuski)': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_sera_sketch',
        name: 'Szkicownik węglowy',
        category: 'personal',
        description: 'Pełen niepokojących, surrealistycznych rysunków.',
      },
      {
        id: 'eq_sera_amulet',
        name: 'Srebrny talizman',
        category: 'occult',
        description: 'Pamiątka rodzinna o nieznanym pochodzeniu.',
      },
];

export const PREDEFINED_CHARACTERS: PredefinedCharacter[] =
  BASE_PREDEFINED_CHARACTERS.map((character) => ({
    ...character,
    equipment: buildPredefinedEquipment(character),
  }));

export function getPredefinedCharactersByEra(
  era: string
): PredefinedCharacter[] {
  if (era === 'gaslight' || era === 'classic' || era === 'modern') {
    return PREDEFINED_CHARACTERS.filter((character) => character.era === era);
  }
  return [];
}
