import { Character } from '@/lib/types';
import { buildPredefinedEquipment } from './predefined-equipment';

export type PredefinedCharacterEra = 'gaslight' | 'classic' | 'modern';
export type PredefinedCharacterArchetype =
  | 'investigator'
  | 'scholar'
  | 'action'
  | 'healer'
  | 'mystic';

export interface PredefinedCharacter extends Character {
  era: PredefinedCharacterEra;
  archetype: PredefinedCharacterArchetype;
}

// Baza 30 predefiniowanych postaci zbalansowanych pod mechanike CoC 7e (3 ery x 5 archetypow x 2 plcie = 30 postaci)
const BASE_PREDEFINED_CHARACTERS: PredefinedCharacter[] = [
  // ==========================================================================
  // ERA: LATA 90. XIX WIEKU (1890s / Gaslight) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDĆZY (Investigator) ---
  {
    id: 'pref_arthur_pendleton_1890s',
    era: 'gaslight',
    archetype: 'investigator',
    name: 'Arthur Pendleton',
    occupation: 'Dziennikarz',
    age: 42,
    gender: 'male',
    portraitUrl: '/portraits/predefined/arthur-pendleton.webp',
    str: 55,
    dex: 60,
    con: 55,
    app: 50,
    pow: 65,
    edu: 75,
    siz: 60,
    int: 70,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Weteran londyńskiego dziennikarstwa śledczego z gazety "The Pall Mall Gazette". Od piętnastu lat dokumentuje mroczną stronę epoki wiktoriańskiej – od spisków finansowych po nierozwiązane zbrodnie we mgłach East Endu. Zawsze nosi przy sobie skórzany notes z mosiężną zapinką i zepsuty zegarek po ojcu.',
    birthplace: 'Londyn, Anglia',
    residence: 'Londyn, dzielnica Chelsea',
    characterConcept: 'Dociekliwy reporter tropiący to, o czym inni boją się pisać w prasie.',
    ideology: 'Prawda i fakty są jedyną bronią chroniącą cywilizowany świat przed mrokiem i zabobonem.',
    significantPerson: 'Edward H. Sterling, redaktor naczelny "Pall Mall Gazette", który wielokrotnie chronił Arthura przed procesami o zniesławienie i więzieniem.',
    meaningfulLocation: 'Zapchlona redakcja przy Fleet Street, pachnąca tanim tytoniem, gorącym ołowiem zecerskim i atramentem.',
    treasuredPossession: 'Mosiężny zegarek kieszonkowy po ojcu, zatrzymany na godzinie 03:17 – pamiątka po nocy, w której jego ojciec zaginął bez śladu na Tamizie.',
    traits: ['Dociekliwy', 'Sceptyczny', 'Uparty'],
    description: 'Mężczyzna średniego wzrostu o lekko poszarzałej cerze i wąsach przyciętych w stylu wojskowym. Nosi lekko wytarty, tweedowy garnitur z kamizelką, a jego palce są trwale poplamione czarnym atramentem.',
    backstory: 'Arthur spędził dekady na spisywaniu historii z najuboższych dzielnic Londynu. Jednak seria ostatnich artykułów o tajemniczych zaginięciach marynarzy w dokach Limehouse doprowadziła go do odnalezienia dziwnych symetrii i bluźnierczych symboli na ścianach opuszczonych magazynów.\n\n[Kluczowa więź: Redaktor Edward H. Sterling - jedyny człowiek, który wciąż odważa się publikować jego raporty.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wnikliwy obserwator, świetny w wywiadach i zbieraniu plotek.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 65,
      Psychologia: 60,
      'Korzystanie z Bibliotek': 60,
      Perswazja: 55,
      Historia: 50,
      'Język Ojczysty (Angielski)': 75,
      Nasłuchiwanie: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_arthur_notebook',
        name: 'Skórzany notatnik i pióro',
        category: 'tool',
      },
      {
        id: 'eq_arthur_lamp',
        name: 'Lampa naftowa kieszonkowa',
        category: 'tool',
      },
      {
        id: 'eq_arthur_card',
        name: 'Legitymacja prasowa gazety',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_beatrice_vance_1890s',
    era: 'gaslight',
    archetype: 'investigator',
    name: 'Beatrice Vance',
    occupation: 'Prywatna Detektyw',
    age: 31,
    gender: 'female',
    portraitUrl: '/portraits/predefined/beatrice-vance.webp',
    str: 50,
    dex: 65,
    con: 60,
    app: 60,
    pow: 70,
    edu: 65,
    siz: 55,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Pionierka wśród wiktoriańskich śledczych, prowadząca dyskretną agencję w londyńskim Soho. Zamiast spraw małżeńskich koncentruje się na tajemniczych zaginięciach wśród arystokracji i działaniach nielegalnych stowarzyszeń.',
    birthplace: 'Bristol, Anglia',
    residence: 'Londyn, Soho',
    characterConcept: 'Niezależna śledcza działająca w cieniu patriarchalnego społeczeństwa wiktoriańskiego.',
    ideology: 'Każdy sekret, nieważne jak głęboko zakopany pod pozorami cnoty, ostatecznie wychodzi na jaw.',
    significantPerson: 'Zaginiony brat Thomas Vance, którego nagłe zniknięcie podczas badań nad sektą różokrzyżowców pchnęło ją do otwarcia agencji.',
    meaningfulLocation: 'Ciche biuro na piętrze przy Greek Street w Soho, skąd obserwuje tętniącą życiem ulicę.',
    treasuredPossession: 'Srebrny medalion ze zdjęciem brata oraz zasuszonym kwiatem wrzosu z ich rodzinnego domu.',
    traits: ['Spostrzegawcza', 'Dyskretna', 'Zdecydowana'],
    description: 'Szczupła kobieta o bystrym, przenikliwym spojrzeniu szarych oczu. Ubrana w nienaganną, praktyczną garsonkę z ciętego sukna oraz kapelusz z czarnym welonem, który pozwala jej zachować anonimowość.',
    backstory: 'Gdy policja zbagatelizowała zaginięcie Thomasa jako ucieczkę przed dłużnikami, Beatrice wzięła sprawy we własne ręce. Przeszukując jego gabinet, odnalazła szyfrowany dziennik prowadzący do podziemnych sal pod Londynem.\n\n[Kluczowa więź: Zaginiony brat Thomas - motywacja do podważania oficjalnych wersji wydarzeń.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Doskonała w ukrywaniu się, śledzeniu celów i otwieraniu zamków.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Skradanie: 70,
      Spostrzegawczość: 65,
      Ślusarstwo: 60,
      Psychologia: 55,
      'Walka Wręcz': 50,
      'Broń Palna (Krótka)': 45,
      'Szybkie Czytanie': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_beatrice_derringer',
        name: 'Mały pistolet Derringer .41',
        category: 'weapon',
        description: 'Kieszonkowy pistolet dwustrzałowy.',
        modifiers: { damage: '1d10', range: '5 yards' },
      },
      {
        id: 'eq_beatrice_lockpicks',
        name: 'Zestaw wytrychów w etui',
        category: 'tool',
      },
      {
        id: 'eq_beatrice_veil',
        name: 'Czarny welon i kapelusz maskujący',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_archibald_blackwood_1890s',
    era: 'gaslight',
    archetype: 'scholar',
    name: 'Prof. Archibald Blackwood',
    occupation: 'Profesor',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/archibald-blackwood.webp',
    str: 45,
    dex: 50,
    con: 50,
    app: 50,
    pow: 75,
    edu: 90,
    siz: 50,
    int: 80,
    luck: 50,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Wykładowca historii starożytnej na Uniwersytecie w Oxfordzie. Poświęcił ponad trzydzieści lat badaniom nad starożytną Mezopotamią i językiem sumeryjskim. Cieszy się autorytetem w kręgach akademickich w całej Europie.',
    birthplace: 'Oxford, Anglia',
    residence: 'Oxford',
    characterConcept: 'Klasyczny naukowiec szukający racjonalnych wyjaśnień w starożytnych pismach i artefaktach.',
    ideology: 'Wiedza zgromadzona przez przodków jest jedynym bastionem chroniącym ludzkość przed chaosem.',
    significantPerson: 'Profesor Henry Higgins, zmarły mentor z Oxfordu, który zaszczepił w nim pasję do asyriologii.',
    meaningfulLocation: 'Zakurzone, odgrodzone od świata archiwum Bodleian Library w Oxfordzie.',
    treasuredPossession: 'Mosiężna lupa ze szkiełkiem szlifowanym w Kairze, podarunek od mentora po pierwszych wykopaliskach.',
    traits: ['Erudyta', 'Rozważny', 'Sceptyczny'],
    description: 'Starszy szacowny mężczyzna o posiwiałych skroniach i wnikliwym spojrzeniu spomiędzy okrągłych szkieł okularów. Nosi klasyczny tweedowy garnitur z kamizelką i dewizką.',
    backstory: 'Spędziwszy życie pośród zakurzonych ksiąg, profesor uważał mity o dawnych bogach jedynie za poetycką metaforę starożytnych lęków. Wszystko zmieniło się po przeanalizowaniu tabliczki z zapomnianą inskrypcją przywiezioną z Uruku.\n\n[Kluczowa więź: Mosiężna lupa mentora - symbol naukowej dociekliwości i rzetelności.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Chodząca encyklopedia. Zna martwe języki i stare księgi.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 80,
      Historia: 75,
      'Język Obcy (Łacina)': 60,
      'Język Obcy (Egipskie Hieronimy)': 50,
      Archeologia: 65,
      Spostrzegawczość: 50,
      Psychologia: 50,
      'Nauka (Astronomia)': 40,
      Okultyzm: 45,
      Unik: 25,
    },
    equipment: [
      {
        id: 'eq_arch_briefcase',
        name: 'Skórzana aktówka',
        category: 'tool',
        description: 'Pełna notatek i wycinków prasowych.',
      },
      {
        id: 'eq_arch_magnifier',
        name: 'Lupa w mosiężnej oprawie',
        category: 'tool',
      },
      {
        id: 'eq_arch_journal',
        name: 'Dziennik wykopalisk',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_cordelia_ashford_1890s',
    era: 'gaslight',
    archetype: 'scholar',
    name: 'Cordelia Ashford',
    occupation: 'Antykwariusz',
    age: 34,
    gender: 'female',
    portraitUrl: '/portraits/predefined/cordelia-ashford.webp',
    str: 50,
    dex: 60,
    con: 55,
    app: 60,
    pow: 70,
    edu: 80,
    siz: 50,
    int: 75,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Właścicielka antykwariatu w londyńskim Kensington. Znawczyni starodruków, opraw introligatorskich oraz rzadkich inkunabułów. Znana ze zdolności bezbłędnej oceny autentyczności najstarszych manuskryptów.',
    birthplace: 'Bath, Anglia',
    residence: 'Londyn, Kensington',
    characterConcept: 'Konserwatorka ksiąg o niezwykłej intuicji do zakazanej wiedzy.',
    ideology: 'Słowo pisane przetrwa każdego monarchę; to ludzie błądzą w jego interpretacji.',
    significantPerson: 'Lord Reginald Greville, stały mecenas antykwariatu, który powierza jej najcenniejsze zbiory.',
    meaningfulLocation: 'Zaplecze antykwariatu pachnące woskiem pszczelim, starą skórą i suszonymi ziołami.',
    treasuredPossession: 'Pęk mosiężnych kluczy do podziemnego sejfu, w którym przechowuje nieokreślone katalogowo księgi.',
    traits: ['Skrupulatna', 'Dociekliwa', 'Spokojna'],
    description: 'Kobieta o subtelnych rysach i spiętych w elegancki kok kasztanowych włosach. Zawsze nosi płócienny fartuch ochronny podczas pracy z delikatnym papierem.',
    backstory: 'Cordelia przejęła sklep po wuju. Przeglądając skrytki jego kantorka, natrafiła na łaciński przekład grimoire’a o rybich hybrydach z nadmorskich osad. Od tamtej pory wie, że niektóre tomy nie powinny ujrzeć światła dziennego.\n\n[Kluczowa więź: Pęk mosiężnych kluczy do sejfu z zakazanymi dziełami.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Potrafi odczytać najstarsze pisma i ocenić każdy artefakt.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 75,
      Wycena: 70,
      Historia: 65,
      'Język Obcy (Sanskryt)': 50,
      Spostrzegawczość: 60,
      'Sztuka/Rzemiosło (Konserwacja Ksiąg)': 55,
      Perswazja: 50,
      Okultyzm: 50,
      Nasłuchiwanie: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_cord_glasses',
        name: 'Okulary do czytania',
        category: 'personal',
      },
      {
        id: 'eq_cord_monograph',
        name: 'Monografia o demonologii',
        category: 'document',
      },
      {
        id: 'eq_cord_keys',
        name: 'Pęk starych kluczy do archiwum',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_ronald_shaw_1890s',
    era: 'gaslight',
    archetype: 'action',
    name: 'Capt. Ronald Shaw',
    occupation: 'Wojskowy',
    age: 45,
    gender: 'male',
    portraitUrl: '/portraits/predefined/ronald-shaw.webp',
    str: 70,
    dex: 55,
    con: 65,
    app: 50,
    pow: 60,
    edu: 60,
    siz: 65,
    int: 65,
    luck: 50,
    hp: 13,
    maxHp: 13,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Emerytowany kapitan piechoty Jej Królewskiej Mości. Służył podczas kampanii w Indiach oraz Afganistanie. Przeszedł do rezerwy z powodem honorowych ran wojennych, lecz wciąż utrzymuje reżim wojskowy.',
    birthplace: 'York, Anglia',
    residence: 'Londyn',
    characterConcept: 'Zdyscyplinowany oficer zmagający się z demonami wojennej przeszłości.',
    ideology: 'Lojalność wobec złożonej przysięgi i towarzyszy broni jest jedyną miarą wartości człowieka.',
    significantPerson: 'Sierżant Samuel Evans, jego były ordynans, który uratował mu życie podczas odwrotu spod Kandaharu.',
    meaningfulLocation: 'Cichy salerek Klubu Oficerskiego w Londynie, gdzie spędza wieczory nad mapami.',
    treasuredPossession: 'Grawerowana srebrna piersiówka, pamiątka od kolegów z pułku z wyrytym mottem "Semper Fidelis".',
    traits: ['Szorstki', 'Opanowany', 'Honorowy'],
    description: 'Postawny mężczyzna o prostych plecach i twarzy naznaczonej głęboką blizną na lewym policzku. Jego spojrzenie jest chłodne, a głos opanowany i doniosły.',
    backstory: 'Po powrocie z kolonii Shaw nie odnalazł spokoju w miejskim zgiełku. Kiedy jego dawny kompan z pułku zginął w tajemniczym wypadku w londyńskich dokach, kapitan postanowił przeprowadzić własne śledztwo.\n\n[Kluczowa więź: Ordynans Samuel Evans - czuwa nad pamięcią poległych braci broni.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Mistrz broni palnej długiej, odporny psychicznie.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Długa)': 75,
      Zastraszanie: 60,
      'Walka Wręcz': 55,
      Jeździectwo: 50,
      Spostrzegawczość: 50,
      'Pierwsza Pomoc': 45,
      Nasłuchiwanie: 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_ronald_rifle',
        name: 'Karabin Lee-Metford .303',
        category: 'weapon',
        description: 'Celny karabin powtarzalny.',
        modifiers: { damage: '2d6+4', range: '100 yards' },
      },
      {
        id: 'eq_ronald_flask',
        name: 'Srebrna piersiówka z brandy',
        category: 'personal',
      },
      {
        id: 'eq_ronald_compass',
        name: 'Wojskowy kompas mosiężny',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_alexandra_croft_1890s',
    era: 'gaslight',
    archetype: 'action',
    name: 'Lady Alexandra Croft',
    occupation: 'Podróżnik',
    age: 28,
    gender: 'female',
    portraitUrl: '/portraits/predefined/alexandra-croft.webp',
    str: 60,
    dex: 70,
    con: 65,
    app: 60,
    pow: 65,
    edu: 70,
    siz: 55,
    int: 70,
    luck: 60,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Arystokratka, która sprzeniewierzyła się oczekiwaniom londyńskiej socjety na rzecz niebezpiecznych ekspedycji kartograficznych. Przebyła dorzecze Amazonki i bezdroża Afryki Wschodniej.',
    birthplace: 'Surrey, Anglia',
    residence: 'Londyn / W podróży',
    characterConcept: 'Niezależna badaczka terenowa szukająca wyzwań na krańcach znanego świata.',
    ideology: 'Tylko stając oko w oko z nieznanym sprawdzamy granice własnego ducha.',
    significantPerson: 'Lord George Croft, wyrozumiały ojciec, który dyskretnie finansuje jej wyprawy badawcze.',
    meaningfulLocation: 'Obozowisko pod gwiaździstym niebem w dżungli lub w wysokich partiach gór.',
    treasuredPossession: 'Oprawiony w skórę skatowanego węża dziennik z odręcznymi mapami nieznanych terytoriów.',
    traits: ['Odważna', 'Niezależna', 'Porywcza'],
    description: 'Niska, lecz nadzwyczaj wysportowana kobieta o opalonej słońcem skórze i ostrych rysach. W terenie rezygnuje z sukni na rzecz skórzanych spodni i męskiej kurtki.',
    backstory: 'Odrzuciwszy propozycje salonowych zamążpójść, Alexandra poświęciła się odkrywaniu nieznanego. W ruinach Ameryki Południowej natrafiła na płaskorzeźby przedstawiające uskrzydlone istoty, które zmotywowały ją do szukania odpowiedzi w Anglii.\n\n[Kluczowa więź: Ojciec Lord George Croft - jedyna osoba wierząca w jej powołanie.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo zwinna, świetna w nawigacji i wspinaczce.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Wspinaczka: 70,
      Nawigacja: 60,
      Spostrzegawczość: 60,
      'Broń Palna (Krótka)': 55,
      Archeologia: 50,
      Jeździectwo: 50,
      Przetrwanie: 50,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_alexandra_webley',
        name: 'Rewolwer Webley .455',
        category: 'weapon',
        description: 'Mocny brytyjski rewolwer służbowy.',
        modifiers: { damage: '1d10+2', range: '15 yards' },
      },
      { id: 'eq_alexandra_whip', name: 'Skórzany bicz', category: 'tool' },
      {
        id: 'eq_alexandra_journal',
        name: 'Notatnik podróżnika',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_alistair_sterling_1890s',
    era: 'gaslight',
    archetype: 'healer',
    name: 'Dr Alistair Sterling',
    occupation: 'Lekarz',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/alistair-sterling.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 50,
    pow: 70,
    edu: 85,
    siz: 55,
    int: 75,
    luck: 50,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Doświadczony chirurg i patolog z Marylebone. Jego bezbłędne ekspertyzy toksykologiczne wielokrotnie pomagały policji w ustalaniu przyczyn tajemniczych zgonów w wyższych sferach.',
    birthplace: 'Edynburg, Szkocja',
    residence: 'Londyn, Marylebone',
    characterConcept: 'Analityczny medyk sądowy szukający racjonalnych wyjaśnień anomalii anatomicznych.',
    ideology: 'Ciało ludzkie nie kłamie; każda śmierć zostawia po sobie czytelne fizjologiczne ślady.',
    significantPerson: 'Inspektor Abberline ze Scotland Yardu, który polega na jego chłodnej ocenie przy trudnych sprawach.',
    meaningfulLocation: 'Laboratorium prosektoryjne oświetlone gazowymi palnikami, chłodne i sterylne.',
    treasuredPossession: 'Złoty zegarek kieszonkowy z wyrytą przysięgą Hipokratesa – pamiątka ukończenia studiów w Edynburgu.',
    traits: ['Analityczny', 'Chłodny', 'Sceptyczny'],
    description: 'Poważny mężczyzna w średnim wieku o przystrzyżonej brodzie i skrupulatnych gestach. Nosi wełniany płaszcz i zestaw osobistych lancetów chirurgicznych.',
    backstory: 'Alistair przeprowadził setki rutynowych sekcji zwłok. Jednak niedawna autopsja wyłowionego z Tamizy ciała ujawniła nienaturalną strukturę kostną i narządy wewnętrzne, których anatomii nie potrafił wyjaśnić żaden akademicki podręcznik.\n\n[Kluczowa więź: Złoty zegarek z przysięgą Hipokratesa - przypomnienie o etyce medycznej.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Ekspert od medycyny, biologii i identyfikacji trucizn.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 70,
      'Nauka (Chemia)': 65,
      'Nauka (Biologia)': 60,
      Psychologia: 55,
      Spostrzegawczość: 50,
      'Korzystanie z Bibliotek': 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_alistair_kit',
        name: 'Wiktoriańska torba lekarska',
        category: 'medical',
        description: 'Komplet narzędzi chirurgicznych i odtrutek.',
      },
      {
        id: 'eq_alistair_laudanum',
        name: 'Buteleczka z laudanum',
        category: 'medical',
      },
      {
        id: 'eq_alistair_ledger',
        name: 'Dziennik sekcji zwłok',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_edith_cavell_1890s',
    era: 'gaslight',
    archetype: 'healer',
    name: 'Edith Cavell',
    occupation: 'Pielęgniarka',
    age: 32,
    gender: 'female',
    portraitUrl: '/portraits/predefined/edith-cavell.webp',
    str: 55,
    dex: 60,
    con: 60,
    app: 60,
    pow: 75,
    edu: 70,
    siz: 50,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Siostra przełożona w przytułku dla ubogich w Whitechapel. Oddana służbie najsłabszym, znana z wyjątkowej odporności psychicznej i niezłomnej postawy moralnej.',
    birthplace: 'Norfolk, Anglia',
    residence: 'Londyn, East End',
    characterConcept: 'Empatyczna pielęgniarka niosąca ulgę w cierpieniu bez względu na niebezpieczeństwo.',
    ideology: 'Kultura człowieka objawia się w sposobie, w jaki opiekuje się on najsłabszymi.',
    significantPerson: 'Matka Louisa Cavell, która wykształciła w niej dyscyplinę oraz chrześcijańską etykę pomocy.',
    meaningfulLocation: 'Ciasny, lecz czysty oddział szpitalny w przytułku miejskim.',
    treasuredPossession: 'Srebrny krzyż pielęgniarski przypięty do fartucha, odznaczony za postawę podczas epidemii.',
    traits: ['Empatyczna', 'Niezłomna', 'Cierpliwa'],
    description: 'Kobieta o spokojnych rysach twarzy i ciepłym głosie. Nosi nienagannie skrojony czepek oraz ciemny fartuch pielęgniarski.',
    backstory: 'Pracując w najuboższych dzielnicach Londynu, Edith widziała skrajne ubóstwo. Ostatnio w szpitalu pojawiło się kilku pacjentów z doków cierpiących na halucynacje o potężnych miastach ukrytych pod falami oceanicznymi.\n\n[Kluczowa więź: Matka Louisa - autorytet moralny wspierający jej misję.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezastąpiona w pierwszej pomocy i podnoszeniu morali zespołu.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Pierwsza Pomoc': 80,
      Medycyna: 55,
      Psychologia: 65,
      Nasłuchiwanie: 60,
      Spostrzegawczość: 55,
      Perswazja: 50,
      Skradanie: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_edith_bandages',
        name: 'Rolki bandaży i antyseptyk',
        category: 'medical',
      },
      {
        id: 'eq_edith_pills',
        name: 'Sole trzeźwiące i toniki',
        category: 'medical',
      },
      {
        id: 'eq_edith_cross',
        name: 'Srebrny krzyżyk pielęgniarki',
        category: 'personal',
      },
    ],
  },

  // ==========================================================================
  // ERA: LATA 20. XX WIEKU (1920s / Classic) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDĆZY (Investigator) ---
  {
    id: 'pref_tommy_obrien_1920s',
    era: 'classic',
    archetype: 'investigator',
    name: 'Thomas "Tommy" O\'Brien',
    occupation: 'Prywatny Detektyw',
    age: 38,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tommy-obrien.webp',
    str: 65,
    dex: 65,
    con: 60,
    app: 55,
    pow: 65,
    edu: 60,
    siz: 65,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Były detektyw bostońskiej policji, który odszedł ze służby po odkryciu korupcji sięgającej ratusza i prokuratury. Prowadzi jednoosobowe biuro śledcze w North End, przyjmując sprawy, przed którymi oficjalny wymiar sprawiedliwości zamyka oczy.',
    birthplace: 'Boston, USA',
    residence: 'Boston, North End',
    characterConcept: 'Twardy prywatny detektyw w stylu noir, hołdujący własnemu kodeksowi honorowemu.',
    ideology: 'Sprawiedliwość i paragrafy kodeksu to dwie zupełnie różne rzeczy w tym mieście.',
    significantPerson: 'Porucznik Michael O’Halloran, dawny partner z wydziału zabójstw, jedyny sprawiedliwy gliniarz w Bostonie.',
    meaningfulLocation: 'Biuro na drugim piętrze z żaluzjami, w których tańczy dym z papierosa i zapach taniego bourbona.',
    treasuredPossession: 'Zniszczona odznaka policyjna z wyrytym numerem 404, głęboko schowana na dnie szuflady kantorka.',
    traits: ['Cyniczny', 'Uparty', 'Lojalny'],
    description: 'Szorstki mężczyzna o kwadratowej szczęce i zmęczonych oczach. Nosi pognieciony szary prochowiec i filcowy kapelusz z rondem rzucającym cień na twarz.',
    backstory: 'Tommy odszedł z policji po tym, jak jego śledztwo w sprawie zniknięcia dokera doprowadziło go do sędziego powiązanego z kultem morskich głębin. Kiedy sędzia umorzył sprawę, O’Brien rzucił odznakę na biurko szefa.\n\n[Kluczowa więź: Zniszczona odznaka policyjna - pamiątka dawnej wiary w zasady.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Klimat noir. Szorstki w obyciu, ale ma miękkie serce do sprawiedliwości.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 70,
      Psychologia: 60,
      'Broń Palna (Krótka)': 65,
      Zastraszanie: 55,
      Prawo: 40,
      Skradanie: 50,
      'Prowadzenie Samochodu': 50,
      'Walka Wręcz': 55,
      Nasłuchiwanie: 55,
      'Korzystanie z Bibliotek': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_tommy_gun',
        name: 'Rewolwer Colt .38',
        category: 'weapon',
        description: 'Niezawodny rewolwer detektywistyczny.',
        modifiers: { damage: '1d10', range: '15 yards' },
      },
      {
        id: 'eq_tommy_badge',
        name: 'Zniszczona odznaka',
        category: 'personal',
        description: 'Pamiątka z czasów pracy w policji.',
      },
      {
        id: 'eq_tommy_trench',
        name: 'Prochowiec i kapelusz',
        category: 'personal',
      },
    ],
  },
  {
    id: 'pref_margaret_sullivan_1920s',
    era: 'classic',
    archetype: 'investigator',
    name: 'Margaret Sullivan',
    occupation: 'Dziennikarka',
    age: 28,
    gender: 'female',
    portraitUrl: '/portraits/predefined/margaret-sullivan.webp',
    str: 50,
    dex: 65,
    con: 55,
    app: 65,
    pow: 70,
    edu: 70,
    siz: 55,
    int: 75,
    luck: 65,
    hp: 11,
    maxHp: 11,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Pionierka dziennikarstwa śledczego z redakcji "Arkham Advertiser". Słynie z odważnych doniesień o przemycie alkoholu i nielegalnych obrzędach w dolinie Miskatonic.',
    birthplace: 'Arkham, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Bezkompromisowa dziennikarka śledcza szukająca prawdy bez względu na ryzyko.',
    ideology: 'Wolność słowa i jawność informacji są jedyną defensywą społeczeństwa przed zepsuciem i terrorem.',
    significantPerson: 'Brat Sean Sullivan, wydawca "Arkham Advertiser", który mimo gróźb drukuje jej artykuły śledcze.',
    meaningfulLocation: 'Hucząca maszynami drukarskimi zecernia przy Garrison Street w Arkham.',
    treasuredPossession: 'Mały aparat fotograficzny Kodak z podwójną soczewką podarowany przez zmarłego ojca.',
    traits: ['Odważna', 'Bystra', 'Elokwentna'],
    description: 'Energetyczna kobieta o krótkich, czarnych włosach spiętych spinkami. Nosi ze sobą ciężką skórzaną torbę z przyborami do pisania, błyskiem magnezowym i aparatem.',
    backstory: 'Margaret zdobyła rozgłos po rozbiciu szajki przemytniczej w dokach Innsmouth. Ostatnio w jej ręce trafiły anonimowe listy opisujące nocne zgromadzenia w czarnych lasach wokół Billingsgate.\n\n[Kluczowa więź: Brat Sean Sullivan - lojalny sojusznik w świecie prasy.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wyśmienita w rozmowach i badaniu starych archiwów.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Perswazja: 65,
      'Urok Osobisty': 60,
      'Sztuka/Rzemiosło (Pisanie)': 65,
      Spostrzegawczość: 60,
      'Korzystanie z Bibliotek': 65,
      Psychologia: 55,
      Historia: 50,
      Nasłuchiwanie: 50,
      'Broń Palna (Krótka)': 30,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_margaret_notebook',
        name: 'Notatnik i ołówek',
        category: 'tool',
        description: 'Zapisane setkami wywiadów.',
      },
      {
        id: 'eq_margaret_camera',
        name: 'Aparat małoobrazkowy Kodak',
        category: 'tool',
      },
      {
        id: 'eq_margaret_press',
        name: 'Legitymacja prasowa',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_william_dyer_1920s',
    era: 'classic',
    archetype: 'scholar',
    name: 'Prof. William Dyer',
    occupation: 'Geolog',
    age: 46,
    gender: 'male',
    portraitUrl: '/portraits/predefined/william-dyer.webp',
    str: 55,
    dex: 55,
    con: 60,
    app: 50,
    pow: 65,
    edu: 85,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Ceniony profesor geologii i mineralogii na Uniwersytecie Miskatonic w Arkham. Weteran ekspedycji badawczych w Ameryce Północnej. Rzeczowy naukowiec przyzwyczajony do obozowego życia i skrupulatnej analizy formacji skalnych.',
    birthplace: 'Providence, USA',
    residence: 'Arkham, dzielnica uniwersytecka',
    characterConcept: 'Doświadczony geolog o analitycznym intelekcie i głębokim szacunku do praw natury.',
    ideology: 'Struktura geologiczna Ziemi zapisuje prawdziwą historię planety, przy której dzieje ludzkie są zaledwie sekundowym błyskiem.',
    significantPerson: 'Profesor Frank H. Pabodie, konstruktor specjalistycznych wierteł geologicznych i zaufany przyjaciel z uczelni.',
    meaningfulLocation: 'Laboratorium geologiczne w Science Hall na Uniwersytecie Miskatonic, wypełnione próbkami z całego świata.',
    treasuredPossession: 'Mosiężny kompas geologiczny Bruntona w skórzanym etui, używany podczas trudnych wypraw na Alaskę.',
    traits: ['Spokojny', 'Dociekliwy', 'Odporny'],
    description: 'Twardy mężczyzna o posiwiałych włosach i cerze zahartowanej wiatrem arktycznym. Ubiera się w proste, trwałe garnitury tweedowe z grubą kamizelką.',
    backstory: 'William Dyer poświęcił karierę badaniu struktury skorupy ziemskiej. Jednak analiza próbek nadesłanych niedawno z głębokich kamieniołomów pod Dunwich wykazuje obecność pierwiastków o krystalizacji nieznanej w ziemskim układzie okresowym.\n\n[Kluczowa więź: Kompas geologiczny Bruntona - pamiątka przetrwania w trudnych warunkach.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Szeroka wiedza akademicka, geologiczna i umiejętności przetrwania.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Nauka (Geologia)': 75,
      'Korzystanie z Bibliotek': 65,
      Nawigacja: 60,
      Przetrwanie: 55,
      Spostrzegawczość: 50,
      Historia: 45,
      'Język Obcy (Niemiecki)': 40,
      Unik: 27,
    },
    equipment: [
      { id: 'eq_william_pick', name: 'Młotek geologiczny', category: 'tool' },
      {
        id: 'eq_william_compass',
        name: 'Kompas geologiczny Bruntona',
        category: 'tool',
      },
      {
        id: 'eq_william_charts',
        name: 'Mapy topograficzne Nowej Anglii',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_dorothy_updike_1920s',
    era: 'classic',
    archetype: 'scholar',
    name: 'Dr Dorothy Updike',
    occupation: 'Bibliotekarka',
    age: 35,
    gender: 'female',
    portraitUrl: '/portraits/predefined/dorothy-updike.webp',
    str: 45,
    dex: 60,
    con: 50,
    app: 60,
    pow: 75,
    edu: 80,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Kustoszka sekcji ksiąg rzadkich w Bibliotece Orne na Uniwersytecie Miskatonic. Dyskretna badaczka, której wiedza o szyfrach i dawnych językach pomaga odczytywać najstarsze źródła.',
    birthplace: 'Ipswich, USA',
    residence: 'Arkham, Northside',
    characterConcept: 'Dyskretna archiwistka strzegąca dostępu do zakazanych wiedzą woluminów.',
    ideology: 'Wiedza jest narzędziem o niebywałej mocy; nieprzygotowany umysł ulegnie jej destrukcyjnemu wpływowi.',
    significantPerson: 'Profesor Henry Armitage, jej dyrektor i przełożony w Bibliotece Orne, który powierzył jej nadzór nad zamkniętym skarbcem ksiąg.',
    meaningfulLocation: 'Cichy czytelniany kącik w podziemiach Biblioteki Orne pośród regałów ze starodrukami.',
    treasuredPossession: 'Oprawiony w czarną skórę zeszyt z własnoręcznymi tłumaczeniami i glosami do ksiąg zakazanych.',
    traits: ['Skupiona', 'Cicha', 'Ciekawska'],
    description: 'Elegancka kobieta w okularach w rogowej oprawce, o skupionym i życzliwym wyrazie twarzy. Porusza się z niezwykłym opanowaniem i dbałością o każdy gest.',
    backstory: 'Podczas opracowywania spuścizny po zmarłym darczyńcy uniwersytetu Dorothy natrafiła na bezimienny rękopis spisany w szyfrze Trithemiusa. Jego odkodowanie ujawniło relację z zakazanych rytuałów odblaskowych na wzgórzach wokół Arkham.\n\n[Kluczowa więź: Dyrektor Henry Armitage - przełożony dający jej zaufanie i dostęp do zbiorów specjalnych.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezrównana w researchu, znajomości historii i starych języków.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 85,
      Historia: 70,
      'Język Obcy (Łacina)': 60,
      'Język Obcy (Greka Starożytna)': 50,
      Okultyzm: 55,
      Spostrzegawczość: 50,
      Wycena: 45,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_dorothy_magnifier',
        name: 'Lupa kieszonkowa',
        category: 'tool',
      },
      {
        id: 'eq_dorothy_notes',
        name: 'Zeszyt z odręcznymi tłumaczeniami',
        category: 'document',
      },
      {
        id: 'eq_dorothy_flashlight',
        name: 'Lampa elektryczna (latarka)',
        category: 'tool',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_gerald_grant_1920s',
    era: 'classic',
    archetype: 'action',
    name: 'Gerald Grant',
    occupation: 'Wojskowy',
    age: 32,
    gender: 'male',
    portraitUrl: '/portraits/predefined/gerald-grant.webp',
    str: 75,
    dex: 65,
    con: 70,
    app: 50,
    pow: 60,
    edu: 55,
    siz: 70,
    int: 60,
    luck: 50,
    hp: 14,
    maxHp: 14,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Weteran I Wojny Światowej z piechoty morskiej USA. Walczył we Francji pod Meuse-Argonne. Po demobilizacji nie potrafił dopasować się do realiów powojennych. Pracuje jako instruktor w klubie strzeleckim oraz stróż nocny.',
    birthplace: 'Chicago, USA',
    residence: 'Arkham, Downtown',
    characterConcept: 'Weteran wojenny zmagający się z traumą frontową, szukający sensu w ochronie bezbronnych.',
    ideology: 'Tylko dyscyplina, przygotowanie i zimna krew chronią jednostkę przed otaczającym chaosem.',
    significantPerson: 'Młodsza siostra Clara Grant z Chicago, dla której stara się zachować pozory normalnego życia.',
    meaningfulLocation: 'Zimna, spowita mgłą strzelnica leśna na obrzeżach Arkham.',
    treasuredPossession: 'Parciana apteczka polowa z frontu we Francji, zachowana z kompletnym wyposażeniem sanitarnym.',
    traits: ['Milczący', 'Zdyscyplinowany', 'Napięty'],
    description: 'Szeroki w barach mężczyzna o wojskowym strzyżeniu i surowych rysach. Jego spojrzenie jest stale czujne, a dłonie noszą ślady licznych blizn.',
    backstory: 'Gerald przeżył piekło okopów we Francji. Po powrocie do Nowej Anglii zaciągnął się do ochrony transportów kolejowych w Arkham, gdzie niedawno udaremnił napad napastników posługujących się nieludzką siłą i nieznaną bronią.\n\n[Kluczowa więź: Siostra Clara Grant - motywacja do przetrwania i obrony najbliższych.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Doskonały w walce, posługiwaniu się bronią palną i przetrwaniu w trudnych warunkach.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Długa)': 70,
      'Broń Palna (Krótka)': 60,
      'Walka Wręcz': 65,
      Przetrwanie: 60,
      'Pierwsza Pomoc': 50,
      Zastraszanie: 55,
      Spostrzegawczość: 50,
      Wspinaczka: 45,
      Skradanie: 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_gerald_rifle',
        name: 'Karabin Springfield M1903',
        category: 'weapon',
        description: 'Karabin wojskowy z czasów wojny.',
        modifiers: { damage: '2d6+4', range: '110 yards' },
      },
      { id: 'eq_gerald_canteen', name: 'Manierka wojskowa', category: 'tool' },
      { id: 'eq_gerald_medkit', name: 'Apteczka polowa', category: 'medical' },
    ],
  },
  {
    id: 'pref_agnes_mason_1920s',
    era: 'classic',
    archetype: 'action',
    name: 'Agnes Mason',
    occupation: 'Pilot',
    age: 26,
    gender: 'female',
    portraitUrl: '/portraits/predefined/agnes-mason.webp',
    str: 60,
    dex: 75,
    con: 65,
    app: 60,
    pow: 65,
    edu: 60,
    siz: 55,
    int: 65,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Pionierka lotnictwa cywilnego w Nowej Anglii. Prowadzi niezależną firmę przewozów lotniczych "Mason Aviation". Nie boi się lotów nocnych ani trudnych warunków atmosferycznych.',
    birthplace: 'Gloucester, USA',
    residence: 'Arkham / Lotnisko',
    characterConcept: 'Niezależna lotniczka o nieustraszonej naturze i zmysłach do mechaniki.',
    ideology: 'Z perspektywy lotu świat jest czysty i uporządkowany; zło rodzi się na powierzchni Ziemi.',
    significantPerson: 'Oszczędny mechanik pokładowy Caleb Vance, z którym dzieli pasję do ulepszania silników dwupłatowców.',
    meaningfulLocation: 'Kokpit jej dwupłatowca Curtiss JN-4 "Jenny" na wysokości trzech tysięcy stóp.',
    treasuredPossession: 'Ciężki klucz francuski z wygrawerowanym własnym imieniem, prezent od pierwszego instruktora lotnictwa.',
    traits: ['Śmiała', 'Zaradna', 'Niecierpliwa'],
    description: 'Zgrabna, zwinna kobieta nosząca skórzaną kurtkę lotniczą, pilotkę oraz gogle. Pachnie olejem lotniczym i benzyną.',
    backstory: 'Agnes wykonuje zlecenia pocztowe wzdłuż wybrzeża Massachusetts. Podczas jednego z nocnych lotów nad ujściem rzeki Manuxet dostrzegła w oceanie fosforyzujące światła tworzące geometryczne symetrie pod wodą.\n\n[Kluczowa więź: Klucz francuski z imieniem - symbol samodzielności i fachu.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezwykle zręczna, zna się na maszynach i nawigacji.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Pilotowanie (Samoloty)': 70,
      Mechanika: 60,
      Nawigacja: 55,
      Spostrzegawczość: 60,
      Elektryka: 45,
      Strzelanie: 40,
      'Prowadzenie Samochodu': 50,
      'Walka Wręcz': 40,
      Unik: 37,
    },
    equipment: [
      {
        id: 'eq_agnes_goggles',
        name: 'Gogle i skórzana pilotka',
        category: 'personal',
      },
      {
        id: 'eq_agnes_wrench',
        name: 'Klucz francuski',
        category: 'tool',
        description: 'Ciężkie narzędzie, może służyć jako broń improwizowana.',
      },
      {
        id: 'eq_agnes_map',
        name: 'Mapy lotnicze regionu',
        category: 'document',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_henry_whitman_1920s',
    era: 'classic',
    archetype: 'healer',
    name: 'Dr Henry Whitman',
    occupation: 'Lekarz',
    age: 41,
    gender: 'male',
    portraitUrl: '/portraits/predefined/henry-whitman.webp',
    str: 50,
    dex: 60,
    con: 60,
    app: 60,
    pow: 65,
    edu: 85,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Chirurg ogólny w Szpitalu św. Marii w Arkham. Podczaz służby w jednostkach sanitarnych w Europie nabył umiejętność podejmowania błyskawicznych decyzji pod presją.',
    birthplace: 'Philadelphia, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Opanowany chirurg ratujący życie bez względu na stan ról społecznych pacjenta.',
    ideology: 'Walka ze śmiercią i cierpieniem to jedyne powołanie wolne od fałszu.',
    significantPerson: 'Dr Samuel Eliot, ordynator chirurgii, który powierza mu najtrudniejsze przypadki powypadkowe.',
    meaningfulLocation: 'Sala operacyjna szpitala w Arkham z oświetleniem bezcieniowym.',
    treasuredPossession: 'Mosiężna torba chirurgiczna ze stali nierdzewnej, używana na froncie zachodnim.',
    traits: ['Opanowany', 'Precyzyjny', 'Sceptyczny'],
    description: 'Postawny mężczyzna o gładko ogolonej twarzy i skupionym spojrzeniu. Ubiera się w eleganckie garnitury prążkowane pod fartuchem.',
    backstory: 'Dr Whitman przeprowadzał setki operacji ratujących życie. Ostatnio operował nieprzytomnego marynarza z Innsmouth, z którego tkanek usunął struktury krystaliczne nieposiadające odpowiednika w tkance ludzkiej.\n\n[Kluczowa więź: Ordynator Dr Samuel Eliot - przełożony szanujący jego kunszt medyczny.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Najlepszy specjalista od leczenia ran fizycznych i znajomości biologii.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 75,
      'Nauka (Biologia)': 65,
      'Nauka (Farmacja)': 55,
      Psychologia: 55,
      Spostrzegawczość: 60,
      'Język Obcy (Łacina)': 50,
      Perswazja: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_henry_bag',
        name: 'Torba lekarska',
        category: 'medical',
        description: 'Zawiera stetoskop, skalpele i podstawowe leki.',
      },
      {
        id: 'eq_henry_morphine',
        name: 'Ampułki z morfiną',
        category: 'medical',
        description: 'Do łagodzenia silnego bólu.',
      },
      {
        id: 'eq_henry_bandages',
        name: 'Zestaw sterylnych bandaży',
        category: 'medical',
      },
    ],
  },
  {
    id: 'pref_evelyn_sterling_1920s',
    era: 'classic',
    archetype: 'healer',
    name: 'Dr Evelyn Sterling',
    occupation: 'Lekarz',
    age: 36,
    gender: 'female',
    portraitUrl: '/portraits/predefined/evelyn-sterling.webp',
    str: 45,
    dex: 55,
    con: 55,
    app: 65,
    pow: 70,
    edu: 80,
    siz: 50,
    int: 75,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Lekarka psychiatra z Arkham Sanitarium. Specjalizuje się w przypadkach katatonii, fobii zbiorowych i halucynacji. Wykorzystuje psychoanalizę do poszukiwania ukrytych motywów lęku.',
    birthplace: 'Boston, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Psychoanalityczka zgłębiająca sekrety ludzkiego umysłu i granice obłędu.',
    ideology: 'Szaleństwo nie jest chaosem; to tylko nieznana matryca mowy, którą musimy naukowo odszyfrować.',
    significantPerson: 'Zbiegły pacjent Robert Jackson, którego rysunki geometrii gwiezdnej stanowią klucz do jej badań nad omamami.',
    meaningfulLocation: 'Cichy, wyciszony gabinet terapeutyczny w Arkham Sanitarium.',
    treasuredPossession: 'Notes w skórzanej oprawie z zapiskami snów i majaczeń pacjentów.',
    traits: ['Cierpliwa', 'Uważna', 'Wnikliwa'],
    description: 'Spokojna kobieta o badawczym spojrzeniu i chłodnym głosie. Zawsze ma przy sobie notes i ołówek do spisywania reakcji rozmówców.',
    backstory: 'Evelyn Sterling bada przypadki nagłych załamań nerwowych u mieszkańców Arkham. Odkryła, że wielu pacjentów bez kontaktu ze sobą powtarza te same słowa w nieznanym języku akadyjskim oraz rysuje tę samą figurę geometryczną na ścianach izolatek.\n\n[Kluczowa więź: Notes z zapiskami snów pacjentów - zbiór unikalnych przesłanek o nawracających koszmarach.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Kluczowa postać do leczenia utraty Poczytalności (SAN) i analizowania zachowań.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Psychoanaliza: 75,
      Psychologia: 70,
      Medycyna: 60,
      'Pierwsza Pomoc': 55,
      'Nauka (Medycyna Sądowa)': 50,
      Spostrzegawczość: 55,
      'Urok Osobisty': 50,
      'Korzystanie z Bibliotek': 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_evelyn_records',
        name: 'Akta pacjentów',
        category: 'document',
        description: 'Notatki dotyczące nietypowych przypadków schizofrenii.',
      },
      {
        id: 'eq_evelyn_sedatives',
        name: 'Środki uspokajające',
        category: 'medical',
      },
      {
        id: 'eq_evelyn_journal',
        name: 'Notes z zapiskami snów',
        category: 'document',
      },
    ],
  },

  // ==========================================================================
  // ERA: WSPÓŁCZESNOŚĆ (Modern) - 8 POSTACI
  // ==========================================================================

  // --- ARCHETYP: ŚLEDĆZY (Investigator) ---
  {
    id: 'pref_david_miller_modern',
    era: 'modern',
    archetype: 'investigator',
    name: 'David Miller',
    occupation: 'Dziennikarz',
    age: 34,
    gender: 'male',
    portraitUrl: '/portraits/predefined/david-miller.webp',
    str: 55,
    dex: 60,
    con: 55,
    app: 60,
    pow: 65,
    edu: 70,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Niezależny dziennikarz śledczy i twórca popularnego podkastu "Poza Granicą Prawdy". Wykorzystuje technologie cyfrowe i sieć kontaktów do analizowania spraw zaginionych i niewyjaśnionych fenomenów.',
    birthplace: 'Nowy Jork, USA',
    residence: 'Boston, Back Bay',
    characterConcept: 'Nowoczesny podcaster śledczy weryfikujący podziemne doniesienia o anomaliach.',
    ideology: 'Otwarty dostęp do wiedzy w internecie jest jedyną tamą powstrzymującą urzędową cenzurę i dezinformację.',
    significantPerson: 'Anonimowy darczyńca z platformy patronackiej o pseudonimie "Arkham_Echo", przesyłający mu wiarygodne materiały dowodowe.',
    meaningfulLocation: 'Dźwiękoszczelne studio nagraniowe w domowym poddaszu, wyposażone w profesjonalne mikrofony i konsolę.',
    treasuredPossession: 'Smartfon ze specjalną szyfrowaną aplikacją do rejestracji dźwięku oraz bazą danych kontaktów informatorów.',
    traits: ['Komunikatywny', 'Ciekawski', 'Sceptyczny'],
    description: 'Młody mężczyzna w okularach w drucianej oprawce, ubrany w jeansową kurtkę i sportowe buty. Zawsze nosi bezprzewodowe słuchawki wokół szyi.',
    backstory: 'David zyskał rozgłos po tym, jak opublikował serię nagrań o niewyjaśnionych zaginięciach turystów w lasach górskich Maine. Kiedy jego profil społecznościowy został niespodziewanie zablokowany, zaczął zgłębiać temat głębiej, docierając do wzorców rytualnych.\n\n[Kluczowa więź: Informator "Arkham_Echo" - źródło zweryfikowanych przecieków.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Świetny w technologiach cyfrowych, pozyskiwaniu informacji i wywiadach.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Spostrzegawczość: 65,
      Komputery: 60,
      Perswazja: 60,
      Psychologia: 55,
      'Korzystanie z Bibliotek': 55,
      'Sztuka/Rzemiosło (Podcast)': 50,
      Nasłuchiwanie: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_david_smartphone',
        name: 'Najnowszy smartfon',
        category: 'tool',
        description: 'Służy do nagrywania, kontaktu i GPS.',
      },
      {
        id: 'eq_david_laptop',
        name: 'Laptop ze stacją audio',
        category: 'tool',
      },
      {
        id: 'eq_david_recorder',
        name: 'Mikrofon kierunkowy',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_chloe_vance_modern',
    era: 'modern',
    archetype: 'investigator',
    name: 'Chloe Vance',
    occupation: 'Prywatna Detektyw',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/chloe-vance.webp',
    str: 50,
    dex: 70,
    con: 55,
    app: 65,
    pow: 70,
    edu: 65,
    siz: 50,
    int: 75,
    luck: 65,
    hp: 10,
    maxHp: 10,
    san: 70,
    maxSan: 99,
    mp: 14,
    maxMp: 14,
    background:
      'Ex-analityczka białego wywiadu (OSINT) z agencji rządowej. Prowadzi agencję śledczo-cyfrową w Bostonie, łącząc analitykę danych z operacjami rozpoznawczymi w terenie.',
    birthplace: 'Washington D.C., USA',
    residence: 'Boston, South End',
    characterConcept: 'Analityczka śledcza wykorzystująca zaawansowaną analitykę sieciową i działania terenowe.',
    ideology: 'Żaden system nie jest szczelny; każda ludzka i cyfrowa aktywność pozostawia po sobie wykrywalny ślad.',
    significantPerson: 'Arthur Vance, wuj i dawny kierownik z agencji, który cicho wspiera jej niezależne śledztwa.',
    meaningfulLocation: 'Mobilne stanowisko analityczne w zaciemnionym apartamencie z wieloma ekranami monitorów.',
    treasuredPossession: 'Zabezpieczony sprzętowo ultrabook z autorskim oprogramowaniem do przeszukiwania baz wywiadowczych.',
    traits: ['Analityczna', 'Dyskretna', 'Zdecydowana'],
    description: 'Wysportowana kobieta o skupionym spojrzeniu i ciemnych włosach związanych w kucyk. Nosi ciemną odzież taktyczną umożliwiającą swobodę ruchów.',
    backstory: 'Chloe odeszła ze służb państwowych po wykryciu utajnionych przepływów kapitałowych z fikcyjnych kont spółek do podziemnych sekt religijnych. Gdy agencja nakazała jej zamknąć temat, zaczęła prowadzić go prywatnie.\n\n[Kluczowa więź: Ultrabook z oprogramowaniem śledczym - narzędzie pracy i niezależności.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Mistrzyni hakowania, dyskrecji oraz walki wręcz obronnej.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Komputery: 70,
      Skradanie: 65,
      Spostrzegawczość: 60,
      'Broń Palna (Krótka)': 55,
      Psychologia: 55,
      'Walka Wręcz': 50,
      Ślusarstwo: 45,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_chloe_glock',
        name: 'Pistolet Glock 19',
        category: 'weapon',
        description: 'Niezawodny pistolet 9mm.',
        modifiers: { damage: '1d10', range: '15 yards' },
      },
      {
        id: 'eq_chloe_laptop',
        name: 'Zabezpieczony Ultrabook',
        category: 'tool',
      },
      { id: 'eq_chloe_kit', name: 'Zestaw cyber-śledczy', category: 'tool' },
    ],
  },

  // --- ARCHETYP: UCZONY (Scholar) ---
  {
    id: 'pref_eric_carter_modern',
    era: 'modern',
    archetype: 'scholar',
    name: 'Prof. Eric Carter',
    occupation: 'Archeolog',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/eric-carter.webp',
    str: 55,
    dex: 55,
    con: 60,
    app: 50,
    pow: 65,
    edu: 80,
    siz: 60,
    int: 75,
    luck: 55,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Profesor archeologii cyfrowej na Uniwersytecie Harvarda. Łączy archeologię terenową z fotogrametrią 3D i skanowaniem laserowym LiDAR. Zasłynął odkryciem nieznanych dotąd ruin sakralnych w górskich rejonach Ameryki Południowej.',
    birthplace: 'Boston, USA',
    residence: 'Cambridge, USA',
    characterConcept: 'Nowoczesny archeolog cyfrowy odnajdujący zatarte struktury cywilizacyjne pod gęstą roślinnością.',
    ideology: 'Warstwy geologiczne i architektura ruin zachowują prawdę o prahistorii ludzkości bez fałszerstw politycznych.',
    significantPerson: 'Doktorant Lucas Silva, zaufany asystent operacyjny zarwujący noce przy kalibracji głowic skanerów terenowych.',
    meaningfulLocation: 'Zacienione, porośnięte mchem grobowisko w górach peruwiańskich, z którego pobrał pierwsze trójwymiarowe skany anomalii.',
    treasuredPossession: 'Wstrząsoodporny tablet pancerny ze skanerem LiDAR i oprogramowaniem do generowania modeli przestrzennych w czasie rzeczywistym.',
    traits: ['Cierpliwy', 'Dociekliwy', 'Skrupulatny'],
    description: 'Mężczyzna o szpakowatych włosach i spokojnym spojrzeniu. Noszący wygodne odzieże trekkingowe z pasem narzędziowym.',
    backstory: 'Eric przebył dziesiątki wypraw badawczych. Podczas skanowania laserowego ruin w Gwatemali promień LiDAR spenetrował warstwę gleby, ujawniając podziemny kompleks o podziałach geometrycznych nienależących do żadnej znanej cywilizacji.\n\n[Kluczowa więź: Wstrząsoodporny tablet ze skanerem - technologiczne okno na niewidoczne struktury.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Zna się na archeologii, historii i technologiach skanowania 3D.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Archeologia: 75,
      Historia: 65,
      Komputery: 60,
      Nawigacja: 55,
      'Nauka (Fizyka)': 50,
      'Korzystanie z Bibliotek': 50,
      'Język Obcy (Hiszpański)': 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_eric_tablet',
        name: 'Wstrząsoodporny tablet ze skanerem LiDAR',
        category: 'tool',
      },
      {
        id: 'eq_eric_gps',
        name: 'Odbiornik GPS satelitarny',
        category: 'tool',
      },
      { id: 'eq_eric_tool', name: 'Multitool Leatherman', category: 'tool' },
    ],
  },
  {
    id: 'pref_elena_rostova_modern',
    era: 'modern',
    archetype: 'scholar',
    name: 'Dr Elena Rostova',
    occupation: 'Lingwistka',
    age: 37,
    gender: 'female',
    portraitUrl: '/portraits/predefined/elena-rostova.webp',
    str: 45,
    dex: 60,
    con: 50,
    app: 60,
    pow: 75,
    edu: 85,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Wybitna lingwistka i kryptografka z MIT. Specjalistka od rekonstrukcji nieistniejących pism oraz analizy matematycznej kodów lingwistycznych. Konsultuje sprawy utajnionych zapisków dla instytutów badawczych.',
    birthplace: 'Petersburg, Rosja',
    residence: 'Boston, USA',
    characterConcept: 'Genialna analityczka lingwistyczna rozkodowująca nieludzkie systemy pisma.',
    ideology: 'Język jest fizycznym odzwierciedleniem struktury myśli; odczytanie zapisu pozwala pojąć naturę jego twórcy.',
    significantPerson: 'Brat Nikolai Rostov, inżynier ds. cyberbezpieczeństwa w Kopenhadze, wspierający ją w budowie algorytmów deszyfrujących.',
    meaningfulLocation: 'Gabinet akademicki na MIT, w którym ściany pokrywają tablice z analizą ciągów fonetycznych.',
    treasuredPossession: 'Niewielki, rzadki słownik porównawczy starożytnych języków semickich i klinowych z XIX wieku.',
    traits: ['Genialna', 'Spokojna', 'Skupiona'],
    description: 'Kobieta o głębokim, uważnym spojrzeniu zza szkieł okularów. Porusza się z nienaganną gracją, mówiąc cichym, precyzyjnym głosem.',
    backstory: 'Elena odcyfrowała najtrudniejsze szyfry państwowe. Jednak otrzymanie cyfrowego skanu glinianego cylindra z Bliskiego Wschodu zszokowało ją – fonetyka języka sugeruje budowę strun głosowych odmienną od ssaków.\n\n[Kluczowa więź: Brat Nikolai Rostov - jedyna osoba rozumiejąca wagę jej matematycznych odkryć.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Geniusz lingwistyczny i analityczny, odczytuje najtrudniejsze kody.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Język Obcy (Sumeryjski)': 70,
      'Język Obcy (Łacina)': 60,
      Kryptografia: 75,
      Komputery: 60,
      'Korzystanie z Bibliotek': 70,
      Historia: 55,
      Spostrzegawczość: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_elena_device',
        name: 'Zaszyfrowany pendrive i dysk zewnętrzny',
        category: 'tool',
      },
      {
        id: 'eq_elena_dictionary',
        name: 'Rzadkie słowniki lingwistyczne',
        category: 'document',
      },
      {
        id: 'eq_elena_glasses',
        name: 'Okulary z filtrem światła niebieskiego',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: CZŁOWIEK CZYNU (Action) ---
  {
    id: 'pref_marcus_vance_modern',
    era: 'modern',
    archetype: 'action',
    name: 'Marcus Vance',
    occupation: 'Wojskowy',
    age: 35,
    gender: 'male',
    portraitUrl: '/portraits/predefined/marcus-vance.webp',
    str: 75,
    dex: 70,
    con: 70,
    app: 50,
    pow: 60,
    edu: 60,
    siz: 70,
    int: 65,
    luck: 50,
    hp: 14,
    maxHp: 14,
    san: 60,
    maxSan: 99,
    mp: 12,
    maxMp: 12,
    background:
      'Były operator sił specjalnych Navy SEALs, obecnie prywatny kontraktor wojskowy w agencji ochrony aktywów strategicznych. Doskonale przeszkolony w walce w zwarciu i taktyce czarnej.',
    birthplace: 'San Diego, USA',
    residence: 'Dallas / W podróży',
    characterConcept: 'Weteran jednostek specjalnych o absolutnym opanowaniu i wyszkoleniu taktycznym.',
    ideology: 'Zaskoczenie, szybkość działania i żelazna dyscyplina decydują o przetrwaniu w strefie rażenia.',
    significantPerson: 'Kapitan David Miller, były dowódca sekcji bojowej, który wdrożył go do służby.',
    meaningfulLocation: 'Poligon taktyczny w Teksasie, gdzie spędza godziny na doskonaleniu strzelectwa.',
    treasuredPossession: 'Poszarpana kamizelka taktyczna, która zatrzymała odłamek podczas ewakuacji w Faludży.',
    traits: ['Opanowany', 'Czujny', 'Twardy'],
    description: 'Niezwykle postawny mężczyzna o krótkich włosach i żuchwie pokrytej bliznami. Jego ruchy są oszczędne, zdradzające nawyki czujności bojowej.',
    backstory: 'Marcus brał udział w dziesiątkach misji bojowych. Podczas ochrony instalacji badawczej w Afryce Środkowej jego oddział został odcięty przez agresywne istoty odporne na amunicję małokalibrową.\n\n[Kluczowa więź: Kamizelka taktyczna - dowód na opanowanie w sytuacjach granicznych.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Najwyższa sprawność bojowa, ekspert od broni palnej, taktyki i przetrwania.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Broń Palna (Krótka)': 75,
      'Broń Palna (Długa)': 70,
      'Walka Wręcz': 70,
      Przetrwanie: 60,
      'Pierwsza Pomoc': 55,
      Spostrzegawczość: 55,
      Zastraszanie: 50,
      Unik: 35,
    },
    equipment: [
      {
        id: 'eq_marcus_hk',
        name: 'Karabinek H&K 416',
        category: 'weapon',
        description: 'Karabin szturmowy kalibru 5.56mm.',
        modifiers: { damage: '2d6', range: '100 yards' },
      },
      {
        id: 'eq_marcus_vest',
        name: 'Kamizelka taktyczna',
        category: 'personal',
      },
      {
        id: 'eq_marcus_radio',
        name: 'Zabezpieczone radio satelitarne',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_jessica_cross_modern',
    era: 'modern',
    archetype: 'action',
    name: 'Jessica Cross',
    occupation: 'Fotoreporter',
    age: 30,
    gender: 'female',
    portraitUrl: '/portraits/predefined/jessica-cross.webp',
    str: 60,
    dex: 75,
    con: 65,
    app: 60,
    pow: 65,
    edu: 65,
    siz: 55,
    int: 70,
    luck: 60,
    hp: 12,
    maxHp: 12,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Fotoreporterka dokumentująca konflikty zbrojne i wyprawy wysokogórskie dla magazynów geograficznych. Znakomita alpinistka o błyskawicznym refleksie i opanowaniu.',
    birthplace: 'Denver, USA',
    residence: 'Seattle, USA',
    characterConcept: 'Nieustraszona fotografka i alpinistka utwalająca prawdę w obiektywie.',
    ideology: 'Pojedyncza klatka fotograficzna potrafi powiedzieć o prawdzie więcej niż tom opracowań politycznych.',
    significantPerson: 'Brat Ryan Cross, instruktor wspinaczki, z którym uczyła się technik asekuracji w Górach Skalistych.',
    meaningfulLocation: 'Pionowa ściana skalna w Parku Narodowym Yosemite podczas wschodu słońca.',
    treasuredPossession: 'Szczelny, plecak wodoodporny na sprzęt optyczny z pamiątkowymi plakietkami z 5 kontynentów.',
    traits: ['Odważna', 'Energiczna', 'Spostrzegawcza'],
    description: 'Wysportowana kobieta w odzieży sportowej i z aparatem fotograficznym zawieszonym na pasku piersiowym. Posiada bystre zielone oczy.',
    backstory: 'Jessica fotografowała zniszczenia wojenne i dziką przyrodę. Podczas ostatniego zlecenia w Himalajach uchwyciła na matrycy cyfrowej olbrzymie, trójpalczaste ślady odciśnięte w świeżym śniegu wokół wejścia do jaskini.\n\n[Kluczowa więź: Brat Ryan Cross - kompan i autorytet w dziedzinie asekuracji terenowej.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Wyjątkowo sprawna fizycznie, doskonała w robieniu zdjęć i wspinaczce.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Sztuka/Rzemiosło (Fotografia)': 75,
      Wspinaczka: 70,
      Spostrzegawczość: 65,
      Nawigacja: 60,
      Nasłuchiwanie: 55,
      Przetrwanie: 50,
      Skradanie: 50,
      Unik: 37,
    },
    equipment: [
      {
        id: 'eq_jessica_camera',
        name: 'Aparat cyfrowy Sony Alpha z zoomem',
        category: 'tool',
      },
      {
        id: 'eq_jessica_rope',
        name: 'Lina wspinaczkowa i karabinki',
        category: 'tool',
      },
      {
        id: 'eq_jessica_backpack',
        name: 'Wstrząsoodporny plecak turystyczny',
        category: 'personal',
      },
    ],
  },

  // --- ARCHETYP: UZDROWICIEL (Healer) ---
  {
    id: 'pref_christian_cole_modern',
    era: 'modern',
    archetype: 'healer',
    name: 'Dr Christian Cole',
    occupation: 'Lekarz',
    age: 43,
    gender: 'male',
    portraitUrl: '/portraits/predefined/christian-cole.webp',
    str: 50,
    dex: 60,
    con: 60,
    app: 55,
    pow: 65,
    edu: 85,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 11,
    maxHp: 11,
    san: 65,
    maxSan: 99,
    mp: 13,
    maxMp: 13,
    background:
      'Ordynator Szpitalnego Oddziału Ratunkowego w Chicago. Lekarz urazowy z wieloletnim doświadczeniem w przyjmowaniu pacjentów w stanie zagrożenia życia.',
    birthplace: 'Chicago, USA',
    residence: 'Chicago, USA',
    characterConcept: 'Lekarz medycyny ratunkowej zachowujący zimną krew w skrajnym chaosie.',
    ideology: 'Każde życie ludzkie jest warte najwyższego wysiłku; na szpitalnym oddziale oddzielamy przesądy od biologii.',
    significantPerson: 'Dr Sarah Jenkins, rezydentka medyczna, którą prowadzi i chroni przed wypaleniem zawodowym.',
    meaningfulLocation: 'Jasno oświetlona, pełna aparatury sala reanimacyjna na oddziale ratunkowym w Chicago.',
    treasuredPossession: 'Poręczna walizka reanimacyjna z zestawem sterylnych igieł, rurek intubacyjnych i leków naczyniowych.',
    traits: ['Opanowany', 'Zaradny', 'Precyzyjny'],
    description: 'Postawny mężczyzna w zielonym stroju operacyjnym i ze stetoskopem na szyi. Jego spojrzenie jest opanowane, a decyzje podejmowane natychmiastowo.',
    backstory: 'Christian uratował setki poszkodowanych. Tydzień temu na oddział trafił nieprzytomny pacjent wyłowiony z jeziora Michigan, z którego ran zamiast krwi wypływała gęsta, ciemna substancja o zapachu ozonu.\n\n[Kluczowa więź: Walizka reanimacyjna - niezawodne narzędzie ratowania pacjentów.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Genialny chirurg, najlepszy w opatrywaniu najcięższych ran fizycznych.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Medycyna: 80,
      'Pierwsza Pomoc': 80,
      'Nauka (Farmacja)': 60,
      'Nauka (Biologia)': 60,
      Psychologia: 55,
      Spostrzegawczość: 55,
      Komputery: 50,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_christian_kit',
        name: 'Zaawansowana torba reanimacyjna',
        category: 'medical',
        description: 'Defibrylator, leki znieczulające, sterylne szwy.',
      },
      {
        id: 'eq_christian_adrenaline',
        name: 'Ampułkostrzykawki z adrenaliną',
        category: 'medical',
      },
      {
        id: 'eq_christian_id',
        name: 'Identyfikator medyczny ordynatora',
        category: 'document',
      },
    ],
  },
  {
    id: 'pref_maya_patel_modern',
    era: 'modern',
    archetype: 'healer',
    name: 'Dr Maya Patel',
    occupation: 'Lekarz',
    age: 38,
    gender: 'female',
    portraitUrl: '/portraits/predefined/maya-patel.webp',
    str: 45,
    dex: 55,
    con: 55,
    app: 65,
    pow: 75,
    edu: 80,
    siz: 50,
    int: 75,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Neurobiolożka i psychoterapeutka kliniczna w Bostonie. Prowadzi badania nad mechanizmami obronnymi mózgu u pacjentów dotkniętych głębokim wstrząsem psychicznym i zaburzeniami percepcji.',
    birthplace: 'Londyn, Anglia',
    residence: 'Boston, USA',
    characterConcept: 'Wybitna terapeutka zgłębiająca traumę i nieznane zakamarki ludzkiego umysłu.',
    ideology: 'Zrozumienie struktury lęku pozwala uzdrowić nawet najbardziej okaleczoną psychikę.',
    significantPerson: 'Dr Vikram Patel, brat i biochemik, pomagający jej przy syntezie leków wyciszających stany urojeniowe.',
    meaningfulLocation: 'Cichy gabinet terapeutyczny w Bostonie z oświetleniem punktowym i wygodną sofą.',
    treasuredPossession: 'Zabezpieczony biometrycznie tablet z zaszyfrowanym rejestrem anomalii neurogennych u pacjentów.',
    traits: ['Wnikliwa', 'Empatyczna', 'Opanowana'],
    description: 'Kobieta o spokojnym, głębokim głosie i spiętych czarnych włosach. Jej spojrzenie budzi poczucie bezpieczeństwa i zaufania.',
    backstory: 'Dr Patel prowadziła psychoterapię świadków incydentu w bostońskim metrze. Analiza fal mózgowych pacjentów wykazała identyczne wyładowania bioelektryczne powiązane z nawracającymi wizjami morskiego miasteczka.\n\n[Kluczowa więź: Brat Dr Vikram Patel - bliski sojusznik w naukowej pracy nad lekami.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes:
      'Kluczowa badaczka do stabilizowania zdrowia psychicznego (Poczytalności) zespołu.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Psychoanaliza: 75,
      Psychologia: 70,
      Medycyna: 60,
      'Pierwsza Pomoc': 50,
      'Nauka (Neurobiologia)': 65,
      Spostrzegawczość: 55,
      'Korzystanie z Bibliotek': 50,
      Komputery: 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_maya_tablet',
        name: 'Tablet z dokumentacją pacjentów',
        category: 'tool',
      },
      {
        id: 'eq_maya_drugs',
        name: 'Przenośna apteczka z lekami psychotropowymi',
        category: 'medical',
      },
      {
        id: 'eq_maya_glass',
        name: 'Dziennik analiz snów pacjentów',
        category: 'document',
      },
    ],
  },

  // ==========================================================================
  // ARCHETYP: MISTYK (Mystic) - 6 POSTACI (2 na epoke)
  // ==========================================================================

  // --- GASLIGHT MYSTIC ---
  {
    id: 'pref_silas_thorne_gaslight',
    era: 'gaslight',
    archetype: 'mystic',
    name: 'Silas Thorne',
    occupation: 'Okultysta',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/silas-thorne.webp',
    str: 45,
    dex: 50,
    con: 50,
    app: 40,
    pow: 85,
    edu: 70,
    siz: 55,
    int: 80,
    luck: 55,
    hp: 10,
    maxHp: 10,
    san: 65,
    maxSan: 99,
    mp: 17,
    maxMp: 17,
    background:
      'Dawny profesor filozofii z Uniwersytetu Londyńskiego, który po natrafieniu na bluźniercze fragmenty w archiwach porzucił karierę akademicką. Poświęcił majątek i zdrowie na badanie granic między światem materialnym a nieznanymi wymiarami.',
    birthplace: 'Londyn, Anglia',
    residence: 'Londyn, Bloomsbury',
    characterConcept: 'Dawny akademicki filozof, który odrzucił doktrynę racjonalizmu na rzecz badania tajemnic okultyzmu.',
    ideology: 'Świat widzialny jest zaledwie cienką, niestałą zasłoną skrywającą przed nami potężne, pierwotne bytowości.',
    significantPerson: 'Wuj Barnaby Thorne, ekscentryczny badacz kabały, który pozostawił mu tajemny księgozbiór i rękopisy.',
    meaningfulLocation: 'Zastawiony szafami gabinet w Bloomsbury, pachnący kadzidłem, starą pergamą i woskiem.',
    treasuredPossession: 'Oprawny w ludzką skórę grimuar z ręcznymi diagramami ułożenia gwiazd i pentagramów.',
    traits: ['Tajemniczy', 'Dociekliwy', 'Ekscentryczny'],
    description: 'Chudy, wysoki mężczyzna o głęboko osadzonych czarnych oczach i posiwiałej, długiej brodzie. Nosi wytarty czarny płaszcz i srebro z rytymi sigilami.',
    backstory: 'Silas przeżył załamanie światopoglądowe, kiedy odcyfrował manuskrypt opisujący istoty egzystujące poza czasem. Od tamtego momentu prowadzi prywatne rytuały i obserwacje astronomiczne, starając się ostrzec ludzkość przed tym, co nadchodzi.\n\n[Kluczowa więź: Oprawny w skórę grimuar - jedyne źródło wiedzy o strukturze rytuałów.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo wysoka MOC. Ekspert od okultyzmu i starozytnych jezykow.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 75,
      'Korzystanie z Bibliotek': 65,
      'Język Obcy (Łacina)': 55,
      'Język Obcy (Greka)': 40,
      Historia: 60,
      Spostrzegawczość: 55,
      Psychologia: 45,
      Nasłuchiwanie: 50,
      Unik: 25,
    },
    equipment: [
      {
        id: 'eq_silas_grimoire',
        name: 'Oprawny w skore grimuar',
        category: 'occult',
        description: 'Pelny odrecznie zapisanych not i rysunkow pentagramow.',
      },
      {
        id: 'eq_silas_pendant',
        name: 'Srebrny amulet z siglem',
        category: 'occult',
        description: 'Odziedziczony po mistrzu - daje poczucie ochrony.',
      },
      { id: 'eq_silas_candles', name: 'Zestaw rytualnych swiec', category: 'occult' },
    ],
  },
  {
    id: 'pref_vivienne_moreau_gaslight',
    era: 'gaslight',
    archetype: 'mystic',
    name: 'Vivienne Moreau',
    occupation: 'Medium spirytystyczne',
    age: 34,
    gender: 'female',
    portraitUrl: '/portraits/predefined/vivienne-moreau.webp',
    str: 40,
    dex: 60,
    con: 50,
    app: 65,
    pow: 80,
    edu: 55,
    siz: 45,
    int: 75,
    luck: 70,
    hp: 9,
    maxHp: 9,
    san: 70,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Znana wiktoriańska spirytystka, przyjmująca elity w londyńskich salonach. Choć krytycy zarzucają jej mistyfikację, jej seanse ujawniają fakty z życia zmarłych, których nie mogła poznać drogą racjonalną.',
    birthplace: 'Paryż, Francja',
    residence: 'Londyn',
    characterConcept: 'Towarzyskie medium o autentycznym, lecz przerażającym darze kontaktu z bytowaniami zaświatowymi.',
    ideology: 'Granica między życiem a śmiercią jest jedynie złudzeniem percepcji.',
    significantPerson: 'Zjawa młodej dziewczynki, nawiedzająca ją od dzieciństwa i ostrzegająca przed zagrożeniem.',
    meaningfulLocation: 'Salon seansów oświetlony blaskiem czerwonych świec i zasłonięty aksamitnymi kotarami.',
    treasuredPossession: 'Ręcznie malowana talia kart Tarota o niepokojących, unikalnych symbolach na rewersie.',
    traits: ['Intuicyjna', 'Urocza', 'Wrażliwa'],
    description: 'Elegancka kobieta o bladoszarych oczach i melancholijnym uśmiechu. Nosi aksamitne suknie w odcieniach purpury oraz koronkowy welon.',
    backstory: 'Vivienne zaczynała jako modne medium. Podczas jednego z seansów przemówiła głosem bytu, który ujawnił szczegóły morderstwa popełnionego w zapomnianym doku, co sprowadziło na nią zainteresowanie mrocznych stowarzyszeń.\n\n[Kluczowa więź: Zjawa dziewczynki - niecielesny opiekun ostrzegający przed niebezpieczeństwem.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wysoka MOC i Szczescie. Perswazja i intuicja.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 60,
      Perswazja: 65,
      Psychologia: 60,
      Spostrzegawczość: 55,
      Nasłuchiwanie: 60,
      'Urok Osobisty': 55,
      'Korzystanie z Bibliotek': 40,
      Historia: 35,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_viv_cards',
        name: 'Talia kart Tarota',
        category: 'occult',
        description: 'Recznie malowana talia z nieznanymi symbolami na rewersach.',
      },
      {
        id: 'eq_viv_crystal',
        name: 'Kula krysztalowa',
        category: 'occult',
        description: 'Uzywana podczas seansow spirytystycznych.',
      },
      { id: 'eq_viv_veil', name: 'Czarny welon', category: 'personal' },
    ],
  },

  // --- CLASSIC MYSTIC ---
  {
    id: 'pref_nathaniel_ward_classic',
    era: 'classic',
    archetype: 'mystic',
    name: 'Nathaniel Ward',
    occupation: 'Antykwariusz / Badacz okultyzmu',
    age: 43,
    gender: 'male',
    portraitUrl: '/portraits/predefined/nathaniel-ward.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 45,
    pow: 80,
    edu: 75,
    siz: 50,
    int: 80,
    luck: 55,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Właściciel antykwariatu przy Church Street w Arkham. Specjalizuje się w sprowadzaniu i wycenie unikalnych woluminów z zakresu filozofii naturalnej i wiedzy tajemnej. Regularnie konsultuje zbiory specjalne z wykładowcami Uniwersytetu Miskatonic.',
    birthplace: 'Providence, USA',
    residence: 'Arkham, French Hill',
    characterConcept: 'Dyskretny badacz okultyzmu z bogatym zapleczem księgozbiorów starożytnych.',
    ideology: 'Mitologie ludzkie nie są bajkami; stanowią one zniekształcone świadectwo obecności bytów władających światem przed nadejściem człowieka.',
    significantPerson: 'Profesor Henry Armitage z Uniwersytetu Miskatonic, z którym wymienia oceny dotyczące rzadkich pism okultystycznych.',
    meaningfulLocation: 'Zaplecze antykwariatu oświetlone zieloną lampą naftową, zasłonięte ciężką kotarą przed wzrokiem przypadkowych klientów.',
    treasuredPossession: 'Łaciński pergamin z XIV wieku, będący urwanym fragmentem traktatu o architekturze Miast Bez Imienia.',
    traits: ['Poważny', 'Wnikliwy', 'Skryty'],
    description: 'Mężczyzna w średnim wieku o ciemnych, badawczych oczach i ostrych gestach. Ubiera się w stary, zadbany garnitur wełniany z dewizką.',
    backstory: 'Nathaniel Ward spędził dekady na kolekcjonowaniu ksiąg. Analizując manuskrypty, odkrył przerażającą zależność między datami cyklicznych zaginięć mieszkańców w kotlinie Miskatonic a układem gwiezdnym zapowiadającym otwarcie Wrót.\n\n[Kluczowa więź: Łaciński pergamin z XIV wieku - dowód na starożytny rodowód koszmaru.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Silna wola i szerokie wyksztalcenie. Ekspert od rzadkich ksiag.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 70,
      'Korzystanie z Bibliotek': 70,
      Wycena: 65,
      Historia: 55,
      'Język Obcy (Łacina)': 50,
      Spostrzegawczość: 55,
      Psychologia: 45,
      Nasłuchiwanie: 50,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_nath_tome',
        name: 'Lacinski zwoj z XIV wieku',
        category: 'occult',
        description: 'Fragment traktatu o istotach z zaswiatow.',
      },
      {
        id: 'eq_nath_loupe',
        name: 'Lupa jubilerska',
        category: 'tool',
        description: 'Do odczytywania drobnych inskrypcji.',
      },
      { id: 'eq_nath_journal', name: 'Dziennik badan', category: 'document' },
    ],
  },
  {
    id: 'pref_iris_blackwell_classic',
    era: 'classic',
    archetype: 'mystic',
    name: 'Iris Blackwell',
    occupation: 'Wrozka / Jasnowidz',
    age: 26,
    gender: 'female',
    portraitUrl: '/portraits/predefined/iris-blackwell.webp',
    str: 40,
    dex: 60,
    con: 50,
    app: 70,
    pow: 75,
    edu: 55,
    siz: 45,
    int: 75,
    luck: 75,
    hp: 9,
    maxHp: 9,
    san: 70,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Jasnowidzka z dzielnicy portowej w Arkham. Córka wędrownych rzemieślników z rodowodem Salem. Posiada niezwykły zmysł intuicyjnego przeczuwania zagrożenia oraz czytania intencji z symboli.',
    birthplace: 'Salem, USA',
    residence: 'Arkham, Dzielnica Portowa',
    characterConcept: 'Wyostrzona intuicyjnie jasnowidzka o niezwykłym szczęściu i darze odczytywania omenów.',
    ideology: 'Świat przesyłany jest ciągłymi sygnałami; mądrość polega na umiejętności odczytania ich przed tragedią.',
    significantPerson: 'Babka Esmeralda Blackwell, która przekazała jej wiedzę o odczytywaniu układów runicznych i chroniących zaklęciach.',
    meaningfulLocation: 'Zaplecze wozu wędrownego pachnące szałwią, czarną herbatą i woskiem świec.',
    treasuredPossession: 'Zestaw kamiennych run ochronnych po babce, noszony w wyściełanym woreczku.',
    traits: ['Intuicyjna', 'Tajemnicza', 'Sprytna'],
    description: 'Młoda kobieta o gęstych czarnych włosach i czujnych, ciemnych oczach. Ubiera się w barwne szale haftowane w tradycyjne symbole ochronne.',
    backstory: 'Iris zarabia na życie odczytywaniem losu w dokach Arkham. Jednak ostatnio jej nocne sny zostały zdominowane przez powracający obraz ogromnej sylwetki wyłaniającej się z pękających spękań w dnie oceanicznym.\n\n[Kluczowa więź: Kamienne runy babki - materialny amulet łączący ją z rodzinną tradycją.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Bardzo wysokie Szczescie (75). Intuicyjna i spostrzegawcza.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 55,
      Psychologia: 65,
      Spostrzegawczość: 60,
      Nasłuchiwanie: 55,
      'Urok Osobisty': 60,
      Perswazja: 50,
      'Sztuka/Rzemiosło (Kartomancja)': 70,
      Historia: 35,
      Unik: 30,
    },
    equipment: [
      {
        id: 'eq_iris_runes',
        name: 'Zestaw starozytnych run',
        category: 'occult',
        description: 'Kamienne runy przekazane przez babke.',
      },
      {
        id: 'eq_iris_shawl',
        name: 'Haftowany szal',
        category: 'personal',
        description: 'Z tajemniczymi symbolami wplecionymi w wzor.',
      },
      { id: 'eq_iris_herbs', name: 'Woreczek ziol ochronnych', category: 'occult' },
    ],
  },

  // --- MODERN MYSTIC ---
  {
    id: 'pref_victor_crowley_modern',
    era: 'modern',
    archetype: 'mystic',
    name: 'Victor Crowley',
    occupation: 'Parapsychologist',
    age: 44,
    gender: 'male',
    portraitUrl: '/portraits/predefined/victor-crowley.webp',
    str: 50,
    dex: 55,
    con: 55,
    app: 50,
    pow: 80,
    edu: 75,
    siz: 50,
    int: 80,
    luck: 60,
    hp: 10,
    maxHp: 10,
    san: 80,
    maxSan: 99,
    mp: 16,
    maxMp: 16,
    background:
      'Niezależny parapsycholog i autor prac o anomalnych polach elektromagnetycznych. Odrzuca seansowy spirytyzm na rzecz pomiarów fizycznych i analizy akustycznej.',
    birthplace: 'Nowy Orlean, USA',
    residence: 'Boston, USA',
    characterConcept: 'Sceptyczny badacz zjawisk niewyjaśnionych posługujący się aparaturą pomiarową.',
    ideology: 'Większość doniesień to omamy lub oszustwa; dążę do uchwycenia tego jednego procenta spraw niepodważalnie prawdziwych.',
    significantPerson: 'Zmarła żona Elizabeth Crowley, której przedśmiertna obietnica sygnału z drugiej strony stała się dla niego osobistym impulsem badawczym.',
    meaningfulLocation: 'Zapomniane, zdewastowane kaplice i wille w kotlinie Miskatonic, w których rejestruje anomalie.',
    treasuredPossession: 'Zodyfikowany miernik pola elektromagnetycznego (EMF) z kalibracją dr. Rhinea.',
    traits: ['Sceptyczny', 'Niezłomny', 'Analityczny'],
    description: 'Poważny mężczyzna o szpakowatych włosach i analitycznym wzroku. Nosi ciemne golfy pod marynarkami z grubego materiału.',
    backstory: 'Victor opublikował cenione opracowania parapsychologiczne. Podczas nocnej rejestracji w ruinach kaplicy pod Dunwich jego mierniki odnotowały ujemne skoki temperatury oraz poddźwiękowe ciągi fonetyczne wykraczające poza ludzkie możliwości wokalne.\n\n[Kluczowa więź: Pamięć o Elizabeth Crowley - obietnica poszukiwania prawdy poza granicami życia.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Niezwykle silna wola. Wiedza o okultyzmie i badaniach terenowych.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      Okultyzm: 70,
      Psychologia: 60,
      'Nauka (Fizyka)': 45,
      Spostrzegawczość: 60,
      'Korzystanie z Bibliotek': 60,
      Nasłuchiwanie: 55,
      Fotografia: 50,
      Perswazja: 45,
      Unik: 27,
    },
    equipment: [
      {
        id: 'eq_victor_emf',
        name: 'Miernik pola elektromagnetycznego',
        category: 'tool',
        description: 'Wykrywa anomalie magnetyczne.',
      },
      { id: 'eq_victor_recorder', name: 'Dyktafon cyfrowy', category: 'tool' },
      {
        id: 'eq_victor_camera',
        name: 'Lustrzanka z fleszem',
        category: 'tool',
      },
    ],
  },
  {
    id: 'pref_seraphina_marsh_modern',
    era: 'modern',
    archetype: 'mystic',
    name: 'Seraphina Marsh',
    occupation: 'Artysta',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/seraphina-marsh.webp',
    str: 45,
    dex: 65,
    con: 50,
    app: 65,
    pow: 75,
    edu: 60,
    siz: 50,
    int: 75,
    luck: 70,
    hp: 10,
    maxHp: 10,
    san: 75,
    maxSan: 99,
    mp: 15,
    maxMp: 15,
    background:
      'Współczesna malarka ekspresjonistka z bostońskiego bohemy. Tworzy niepokojące, wielkoformatowe płótna przedstawiające podwodne krajobrazy i struktury cyklopowe, widywane we własnych snach.',
    birthplace: 'Innsmouth, USA',
    residence: 'Boston, North End',
    characterConcept: 'Wrażliwa artystka przelewająca podświadome wizje i szepty na płótna.',
    ideology: 'Sztuka jest jedynym medium zdolnym wyrazić prawdy zbyt zatrważające dla słów.',
    significantPerson: 'Julian Mercer, marszand i właściciel galerii sztuki, który sprzedaje jej prace, mimo że sam niepokoi się ich wymową.',
    meaningfulLocation: 'Jasna pracownia malarska w North End, wypełniona zapachami wosku, terpentyny i farb olejnych.',
    treasuredPossession: 'Oprawiony w szorstką płócienną okładkę szkicownik węglowy z rysunkami podwodnej architektury.',
    traits: ['Wrażliwa', 'Intuicyjna', 'Melancholijna'],
    description: 'Młoda kobieta o artystycznym nieładzie kasztanowych włosów i śladach farb na dłoniach. Ubiera się w luźne swetry i chusty.',
    backstory: 'Seraphina opuściła Innsmouth we wczesnej młodości. Jej sny od dziecka nawiedzane są przez podwodne cyklopowe monolithy i nieludzkie postaci. Ostatnio jednak zaczęła słyszeć te same szeptane frazy także na jawie podczas malowania.\n\n[Kluczowa więź: Szkicownik węglowy - bezpośrednie przeniesienie podświadomych powrotów pamięci.]',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: 'Wysokie Szczęście. Intuicyjna i spostrzegawcza.',
    experience: {
      totalXP: 0,
      availableXP: 0,
      earnedThisSession: 0,
      maxEarnedThisSession: 0,
    },
    developmentHistory: [],
    skills: {
      'Sztuka/Rzemiosło (Malarstwo)': 75,
      Spostrzegawczość: 65,
      Psychologia: 60,
      Nasłuchiwanie: 55,
      Okultyzm: 50,
      'Urok Osobisty': 55,
      Historia: 40,
      'Język Obcy (Francuski)': 40,
      Unik: 32,
    },
    equipment: [
      {
        id: 'eq_sera_sketch',
        name: 'Szkicownik węglowy',
        category: 'personal',
        description: 'Pełen niepokojących, surrealistycznych rysunków.',
      },
      {
        id: 'eq_sera_amulet',
        name: 'Srebrny talizman',
        category: 'occult',
        description: 'Pamiątka rodzinna o nieznanym pochodzeniu.',
      },
    ],
  },
];

export const PREDEFINED_CHARACTERS: PredefinedCharacter[] =
  BASE_PREDEFINED_CHARACTERS.map((character) => ({
    ...character,
    equipment: buildPredefinedEquipment(character),
  }));

export function getPredefinedCharactersByEra(
  era: string
): PredefinedCharacter[] {
  if (era === 'gaslight' || era === 'classic' || era === 'modern') {
    return PREDEFINED_CHARACTERS.filter((character) => character.era === era);
  }
  return [];
}
