import { PredefinedCharacter } from './predefined-characters';

export const STREFA_11_CHARACTERS: PredefinedCharacter[] = [
  {
    id: 'strefa11_tomasz_nowicki',
    era: 'modern',
    archetype: 'investigator',
    name: 'Tomasz Nowicki',
    occupation: 'Dziennikarz Śledczy / Prowadzący',
    age: 42,
    gender: 'male',
    portraitUrl: '/portraits/predefined/male_investigator_1.webp',
    str: 55, dex: 60, con: 65, app: 60, pow: 70, edu: 75, siz: 65, int: 70, luck: 55,
    hp: 13, maxHp: 13, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Gospodarz programu "Sygnały Nieznanego", znany z posępnego głosu i chłodnej analizy nadprzyrodzonych zjawisk na antenie telewizyjnej. Dawniej pracował w dziale kryminalnym dużego dziennika.',
    birthplace: 'Warszawa, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Sceptyczny dziennikarz, który widział już zbyt wiele zjawisk niewyjaśnionych, by całkowicie zaprzeczać istnieniu nieznanego.',
    ideology: 'Zawsze jest jakieś logiczne wytłumaczenie – a jeśli go nie ma, oznacza to, że nauka ma jeszcze wiele do odkrycia.',
    significantPerson: 'Była żona, która zostawiła go przez jego obsesję na punkcie "tych dziwnych spraw".',
    meaningfulLocation: 'Studio nagraniowe telewizji, jedyne miejsce, gdzie czuje, że w pełni kontroluje sytuację.',
    treasuredPossession: 'Kasetowy dyktafon reporterski marki Sony z lat 90., który nagrał kiedyś głos EVP.',
    traits: ['Opanowany', 'Sceptyczny', 'Dociekliwy'],
    description: 'Nosi charakterystyczną, czarną skórzaną kurtkę, z ciemnymi okularami zawieszonymi na kołnierzyku.',
    backstory: 'Od lat prowadzi śledztwa dotyczące UFO, poltergeistów i rzekomych nawiedzeń. Z reguły udaje mu się zdemaskować oszustów, jednak niektóre archiwalne sprawy "Sygnałów Nieznanego" do dziś spędzają mu sen z powiek.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Dobry w zbieraniu informacji, nawiązywaniu kontaktów i przesłuchiwaniu świadków.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Spostrzegawczość': 70, 'Perswazja': 65, 'Psychologia': 60, 'Korzystanie z Bibliotek': 50, 'Nasłuchiwanie': 55 },
    equipment: [{ id: 'eq_tom_dyktafon', name: 'Dyktafon na mikrokasety', category: 'tool' }, { id: 'eq_tom_latarka', name: 'Mocna latarka policyjna', category: 'tool' }]
  },
  {
    id: 'strefa11_helena_krawczyk',
    era: 'modern',
    archetype: 'trickster',
    name: 'Helena Krawczyk',
    occupation: 'Producentka Telewizyjna',
    age: 38,
    gender: 'female',
    portraitUrl: '/portraits/predefined/female_social_1.webp',
    str: 40, dex: 65, con: 55, app: 70, pow: 60, edu: 80, siz: 50, int: 75, luck: 65,
    hp: 10, maxHp: 10, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Z żelazną ręką zarządza ekipą "Sygnałów Nieznanego". Załatwia zgody na wejścia, finanse, oraz potrafi przekonać policję do przymknięcia oka na wejście na teren zamknięty.',
    birthplace: 'Kraków, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Wyrachowana organizatorka, dla której liczy się oglądalność i dobrze opowiedziana historia.',
    ideology: 'Telewizja to iluzja, a ludzie chcą wierzyć w niesamowite rzeczy.',
    significantPerson: 'Tomasz Nowicki – choć często się kłócą, tworzą niepokonany zespół.',
    meaningfulLocation: 'Wóz transmisyjny – mobilne centrum dowodzenia.',
    treasuredPossession: 'Notatnik z kontaktami do niemal każdego oficjela w państwie.',
    traits: ['Ambitna', 'Czarująca', 'Stanowcza'],
    description: 'Zawsze nienagannie ubrana (zwykle w dopasowane garnitury damskie i płaszcze), z telefonem komórkowym "cegłą" ciągle w ręku.',
    backstory: 'Helena przeszła długą drogę od asystentki do czołowej producentki programów paranormalnych w latach 90. Często balansuje na granicy prawa, wdzierając się do archiwów lub prywatnych posesji, "dla dobra materiału".',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Rewelacyjna w załatwianiu spraw urzędowych i urokach osobistych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Urok osobisty': 75, 'Perswazja': 70, 'Gadanina': 65, 'Prawo': 45, 'Spostrzegawczość': 50 },
    equipment: [{ id: 'eq_hel_telefon', name: 'Telefon komórkowy (wielki)', category: 'tool' }, { id: 'eq_hel_notes', name: 'Notes kontaktów', category: 'tool' }]
  },
  {
    id: 'strefa11_barbara_zawadzka',
    era: 'modern',
    archetype: 'scholar',
    name: 'Dr Barbara Zawadzka',
    occupation: 'Etnograf / Parapsycholog',
    age: 45,
    gender: 'female',
    portraitUrl: '/portraits/predefined/female_scholar_1.webp',
    str: 45, dex: 55, con: 60, app: 55, pow: 80, edu: 85, siz: 55, int: 80, luck: 60,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background: 'Naukowiec Uniwersytetu Warszawskiego. Regularna ekspertka w programie "Sygnały Nieznanego", oceniająca materiały wideo i ślady fenomenów.',
    birthplace: 'Lublin, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Racjonalny umysł w kontakcie z niewytłumaczalnym. Analizuje kulty, demonologię i ludowe legendy na polskich wsiach.',
    ideology: 'Za każdą legendą i zabobonem kryje się zniekształcone ziarno prawdziwej historii i fizyki.',
    significantPerson: 'Jej mentor ze studiów, który popadł w obłęd podczas badań nad folklorem Podlasia.',
    meaningfulLocation: 'Biblioteka wydziałowa, wśród starych zapisów ludoznawczych.',
    treasuredPossession: 'Kamera na podczerwień i sprzęt do pomiaru pola elektromagnetycznego (EMF).',
    traits: ['Metodyczna', 'Otwarty umysł', 'Skoncentrowana'],
    description: 'Nosi luźne wełniane swetry, okulary na łańcuszku, często z teczką pełną wydruków i ryciny.',
    backstory: 'Wykłada folklor i etnografię. Od czasu dziwnych doświadczeń w terenie zjawiska poltergeist, stała się czołowym parapsychologiem w Polsce, badając korelację między polami magnetycznymi a "duchami".',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Niezbędna do analizy okultyzmu, historii i dziwnych przedmiotów.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 70, 'Historia': 65, 'Antropologia': 60, 'Korzystanie z Bibliotek': 75, 'Języki obce (Łacina)': 50, 'Nauka (Fizyka)': 45 },
    equipment: [{ id: 'eq_barb_emf', name: 'Miernik pola elektromagnetycznego', category: 'tool' }, { id: 'eq_barb_camera', name: 'Kamera z trybem NightVision', category: 'tool' }]
  },
  {
    id: 'strefa11_ryszard_klucznik',
    era: 'modern',
    archetype: 'action',
    name: 'Ryszard "Klucznik" Kaczmarek',
    occupation: 'B. Oficer SB / Technik Ochrony',
    age: 55,
    gender: 'male',
    portraitUrl: '/portraits/predefined/male_action_1.webp',
    str: 75, dex: 65, con: 70, app: 45, pow: 60, edu: 60, siz: 75, int: 65, luck: 50,
    hp: 14, maxHp: 14, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Ochroniarz i "załatwiacz" dla ekipy telewizyjnej. Były funkcjonariusz bezpieczeństwa z okresu PRL, który ma kontakty w milicji/policji i potrafi otworzyć każde drzwi.',
    birthplace: 'Gdańsk, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Twardy facet, który widział najgorsze twarze ludzi i systemów. Zapewnia fizyczne bezpieczeństwo badaczom.',
    ideology: 'Bezpieczeństwo przede wszystkim. Czasem brutalna siła jest jedynym argumentem.',
    significantPerson: 'Jego córka, dla której stara się odkupić dawne winy w SB.',
    meaningfulLocation: 'Jego stara Łada Niva (lub Polonez Caro), służąca za bazę i magazyn sprzętu.',
    treasuredPossession: 'Legalnie zarejestrowany pistolet P-64, w kaburze pod pachą.',
    traits: ['Podejrzliwy', 'Lojalny', 'Bezkompromisowy'],
    description: 'Masywnej postury, zawsze lekko niedogolony. Nosi sprane jeansy, ciężkie buty i wojskową kurtkę.',
    backstory: 'W latach 80. pracował w wydziale zabezpieczenia. Odszedł ze służby po 1989 i odnalazł się jako ekspert ds. fizycznego bezpieczeństwa i technik zakładania podsłuchów. Dziś dba o to, by redakcji "Sygnałów Nieznanego" nie stała się krzywda w opuszczonych fabrykach i bunkrach.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Mistrz przetrwania, walki i dyskretnego otwierania drzwi.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Walka wręcz': 75, 'Broń palna (krótka)': 70, 'Unik': 60, 'Ślusarstwo': 65, 'Zastraszanie': 60, 'Spostrzegawczość': 55 },
    equipment: [{ id: 'eq_rysz_gun', name: 'Pistolet P-64 z zapasowym magazynkiem', category: 'weapon' }, { id: 'eq_rysz_lockpicks', name: 'Zestaw wytrychów i łom', category: 'tool' }]
  }
];
