import { ExtendedJournalEntry } from '@/components/ui/session-journal';
import { EvidenceNode, EvidenceRelation } from '@/types/investigator-board';

export const MOCK_JOURNAL_ENTRIES: ExtendedJournalEntry[] = [
  // 1. MISJE (Quests)
  {
    id: 'test_quest_1',
    type: 'quest',
    title: 'Tajemnica Domu Corbitta',
    content:
      'Pan Stephen Knott poprosił o zbadanie starych ruin i kamienicy Corbitta w Bostonie. Poprzedni lokatorzy popadli w obłęd lub ponieśli tragiczną śmierć. Należy ustalić źródło mrocznej siły nawiedzającej dom.',
    questStatus: 'active',
    category: 'Badania',
    inGameDate: '21 Lipca 1926',
    gameDay: 2,
    gameHour: 14,
    tags: ['Misja', 'Corbitt', 'Boston', 'Śledztwo'],
    objectives: [
      {
        id: 'obj_1',
        description: 'Przeszukaj piwnicę i sprawdź zamurowaną ścianę',
        completed: false,
        gameDay: 2,
        gameHour: 15,
      },
      {
        id: 'obj_2',
        description: 'Przeprowadź wywiad z sąsiadami i panem Knottem',
        completed: true,
        dateCompleted: '21.07.1926',
        gameDay: 1,
        gameHour: 11,
      },
      {
        id: 'obj_3',
        description: 'Odnajdź dziennik Waltera Corbitta w Archiwum Miskatonic',
        completed: true,
        dateCompleted: '21.07.1926',
        gameDay: 1,
        gameHour: 16,
      },
    ],
  },
  {
    id: 'test_quest_2',
    type: 'quest',
    title: 'Rytuał pod Srebrną Poświatą',
    content:
      'Lokalna policja złożyła raport o tajemniczych zgromadzeniach w lasach wokół Arkham. Obserwatorzy twierdzą, że widziano postaci w szatach śpiewające w zapomnianym języku.',
    questStatus: 'completed',
    category: 'Walka',
    inGameDate: '18 Lipca 1926',
    gameDay: 1,
    gameHour: 23,
    tags: ['Kult', 'Arkham', 'Rytuał'],
    objectives: [
      {
        id: 'obj_21',
        description: 'Przerwij odprawianie rytuału na polanie',
        completed: true,
        dateCompleted: '18.07.1926',
        gameDay: 1,
      },
    ],
  },

  // 2. KRONIKA (Journal / Events)
  {
    id: 'test_journal_1',
    type: 'journal',
    title: 'Odkrycie w Archiwum Miskatonic',
    content:
      'Spędziłem długie godziny w mrocznych salach Biblioteki Uniwersytetu Miskatonic. Wśród zakurzonych woluminów natrafiłem na wzmiankę o zakonie kapłanów Pana Głębin pracujących w Arkham pod koniec XIX wieku. Zapiski sugerują, że starożytny amulet znajduje się w domowym sejfie Corbitta.',
    category: 'Badania',
    inGameDate: '21 Lipca 1926',
    gameDay: 2,
    gameHour: 10,
    isAutoGenerated: true,
    tags: ['Badania', 'Biblioteka', 'Artefakt'],
  },
  {
    id: 'test_journal_2',
    type: 'journal',
    title: 'Nocne Koszmary i Utrata Zmysłów',
    content:
      'Gdy tylko zamknąłem oczy, nawiedziła mnie wizja cyklopowych miast wzniesionych z zielonkawego kamienia pod obcymi gwiazdami. Obudziłem się z zimnym potym na czole i poczuciem, że ktoś patrzy na mnie z narożnika pokoju. Mój umysł ledwo znosi ten nacisk.',
    category: 'Sny',
    inGameDate: '20 Lipca 1926',
    gameDay: 1,
    gameHour: 3,
    tags: ['Koszmary', 'Poczytalność', 'Cthulhu'],
  },

  // 3. ENCYKLOPEDIA (Characters, Locations, Items)
  {
    id: 'test_encyclo_1',
    type: 'npc',
    title: 'Profesor Henry Armitage',
    content:
      'Kustosz i dyrektor biblioteki Uniwersytetu Miskatonic. Człowiek o wybitnej wiedzy fizycznej i znajomości zakazanych ksiąg. Twierdzi, że Wilbur Whateley próbował wypożyczyć lub skopiować fragmenty z oryginalnego wyciągu z Necronomiconu.',
    category: 'Odkrycia',
    tags: ['NPC', 'Miskatonic', 'Armitage', 'Necronomicon'],
  },
  {
    id: 'test_encyclo_2',
    type: 'npc',
    title: 'Inspector John Legrasse',
    content:
      'Śledczy z Nowego Orleanu, który prowadził sprawę mrocznego kultu w bagnach Luizjany. Posiadał małą statuetkę wykonaną z nieznanego zielono-czarnego kamienia.',
    category: 'Odkrycia',
    tags: ['NPC', 'Policja', 'Kult', 'Nowy Orlean'],
  },
  {
    id: 'test_encyclo_3',
    type: 'location',
    title: 'Biblioteka Uniwersytetu Miskatonic',
    content:
      'Stary, kamienny budynek w sercu Arkham. Miejsce przechowywania rzadkich i niebezpiecznych wolumenów, w tym chronionego w specjalnym sejfie Necronomiconu.',
    category: 'Odkrycia',
    tags: ['Lokalizacje', 'Arkham', 'Miskatonic', 'Biblioteka'],
  },
  {
    id: 'test_encyclo_4',
    type: 'item',
    title: 'Srebrny Klucz z Providence',
    content:
      'Kunsztownie wykonany klucz pokryty arabeskami i nieznanymi symbolem astrologicznymi. Prawdopodobnie powiązany ze Srebrną Brama Krainy Snów.',
    category: 'Odkrycia',
    tags: ['Artefakty', 'Krainy Snów', 'Srebrny Klucz'],
  },

  // 4. NOTATKI (Notes)
  {
    id: 'test_note_1',
    type: 'note',
    title: 'Teoria na temat symetrii okien',
    content:
      'Zauważyłem, że rozkład okien na drugim piętrze Domu Corbitta podważa zasady geometrii euklidesowej. Z zewnątrz są trzy okna, ale od środka widać cztery wnęki. Czy wewnątrz znajduje się ukryte pomieszczenie?',
    category: 'Notatki',
    inGameDate: '21 Lipca 1926',
    tags: ['Notatka', 'Hipoteza', 'Geometria'],
  },
  {
    id: 'test_note_2',
    type: 'note',
    title: 'Zastrzeżenia co do zeznań sąsiada',
    content:
      'Pan Thomas twierdzi, że nie słyszał niczego zza ściany, ale jego lewa dłoń drży niekontrolowanie za każdym razem, gdy padnie nazwisko Corbitta. Ewidentnie ukrywa prawdę ze strachu.',
    category: 'Notatki',
    inGameDate: '21 Lipca 1926',
    tags: ['Notatka', 'Wywiad', 'Podejrzany'],
  },
];

export const MOCK_BOARD_NODES: EvidenceNode[] = [
  {
    id: 'node_corbitt_house',
    title: 'Dom Corbitta (Harrison St.)',
    description: 'Nawiedzona nieruchomość stanowiąca cel śledztwa.',
    type: 'location',
    status: 'confirmed',
    position: { x: 420, y: 220 },
    tags: ['Lokalizacja', 'Boston'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'node_walter_corbitt',
    title: 'Walter Corbitt',
    description: 'Buntowniczy okultysta, zmarły właściciel.',
    type: 'suspect',
    status: 'hypothesis',
    position: { x: 200, y: 120 },
    tags: ['Kultysta', 'Zwłoki'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'node_silver_key',
    title: 'Srebrny Klucz',
    description: 'Artefakt odnaleziony w bibliotece.',
    type: 'artifact',
    status: 'confirmed',
    position: { x: 650, y: 150 },
    tags: ['Artefakt'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'node_miskatonic_log',
    title: 'Dziennik z Miskatonic',
    description: 'Zapiski z 1864 roku ujawniające rytuał pod ziemią.',
    type: 'evidence',
    status: 'confirmed',
    position: { x: 220, y: 380 },
    tags: ['Dowód', 'Dokument'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'node_hidden_room',
    title: 'Ukryte Pomieszczenie w Piwnicy',
    description: 'Podejrzenie zamurowanej ściany z nieeuklidesową przestrzenią.',
    type: 'clue',
    status: 'hypothesis',
    position: { x: 580, y: 360 },
    tags: ['Poszlaka'],
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_BOARD_RELATIONS: EvidenceRelation[] = [
  {
    id: 'rel_1',
    fromNodeId: 'node_walter_corbitt',
    toNodeId: 'node_corbitt_house',
    label: 'Zbudował i zamieszkuje',
    status: 'strong',
  },
  {
    id: 'rel_2',
    fromNodeId: 'node_miskatonic_log',
    toNodeId: 'node_walter_corbitt',
    label: 'Opisuje praktyki magii',
    status: 'weak',
  },
  {
    id: 'rel_3',
    fromNodeId: 'node_corbitt_house',
    toNodeId: 'node_hidden_room',
    label: 'Ukryte w piwnicy',
    status: 'strong',
  },
  {
    id: 'rel_4',
    fromNodeId: 'node_silver_key',
    toNodeId: 'node_hidden_room',
    label: 'Może pasować do zamka',
    status: 'doubtful',
  },
];
