import type { JournalEntry } from './types';

/**
 * Pure function: buduje HTML+CSS template dla eksportu PDF dziennika kampanii.
 *
 * Wydzielona z `src/components/ui/journal.tsx:226-348` (block `exportToPDF`) w IND-101 (sesja 97).
 * Pełne 1:1 z oryginałem z 1 zmianą semantyczną: parametr `now: Date` injectowany dla testowalności.
 *
 * Caller `journal.tsx:226 exportToPDF` woła `window.open + document.write(buildPdfHtml(entries, new Date()))`.
 */
export function buildPdfHtml(
  entries: JournalEntry[],
  now: Date = new Date()
): string {
  const dateLabel = now.toLocaleDateString('pl-PL');

  const sections = Object.entries(
    entries.reduce(
      (acc, entry) => {
        if (!acc[entry.category]) acc[entry.category] = [];
        acc[entry.category].push(entry);
        return acc;
      },
      {} as Record<string, JournalEntry[]>
    )
  )
    .map(
      ([category, categoryEntries]) => `
    <h2>${category}</h2>
    ${categoryEntries
      .map(
        (entry) => `
      <div class="entry">
        <h3>${entry.title}</h3>
        <div class="meta">
          📅 ${entry.date}
          ${entry.isAutoGenerated ? '<span class="auto-tag">Auto</span>' : ''}
        </div>
        <p>${entry.content.replace(/\n/g, '<br>')}</p>
        ${
          entry.tags.length > 0
            ? `
          <div class="tags">
            ${entry.tags.map((tag) => `<span class="tag">#${tag}</span>`).join('')}
          </div>
        `
            : ''
        }
      </div>
    `
      )
      .join('')}
  `
    )
    .join('');

  return `
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <title>Dziennik Kampanii - ${dateLabel}</title>
  <style>
    body {
      font-family: 'Georgia', serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #333;
      line-height: 1.6;
    }
    h1 {
      text-align: center;
      border-bottom: 2px solid #8B4513;
      padding-bottom: 20px;
      color: #2c1810;
    }
    h2 {
      color: #8B4513;
      margin-top: 30px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 10px;
    }
    h3 {
      color: #4a3c31;
      margin-bottom: 5px;
    }
    .entry {
      background: #faf8f5;
      padding: 15px 20px;
      margin: 15px 0;
      border-left: 3px solid #8B4513;
      page-break-inside: avoid;
    }
    .meta {
      font-size: 0.85em;
      color: #666;
      margin-bottom: 10px;
    }
    .auto-tag {
      background: #e3f2fd;
      color: #1565c0;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.75em;
    }
    .tags {
      margin-top: 10px;
    }
    .tag {
      background: #f0f0f0;
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 0.8em;
      margin-right: 5px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      color: #999;
      font-size: 0.9em;
    }
    @media print {
      body { padding: 20px; }
      .entry { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <h1>📖 Dziennik Kampanii</h1>
  <p style="text-align: center; color: #666;">Call of Cthulhu • Wyeksportowano: ${dateLabel}</p>

  ${sections}

  <div class="footer">
    <p>Wygenerowano przez Zew Cthulhu App</p>
  </div>
</body>
</html>`;
}
