/**
 * Typed kontrakt dla wpisu dziennika kampanii (cloud-synced via /api/journal).
 *
 * Wydzielony z `src/components/ui/journal.tsx:8` w IND-101 Faza 1+2 (sesja 97 wzorzec
 * sesji 91 IND-123 - extract pure code bez integration UI). journal.tsx re-eksportuje
 * `JournalEntry` z tego pliku dla backward compat z caller'em `src/app/journal/page.tsx:3`.
 *
 * UWAGA: w aplikacji istnieją 3 osobne implementacje typu JournalEntry:
 *   1. TEN PLIK - cloud journal (date/category/tags/isAutoGenerated/sessionId)
 *   2. `src/lib/types.ts` - session-journal JournalEntry (timestamp/JournalEventType)
 *   3. `src/components/dialogs/JournalDialog.tsx:16` - inline duplikacja
 *   4. `src/app/api/journal/route.ts:5` - backend duplikacja
 *
 * Konsolidacja 3 typów = osobny ticket follow-up.
 */
export type JournalEntryType = 'quest' | 'journal' | 'encyclopedia_location' | 'encyclopedia_character' | 'encyclopedia_item' | 'note';

export interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  dateCompleted?: string;
  gameDay?: number;
  gameHour?: number;
}

export interface JournalEntry {
  id: string;
  date: string;
  title: string;
  content: string;
  category: string;
  tags: string[];
  isAutoGenerated: boolean;
  sessionId?: string;
  
  // Nowe pola RPG
  type?: JournalEntryType;
  gameDay?: number;
  gameHour?: number;
  questStatus?: 'active' | 'completed' | 'failed';
  objectives?: QuestObjective[];
}

