import type { JournalEntry } from './types';

/**
 * Pure function: generuje string Markdown z wpisów dziennika.
 *
 * Wydzielona z `src/components/ui/journal.tsx:189-223` w IND-101 (sesja 97). Pełne 1:1 z oryginałem
 * z 1 zmianą semantyczną: parametr `now: Date` injectowany dla testowalności (oryginał używał
 * `new Date()` inline → niedeterministyczne testy).
 *
 * Caller `journal.tsx:175 exportToMarkdown` woła `generateMarkdown(entries, new Date())`.
 */
export function generateMarkdown(
  entries: JournalEntry[],
  now: Date = new Date()
): string {
  let md = `# 📖 Dziennik Kampanii\n\n`;
  md += `> Wyeksportowano: ${now.toLocaleDateString('pl-PL')} ${now.toLocaleTimeString('pl-PL')}\n\n`;
  md += `---\n\n`;

  // Grupowanie według kategorii
  const byCategory = entries.reduce(
    (acc, entry) => {
      if (!acc[entry.category]) acc[entry.category] = [];
      acc[entry.category].push(entry);
      return acc;
    },
    {} as Record<string, JournalEntry[]>
  );

  for (const [category, categoryEntries] of Object.entries(byCategory)) {
    md += `## ${category}\n\n`;

    for (const entry of categoryEntries) {
      md += `### ${entry.title}\n\n`;
      md += `**Data:** ${entry.date}`;
      if (entry.isAutoGenerated) {
        md += ` _(automatycznie wygenerowane)_`;
      }
      md += `\n\n`;
      md += `${entry.content}\n\n`;

      if (entry.tags.length > 0) {
        md += `**Tagi:** ${entry.tags.map((t) => `\`#${t}\``).join(', ')}\n\n`;
      }

      md += `---\n\n`;
    }
  }

  md += `\n*Wygenerowano przez Zew Cthulhu App*\n`;
  return md;
}
