import type { PredefinedCharacter } from './predefined-characters';
import { applyCatalogTemplate, CATEGORY_FALLBACK_ASSETS } from '@/lib/equipment-catalog';

const BASE_AMERICAN_COLD_CASES_CHARACTERS: PredefinedCharacter[] = [
  // ==========================================================================
  // 1. 1893 (GASLIGHT) - THE ENGLEWOOD LABYRINTH: HOLMES'S CASTLE
  // ==========================================================================
  {
    id: 'coldcase_frank_geyer',
    scenarioIds: ['englewood-murder-castle-1893'],
    startingNodeId: 'node-chicago-precinct',
    openingHook:
      'Arrives at Englewood Precinct from Philadelphia carrying the Pitezel insurance dossier and a warrant to search 63rd and Wallace Street.',
    era: 'gaslight',
    archetype: 'investigator',
    name: 'Det. Frank Geyer',
    occupation: 'Police Detective (Philadelphia Bureau)',
    age: 41,
    gender: 'male',
    portraitUrl: '/portraits/predefined/archibald-blackwood.webp',
    str: 65, dex: 60, con: 70, app: 55, pow: 75, edu: 70, siz: 65, int: 75, luck: 60,
    hp: 13, maxHp: 13, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background:
      'Methodical Philadelphia detective who has tracked H.H. Holmes across three states to find the missing Pitezel children: Alice, Nellie, and Howard.',
    birthplace: 'Philadelphia, Pennsylvania',
    residence: 'Philadelphia, Pennsylvania',
    characterConcept: 'Relentless bloodhound of the law who refuses to let bureaucratic apathy bury missing children.',
    ideology: 'Every lie leaves a physical ledger; follow the paper and the bones will speak.',
    significantPerson: 'Carrie Pitezel, the distraught mother who entrusted him with finding her three children.',
    meaningfulLocation: 'Englewood Police Precinct telegraph room, where the trail of Holmes converges.',
    treasuredPossession: 'A stack of unmailed letters written by young Alice Pitezel to her mother.',
    traits: ['Methodical', 'Compassionate', 'Unflinching'],
    description: 'Heavy wool overcoat, neat mustache, carrying a leather satchel of hotel registers and railway timetables.',
    backstory:
      'Frank Geyer has spent twenty years walking the cobblestone alleys of Philadelphia, but nothing prepared him for the cold, smiling void of Herman Webster Mudgett, known to the world as Dr. H.H. Holmes. After uncovering the staged laboratory explosion of Benjamin Pitezel, Geyer realized that Holmes had taken three of the Pitezel children - Alice, Nellie, and little Howard - northward toward the Great Lakes. Armed with a stack of the children’s unmailed letters that Holmes callously kept in a tin box, Geyer has arrived in Chicago on a freezing November evening in 1894. Starting at the Englewood Police Precinct, he intends to force open the doors of Holmes’s notorious three-story building at 63rd and Wallace Street before the doctor’s unseen accomplices can set a match to the evidence.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Englewood Precinct. High Spot Hidden, Law, and Psychology for interrogating witnesses.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Spostrzegawczość': 75,
      'Psychologia': 70,
      'Prawo': 65,
      'Perswazja': 65,
      'Tropienie': 60,
      'Korzystanie z Bibliotek': 55,
      'Broń Palna (Krótka)': 60,
      'Walka Wręcz': 55,
      'Nasłuchiwanie': 50,
      'Język Ojczysty (Angielski)': 70,
      'Unik': 40,
    },
    equipment: [
      { id: 'eq_geyer_revolver', name: 'Colt .38 Police Positive Revolver', category: 'weapon' },
      { id: 'eq_geyer_lantern', name: 'Bullseye Brass Dark-Lantern', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_clara_vance',
    scenarioIds: ['englewood-murder-castle-1893'],
    startingNodeId: 'node-castle-pharmacy',
    openingHook:
      'Enters the ground-floor pharmacy at 63rd and Wallace Street posing as a buyer while investigating her friend Emeline Cigrand’s disappearance.',
    era: 'gaslight',
    archetype: 'trickster',
    name: 'Clara Vance',
    occupation: 'Investigative Reporter (Chicago Tribune)',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/beatrice-vance.webp',
    str: 45, dex: 65, con: 55, app: 70, pow: 70, edu: 75, siz: 50, int: 80, luck: 65,
    hp: 10, maxHp: 10, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background:
      'Undercover journalist who noticed that dozens of female stenographers hired at Holmes’s building during the 1893 World’s Fair vanished without a trace.',
    birthplace: 'Boston, Massachusetts',
    residence: 'Chicago, Illinois',
    characterConcept: 'Fearless investigative reporter who uses charm and shorthand to expose Gilded Age monsters.',
    ideology: 'City Hall protected the World’s Fair profits; the press must protect the dead.',
    significantPerson: 'Emeline Cigrand, a former stenographer whose last letter came from 63rd and Wallace Street.',
    meaningfulLocation: 'The ground-floor pharmacy counter of Holmes’s Castle.',
    treasuredPossession: 'A silver locket containing Emeline Cigrand’s photograph and a skeleton key.',
    traits: ['Inquisitive', 'Audacious', 'Sharp-tongued'],
    description: 'Tailored tweed walking suit, ink-stained gloves, and a concealed Kodak detective camera in her muff.',
    backstory:
      'During the glittering summer of the 1893 World’s Columbian Exposition, Clara Vance covered the White City for the Chicago Tribune. While the newspapers celebrated progress and electric light, Clara kept a private ledger of young women who answered employment advertisements at a three-story drugstore in Englewood and never returned to their boarding houses. Among them was her close acquaintance, Emeline Cigrand. When word reached Chicago that Dr. H.H. Holmes had been arrested in the East, Clara did not wait for the police. Slipping past the watchman into the ground-floor pharmacy at 63rd and Wallace Street, she can smell the chloroform and quicklime seeping up through the floorboards - and she intends to find the hidden staircase to the second floor.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts directly inside the Ground-Floor Pharmacy. Excels at Fast Talk, Spot Hidden, and Photography.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Gadanina': 75,
      'Urok osobisty': 70,
      'Spostrzegawczość': 70,
      'Fotografia': 65,
      'Korzystanie z Bibliotek': 60,
      'Psychologia': 55,
      'Skradanie': 55,
      'Ślusarstwo': 45,
      'Język Ojczysty (Angielski)': 75,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_clara_kodak', name: 'Folding Pocket Kodak Camera & Flash Powder', category: 'tool' },
      { id: 'eq_clara_hatpin', name: 'Nine-Inch Steel Hatpin & Skeleton Key', category: 'weapon' },
    ],
  },
  {
    id: 'coldcase_arthur_pym',
    scenarioIds: ['englewood-murder-castle-1893'],
    startingNodeId: 'node-castle-second-floor',
    openingHook:
      'Summoned to Englewood Precinct by Fidelity Mutual counsel Horace Gary to examine chemical and anatomical evidence from the Castle.',
    era: 'gaslight',
    archetype: 'scholar',
    name: 'Dr. Arthur Pym',
    occupation: 'Forensic Physician & Toxicologist',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/arthur-pendleton.webp',
    str: 50, dex: 60, con: 60, app: 55, pow: 80, edu: 85, siz: 55, int: 80, luck: 55,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background:
      'Consulting medical examiner for Fidelity Mutual Life Association and Rush Medical College who discovered anomalous geometric carvings on skeletons sold by Holmes.',
    birthplace: 'Providence, Rhode Island',
    residence: 'Chicago, Illinois',
    characterConcept: 'Clinical man of science confronting an alchemical geometry that violates human anatomy.',
    ideology: 'Nature obeys fixed laws; whatever Mudgett built in that cellar is a deliberate perversion of matter.',
    significantPerson: 'Horace Gary, the insurance counsel who retained him to verify the Pitezel autopsy.',
    meaningfulLocation: 'The anatomy laboratory at Rush Medical College.',
    treasuredPossession: 'A brass pocket spectroscope and a chemical reagent kit.',
    traits: ['Analytical', 'Stoic', 'Erudite'],
    description: 'Wire-rimmed pince-nez spectacles, black frock coat smelling faintly of carbolic acid.',
    backstory:
      'As a consulting anatomist in Chicago, Dr. Arthur Pym twice purchased articulated human skeletons from an affable Englewood pharmacist named Dr. H.H. Holmes. Upon examining the craniums under a magnifying glass, Pym discovered microscopic, non-Euclidean grooves scored into the interior temporal bone - marks that could only have been made while the bone was subjected to an unknown high-frequency vibration. Now retained by the Fidelity Mutual Life Association to assist Detective Geyer at the Englewood Precinct, Pym suspects that Holmes’s "Castle" is not merely a slaughterhouse for insurance fraud, but a physical apparatus designed around forbidden 17th-century alchemical geometry.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Englewood Precinct. Master of Medicine, Chemistry, Accounting, and Occult analysis.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Medycyna': 80,
      'Nauka (Chemia)': 75,
      'Księgowość': 60,
      'Okultyzm': 55,
      'Spostrzegawczość': 65,
      'Korzystanie z Bibliotek': 70,
      'Pierwsza Pomoc': 70,
      'Psychologia': 50,
      'Język Ojczysty (Angielski)': 85,
      'Unik': 35,
    },
    equipment: [
      { id: 'eq_pym_kit', name: 'Leather Forensic & Chemical Reagent Valise', category: 'tool' },
      { id: 'eq_pym_cane', name: 'Silver-Headed Sword Cane', category: 'weapon' },
    ],
  },
  {
    id: 'coldcase_thomas_oconnell',
    scenarioIds: ['englewood-murder-castle-1893'],
    startingNodeId: 'node-quinlan-quarters',
    openingHook:
      'Confronts caretaker Pat Quinlan in the Castle courtyard quarters to demand the hidden blueprints and find his vanished brother.',
    era: 'gaslight',
    archetype: 'action',
    name: 'Thomas "Bricklayer" O’Connell',
    occupation: 'Master Builder & Structural Mason',
    age: 36,
    gender: 'male',
    portraitUrl: '/portraits/predefined/silas-thorne.webp',
    str: 80, dex: 60, con: 75, app: 50, pow: 65, edu: 55, siz: 75, int: 65, luck: 55,
    hp: 15, maxHp: 15, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background:
      'Foreman of one of the construction crews hired and abruptly fired by Holmes in 1892 after building the blind brick shafts and iron-lined vaults on the second floor.',
    birthplace: 'Cork, Ireland',
    residence: 'South Halsted, Chicago',
    characterConcept: 'Brawny mason who knows with his own hands that the walls of the Castle do not add up.',
    ideology: 'A plumb line never lies - and the walls I laid on that second floor bend in ways stone never should.',
    significantPerson: 'His younger brother Liam, an apprentice pipefitter who went back to collect unpaid wages from Holmes and never came out.',
    meaningfulLocation: 'The inner courtyard outside caretaker Pat Quinlan’s quarters.',
    treasuredPossession: 'His brass surveyor’s plumb-bob and a heavy mason’s hammer.',
    traits: ['Fierce', 'Practical', 'Haunted'],
    description: 'Broad-shouldered, calloused hands, wearing a heavy canvas work coat and carrying an iron crowbar.',
    backstory:
      'In the spring of 1892, Thomas O’Connell and his masonry crew were paid double wages by Dr. Holmes to brick up windows from the inside, hang false doors against solid walls, and line Room 14 with sheet iron and gas pipes. When Thomas pointed out that the interior angles of the second-floor corridor measured 114 degrees without expanding the outer wall, Holmes fired the entire crew on the spot and refused to pay their final week. Thomas’s younger brother Liam went back to the Castle at night to demand their money and vanished. Tonight, Thomas has cornered caretaker Pat Quinlan in the courtyard quarters with a crowbar in hand: he wants the composite blueprint, and he is going down into the cellar kiln.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts in Caretaker Quinlan’s Quarters. High Strength, Mechanical Repair, Navigate, and Brawn.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Walka Wręcz': 75,
      'Mechanika': 70,
      'Nawigacja': 65,
      'Ślusarstwo': 60,
      'Zastraszanie': 65,
      'Spostrzegawczość': 60,
      'Nasłuchiwanie': 55,
      'Broń Palna (Krótka)': 50,
      'Język Ojczysty (Angielski)': 55,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_oconnell_bar', name: 'Forged Iron Wrecking Bar & Mason’s Hammer', category: 'weapon' },
      { id: 'eq_oconnell_plumb', name: 'Brass Surveyor’s Plumb-Line & Oil Lantern', category: 'tool' },
    ],
  },

  // ==========================================================================
  // 2. 1924 (CLASSIC) - THE ALMER COE SPECTACLES: THE FRANKS AFFAIR
  // ==========================================================================
  {
    id: 'coldcase_samuel_michalski',
    scenarioIds: ['almer-coe-spectacles-1924'],
    startingNodeId: 'node-wolf-lake-culvert',
    openingHook:
      'Inspects the Wolf Lake drainage culvert alongside Pump Tender Tony Minke with the horn-rimmed spectacles sealed in an evidence envelope.',
    era: 'classic',
    archetype: 'investigator',
    name: 'Insp. Samuel Michalski',
    occupation: 'State’s Attorney Detective',
    age: 39,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tommy-obrien.webp',
    str: 65, dex: 60, con: 70, app: 55, pow: 70, edu: 65, siz: 70, int: 70, luck: 55,
    hp: 14, maxHp: 14, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background:
      'Senior investigator for Cook County State’s Attorney Robert E. Crowe, assigned to trace the spectacles found beside Bobby Franks’s body at Wolf Lake.',
    birthplace: 'Chicago, Illinois',
    residence: 'Pilsen, Chicago',
    characterConcept: 'Working-class Chicago detective determined not to let millionaire heirs buy their way out of murder.',
    ideology: 'Rich boys in Kenwood think they are gods until the handcuffs click shut.',
    significantPerson: 'State’s Attorney Robert E. Crowe, who gave him 28 hours to break the alibi.',
    meaningfulLocation: 'The cinder embankment at Wolf Lake where the spectacles were dropped.',
    treasuredPossession: 'Evidence Envelope #1 containing the tortoise-shell Almer Coe eyeglasses.',
    traits: ['Tenacious', 'Streetwise', 'incorruptible'],
    description: 'Gray fedora, rumpled three-piece suit, mud-caked oxfords from wading the Calumet reeds.',
    backstory:
      'Born to Polish immigrants on the South Side, Samuel Michalski worked his way up to chief investigator for the Cook County State’s Attorney. When 14-year-old Bobby Franks was found dead in a concrete culvert near Wolf Lake, the press assumed a gangland kidnapping for ransom. Standing in the marsh grass at dawn, Michalski knew better: gangsters do not pour laboratory-grade hydrochloric acid over a boy’s face, nor do they drop custom tortoise-shell spectacles with a patented brass hinge in the reeds. Holding the glasses in an evidence envelope, Michalski is ready to trace the prescription from the marshes to the richest mansions in Kenwood.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at the Wolf Lake Culvert crime scene. Strong Spot Hidden, Track, Law, and Firearms.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Spostrzegawczość': 75,
      'Tropienie': 65,
      'Prawo': 65,
      'Psychologia': 65,
      'Zastraszanie': 60,
      'Broń Palna (Krótka)': 65,
      'Prowadzenie auta': 55,
      'Walka Wręcz': 60,
      'Język Ojczysty (Angielski)': 65,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_michalski_colt', name: 'Smith & Wesson .38 Detective Special', category: 'weapon' },
      { id: 'eq_michalski_badge', name: 'State’s Attorney Warrant & Plaster Track Kit', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_eleanor_vance',
    scenarioIds: ['almer-coe-spectacles-1924'],
    startingNodeId: 'node-almer-coe-opticians',
    openingHook:
      'Arrives at Almer Coe & Co. Opticians on Wabash Avenue minutes ahead of the press pack to inspect prescription card #419-C.',
    era: 'classic',
    archetype: 'trickster',
    name: 'Eleanor "Nell" Vance',
    occupation: 'Crime Reporter (Chicago Daily News)',
    age: 27,
    gender: 'female',
    portraitUrl: '/portraits/predefined/dorothy-updike.webp',
    str: 45, dex: 70, con: 55, app: 70, pow: 65, edu: 75, siz: 50, int: 80, luck: 65,
    hp: 10, maxHp: 10, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background:
      'Star reporter at the Chicago Daily News who noticed that young University of Chicago graduate Richard Loeb has been hanging around press row asking too many questions.',
    birthplace: 'Evanston, Illinois',
    residence: 'Near North Side, Chicago',
    characterConcept: 'Razor-sharp Jazz Age reporter who spots the theatrical arrogance behind the ransom note.',
    ideology: 'The cleverest killers always sign their work because they cannot bear to go unadmired.',
    significantPerson: 'Her aunt Clara Vance, who taught her investigative reporting in the 1890s.',
    meaningfulLocation: 'The optical index room at Almer Coe & Co. on Wabash Avenue.',
    treasuredPossession: 'A photostat copy of the "George Johnson" Underwood ransom letter.',
    traits: ['Perceptive', 'Witty', 'Relentless'],
    description: 'Cloche hat, bobbed hair, carrying a press pass and a magnifying loupe for comparing typewriter fonts.',
    backstory:
      'While male reporters from five rival papers chased phantom gangsters across Cicero, Nell Vance studied the photostat of the ransom letter sent to Jacob Franks. The vocabulary was too ornate, the margins too geometric, and a charming 18-year-old millionaire named Richard Loeb kept buying drinks for reporters at the Detective Bureau while offering theories about the kidnapping. Tipped off by a clerk that the spectacles found at Wolf Lake have been brought to Almer Coe & Co. on Wabash Avenue, Nell has talked her way into the optician’s back office just as card #419-C is pulled from the cabinet.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Almer Coe & Co. Opticians. High Library Use, Charm, Persuade, and Spot Hidden.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Korzystanie z Bibliotek': 75,
      'Urok osobisty': 70,
      'Perswazja': 70,
      'Spostrzegawczość': 70,
      'Psychologia': 65,
      'Gadanina': 65,
      'Fotografia': 55,
      'Język Ojczysty (Angielski)': 75,
      'Unik': 40,
    },
    equipment: [
      { id: 'eq_nell_loupe', name: 'Typeface Comparison Loupe & Photostat of Ransom Note', category: 'tool' },
      { id: 'eq_nell_press', name: 'Chicago Daily News Press Credentials', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_julian_ward',
    scenarioIds: ['almer-coe-spectacles-1924'],
    startingNodeId: 'node-uchicago-archive',
    openingHook:
      'Discovers sliced pages from the Hermetic folio "De Voluntate Absoluta" inside the University of Chicago seminar room used by Leopold and Loeb.',
    era: 'classic',
    archetype: 'scholar',
    name: 'Prof. Julian Ward',
    occupation: 'Professor of Psychology & Classical Philology',
    age: 51,
    gender: 'male',
    portraitUrl: '/portraits/predefined/william-dyer.webp',
    str: 45, dex: 55, con: 60, app: 55, pow: 80, edu: 90, siz: 55, int: 85, luck: 55,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background:
      'Senior faculty member at the University of Chicago who taught Nathan Leopold classical Latin and grew alarmed by his cold obsession with ritual amorality.',
    birthplace: 'New Haven, Connecticut',
    residence: 'Hyde Park, Chicago',
    characterConcept: 'Conscience-stricken academic who realizes his most brilliant student has turned philosophy into ritual murder.',
    ideology: 'Intellect divorced from empathy is the oldest and coldest demon in human history.',
    significantPerson: 'Clarence Darrow, his longtime friend with whom he debates criminal responsibility.',
    meaningfulLocation: 'The rare-book seminar room in Harper Memorial Library at the University of Chicago.',
    treasuredPossession: 'Master keys to the University of Chicago special collections and faculty archives.',
    traits: ['Erudite', 'Grave', 'Observant'],
    description: 'Three-piece tweed suit, fountain pen in vest pocket, carrying a leather portfolio of seminar papers.',
    backstory:
      'Professor Julian Ward marveled at Nathan Leopold’s ability to translate 17th-century Latin at sight, until the nineteen-year-old requested access to "De Voluntate Absoluta" - a suppressed Hermetic treatise arguing that a mind of sufficient intellect can sever its mortal tether by executing two emotionless acts of destruction. Tonight, after reading of the Franks murder in Hyde Park, Ward unlocked the seminar room in Harper Library and found three pages razor-sliced from the treatise alongside Leopold’s ornithological notes on Wolf Lake. Starting inside the University archive, Ward must decipher where the second act is scheduled before midnight.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts inside the University of Chicago Archive. Expert in Occult, Psychology, Library Use, and Latin.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Okultyzm': 75,
      'Korzystanie z Bibliotek': 80,
      'Psychologia': 75,
      'Historia': 70,
      'Języki obce (Łacina)': 80,
      'Nauka (Chemia)': 50,
      'Spostrzegawczość': 60,
      'Perswazja': 65,
      'Język Ojczysty (Angielski)': 90,
      'Unik': 30,
    },
    equipment: [
      { id: 'eq_ward_keys', name: 'University of Chicago Faculty Master Keys', category: 'tool' },
      { id: 'eq_ward_folio', name: 'Seminar Thesis Samples & Latin Lexicon', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_arthur_lindqvist',
    scenarioIds: ['almer-coe-spectacles-1924'],
    startingNodeId: 'node-leopold-mansion-garage',
    openingHook:
      'Slips into the Kenwood carriage house at 4754 Greenwood Avenue to question fellow Swede and chauffeur Sven Englund about the red Willys-Knight.',
    era: 'classic',
    archetype: 'action',
    name: 'Arthur Lindqvist',
    occupation: 'Private Inquiry Agent (Retained by the Franks Family)',
    age: 37,
    gender: 'male',
    portraitUrl: '/portraits/predefined/henry-whitman.webp',
    str: 70, dex: 70, con: 70, app: 60, pow: 65, edu: 65, siz: 65, int: 70, luck: 60,
    hp: 13, maxHp: 13, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background:
      'Former Great War military intelligence scout and private operative hired discreetly by the Franks household in Kenwood.',
    birthplace: 'Minneapolis, Minnesota',
    residence: 'South Loop, Chicago',
    characterConcept: 'Discreet, quiet professional who speaks the language of servants and chauffeurs along Millionaires’ Row.',
    ideology: 'The masters of the house never notice the help - and the help sees everything.',
    significantPerson: 'Jacob Franks, who asked him to find the truth no matter which Kenwood family it implicates.',
    meaningfulLocation: 'The alley behind the Leopold mansion garage on Greenwood Avenue.',
    treasuredPossession: 'A custom .32 automatic pistol and a set of tubular lockpicks.',
    traits: ['Discreet', 'Resourceful', 'Cool-headed'],
    description: 'Dark trench coat, driving gloves, speaking fluent Swedish to put Kenwood domestic staff at ease.',
    backstory:
      'When Bobby Franks vanished two blocks from his Kenwood mansion, the Franks family privately retained Arthur Lindqvist to look where the Chicago police might hesitate: inside the neighboring estates of Millionaires’ Row. Tracing red driveway gravel and a rented touring sedan to 4754 Greenwood Avenue, Lindqvist used his shared Swedish heritage to approach the Leopold family chauffeur, Sven Englund. Standing in the carriage garage beside the red Willys-Knight, Lindqvist is about to learn why the boys’ alibi is a lie - and where they have hidden the map to the Calumet boathouse.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at the Leopold Mansion Garage. High Stealth, Locksmith, Drive Auto, and Firearms.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Skradanie': 70,
      'Ślusarstwo': 65,
      'Prowadzenie auta': 75,
      'Broń Palna (Krótka)': 70,
      'Spostrzegawczość': 65,
      'Perswazja': 60,
      'Walka Wręcz': 65,
      'Nawigacja': 60,
      'Język Ojczysty (Angielski)': 65,
      'Unik': 50,
    },
    equipment: [
      { id: 'eq_lindqvist_gun', name: 'Colt Model 1903 .32 Pocket Hammerless', category: 'weapon' },
      { id: 'eq_lindqvist_picks', name: 'Precision Lockpick Roll & Flashlight', category: 'tool' },
    ],
  },

  // ==========================================================================
  // 3. 1983 (NOIR / COLD WAR) - POSTMARKED COLUMBUS: THE CIRCLEVILLE LETTERS
  // ==========================================================================
  {
    id: 'coldcase_ray_miller',
    scenarioIds: ['circleville-letters-1983'],
    startingNodeId: 'node-pickaway-sheriff',
    openingHook:
      'Stands outside Paul Freshour’s solitary cell in Pickaway County Jail holding a fresh block-letter envelope that just arrived in the morning mail.',
    era: '1990s',
    archetype: 'action',
    name: 'Deputy Ray Miller',
    occupation: 'Pickaway County Sheriff’s Deputy',
    age: 38,
    gender: 'male',
    portraitUrl: '/portraits/predefined/david-miller.webp',
    str: 70, dex: 65, con: 75, app: 55, pow: 65, edu: 60, siz: 70, int: 65, luck: 55,
    hp: 14, maxHp: 14, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background:
      'Patrol deputy who responded to Ron Gillespie’s 1977 crash on Route 56 and dismantled the .25 pistol booby trap on the Westfall bus route.',
    birthplace: 'Circleville, Ohio',
    residence: 'Circleville, Ohio',
    characterConcept: 'Honest rural deputy haunted by the realization that locking up Paul Freshour has not stopped the Writer.',
    ideology: 'A badge means telling the truth even when the Sheriff wants the case closed.',
    significantPerson: 'His late friend Ron Gillespie, whose 1977 crash was written off as drunk driving despite the single spent shell casing.',
    meaningfulLocation: 'The evidence locker at the Pickaway County Sheriff’s Office.',
    treasuredPossession: 'The spent .38 brass casing he quietly pocketed from Ron Gillespie’s truck in 1977.',
    traits: ['Stubborn', 'Vigilant', 'Grounded'],
    description: 'Tan sheriff’s department parka, Stetson hat, carrying a heavy Kel-Lite aluminum flashlight.',
    backstory:
      'Ray Miller grew up in Circleville and knew Ron Gillespie didn’t drink enough to wrap his pickup around an oak tree at Route 56 in 1977 - especially not after firing a single shot into the utility pole above the road. Six years later, Ray helped disarm the wooden box trap rigged with a .25 automatic on Mary Gillespie’s bus route. Sheriff Radcliff swears Paul Freshour is the sole culprit. But Ray has been guarding Freshour’s solitary cell without pen or paper for forty-eight hours, and ten minutes ago the mail carrier delivered a brand-new Columbus-postmarked letter in those same hypnotic geometric capitals.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Pickaway County Sheriff’s Office. Strong Firearms, Spot Hidden, Electrical Repair, and Drive Auto.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Broń Palna (Krótka)': 75,
      'Spostrzegawczość': 70,
      'Prowadzenie auta': 70,
      'Prawo': 60,
      'Elektryka': 55,
      'Walka Wręcz': 65,
      'Tropienie': 60,
      'Nasłuchiwanie': 55,
      'Język Ojczysty (Angielski)': 60,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_ray_revolver', name: 'Smith & Wesson Model 19 .357 Service Revolver', category: 'weapon' },
      { id: 'eq_ray_cuffs', name: 'Sheriff’s Master Evidence Key & Kel-Lite Flashlight', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_sarah_freshour',
    scenarioIds: ['circleville-letters-1983'],
    startingNodeId: 'node-bus-route-trap',
    openingHook:
      'Inspects the wooden fence post on the Westfall school bus route where the .25 pistol box trap was rigged, searching for the real culprit’s tracks.',
    era: '1990s',
    archetype: 'investigator',
    name: 'Sarah Freshour-Cole',
    occupation: 'Defense Attorney & Legal Investigator',
    age: 34,
    gender: 'female',
    portraitUrl: '/portraits/predefined/alexandra-croft.webp',
    str: 45, dex: 60, con: 60, app: 65, pow: 75, edu: 80, siz: 55, int: 75, luck: 60,
    hp: 11, maxHp: 11, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background:
      'Columbus defense attorney and relative of Paul Freshour who discovered that Paul suffered a four-hour hypnotic memory blackout on the night the trap was planted.',
    birthplace: 'Chillicothe, Ohio',
    residence: 'Columbus, Ohio',
    characterConcept: 'Fierce defense counsel who realizes her client was used as a sleepwalking pawn.',
    ideology: 'When the physical evidence is too neat and the letters keep coming, you are looking at a setup.',
    significantPerson: 'Paul Freshour, sitting in solitary confinement while the real mastermind broadcasts over the phone lines.',
    meaningfulLocation: 'The roadside fence post on the Westfall school bus route.',
    treasuredPossession: 'A Polaroid camera and a folder of 42 postmarked Circleville envelopes.',
    traits: ['Sharp', 'Determined', 'Skeptical'],
    description: 'Wool trench coat over a courtroom suit, carrying a Polaroid SX-70 and a legal pad.',
    backstory:
      'When Paul Freshour was arrested for planting a .25-caliber booby trap on his sister-in-law Mary Gillespie’s bus route, Sarah drove down from Columbus expecting a bitter family dispute. Instead, she found a terrified man in isolation who could not remember anything after answering a strange, chiming phone call at 11:00 PM - and whose handwriting failed every independent forensic match until he was placed under hypnosis. Standing at the roadside fence post along the Westfall bus route, Sarah has just spotted green drafting-stencil shavings and a spliced black wire running up the utility pole.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at the Westfall Bus Route Trap site. High Law, Persuade, Psychology, and Spot Hidden.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Prawo': 80,
      'Perswazja': 75,
      'Psychologia': 70,
      'Spostrzegawczość': 65,
      'Korzystanie z Bibliotek': 65,
      'Fotografia': 55,
      'Gadanina': 60,
      'Język Ojczysty (Angielski)': 80,
      'Unik': 35,
    },
    equipment: [
      { id: 'eq_sarah_polaroid', name: 'Polaroid SX-70 Camera & Evidence Binders', category: 'tool' },
      { id: 'eq_sarah_recorder', name: 'Panasonic Micro-Cassette Dictaphone', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_marcus_vance',
    scenarioIds: ['circleville-letters-1983'],
    startingNodeId: 'node-route56-crash-site',
    openingHook:
      'Meets Karen Sue Gillespie at the scarred oak tree at Route 56 & Florence Chapel Pike where Ron Gillespie died in 1977.',
    era: '1990s',
    archetype: 'trickster',
    name: 'Marcus Vance',
    occupation: 'Investigative Reporter (Columbus Dispatch)',
    age: 40,
    gender: 'male',
    portraitUrl: '/portraits/predefined/marcus-vance.webp',
    str: 55, dex: 60, con: 65, app: 60, pow: 70, edu: 75, siz: 60, int: 75, luck: 60,
    hp: 12, maxHp: 12, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background:
      'Veteran Ohio journalist who has covered the Circleville Writer since 1977 and suspects a link to a classified 1976 Battelle acoustic grant.',
    birthplace: 'Cleveland, Ohio',
    residence: 'Columbus, Ohio',
    characterConcept: 'Post-Watergate investigative reporter following the telephone wires behind small-town paranoia.',
    ideology: 'Small towns don’t go mad on their own; someone built the amplifier.',
    significantPerson: 'Mary Gillespie, who secretly trusted him with the existence of Ron’s 1977 phone tape.',
    meaningfulLocation: 'The intersection of Route 56 and Florence Chapel Pike.',
    treasuredPossession: 'A frequency counter and a press dossier on 1970s Ohio defense contractors.',
    traits: ['Cynical', 'Persistent', 'Resourceful'],
    description: 'Corduroy jacket, aviators, carrying a 35mm Nikon camera and a portable tape deck.',
    backstory:
      'Marcus Vance wrote his first article on the Circleville letters in August 1977, the week Ron Gillespie drove his pickup into an oak tree on Route 56 after getting a late-night call from the Writer. Marcus never bought the official drunk-driving ruling - especially after learning a bullet from Ron’s revolver was lodged eighteen feet up the telephone pole at the crash site. Tonight, standing beside that scarred oak tree on Route 56, Marcus can hear the overhead telephone repeater box humming at a low, nauseating frequency.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Route 56 Crash Site. Excels at Listen, Electrical Repair, Library Use, and Fast Talk.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Nasłuchiwanie': 70,
      'Spostrzegawczość': 70,
      'Gadanina': 70,
      'Korzystanie z Bibliotek': 65,
      'Elektryka': 55,
      'Fotografia': 65,
      'Psychologia': 60,
      'Prowadzenie auta': 55,
      'Język Ojczysty (Angielski)': 75,
      'Unik': 40,
    },
    equipment: [
      { id: 'eq_marcus_nikon', name: 'Nikon FM2 35mm Camera & Telephoto Lens', category: 'tool' },
      { id: 'eq_marcus_meter', name: 'Analog Line-Frequency & Voltage Tester', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_evelyn_hayes',
    scenarioIds: ['circleville-letters-1983'],
    startingNodeId: 'node-westfall-school-board',
    openingHook:
      'Examines the geometric block-letter envelopes in the Pickaway County Sheriff’s Office under an optical comparator.',
    era: '1990s',
    archetype: 'scholar',
    name: 'Dr. Evelyn Hayes',
    occupation: 'Forensic Linguist & Behavioral Scientist',
    age: 43,
    gender: 'female',
    portraitUrl: '/portraits/predefined/evelyn-sterling.webp',
    str: 45, dex: 60, con: 55, app: 60, pow: 80, edu: 85, siz: 50, int: 85, luck: 55,
    hp: 10, maxHp: 10, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background:
      'Consulting forensic document examiner from Quantico who discovered that the Circleville letters were written by multiple townspeople using the same hypnotic stencil geometry.',
    birthplace: 'Annapolis, Maryland',
    residence: 'Arlington, Virginia',
    characterConcept: 'Cold War behavioral analyst who recognizes weaponized cognitive conditioning when she sees it.',
    ideology: 'Language can be engineered like a virus; the block letters are not handwriting, they are a trigger.',
    significantPerson: 'Her former mentor at Walter Reed, who warned her about Project TOWN CRIER.',
    meaningfulLocation: 'The document analysis table at the Pickaway County Sheriff’s Office.',
    treasuredPossession: 'An ultraviolet document lamp and acoustic spectrum analyzer.',
    traits: ['Clinical', 'Perceptive', 'Unrattled'],
    description: 'Charcoal blazer, horn-rimmed reading glasses, carrying an aluminum forensic case.',
    backstory:
      'Called in to settle the handwriting dispute in the Paul Freshour case, Dr. Evelyn Hayes placed forty Circleville letters under an optical comparator and uncovered a chilling impossibility: while every letter shared the exact same 90-degree geometric block proportions, the pen-pressure micro-tremors belonged to at least six different residents of Pickaway County. Even more disturbing, staring at the angular spacing without a filter triggered an immediate 18.9 Hz auditory hallucination. Starting in the Sheriff’s evidence room, Evelyn knows she is dealing with a live Cold War psychotronic experiment.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Pickaway County Sheriff’s Office. Master of Psychology, Library Use, Science, and Spot Hidden.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Psychologia': 80,
      'Korzystanie z Bibliotek': 75,
      'Spostrzegawczość': 70,
      'Nauka (Fizyka)': 65,
      'Nasłuchiwanie': 65,
      'Perswazja': 60,
      'Prawo': 55,
      'Język Ojczysty (Angielski)': 85,
      'Unik': 35,
    },
    equipment: [
      { id: 'eq_evelyn_uv', name: 'Portable UV Document Lamp & Optical Loupe', category: 'tool' },
      { id: 'eq_evelyn_osc', name: 'Handheld Acoustic Frequency Analyzer', category: 'tool' },
    ],
  },

  // ==========================================================================
  // 4. 2005 (MODERN) - I'M IN A FIELD: THE OVIDHALL LAKE ANOMALY
  // ==========================================================================
  {
    id: 'coldcase_kevin_gannon',
    scenarioIds: ['ovidhall-lake-anomaly-2005'],
    startingNodeId: 'node-ovidhall-lake-shore',
    openingHook:
      'Inspects the concrete weir at Ovidhall Lake where the yellow UV Smiley Face glyph was painted thirty yards from the vertical body recovery site.',
    era: 'modern',
    archetype: 'investigator',
    name: 'Det. Kevin Gannon',
    occupation: 'Homicide Detective (NYPD Ret.)',
    age: 49,
    gender: 'male',
    portraitUrl: '/portraits/predefined/ronald-shaw.webp',
    str: 65, dex: 60, con: 70, app: 55, pow: 75, edu: 70, siz: 70, int: 75, luck: 55,
    hp: 14, maxHp: 14, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background:
      'Decorated retired NYPD detective who mortgaged his home to investigate a nationwide pattern of young men vanishing near water and reappearing near Smiley Face graffiti.',
    birthplace: 'Queens, New York',
    residence: 'New York City',
    characterConcept: 'Obsessed veteran detective who knows the Midwest lake drownings are connected.',
    ideology: 'Bodies do not tread water after death, and they do not stay fresh for three weeks in July.',
    significantPerson: 'His investigative partner Anthony Duarte, tracking parallel cases in Wisconsin.',
    meaningfulLocation: 'The reed-choked shore of Ovidhall Lake in Casnovia, Michigan.',
    treasuredPossession: 'A case binder mapping 40 Great Lakes disappearances along glacial karst lines.',
    traits: ['Relentless', 'Gritty', 'Protective'],
    description: 'Dark windbreaker, NYPD gold shield in leather wallet, carrying a UV crime-scene flashlight.',
    backstory:
      'For eight years, retired NYPD Detective Kevin Gannon has tracked a terrifying pattern across the Great Lakes: athletic young men leave a bar or bonfire, make one final disoriented phone call, vanish for three weeks while search dogs find nothing, and then turn up in previously searched ponds showing almost no decomposition. When 22-year-old Todd Geib was pulled from Ovidhall Lake standing straight upright from the chest up, Gannon caught the first flight to Michigan. Standing at the concrete weir on the lake shore, his UV lamp has just illuminated a fresh Smiley Face painted in glowing freshwater nacre.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Ovidhall Lake Shore. High Spot Hidden, Psychology, Track, and Firearms.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Spostrzegawczość': 75,
      'Psychologia': 70,
      'Tropienie': 65,
      'Perswazja': 65,
      'Prawo': 65,
      'Broń Palna (Krótka)': 70,
      'Walka Wręcz': 60,
      'Nawigacja': 55,
      'Język Ojczysty (Angielski)': 70,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_gannon_glock', name: 'Glock 19 9mm Pistol (Retired LE Carry)', category: 'weapon' },
      { id: 'eq_gannon_uv', name: 'Forensic UV-A Crime Scene Flashlight & Case Binder', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_elena_rostova',
    scenarioIds: ['ovidhall-lake-anomaly-2005'],
    startingNodeId: 'node-muskegon-morgue',
    openingHook:
      'Completes the autopsy at the Muskegon Forensic Lab after discovering zero water in Todd Geib’s lungs and a metallic spicule in his spine.',
    era: 'modern',
    archetype: 'healer',
    name: 'Dr. Elena Rostova',
    occupation: 'Forensic Pathologist & Toxicologist',
    age: 38,
    gender: 'female',
    portraitUrl: '/portraits/predefined/elena-rostova.webp',
    str: 45, dex: 65, con: 60, app: 60, pow: 80, edu: 90, siz: 55, int: 85, luck: 60,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background:
      'Board-certified forensic pathologist in Muskegon who refused to sign off on an "accidental drowning" after examining Todd Geib’s dry lungs and preserved tissues.',
    birthplace: 'Chicago, Illinois',
    residence: 'Muskegon, Michigan',
    characterConcept: 'Uncompromising forensic scientist confronting biological stasis that defies medical law.',
    ideology: 'The dead do not lie on the autopsy table; if the lungs are dry, he did not drown in that pond.',
    significantPerson: 'Dr. Alan Mercer, her superior who is pressuring her to bury the spinal-fluid findings.',
    meaningfulLocation: 'The autopsy suite at the Muskegon County Medical Examiner’s Office.',
    treasuredPossession: 'A sealed cryo-vial containing the crystalline metallic spicule extracted from the C3 vertebra.',
    traits: ['Precise', 'Fearless', 'Scientific'],
    description: 'Surgical scrubs under a white lab coat, nitrile gloves, carrying a portable toxicology sample kit.',
    backstory:
      'When Todd Geib’s body arrived at the Muskegon County morgue on July 2, 2005, Dr. Elena Rostova expected advanced aquatic decomposition after twenty-one days in a warm Michigan bog. Instead, the body on her steel table looked as if death had occurred barely thirty-six hours ago. Worse, the lungs contained zero milliliters of pond water, blind cave-shrimp chitin was wedged beneath the fingernails, and her forceps struck a microscopic needle of iridescent metal embedded in the cervical spine. Starting in the Muskegon morgue, Elena is determined to trace those subterranean organisms back to the Casnovia karst.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at the Muskegon County Morgue. Expert in Medicine, Biology, Chemistry, and Spot Hidden.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Medycyna': 85,
      'Nauka (Biologia)': 75,
      'Nauka (Chemia)': 75,
      'Pierwsza Pomoc': 75,
      'Spostrzegawczość': 65,
      'Korzystanie z Bibliotek': 70,
      'Psychologia': 55,
      'Język Ojczysty (Angielski)': 85,
      'Unik': 35,
    },
    equipment: [
      { id: 'eq_elena_kit', name: 'Forensic Autopsy & Sample Extraction Kit', category: 'tool' },
      { id: 'eq_elena_vial', name: 'Cryo-Vial with Crystalline Spinal Spicule', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_ryan_miller',
    scenarioIds: ['ovidhall-lake-anomaly-2005'],
    startingNodeId: 'node-casnovia-orchard',
    openingHook:
      'Stands in the Casnovia apple orchard at the exact spot where Todd called at 12:51 AM saying "I’m in a field", beside a sunken iron grate.',
    era: 'modern',
    archetype: 'action',
    name: 'Ryan Geib-Miller',
    occupation: 'Search Volunteer & Rural Contractor (Victim’s Cousin)',
    age: 26,
    gender: 'male',
    portraitUrl: '/portraits/predefined/christian-cole.webp',
    str: 75, dex: 70, con: 75, app: 60, pow: 65, edu: 60, siz: 70, int: 65, luck: 60,
    hp: 14, maxHp: 14, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background:
      'Todd’s cousin in Casnovia toward whose house Todd was walking on the night of June 12, and who spent 21 straight days searching Ovidhall Lake and the surrounding orchards.',
    birthplace: 'Ravenna, Michigan',
    residence: 'Casnovia, Michigan',
    characterConcept: 'Fiercely loyal local who knows every trail, orchard, and drainage ditch in Casnovia.',
    ideology: 'I walked that pond shoreline ten times in June - Todd was NOT in that water until someone put him there.',
    significantPerson: 'His cousin Todd Geib, whose last words on the phone ("I’m in a field") haunt him every night.',
    meaningfulLocation: 'The overgrown field behind the Casnovia apple orchard.',
    treasuredPossession: 'His Nokia cell phone containing the saved 12:51 AM voicemail audio.',
    traits: ['Determined', 'Brave', 'Local Insider'],
    description: 'Carhartt work jacket, muddy work boots, carrying a high-lumen Maglite and a bolt cutter.',
    backstory:
      'On the night of June 11, 2005, Todd Geib left the bonfire behind the Casnovia apple orchard to walk the short stretch of road to Ryan’s house. He never arrived. For twenty-one agonizing days, Ryan led volunteer search parties across every inch of the orchard and waded the reeds of Ovidhall Lake alongside tracking dogs. Ryan knows for an absolute fact that the pond was empty for three weeks. Today, returning to the orchard field where Todd made his final 12:51 AM call, Ryan has found a rusted iron grate hidden in the waist-high weeds where a freezing draft blows up from the limestone below.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts in the Casnovia Apple Orchard. High Navigate, Track, Mechanical Repair, and Brawn.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Nawigacja': 75,
      'Tropienie': 70,
      'Mechanika': 65,
      'Walka Wręcz': 70,
      'Spostrzegawczość': 65,
      'Prowadzenie auta': 65,
      'Nasłuchiwanie': 60,
      'Broń Palna (Długa)': 60,
      'Język Ojczysty (Angielski)': 60,
      'Unik': 50,
    },
    equipment: [
      { id: 'eq_ryan_phone', name: 'Nokia Cell Phone with Saved 12:51 AM Voicemail', category: 'tool' },
      { id: 'eq_ryan_tools', name: 'Heavy Bolt Cutters & High-Lumen Maglite', category: 'tool' },
    ],
  },
  {
    id: 'coldcase_hannah_cole',
    scenarioIds: ['ovidhall-lake-anomaly-2005'],
    startingNodeId: 'node-half-moon-bar',
    openingHook:
      'Arrives at Ovidhall Lake with subpoenaed Cingular GSM tower triangulation logs showing Todd’s 12:51 AM call transmitted from 40 feet underground.',
    era: 'modern',
    archetype: 'scholar',
    name: 'Special Agent Hannah Cole',
    occupation: 'Michigan State Police Technical & Cold Case Specialist',
    age: 35,
    gender: 'female',
    portraitUrl: '/portraits/predefined/jessica-cross.webp',
    str: 55, dex: 65, con: 65, app: 65, pow: 75, edu: 80, siz: 55, int: 80, luck: 60,
    hp: 12, maxHp: 12, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background:
      'Telecommunications and sonar analyst with the Michigan State Police who discovered that Todd Geib’s cell phone transmitted from a subterranean cavity.',
    birthplace: 'Lansing, Michigan',
    residence: 'Grand Rapids, Michigan',
    characterConcept: 'Tech-savvy state investigator who trusts raw telemetry over county politics.',
    ideology: 'Signal attenuation physics cannot be bribed or covered up.',
    significantPerson: 'Volunteer diver Mark Heller, who confided that a cold thermal vortex pulled at him in the center of Ovidhall Lake.',
    meaningfulLocation: 'The shoreline command post at Ovidhall Lake.',
    treasuredPossession: 'Subpoenaed Cingular Wireless GSM triangulation printouts and a side-scan sonar tablet.',
    traits: ['Analytical', 'Composed', 'Tech-focused'],
    description: 'MSP tactical windbreaker, sidearm at hip, carrying a ruggedized field laptop and GSM signal meter.',
    backstory:
      'Assigned to review the search-and-rescue telemetry from the Casnovia disappearance, Special Agent Hannah Cole noticed something that made her blood run cold: not only did three separate sonar sweeps of Ovidhall Lake between June 13 and June 28 show an empty pond floor, but the Cingular Wireless triangulation data from 12:51 AM on June 12 proved Todd’s phone was transmitting from twelve meters below ground level. Arriving at the Ovidhall Lake shore with her ruggedized laptop and side-scan sonar logs, Hannah has just detected a submerged karst tunnel opening beneath the center of the pond.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Starts at Ovidhall Lake Shore. Strong Electrical Repair, Navigate, Spot Hidden, and Firearms.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: {
      'Elektryka': 75,
      'Korzystanie z Bibliotek': 70,
      'Nawigacja': 70,
      'Spostrzegawczość': 70,
      'Broń Palna (Krótka)': 65,
      'Prawo': 60,
      'Nasłuchiwanie': 60,
      'Język Ojczysty (Angielski)': 80,
      'Unik': 45,
    },
    equipment: [
      { id: 'eq_hannah_sig', name: 'SIG Sauer P226 .40 Service Pistol', category: 'weapon' },
      { id: 'eq_hannah_laptop', name: 'Ruggedized Field Laptop with GSM & Sonar Logs', category: 'tool' },
    ],
  },
];

export const AMERICAN_COLD_CASES_CHARACTERS: PredefinedCharacter[] =
  BASE_AMERICAN_COLD_CASES_CHARACTERS.map((character) => ({
    ...character,
    equipment: character.equipment?.map((item) => {
      const catalogItem = applyCatalogTemplate(
        {
          ...item,
          source: item.source ?? 'starting',
          condition: item.condition ?? 'used',
        },
        character.era
      );
      return {
        ...catalogItem,
        imageUrl:
          catalogItem.imageUrl ??
          CATEGORY_FALLBACK_ASSETS[catalogItem.category],
        visualSource: catalogItem.imageUrl ? 'catalog' : 'fallback',
      };
    }),
  }));
