import { PredefinedCharacter } from './predefined-characters';

export const STREFA_11_CHARACTERS: PredefinedCharacter[] = [
  {
    id: 'strefa11_tomasz_nowicki',
    era: 'modern',
    archetype: 'investigator',
    name: 'Tomasz Nowicki',
    occupation: 'Dziennikarz Śledczy / Prowadzący',
    age: 42,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tadeusz-krawiec.webp',
    str: 55, dex: 60, con: 65, app: 60, pow: 70, edu: 75, siz: 65, int: 70, luck: 55,
    hp: 13, maxHp: 13, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Gospodarz programu "Sygnały Nieznanego", znany z posępnego głosu i chłodnej analizy nadprzyrodzonych zjawisk na antenie telewizyjnej. Dawniej pracował w dziale kryminalnym dużego dziennika.',
    birthplace: 'Warszawa, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Sceptyczny dziennikarz, który widział już zbyt wiele zjawisk niewyjaśnionych, by całkowicie zaprzeczać istnieniu nieznanego.',
    ideology: 'Zawsze jest jakieś logiczne wytłumaczenie – a jeśli go nie ma, oznacza to, że nauka ma jeszcze wiele do odkrycia.',
    significantPerson: 'Była żona, która zostawiła go przez jego obsesję na punkcie "tych dziwnych spraw".',
    meaningfulLocation: 'Studio nagraniowe telewizji, jedyne miejsce, gdzie czuje, że w pełni kontroluje sytuację.',
    treasuredPossession: 'Kasetowy dyktafon reporterski marki Sony z lat 90., który nagrał kiedyś głos EVP.',
    traits: ['Opanowany', 'Sceptyczny', 'Dociekliwy'],
    description: 'Nosi charakterystyczną, czarną skórzaną kurtkę, z ciemnymi okularami zawieszonymi na kołnierzyku.',
    backstory: 'Od lat prowadzi śledztwa dotyczące UFO, poltergeistów i rzekomych nawiedzeń. Z reguły udaje mu się zdemaskować oszustów, jednak niektóre archiwalne sprawy "Sygnałów Nieznanego" do dziś spędzają mu sen z powiek.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Dobry w zbieraniu informacji, nawiązywaniu kontaktów i przesłuchiwaniu świadków.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Spostrzegawczość': 70, 'Perswazja': 65, 'Psychologia': 60, 'Korzystanie z Bibliotek': 50, 'Nasłuchiwanie': 55 },
    equipment: [{ id: 'eq_tom_dyktafon', name: 'Dyktafon na mikrokasety', category: 'tool' }, { id: 'eq_tom_latarka', name: 'Mocna latarka policyjna', category: 'tool' }]
  },
  {
    id: 'strefa11_helena_krawczyk',
    era: 'modern',
    archetype: 'trickster',
    name: 'Helena Krawczyk',
    occupation: 'Producentka Telewizyjna',
    age: 38,
    gender: 'female',
    portraitUrl: '/portraits/predefined/ewa-nowak.webp',
    str: 40, dex: 65, con: 55, app: 70, pow: 60, edu: 80, siz: 50, int: 75, luck: 65,
    hp: 10, maxHp: 10, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Z żelazną ręką zarządza ekipą "Sygnałów Nieznanego". Załatwia zgody na wejścia, finanse, oraz potrafi przekonać policję do przymknięcia oka na wejście na teren zamknięty.',
    birthplace: 'Kraków, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Wyrachowana organizatorka, dla której liczy się oglądalność i dobrze opowiedziana historia.',
    ideology: 'Telewizja to iluzja, a ludzie chcą wierzyć w niesamowite rzeczy.',
    significantPerson: 'Tomasz Nowicki – choć często się kłócą, tworzą niepokonany zespół.',
    meaningfulLocation: 'Wóz transmisyjny – mobilne centrum dowodzenia.',
    treasuredPossession: 'Notatnik z kontaktami do niemal każdego oficjela w państwie.',
    traits: ['Ambitna', 'Czarująca', 'Stanowcza'],
    description: 'Zawsze nienagannie ubrana (zwykle w dopasowane garnitury damskie i płaszcze), z telefonem komórkowym "cegłą" ciągle w ręku.',
    backstory: 'Helena przeszła długą drogę od asystentki do czołowej producentki programów paranormalnych w latach 90. Często balansuje na granicy prawa, wdzierając się do archiwów lub prywatnych posesji, "dla dobra materiału".',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Rewelacyjna w załatwianiu spraw urzędowych i urokach osobistych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Urok osobisty': 75, 'Perswazja': 70, 'Gadanina': 65, 'Prawo': 45, 'Spostrzegawczość': 50 },
    equipment: [{ id: 'eq_hel_telefon', name: 'Telefon komórkowy (wielki)', category: 'tool' }, { id: 'eq_hel_notes', name: 'Notes kontaktów', category: 'tool' }]
  },
  {
    id: 'strefa11_barbara_zawadzka',
    era: 'modern',
    archetype: 'scholar',
    name: 'Dr Barbara Zawadzka',
    occupation: 'Etnograf / Parapsycholog',
    age: 45,
    gender: 'female',
    portraitUrl: '/portraits/predefined/magdalena-koper.webp',
    str: 45, dex: 55, con: 60, app: 55, pow: 80, edu: 85, siz: 55, int: 80, luck: 60,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background: 'Naukowiec Uniwersytetu Warszawskiego. Regularna ekspertka w programie "Sygnały Nieznanego", oceniająca materiały wideo i ślady fenomenów.',
    birthplace: 'Lublin, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Racjonalny umysł w kontakcie z niewytłumaczalnym. Analizuje kulty, demonologię i ludowe legendy na polskich wsiach.',
    ideology: 'Za każdą legendą i zabobonem kryje się zniekształcone ziarno prawdziwej historii i fizyki.',
    significantPerson: 'Jej mentor ze studiów, który popadł w obłęd podczas badań nad folklorem Podlasia.',
    meaningfulLocation: 'Biblioteka wydziałowa, wśród starych zapisów ludoznawczych.',
    treasuredPossession: 'Kamera na podczerwień i sprzęt do pomiaru pola elektromagnetycznego (EMF).',
    traits: ['Metodyczna', 'Otwarty umysł', 'Skoncentrowana'],
    description: 'Nosi luźne wełniane swetry, okulary na łańcuszku, często z teczką pełną wydruków i ryciny.',
    backstory: 'Wykłada folklor i etnografię. Od czasu dziwnych doświadczeń w terenie zjawiska poltergeist, stała się czołowym parapsychologiem w Polsce, badając korelację między polami magnetycznymi a "duchami".',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Niezbędna do analizy okultyzmu, historii i dziwnych przedmiotów.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 70, 'Historia': 65, 'Antropologia': 60, 'Korzystanie z Bibliotek': 75, 'Języki obce (Łacina)': 50, 'Nauka (Fizyka)': 45 },
    equipment: [{ id: 'eq_barb_emf', name: 'Miernik pola elektromagnetycznego', category: 'tool' }, { id: 'eq_barb_camera', name: 'Kamera z trybem NightVision', category: 'tool' }]
  },
  {
    id: 'strefa11_ryszard_klucznik',
    era: 'modern',
    archetype: 'action',
    name: 'Ryszard "Klucznik" Kaczmarek',
    occupation: 'B. Oficer SB / Technik Ochrony',
    age: 55,
    gender: 'male',
    portraitUrl: '/portraits/predefined/marek-dabrowski.webp',
    str: 75, dex: 65, con: 70, app: 45, pow: 60, edu: 60, siz: 75, int: 65, luck: 50,
    hp: 14, maxHp: 14, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Ochroniarz i "załatwiacz" dla ekipy telewizyjnej. Były funkcjonariusz bezpieczeństwa z okresu PRL, który ma kontakty w milicji/policji i potrafi otworzyć każde drzwi.',
    birthplace: 'Gdańsk, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Twardy facet, który widział najgorsze twarze ludzi i systemów. Zapewnia fizyczne bezpieczeństwo badaczom.',
    ideology: 'Bezpieczeństwo przede wszystkim. Czasem brutalna siła jest jedynym argumentem.',
    significantPerson: 'Jego córka, dla której stara się odkupić dawne winy w SB.',
    meaningfulLocation: 'Jego stara Łada Niva (lub Polonez Caro), służąca za bazę i magazyn sprzętu.',
    treasuredPossession: 'Legalnie zarejestrowany pistolet P-64, w kaburze pod pachą.',
    traits: ['Podejrzliwy', 'Lojalny', 'Bezkompromisowy'],
    description: 'Masywnej postury, zawsze lekko niedogolony. Nosi sprane jeansy, ciężkie buty i wojskową kurtkę.',
    backstory: 'W latach 80. pracował w wydziale zabezpieczenia. Odszedł ze służby po 1989 i odnalazł się jako ekspert ds. fizycznego bezpieczeństwa i technik zakładania podsłuchów. Dziś dba o to, by redakcji "Sygnałów Nieznanego" nie stała się krzywda w opuszczonych fabrykach i bunkrach.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Mistrz przetrwania, walki i dyskretnego otwierania drzwi.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Walka wręcz': 75, 'Broń palna (krótka)': 70, 'Unik': 60, 'Ślusarstwo': 65, 'Zastraszanie': 60, 'Spostrzegawczość': 55 },
    equipment: [{ id: 'eq_rysz_gun', name: 'Pistolet P-64 z zapasowym magazynkiem', category: 'weapon' }, { id: 'eq_rysz_lockpicks', name: 'Zestaw wytrychów i łom', category: 'tool' }]
  },
  // ==========================================================================
  // TAJEMNICA PĘDNIKA: KOWARY
  // ==========================================================================
  {
    id: 'pednik_inzynier',
    era: 'modern',
    archetype: 'scholar',
    name: 'Inż. Marek Kamiński',
    occupation: 'Inżynier Mechanik',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/jerzy-kossak.webp',
    str: 65, dex: 60, con: 70, app: 50, pow: 60, edu: 80, siz: 65, int: 75, luck: 55,
    hp: 13, maxHp: 13, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Doświadczony projektant zderzaków w przemyśle motoryzacyjnym. Słyszał o przełomowych eksperymentach w Kowarach i chce na własne oczy zobaczyć pochłaniacz kinetyczny.',
    birthplace: 'Wrocław, Polska',
    residence: 'Wrocław, Polska',
    characterConcept: 'Sceptyczny pragmatyk wierzący tylko w prawa fizyki.',
    ideology: 'Energia nie bierze się znikąd i nie może po prostu zniknąć.',
    significantPerson: 'Jego promotor ze studiów, z którym prowadzi ciągły spór naukowy.',
    meaningfulLocation: 'Laboratorium testowe, pełne manekinów zderzeniowych i aparatury pomiarowej.',
    treasuredPossession: 'Precyzyjna suwmiarka cyfrowa w skórzanym etui.',
    traits: ['Pragmatyczny', 'Uparty', 'Ciekawski'],
    description: 'Nosi roboczy drelich z wieloma kieszeniami i wiecznie umazane smarem dłonie.',
    backstory: 'Spędził większość życia na poszukiwaniu sposobów na zminimalizowanie skutków wypadków samochodowych. Zderzak Łągiewki uważa za niemożliwy, ale intrygujący.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Złota rączka, potrafi naprawić lub zepsuć każde urządzenie mechaniczne.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Mechanika': 75, 'Elektryka': 65, 'Spostrzegawczość': 60, 'Fizyka': 55, 'Prowadzenie auta': 65 },
    equipment: [{ id: 'eq_mar_tools', name: 'Zestaw narzędzi w walizce', category: 'tool' }]
  },
  {
    id: 'pednik_kierowca',
    era: 'modern',
    archetype: 'action',
    name: 'Tomasz "Ryzykant" Wójcik',
    occupation: 'Kierowca Testowy',
    age: 32,
    gender: 'male',
    portraitUrl: '/portraits/predefined/wiktor-lesniewski.webp',
    str: 70, dex: 80, con: 75, app: 60, pow: 50, edu: 50, siz: 60, int: 60, luck: 65,
    hp: 13, maxHp: 13, san: 50, maxSan: 99, mp: 10, maxMp: 10,
    background: 'Były kierowca rajdowy, który po poważnym wypadku zatrudnił się jako kaskader i oblatywacz dziwnych pojazdów.',
    birthplace: 'Kraków, Polska',
    residence: 'Kraków, Polska',
    characterConcept: 'Adrenalinowy ćpun, który ufa swojemu refleksowi bardziej niż komukolwiek.',
    ideology: 'Prędkość to wolność, a hamulce są dla tchórzy.',
    significantPerson: 'Pilot rajdowy, który zginął w wypadku, z którego Tomasz cudem ocalał.',
    meaningfulLocation: 'Garaż pełen rozebranych na części silników.',
    treasuredPossession: 'Kluczyki do pierwszego wygranego samochodu rajdowego.',
    traits: ['Odważny', 'Impulsywny', 'Refleksyjny'],
    description: 'Nosi kurtkę skórzaną, często żuje gumę, rzadko ściąga rękawiczki do jazdy.',
    backstory: 'Szuka coraz większych wrażeń. Pędnik w Kowarach to dla niego szansa na test maszyny, która zignoruje przeciążenia.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Mistrz za kółkiem, świetny refleks pozwala mu uniknąć niebezpieczeństw fizycznych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Prowadzenie auta': 85, 'Unik': 70, 'Walka wręcz': 60, 'Spostrzegawczość': 55, 'Nawigacja': 50 },
    equipment: [{ id: 'eq_tom_helmet', name: 'Kask ochronny', category: 'tool' }, { id: 'eq_tom_gloves', name: 'Rękawice ognioodporne', category: 'tool' }]
  },
  {
    id: 'pednik_dziennikarka',
    era: 'modern',
    archetype: 'investigator',
    name: 'Anna Dąbrowska',
    occupation: 'Dziennikarka Śledcza',
    age: 35,
    gender: 'female',
    portraitUrl: '/portraits/predefined/alicja-rudzka.webp',
    str: 50, dex: 65, con: 60, app: 65, pow: 65, edu: 70, siz: 55, int: 75, luck: 60,
    hp: 11, maxHp: 11, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Tropi ukryte technologie i powiązania rządu z tajemniczymi agencjami. Węszy w sprawie Agencji Ochrony Rzeczypospolitej (AOR).',
    birthplace: 'Poznań, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Wścibska reporterka, która nie cofnie się przed niczym dla dobrego tematu.',
    ideology: 'Wiedza należy do społeczeństwa, nie do zamkniętych gabinetów służb specjalnych.',
    significantPerson: 'Informator z wnętrza służb o kryptonimie "Kruk".',
    meaningfulLocation: 'Ciemnia fotograficzna, w której wywołuje niewygodne materiały.',
    treasuredPossession: 'Kompaktowy aparat z bardzo czułym filmem fotograficznym.',
    traits: ['Dociekliwa', 'Podejrzliwa', 'Gadatliwa'],
    description: 'Bystre spojrzenie zza oprawek korekcyjnych, notes zawsze w pogotowiu.',
    backstory: 'Odkryła, że polskie służby interesują się niezależnymi inżynierami w Karkonoszach. Pojechała tam, by udokumentować sprawę Łągiewki.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonale kłamie, podsłuchuje i włłamuje się do archiwów.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Spostrzegawczość': 70, 'Perswazja': 65, 'Psychologia': 60, 'Ukrywanie': 55, 'Gadanina': 70 },
    equipment: [{ id: 'eq_anna_camera', name: 'Aparat fotograficzny z lampą błyskową', category: 'tool' }]
  },
  {
    id: 'pednik_fizyk',
    era: 'modern',
    archetype: 'scholar',
    name: 'Dr Ewa Wiśniewska',
    occupation: 'Fizyk Teoretyk',
    age: 41,
    gender: 'female',
    portraitUrl: '/portraits/predefined/krystyna-mroczek.webp',
    str: 45, dex: 55, con: 55, app: 50, pow: 75, edu: 85, siz: 50, int: 85, luck: 55,
    hp: 10, maxHp: 10, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Pracownica instytutu fizyki. Próbuje udowodnić, że pędnik z Kowar to tylko sprytna iluzja.',
    birthplace: 'Toruń, Polska',
    residence: 'Toruń, Polska',
    characterConcept: 'Błyskotliwa naukowczyni, której całe zrozumienie świata opiera się na twardych obliczeniach.',
    ideology: 'Matematyka to język wszechświata, wszystko musi dać się obliczyć.',
    significantPerson: 'Nieżyjący dziadek, szanowany profesor fizyki klasycznej.',
    meaningfulLocation: 'Tablica pokryta gęsto zapisanymi równaniami.',
    treasuredPossession: 'Kalkulator naukowy CASIO z dodatkowymi funkcjami logarytmicznymi.',
    traits: ['Racjonalna', 'Skupiona', 'Arogancka'],
    description: 'Elegancka, z włosami spiętymi w ciasny kok, zawsze nosi marynarkę.',
    backstory: 'Jej kariera zależy od obalenia mitów pseudonauki. Wyjazd do Kowar ma być prostym zadaniem, udowodnieniem błędu pomiarowego.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Zrozumie skomplikowaną aparaturę, maszyny oraz zjawiska fizyczne, w tym obce technologie.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Nauka (Fizyka)': 80, 'Nauka (Matematyka)': 75, 'Języki obce (Angielski)': 60, 'Korzystanie z Bibliotek': 65, 'Elektronika': 50 },
    equipment: [{ id: 'eq_ewa_calc', name: 'Kalkulator naukowy', category: 'tool' }, { id: 'eq_ewa_notes', name: 'Zeszyt pełen wzorów', category: 'document' }]
  },

  // ==========================================================================
  // TAJEMNICA DZIECI Z TRASZYNA
  // ==========================================================================
  {
    id: 'traszyn_egzorcysta',
    era: 'modern',
    archetype: 'mystic',
    name: 'Ksiądz Jan Kaczmarek',
    occupation: 'Ksiądz Egzorcysta',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/stanislaw-wilczek.webp',
    str: 55, dex: 50, con: 60, app: 50, pow: 85, edu: 75, siz: 65, int: 65, luck: 60,
    hp: 12, maxHp: 12, san: 85, maxSan: 99, mp: 17, maxMp: 17,
    background: 'Duchowny oddelegowany do badania przypadków opętań i nawiedzeń. Cichy, wyważony, ale z potężną wiarą.',
    birthplace: 'Częstochowa, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Narzędzie sił wyższych, stawiające czoła mrokowi, kiedy zawodzą logiczne rozwiązania.',
    ideology: 'Zło wnika przez luki w wierze. Tylko modlitwa i światło chronią duszę.',
    significantPerson: 'Jego biskup, który darzy go bezgranicznym, lecz sekretnym zaufaniem.',
    meaningfulLocation: 'Konfesjonał, miejsce ujawniania najmroczniejszych grzechów.',
    treasuredPossession: 'Srebrny krucyfiks z relikwią wewnątrz.',
    traits: ['Spokojny', 'Niezłomny', 'Wierzący'],
    description: 'Nosi skromną sutannę. Jego oczy sprawiają wrażenie, że patrzą na wskroś człowieka.',
    backstory: 'Wysłany do Traszyna po doniesieniach o niewyjaśnionych zjawiskach i zbeszczeszczonym krzyżu. Wie, jak odróżnić chorobę psychiczną od interwencji z zewnątrz.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Niezastąpiony do walki na płaszczyźnie Mocy, odstraszania istot zjaw i zachowania morale grupy.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 75, 'Języki obce (Łacina)': 70, 'Psychoanaliza': 60, 'Historia': 50, 'Nasłuchiwanie': 55 },
    equipment: [{ id: 'eq_jan_cross', name: 'Srebrny krucyfiks', category: 'tool' }, { id: 'eq_jan_water', name: 'Woda święcona', category: 'tool' }]
  },
  {
    id: 'traszyn_terapeuta',
    era: 'modern',
    archetype: 'healer',
    name: 'Andrzej "Aura" Zalewski',
    occupation: 'Bioenergoterapeuta',
    age: 44,
    gender: 'male',
    portraitUrl: '/portraits/predefined/piotr-wolski.webp',
    str: 50, dex: 60, con: 65, app: 55, pow: 75, edu: 60, siz: 60, int: 60, luck: 65,
    hp: 12, maxHp: 12, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Kontrowersyjny uzdrowiciel, który twierdzi, że leczy aurą. Jego gabinet w Lublinie pęka w szwach od pacjentów odrzuconych przez konwencjonalną medycynę.',
    birthplace: 'Zamość, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Współczesny szaman, który autentycznie coś wyczuwa, ale dorabia do tego new-ageową otoczkę.',
    ideology: 'Wszystko we wszechświecie wibruje, a my możemy dostroić te wibracje.',
    significantPerson: 'Zamożna pacjentka, sponsorująca jego najdroższe warsztaty duchowe.',
    meaningfulLocation: 'Zasnuty kadzidłami pokój przyjęć, pełen kryształów górskich.',
    treasuredPossession: 'Duży, rzekomo stary kryształ kwarcu na rzemyku.',
    traits: ['Empatyczny', 'Charyzmatyczny', 'Ekscentryczny'],
    description: 'Ubiera się swobodnie w lniane koszule, nosi długie włosy związane w kucyk.',
    backstory: 'Po wezwaniu przez znajomego egzorcystę, Andrzej wyczuł w Traszynie ogromne, rozerwane pole energetyczne, co wzbudziło w nim obawy o własne bezpieczeństwo.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skuteczny w niekonwencjonalnym leczeniu (pierwsza pomoc / psychologia) oraz wykrywaniu anomalii magicznych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 65, 'Pierwsza Pomoc': 60, 'Okultyzm': 55, 'Urok osobisty': 70, 'Spostrzegawczość': 60 },
    equipment: [{ id: 'eq_andrzej_crystal', name: 'Wahadełko z kryształem', category: 'tool' }, { id: 'eq_andrzej_incense', name: 'Kadzidła szałwiowe', category: 'tool' }]
  },
  {
    id: 'traszyn_psycholog',
    era: 'modern',
    archetype: 'scholar',
    name: 'Marta Kamińska',
    occupation: 'Psycholog Dziecięcy',
    age: 36,
    gender: 'female',
    portraitUrl: '/portraits/predefined/janina-rozycka.webp',
    str: 40, dex: 55, con: 55, app: 65, pow: 70, edu: 80, siz: 50, int: 75, luck: 60,
    hp: 10, maxHp: 10, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Ekspertka od traum dziecięcych pracująca dla opieki społecznej. Szuka racjonalnego wytłumaczenia w wypartych wspomnieniach i paraliżach sennych dzieci.',
    birthplace: 'Radom, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Anioł stróż straumatyzowanych dzieci, twardo stąpająca po ziemi.',
    ideology: 'Demonom można nadać racjonalne nazwy: to po prostu ukryte w podświadomości traumy i lęki.',
    significantPerson: 'Jej sześcioletnia córka, dla której bardzo mało ma czasu przez nadmiar spraw.',
    meaningfulLocation: 'Pokój do terapii przez zabawę, pełen zabawek i kredek.',
    treasuredPossession: 'Mały, porysowany rysunek "potwora" podarowany przez uratowanego pacjenta.',
    traits: ['Cierpliwa', 'Analityczna', 'Empatyczna'],
    description: 'Spokojny głos, ciepły uśmiech, ubiera się w stonowane barwy, aby nie przerażać dzieci.',
    backstory: 'Zaintrygowana zbieżnością w paraliżach sennych u kilku ofiar incydentu sprzed lat. Postanowiła pojechać do Traszyna z zamiarem znalezienia racjonalnych przyczyn traumy w lokalnej społeczności.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonała do "zbierania rozumu" w momentach grozy. Potrafi bezbłędnie ocenić ludzkie emocje.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 80, 'Psychologia': 75, 'Medycyna': 45, 'Perswazja': 60, 'Ukrywanie': 40 },
    equipment: [{ id: 'eq_marta_notebook', name: 'Zeszyt do notatek psychologicznych', category: 'document' }]
  },
  {
    id: 'traszyn_etnografka',
    era: 'modern',
    archetype: 'investigator',
    name: 'Zofia "Zosia" Sadowska',
    occupation: 'Lokalna Etnografka / Bibliotekarka',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/danuta-kwiecien.webp',
    str: 45, dex: 65, con: 55, app: 70, pow: 65, edu: 70, siz: 55, int: 70, luck: 55,
    hp: 11, maxHp: 11, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Pracuje w małej gminnej bibliotece, a hobbystycznie spisuje ludowe legendy i pieśni okolicznych wiosek.',
    birthplace: 'Traszyn, Polska',
    residence: 'Traszyn, Polska',
    characterConcept: 'Wścibska dziewczyna z sąsiedztwa, która wie, kogo na wsi zapytać o stare plotki i legendy.',
    ideology: 'Dawne legendy to przestrogi, których nie wolno lekceważyć.',
    significantPerson: 'Jej starsza ciotka, która znała wszystkie lokalne znachorki.',
    meaningfulLocation: 'Zakurzone, ciemne sekcje archiwum w starej bibliotece.',
    treasuredPossession: 'Prababci oprawiony w skórę śpiewnik z kilkoma bardzo starymi zaklęciami szeptuch.',
    traits: ['Wścibska', 'Towarzyska', 'Przesądna'],
    description: 'Nosi wełniane kardigany i szale. Zawsze jest w centrum lokalnych wydarzeń.',
    backstory: 'Pamięta z dzieciństwa plotki o trójce znajomych, którzy bawili się w stodole. Kiedy pojawił się obrócony krzyż na polu, Zofia od razu wyczuła okazję do udokumentowania powrotu starego demona z podań.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skupiona na researchu i szukaniu powiązań z mitami. Doskonały zmysł orientacji w plotkach.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Korzystanie z Bibliotek': 75, 'Antropologia': 65, 'Historia': 60, 'Spostrzegawczość': 55, 'Urok osobisty': 60 },
    equipment: [{ id: 'eq_zosia_book', name: 'Zeszyt z legendami i baśniami', category: 'document' }]
  },

  // ==========================================================================
  // PRZYBYSZ Z MATRIKSA: GŁOGÓW
  // ==========================================================================
  {
    id: 'glogow_detektyw',
    era: 'modern',
    archetype: 'investigator',
    name: 'Artur "Stary" Majchrzak',
    occupation: 'Prywatny Detektyw',
    age: 51,
    gender: 'male',
    portraitUrl: '/portraits/predefined/antoni-lis.webp',
    str: 65, dex: 55, con: 70, app: 45, pow: 60, edu: 65, siz: 70, int: 65, luck: 50,
    hp: 14, maxHp: 14, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Wyblakły eks-policjant prowadzący biuro detektywistyczne. Zajmuje się głównie szukaniem młodzieży uciekającej po dyskotekach.',
    birthplace: 'Wrocław, Polska',
    residence: 'Głogów, Polska',
    characterConcept: 'Zmęczony życiem glina, który zaczyna wątpić we własne zmysły po dziwnych zaginięciach.',
    ideology: 'Prawda jest często brzydsza, niż jakiekolwiek dziwaczne wytłumaczenia.',
    significantPerson: 'Jego były partner z milicji, który popadł w alkoholizm po sprawie sprzed 10 lat.',
    meaningfulLocation: 'Jego zagracone, pachnące starym tytoniem biuro.',
    treasuredPossession: 'Srebrna piersiówka, zawsze lekko wypełniona.',
    traits: ['Zgorzkniały', 'Cyniczny', 'Twardy'],
    description: 'Pognieciony trencz i głębokie worki pod oczami, wygląda jak relikt innej epoki.',
    backstory: 'Został wynajęty, by odnaleźć zaginionego chłopaka. Zamiast ucieczki odkrył zapiski o Matriksie, przepowiedniach i wielkim kataklizmie, co wstrząsnęło jego światopoglądem.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skuteczny w przesłuchaniach, szukaniu śladów fizycznych i twardym starciu z bandytami.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Prawo': 50, 'Zastraszanie': 65, 'Broń palna (krótka)': 60, 'Spostrzegawczość': 70, 'Ukrywanie': 55 },
    equipment: [{ id: 'eq_artur_revolver', name: 'Rewolwer kieszonkowy (bez zezwolenia)', category: 'weapon' }, { id: 'eq_artur_flask', name: 'Srebrna piersiówka', category: 'tool' }]
  },
  {
    id: 'glogow_haker',
    era: 'modern',
    archetype: 'trickster',
    name: 'Piotr "Kabel" Wójcicki',
    occupation: 'Programista / Haker',
    age: 26,
    gender: 'male',
    portraitUrl: '/portraits/predefined/krzysztof-boruta.webp',
    str: 40, dex: 70, con: 50, app: 50, pow: 65, edu: 75, siz: 55, int: 85, luck: 70,
    hp: 10, maxHp: 10, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Samouk, który noce spędza na wczesnych forach internetowych BBS. Wierzy, że system, w którym żyjemy, to symulacja.',
    birthplace: 'Legnica, Polska',
    residence: 'Głogów, Polska',
    characterConcept: 'Zafascynowany komputerami paranoik, gotów uwierzyć, że maszyny przejmą kontrolę.',
    ideology: 'Informacja musi być wolna, ale nikt nie jest bezpieczny w sieci.',
    significantPerson: 'Użytkownik o nicku "Oracle", z którym koresponduje od dwóch lat, nie znając go osobiście.',
    meaningfulLocation: 'Piwnica z kilkoma połączonymi w sieć PC-tami na Windowsie 95.',
    treasuredPossession: 'Twardy dysk wypełniony zaszyfrowanymi logami z forów o zjawiskach paranormalnych.',
    traits: ['Paranoiczny', 'Błyskotliwy', 'Introwertyk'],
    description: 'Blady, pije dużo tanich napojów energetycznych. Ubrany w za dużą bluzę z kapturem.',
    backstory: 'Złamał hakerów z Głogowa w jakiejś internetowej przepychance. W zamian przysłali mu dziwne ciągi znaków, które przypominały kod obcej cywilizacji, po czym zniknęli z sieci i rzeczywistości.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonale porusza się po komputerach, technologii, umie ominąć cyfrowe zabezpieczenia.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Korzystanie z Komputerów': 85, 'Elektronika': 60, 'Języki obce (Angielski)': 65, 'Spostrzegawczość': 50, 'Gadanina': 40 },
    equipment: [{ id: 'eq_piotr_laptop', name: 'Ciężki laptop z wczesnym Wi-Fi', category: 'tool' }, { id: 'eq_piotr_cables', name: 'Zestaw narzędzi do elektroniki', category: 'tool' }]
  },
  {
    id: 'glogow_psychiatra',
    era: 'modern',
    archetype: 'healer',
    name: 'Dr Krystyna Zawada',
    occupation: 'Psychiatra',
    age: 49,
    gender: 'female',
    portraitUrl: '/portraits/predefined/zofia-mierzejewska.webp',
    str: 40, dex: 50, con: 55, app: 55, pow: 70, edu: 85, siz: 50, int: 80, luck: 55,
    hp: 10, maxHp: 10, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Pracuje w szpitalu psychiatrycznym w Legnicy. Spotkała się niedawno z wieloma przypadkami nagłej derealizacji u młodzieży.',
    birthplace: 'Szczecin, Polska',
    residence: 'Legnica, Polska',
    characterConcept: 'Współczująca, lecz zmęczona lekarka, której naukowe fundamenty powoli kruszeją pod naporem niewyjaśnionego.',
    ideology: 'Każdy ból umysłu ma chemiczne podłoże – dopóki nie dowiedzie się, że to wpływ koszmarów z zewnątrz.',
    significantPerson: 'Jej pacjent "Zerowy", który przed zapadnięciem w śpiączkę mówił o "siatce na niebie".',
    meaningfulLocation: 'Sterroryzowany, duszny oddział zamknięty, w którym spędza dnie i noce.',
    treasuredPossession: 'Notes z zapiskami z terapii najbardziej uciążliwych przypadków.',
    traits: ['Spokojna', 'Chłodna', 'Wnikliwa'],
    description: 'Nosi elegancki biały kitel na prostej bluzce, jej postawa sugeruje ogromne zmęczenie stresem.',
    backstory: 'Zdecydowała się przeprowadzić dochodzenie na własną rękę, kiedy trzech nastolatków z Głogowa trafiło do niej tej samej nocy z identycznymi, "zaraźliwymi" halucynacjami dotyczącymi końca świata.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Pierwsza pomoc, stabilizowanie Poczytalności u drużyny, dogłębna psychoanaliza świadków.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 80, 'Medycyna': 75, 'Psychologia': 70, 'Perswazja': 50, 'Nauka (Biologia)': 60 },
    equipment: [{ id: 'eq_krys_medkit', name: 'Zestaw pierwszej pomocy z środkami uspokajającymi', category: 'tool' }]
  },
  {
    id: 'glogow_ufolog',
    era: 'modern',
    archetype: 'scholar',
    name: 'Karolina "Luna" Maj',
    occupation: 'UFOlog / Badaczka Anomalii',
    age: 33,
    gender: 'female',
    portraitUrl: '/portraits/predefined/irena-bielska.webp',
    str: 45, dex: 60, con: 60, app: 65, pow: 75, edu: 70, siz: 55, int: 70, luck: 65,
    hp: 11, maxHp: 11, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Redaktorka niszowego magazynu "Czwarty Wymiar". Podróżuje po Polsce z wykrywaczami anomalii magnetycznych w poszukiwaniu śladów kosmitów.',
    birthplace: 'Gdynia, Polska',
    residence: 'Nomada (żyje w wozie typu kamper)',
    characterConcept: 'Niezrażona, pełna pasji kobieta wierząca, że rząd ukrywa przed nami istnienie obcych cywilizacji.',
    ideology: 'Zarówno bogowie, jak i demony, to po prostu przybysze z innych gwiazd, których nasz umysł jeszcze nie ogarnia.',
    significantPerson: 'Jej partner, z którym kiedyś prowadzili kanał, dopóki nie zniknął podczas poszukiwań kręgów w zbożu.',
    meaningfulLocation: 'Jej zagracony kamper, obwieszony folią aluminiową i mapami piktogramów.',
    treasuredPossession: 'Nietypowy kryształ rzekomo odnaleziony na miejscu katastrofy pod Wylatowem.',
    traits: ['Egzaltowana', 'Uparta', 'Otwarta'],
    description: 'Nosi hipisowskie ubrania, dużą ilość bransolet i zawsze z kamerą pod ręką.',
    backstory: 'Śledząc wibracje w promieniowaniu ziemi na Dolnym Śląsku, trafiła na ślad "matriksowej sekty" w Głogowie. Postanowiła zinfiltrować ich szeregi by odkryć dowód na technologiczne ingerencje w ludzką świadomość.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Jako badaczka terenowa z dużą MOC-ą jest świetna w operowaniu na styku mitów, okultyzmu i obserwacji.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 70, 'Nawigacja': 60, 'Spostrzegawczość': 65, 'Korzystanie z Bibliotek': 50, 'Fotografia': 65 },
    equipment: [{ id: 'eq_luna_camera', name: 'Zestaw do zdjęć nocnych', category: 'tool' }, { id: 'eq_luna_detector', name: 'Wykrywacz pól elektromagnetycznych domowej roboty', category: 'tool' }]
  }
];
