import type { PredefinedCharacter } from './predefined-characters';
import { CATEGORY_FALLBACK_ASSETS } from '@/lib/equipment-catalog';

const BASE_STREFA_11_CHARACTERS: PredefinedCharacter[] = [
  // ==========================================================================
  // 1. SYGNAŁY NIEZNANEGO / CIEŃ NAD PRABUTAMI
  // ==========================================================================
  {
    id: 'strefa11_tomasz_nowicki',
    scenarioIds: ['cien-nad-prabutami'],
    era: 'prl-1970s',
    archetype: 'investigator',
    name: 'Tomasz Nowicki',
    occupation: 'Dziennikarz Śledczy / Prowadzący',
    age: 42,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tomasz_nowicki.webp',
    str: 55, dex: 60, con: 65, app: 60, pow: 70, edu: 75, siz: 65, int: 70, luck: 55,
    hp: 13, maxHp: 13, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Gospodarz programu "Sygnały Nieznanego", znany z posępnego głosu i chłodnej analizy nadprzyrodzonych zjawisk na antenie telewizyjnej. Dawniej pracował w dziale kryminalnym dużego dziennika.',
    birthplace: 'Warszawa, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Sceptyczny dziennikarz, który widział już zbyt wiele zjawisk niewyjaśnionych, by całkowicie zaprzeczać istnieniu nieznanego.',
    ideology: 'Zawsze jest jakieś logiczne wytłumaczenie - a jeśli go nie ma, oznacza to, że nauka ma jeszcze wiele do odkrycia.',
    significantPerson: 'Była żona, która zostawiła go przez jego obsesję na punkcie "tych dziwnych spraw".',
    meaningfulLocation: 'Studio nagraniowe telewizji, jedyne miejsce, gdzie czuje, że w pełni kontroluje sytuację.',
    treasuredPossession: 'Kasetowy dyktafon reporterski marki Sony z lat 90., który nagrał kiedyś głos EVP.',
    traits: ['Opanowany', 'Sceptyczny', 'Dociekliwy'],
    description: 'Nosi charakterystyczną, czarną skórzaną kurtkę, z ciemnymi okularami zawieszonymi na kołnierzyku.',
    backstory: 'Tomasz dorastał w cieniu betonowych blokowisk szarej Warszawy, co wcześnie wykształciło w nim instynkt dociekliwości i chłodny, niemal cyniczny dystans do rzeczywistości. Jako gwiazda działu kryminalnego dużego stołecznego dziennika, zyskał sławę obiektywnego analityka poszukującego prawdy ukrytej w aktach milicyjnych. Zawsze wyznawał żelazną zasadę: "Każdy fenomen ma logiczne wytłumaczenie, a ignorancja to tylko dowód na luki w nauce". Złamaniem tej bariery stała się dla niego sprawa zaginięć na obrzeżach Puszczy Kampinoskiej. To tam, samotnie, o trzeciej nad ranem uchwycił na swój reporterski, kasetowy dyktafon marki Sony (z którym od lat się nie rozstaje) mrożący krew w żyłach trzask EVPu, odmawiający imię bytu, którego nigdy nie powinno być w lasach. To brutalne zderzenie z nieznanym zrujnowało nie tylko jego konwencjonalną karierę, ale przede wszystkim małżeństwo - żona odeszła, nie potrafiąc wytrzymać nozdrzy rozszerzonych od strachu i jego obsesyjnych nocnych poszukiwań kolejnych "Sygnałów". Dziś bezpiecznie czuje się jedynie w otoczonym kablami, mrocznym studiu telewizyjnym, w swoim słynnym czarnym, skórzanym płaszczu z uniesionym kołnierzem, za ciemnymi okularami. Mimo opanowania i sceptycyzmu obnażającego naciągaczy i ezoterycznych magów, Tomasz każdego dnia walczy o udowodnienie samemu sobie, że to, co usłyszał przed laty na kasecie, nie było wynikiem wczesnego obłędu.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Dobry w zbieraniu informacji, nawiązywaniu kontaktów i przesłuchiwaniu świadków.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Spostrzegawczość': 70, 'Perswazja': 65, 'Psychologia': 60, 'Korzystanie z Bibliotek': 50, 'Nasłuchiwanie': 55 },
    equipment: [{ id: 'eq_tom_dyktafon', name: 'Dyktafon na mikrokasety', category: 'tool' }, { id: 'eq_tom_latarka', name: 'Mocna latarka policyjna', category: 'tool' }]
  },
  {
    id: 'strefa11_helena_krawczyk',
    scenarioIds: ['cien-nad-prabutami'],
    era: 'prl-1970s',
    archetype: 'trickster',
    name: 'Helena Krawczyk',
    occupation: 'Producent telewizyjny',
    age: 38,
    gender: 'female',
    portraitUrl: '/portraits/predefined/helena_krawczyk.webp',
    str: 40, dex: 65, con: 55, app: 70, pow: 60, edu: 80, siz: 50, int: 75, luck: 65,
    hp: 10, maxHp: 10, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Z żelazną ręką zarządza ekipą "Sygnałów Nieznanego". Załatwia zgody na wejścia, finanse, oraz potrafi przekonać policję do przymknięcia oka na wejście na teren zamknięty.',
    birthplace: 'Kraków, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Wyrachowana organizatorka, dla której liczy się oglądalność i dobrze opowiedziana historia.',
    ideology: 'Telewizja to iluzja, a ludzie chcą wierzyć w niesamowite rzeczy.',
    significantPerson: 'Tomasz Nowicki - choć często się kłócą, tworzą niepokonany zespół.',
    meaningfulLocation: 'Wóz transmisyjny - mobilne centrum dowodzenia.',
    treasuredPossession: 'Notatnik z kontaktami do niemal każdego oficjela w państwie.',
    traits: ['Ambitna', 'Czarująca', 'Stanowcza'],
    description: 'Zawsze nienagannie ubrana (zwykle w dopasowane garnitury damskie i płaszcze), z telefonem komórkowym "cegłą" ciągle w ręku.',
    backstory: 'Kariera Heleny w mediach rozpoczęła się na krakowskich korytarzach ośrodków telewizyjnych, gdzie szybko zorientowała się, że widzowie nie łakną suchej prawdy, lecz zapierających dech w piersiach iluzji i tajemnic. Bezkompromisowa i zdeterminowana, pokonała szczeble od asystentki do głównej producentki "Sygnałów Nieznanego", budując pozycję żelazną stanowczością i urokiem osobistym. Jej świat kręci się wokół notatnika z kontaktami - to dzięki niemu załatwia wejścia tam, gdzie policja wolałaby zamknąć drzwi. Zawsze ubrana w nienaganny garnitur, z przypiętą do ucha nieodłączną komórką w formie "cegły", potrafi dyrygować sztabem ludzi bez podnoszenia głosu. Helena uwielbia adrenalinę pracy w terenie, traktując wóz transmisyjny niczym swój azyl i mobilne centrum dowodzenia. Choć wyznaje, że "telewizja to tylko iluzja", jej zderzenia z niewytłumaczalnymi zjawiskami podczas kręcenia materiałów w opuszczonych klasztorach i nawiedzonych szpitalach zasiały w niej mroczne ziarno wątpliwości. Nigdy nie przyzna się do strachu przed kamerą, polegając na duecie z Tomaszem Nowickim. Choć ich metody pracy prowadzą do ciągłych i głośnych kłótni, oboje wiedzą, że stworzyli zespół, który jako jedyny w kraju potrafi udźwignąć ciężar dokumentowania prawdy czającej się w mroku wolnej Polski.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Rewelacyjna w załatwianiu spraw urzędowych i urokach osobistych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Urok osobisty': 75, 'Perswazja': 70, 'Gadanina': 65, 'Prawo': 45, 'Spostrzegawczość': 50 },
    equipment: [{ id: 'eq_hel_telefon', name: 'Telefon komórkowy (wielki)', category: 'tool' }, { id: 'eq_hel_notes', name: 'Notes kontaktów', category: 'tool' }]
  },
  {
    id: 'strefa11_barbara_zawadzka',
    scenarioIds: ['cien-nad-prabutami'],
    era: 'prl-1970s',
    archetype: 'scholar',
    name: 'Dr Barbara Zawadzka',
    occupation: 'Etnograf / Parapsycholog',
    age: 45,
    gender: 'female',
    portraitUrl: '/portraits/predefined/barbara_zawadzka.webp',
    str: 45, dex: 55, con: 60, app: 55, pow: 80, edu: 85, siz: 55, int: 80, luck: 60,
    hp: 11, maxHp: 11, san: 80, maxSan: 99, mp: 16, maxMp: 16,
    background: 'Naukowiec Uniwersytetu Warszawskiego. Regularna ekspertka w programie "Sygnały Nieznanego", oceniająca materiały wideo i ślady fenomenów.',
    birthplace: 'Lublin, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Racjonalny umysł w kontakcie z niewytłumaczalnym. Analizuje kulty, demonologię i ludowe legendy na polskich wsiach.',
    ideology: 'Za każdą legendą i zabobonem kryje się zniekształcone ziarno prawdziwej historii i fizyki.',
    significantPerson: 'Jej mentor ze studiów, który popadł w obłęd podczas badań nad folklorem Podlasia.',
    meaningfulLocation: 'Biblioteka wydziałowa, wśród starych zapisów ludoznawczych.',
    treasuredPossession: 'Kamera na podczerwień i sprzęt do pomiaru pola elektromagnetycznego (EMF).',
    traits: ['Metodyczna', 'Otwarty umysł', 'Skoncentrowana'],
    description: 'Nosi luźne wełniane swetry, okulary na łańcuszku, często z teczką pełną wydruków i ryciny.',
    backstory: 'Jako szanowany pracownik naukowy Uniwersytetu Warszawskiego, Barbara przez dekady zakładała, że za każdym podaniem ludowym, legendą czy klątwą kryje się zniekształcone przez wieki ziarno historycznej prawdy. Metodyczna do bólu, zorganizowała swój świat w zapachach starego papieru w wydziałowej bibliotece, uchodząc za specjalistkę z zakresu demonologii i ludowych wierzeń z Lubelszczyzny. Jej akademickie, bezpieczne postrzeganie świata pękło podczas wyprawy badawczej na Podlasie, w której asystowała swojemu wieloletniemu mentorowi. Podczas próby skatalogowania zjawisk w zapomnianej wiosce, jej mentor postradał zmysły, wpatrując się w mrok starej stodoły. Od tamtego dnia Barbara porzuciła klasyczną etnografię na rzecz parapsychologii. Wyposażona w nowoczesną - jak na lata 90. - aparaturę: kamerę na podczerwień oraz swój cenny miernik EMF, dołączyła do ekipy "Sygnałów Nieznanego" by znaleźć naukowy dowód na to, co widziała. Za maską spokojnej, ubranej w grube wełniane swetry i okulary na łańcuszku profesorki kryje się umysł łaknący dowodu na istnienie innej fizyki. Barbara uważa, że to nie duchy napadają na ludzi, ale niezrozumiane jeszcze echa energii, a każde odstępstwo od normy na jej mierniku przybliża ją do ocalenia dobrego imienia zamkniętego w zakładzie psychiatrycznym mentora.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Niezbędna do analizy okultyzmu, historii i dziwnych przedmiotów.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 70, 'Historia': 65, 'Antropologia': 60, 'Korzystanie z Bibliotek': 75, 'Języki obce (Łacina)': 50, 'Nauka (Fizyka)': 45 },
    equipment: [{ id: 'eq_barb_emf', name: 'Miernik pola elektromagnetycznego', category: 'tool' }, { id: 'eq_barb_camera', name: 'Kamera z trybem NightVision', category: 'tool' }]
  },
  {
    id: 'strefa11_ryszard_klucznik',
    scenarioIds: ['cien-nad-prabutami'],
    era: 'prl-1970s',
    archetype: 'action',
    name: 'Ryszard "Klucznik" Kaczmarek',
    occupation: 'B. Oficer SB / Technik Ochrony',
    age: 55,
    gender: 'male',
    portraitUrl: '/portraits/predefined/ryszard_kaczmarek.webp',
    str: 75, dex: 65, con: 70, app: 45, pow: 60, edu: 60, siz: 75, int: 65, luck: 50,
    hp: 14, maxHp: 14, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Ochroniarz i "załatwiacz" dla ekipy telewizyjnej. Były funkcjonariusz bezpieczeństwa z okresu PRL, który ma kontakty w milicji/policji i potrafi otworzyć każde drzwi.',
    birthplace: 'Gdańsk, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Twardy facet, który widział najgorsze twarze ludzi i systemów. Zapewnia fizyczne bezpieczeństwo badaczom.',
    ideology: 'Bezpieczeństwo przede wszystkim. Czasem brutalna siła jest jedynym argumentem.',
    significantPerson: 'Jego córka, dla której stara się odkupić dawne winy w SB.',
    meaningfulLocation: 'Jego stara Łada Niva (lub Polonez Caro), służąca za bazę i magazyn sprzętu.',
    treasuredPossession: 'Legalnie zarejestrowany pistolet P-64, w kaburze pod pachą.',
    traits: ['Podejrzliwy', 'Lojalny', 'Bezkompromisowy'],
    description: 'Masywnej postury, zawsze lekko niedogolony. Nosi sprane jeansy, ciężkie buty i wojskową kurtkę.',
    backstory: 'Ryszard był człowiekiem systemu, oficerem służb bezpieczeństwa ukształtowanym przez brutalne realia zimnej wojny i PRL-u. Wychowany w Gdańsku, szybko nauczył się, że lojalność i bezkompromisowa siła są o wiele skuteczniejszymi walutami niż obietnice. W latach 80. zajmował się inwigilacją, otwieraniem zamków bez śladu i dyskretnym rozwiązywaniem problemów. System upadł, a po 1989 roku Ryszard pozostał człowiekiem o kompetencjach niepasujących do nowego świata. Targany wyrzutami sumienia za dawne czyny, których brzemię uderzyło w jego córkę, postanowił wykorzystać swoje paranoiczne nawyki do chronienia tych, którzy są zbyt naiwni, by dbać o siebie sami. Dziś zatrudnia go ekipa telewizyjna "Sygnałów Nieznanego". Za sterami swojej starej Łady Nivy pełni rolę ochroniarza, kierowcy i "ślusarza". Nigdy nie rozstaje się z legalnym pistoletem P-64 skrytym pod wojskową kurtką, a na każdy uśmiech odpowiada podejrzliwym zmrużeniem oka. Ryszard absolutnie nie wierzy w duchy, kulty ani klątwy; wierzy za to, że najgorsze potwory mają dwie ręce, dwie nogi i motyw finansowy. Dopóki ma swój zestaw wytrychów i broń, jest w stanie uchronić "jajogłowych" dziennikarzy przed brutalnymi spotkaniami w zatęchłych piwnicach i opuszczonych bunkrach.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Mistrz przetrwania, walki i dyskretnego otwierania drzwi.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Walka wręcz': 75, 'Broń palna (krótka)': 70, 'Unik': 60, 'Ślusarstwo': 65, 'Zastraszanie': 60, 'Spostrzegawczość': 55 },
    equipment: [{ id: 'eq_rysz_gun', name: 'Pistolet P-64 z zapasowym magazynkiem', category: 'weapon' }, { id: 'eq_rysz_lockpicks', name: 'Zestaw wytrychów i łom', category: 'tool' }]
  },

  // ==========================================================================
  // 2. TAJEMNICA PĘDNIKA: KOWARY
  // ==========================================================================
  {
    id: 'pednik_inzynier',
    scenarioIds: ['tajemnica-pendnika-lagiewki'],
    era: '1990s',
    archetype: 'scholar',
    name: 'Inż. Marek Kamiński',
    occupation: 'Inżynier Mechanik',
    age: 48,
    gender: 'male',
    portraitUrl: '/portraits/predefined/marek_kaminski.webp',
    str: 65, dex: 60, con: 70, app: 50, pow: 60, edu: 80, siz: 65, int: 75, luck: 55,
    hp: 13, maxHp: 13, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Doświadczony projektant zderzaków w przemyśle motoryzacyjnym. Słyszał o przełomowych eksperymentach w Kowarach i chce na własne oczy zobaczyć pochłaniacz kinetyczny.',
    birthplace: 'Wrocław, Polska',
    residence: 'Wrocław, Polska',
    characterConcept: 'Sceptyczny pragmatyk wierzący tylko w prawa fizyki.',
    ideology: 'Energia nie bierze się znikąd i nie może po prostu zniknąć.',
    significantPerson: 'Jego promotor ze studiów, z którym prowadzi ciągły spór naukowy.',
    meaningfulLocation: 'Laboratorium testowe, pełne manekinów zderzeniowych i aparatury pomiarowej.',
    treasuredPossession: 'Precyzyjna suwmiarka cyfrowa w skórzanym etui.',
    traits: ['Pragmatyczny', 'Uparty', 'Ciekawski'],
    description: 'Nosi roboczy drelich z wieloma kieszeniami i wiecznie umazane smarem dłonie.',
    backstory: 'Marek spędził ponad dwadzieścia lat przy deskach kreślarskich i w halach fabrycznych przemysłu motoryzacyjnego na Dolnym Śląsku. Jako inżynier mechaniki precyzyjnej wyznaje prostą zasadę: bilans energii we wszechświecie zawsze musi wyjść na zero. W jego uporządkowanym świecie wszystko da się zmierzyć suwmiarką i opisać prawami dynamiki Newtona. Pęknięcie w tym światopoglądzie pojawiło się podczas tajnych prób zderzeniowych na poligonie pod Jelczem. Zderzak prototypowego pojazdu pochłonął siłę uderzenia o betonowy blok, ale zamiast odkształcenia materiału aparatura pomiarowa zarejestrowała gwałtowny spadek temperatury wokół maszyny i nienaturalny impuls magnetyczny. Kiedy jego promotor ze studiów uznał to za błąd aparatury i zakazał dalszych dociekań, Marek na własną rękę rozpoczął poszukiwania prawdy. Wieść o eksperymentach konstrukcyjnych Lucjana Łągiewki w Kowarach ściągnęła go w Karkonosze. W roboczym drelichu z wiecznie umazanymi smarem dłońmi i wierną suwmiarką w kieszeni, Marek zamierza na własne oczy sprawdzić, czy kowarski pędnik to tylko genialny mechanizm, czy może nieświadome otwarcie wrót do obcej, nieznanej fizyki, przed którą konwencjonalna nauka zamyka oczy.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Złota rączka, potrafi naprawić lub zepsuć każde urządzenie mechaniczne.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Mechanika': 75, 'Elektryka': 65, 'Spostrzegawczość': 60, 'Fizyka': 55, 'Prowadzenie auta': 65 },
    equipment: [{ id: 'eq_mar_tools', name: 'Zestaw narzędzi w walizce', category: 'tool' }]
  },
  {
    id: 'pednik_kierowca',
    scenarioIds: ['tajemnica-pendnika-lagiewki'],
    era: '1990s',
    archetype: 'action',
    name: 'Tomasz "Ryzykant" Wójcik',
    occupation: 'Kierowca Testowy',
    age: 32,
    gender: 'male',
    portraitUrl: '/portraits/predefined/tomasz_wojcik.webp',
    str: 70, dex: 80, con: 75, app: 60, pow: 50, edu: 50, siz: 60, int: 60, luck: 65,
    hp: 13, maxHp: 13, san: 50, maxSan: 99, mp: 10, maxMp: 10,
    background: 'Były kierowca rajdowy, który po poważnym wypadku zatrudnił się jako kaskader i oblatywacz dziwnych pojazdów.',
    birthplace: 'Kraków, Polska',
    residence: 'Kraków, Polska',
    characterConcept: 'Adrenalinowy ćpun, który ufa swojemu refleksowi bardziej niż komukolwiek.',
    ideology: 'Prędkość to wolność, a hamulce są dla tchórzy.',
    significantPerson: 'Pilot rajdowy, który zginął w wypadku, z którego Tomasz cudem ocalał.',
    meaningfulLocation: 'Garaż pełen rozebranych na części silników.',
    treasuredPossession: 'Kluczyki do pierwszego wygranego samochodu rajdowego.',
    traits: ['Odważny', 'Impulsywny', 'Refleksyjny'],
    description: 'Nosi kurtkę skórzaną, często żuje gumę, rzadko ściąga rękawiczki do jazdy.',
    backstory: 'Zapach spalonej gumy, gorącego oleju i etyliny towarzyszy Tomaszowi od dziecka. Jako jeden z najbardziej obiecujących kierowców rajdowych w Polsce lat 90., żył wyłącznie w rytmie obrotomierza i ryku silnika. Wszystko zmieniło się podczas jesiennego Rajdu Karkonoskiego w 1993 roku. Na ostrym wirażu pod Kowarami prowadzony przez niego wóz wypadł z trasy, uderzając w skały. Tomasz cudem ocalał, jednak jego wieloletni pilot i najbliższy przyjaciel Janek zginął na miejscu. Przeżyta trauma nie odebrała Tomaszowi głodu prędkości, lecz zamieniła sportową pasję w ponurą obsesję na punkcie granic ludzkiego przetrwania. Porzucił oficjalne mistrzostwa i został kierowcą testowym oraz kaskaderem do zadań, których nikt inny nie chciał się podjąć. W kieszeni skórzanej kurtki rajdowej zawsze nosi porysowane kluczyki do rozbitego wozu, traktując je jak talizman i wieczne memento. Kiedy usłyszał o zderzaku w Kowarach, który rzekomo całkowicie niweluje przeciążenia i siłę zderzenia, natychmiast zgłosił się na ochotnika. Tomasz nie boi się śmierci ani zniszczenia maszyny; za kółkiem szuka odpowiedzi na pytanie, jaka niepojęta siła ocaliła go w górach tamtej feralnej nocy.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Mistrz za kółkiem, świetny refleks pozwala mu uniknąć niebezpieczeństw fizycznych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Prowadzenie auta': 85, 'Unik': 70, 'Walka wręcz': 60, 'Spostrzegawczość': 55, 'Nawigacja': 50 },
    equipment: [{ id: 'eq_tom_helmet', name: 'Kask ochronny', category: 'tool' }, { id: 'eq_tom_gloves', name: 'Rękawice ognioodporne', category: 'tool' }]
  },
  {
    id: 'pednik_dziennikarka',
    scenarioIds: ['tajemnica-pendnika-lagiewki'],
    era: '1990s',
    archetype: 'investigator',
    name: 'Anna Dąbrowska',
    occupation: 'Dziennikarz śledczy',
    age: 35,
    gender: 'female',
    portraitUrl: '/portraits/predefined/anna_dabrowska.webp',
    str: 50, dex: 65, con: 60, app: 65, pow: 65, edu: 70, siz: 55, int: 75, luck: 60,
    hp: 11, maxHp: 11, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Tropi ukryte technologie i powiązania rządu z tajemniczymi agencjami. Węszy w sprawie Agencji Ochrony Rzeczypospolitej (AOR).',
    birthplace: 'Poznań, Polska',
    residence: 'Warszawa, Polska',
    characterConcept: 'Wścibska reporterka, która nie cofnie się przed niczym dla dobrego tematu.',
    ideology: 'Wiedza należy do społeczeństwa, nie do zamkniętych gabinetów służb specjalnych.',
    significantPerson: 'Informator z wnętrza służb o kryptonimie "Kruk".',
    meaningfulLocation: 'Ciemnia fotograficzna, w której wywołuje niewygodne materiały.',
    treasuredPossession: 'Kompaktowy aparat z bardzo czułym filmem fotograficznym.',
    traits: ['Dociekliwa', 'Podejrzliwa', 'Gadatliwa'],
    description: 'Bystre spojrzenie zza oprawek korekcyjnych, notes zawsze w pogotowiu.',
    backstory: 'Anna jest uosobieniem bezkompromisowego dziennikarstwa śledczego doby polskiej transformacji ustrojowej. Dla niej nie ma drzwi, w które nie da się włożyć buta, ani urzędnika, którego nie da się przycisnąć niewygodnym pytaniem. Swoją karierę zbudowała na ujawnianiu nielegalnego handlu mieniem poradzieckim i dzikiej prywatyzacji na zachodzie kraju. Zawsze nosi przy sobie kompaktowy aparat fotograficzny na czułym filmie, a jej ciemnia w redakcji to jedyne miejsce, w którym czuje się w pełni bezpiecznie. Jej zainteresowanie Kowarami zaczęło się od zaszyfrowanej wiadomości od informatora o kryptonimie Kruk, powiązanego z nowo tworzoną Agencją Ochrony Rzeczypospolitej. Przecieki sugerowały, że wokół warsztatu w Kowarach kręcą się ludzie z zagranicznych koncernów zbrojeniowych oraz dawni oficerowie wywiadu wojskowego. Wścibska i niezwykle czujna, Anna przyjechała w Sudety pod pozorem pisania lekkiego reportażu o lokalnym wynalazcy. Zza korekcyjnych okularów bacznie rejestruje każdy podejrzany ruch, czując w kościach, że sprawa pędnika to nie tylko polski patent techniczny, lecz niebezpieczna gra wywiadów na granicy zjawisk wymykających się ludzkiemu pojmowaniu.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonale kłamie, podsłuchuje i włamuje się do archiwów.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Spostrzegawczość': 70, 'Perswazja': 65, 'Psychologia': 60, 'Ukrywanie': 55, 'Gadanina': 70 },
    equipment: [{ id: 'eq_anna_camera', name: 'Aparat fotograficzny z lampą błyskową', category: 'tool' }]
  },
  {
    id: 'pednik_fizyk',
    scenarioIds: ['tajemnica-pendnika-lagiewki'],
    era: '1990s',
    archetype: 'scholar',
    name: 'Dr Ewa Wiśniewska',
    occupation: 'Fizyk teoretyczna',
    age: 41,
    gender: 'female',
    portraitUrl: '/portraits/predefined/ewa_wisniewska.webp',
    str: 45, dex: 55, con: 55, app: 50, pow: 75, edu: 85, siz: 50, int: 85, luck: 55,
    hp: 10, maxHp: 10, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Pracownica instytutu fizyki. Próbuje udowodnić, że pędnik z Kowar to tylko sprytna iluzja.',
    birthplace: 'Toruń, Polska',
    residence: 'Toruń, Polska',
    characterConcept: 'Błyskotliwa naukowczyni, której całe zrozumienie świata opiera się na twardych obliczeniach.',
    ideology: 'Matematyka to język wszechświata, wszystko musi dać się obliczyć.',
    significantPerson: 'Nieżyjący dziadek, szanowany profesor fizyki klasycznej.',
    meaningfulLocation: 'Tablica pokryta gęsto zapisanymi równaniami.',
    treasuredPossession: 'Kalkulator naukowy CASIO z dodatkowymi funkcjami logarytmicznymi.',
    traits: ['Racjonalna', 'Skupiona', 'Arogancka'],
    description: 'Elegancka, z włosami spiętymi w ciasny kok, zawsze nosi marynarkę.',
    backstory: 'Córka i wnuczka szanowanych toruńskich profesorów, Ewa od najmłodszych lat traktowała matematykę jak jedyny nieskazitelny język wszechświata. Jako pracowniczka instytutu fizyki teoretycznej zyskała renomę bezwzględnej polemistki, tępiącej wszelkie przejawy pseudonauki i ezoteryki, które po 1989 roku zalały polski rynek wydawniczy. Jej życiową tarczą jest kalkulator naukowy Casio i gęsto zapisany zeszyt równań różniczkowych. Wyjazd do Kowar traktowała początkowo jako rutynowy obowiązek akademicki, mający na celu publiczne obalenie mitu o łamaniu zasad zachowania pędu przez konstrukcję Łągiewki. Wszystko zmieniło się, gdy przeprowadziła wstępne kalkulacje rozkładu wektorów sił podczas zderzenia. Wyniki nie wykazały błędu pomiarowego; równania wskazywały na obecność punktowego zagięcia czasoprzestrzeni i transfer energii poza nasz wymiar. Ta świadomość uderzyła w fundamenty jej bezpiecznego, racjonalnego świata. Zawsze elegancka, z włosami spiętymi w ciasny kok, Ewa ukrywa pod maską akademickiej arogancji rosnące przerażenie. Przyjechała do kowarskiego warsztatu, by dowieść samej sobie, że rzeczywistość wokół nas wciąż podlega prawom ludzkiej matematyki.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Zrozumie skomplikowaną aparaturę, maszyny oraz zjawiska fizyczne, w tym obce technologie.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Nauka (Fizyka)': 80, 'Nauka (Matematyka)': 75, 'Języki obce (Angielski)': 60, 'Korzystanie z Bibliotek': 65, 'Elektronika': 50 },
    equipment: [{ id: 'eq_ewa_calc', name: 'Kalkulator naukowy', category: 'tool' }, { id: 'eq_ewa_notes', name: 'Zeszyt pełen wzorów', category: 'document' }]
  },

  // ==========================================================================
  // 3. TAJEMNICA DZIECI Z TRASZYNA
  // ==========================================================================
  {
    id: 'traszyn_egzorcysta',
    scenarioIds: ['tajemnica-dzieci-z-traszyna'],
    era: '1990s',
    archetype: 'mystic',
    name: 'Ksiądz Jan Kaczmarek',
    occupation: 'Ksiądz Egzorcysta',
    age: 52,
    gender: 'male',
    portraitUrl: '/portraits/predefined/jan_kaczmarek.webp',
    str: 55, dex: 50, con: 60, app: 50, pow: 85, edu: 75, siz: 65, int: 65, luck: 60,
    hp: 12, maxHp: 12, san: 85, maxSan: 99, mp: 17, maxMp: 17,
    background: 'Duchowny oddelegowany do badania przypadków opętań i nawiedzeń. Cichy, wyważony, ale z potężną wiarą.',
    birthplace: 'Częstochowa, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Narzędzie sił wyższych, stawiające czoła mrokowi, kiedy zawodzą logiczne rozwiązania.',
    ideology: 'Zło wnika przez luki w wierze. Tylko modlitwa i światło chronią duszę.',
    significantPerson: 'Jego biskup, który darzy go bezgranicznym, lecz sekretnym zaufaniem.',
    meaningfulLocation: 'Konfesjonał, miejsce ujawniania najmroczniejszych grzechów.',
    treasuredPossession: 'Srebrny krucyfiks z relikwią wewnątrz.',
    traits: ['Spokojny', 'Niezłomny', 'Wierzący'],
    description: 'Nosi skromną sutannę. Jego oczy sprawiają wrażenie, że patrzą na wskroś człowieka.',
    backstory: 'Ksiądz Jan spędził ponad dwadzieścia lat w duszpasterstwie diecezji lubelskiej, posługując na styku ludzkiego cierpienia i zjawisk, o których Kościół woli milczeć. Jako oficjalny egzorcysta delegowany przez biskupa, widział dziesiątki przypadków chorób psychicznych i histerii, które potrafił odsiać od prawdziwej obecności zła. Nigdy nie zapomni jednak zimowej nocy w opuszczonej parafii pod Hrubieszowem, gdzie głos wydobywający się z gardła opętanej dziewczynki recytował bluźniercze litanie w języku, którego nie znały żadne teksty biblijne. Od tamtego czasu Jan nosi pod sutanną srebrny krucyfiks z relikwią i nie rozstaje się z butelką wody święconej. Wezwanie do Traszyna po doniesieniach o odwróconym krzyżu i niewytłumaczalnych zachowaniach dzieci traktuje z najwyższą powagą. Cichy, wyważony i obdarzony żelazną wolą, doskonale wie, że zło przenika tam, gdzie pęka ludzka nadzieja. Wchodząc między zabobonnych mieszkańców Traszyna, ksiądz Jan przygotowuje się na duchowe starcie z siłą znacznie starszą i bardziej obcą niż demony z podręczników teologii.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Niezastąpiony do walki na płaszczyźnie Mocy, odstraszania istot zjaw i zachowania morale grupy.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 75, 'Języki obce (Łacina)': 70, 'Psychoanaliza': 60, 'Historia': 50, 'Nasłuchiwanie': 55 },
    equipment: [{ id: 'eq_jan_cross', name: 'Srebrny krucyfiks', category: 'tool' }, { id: 'eq_jan_water', name: 'Woda święcona', category: 'tool' }]
  },
  {
    id: 'traszyn_terapeuta',
    scenarioIds: ['tajemnica-dzieci-z-traszyna'],
    era: '1990s',
    archetype: 'healer',
    name: 'Andrzej "Aura" Zalewski',
    occupation: 'Bioenergoterapeuta',
    age: 44,
    gender: 'male',
    portraitUrl: '/portraits/predefined/andrzej_zalewski.webp',
    str: 50, dex: 60, con: 65, app: 55, pow: 75, edu: 60, siz: 60, int: 60, luck: 65,
    hp: 12, maxHp: 12, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Kontrowersyjny uzdrowiciel, który twierdzi, że leczy aurą. Jego gabinet w Lublinie pęka w szwach od pacjentów odrzuconych przez konwencjonalną medycynę.',
    birthplace: 'Zamość, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Współczesny szaman, który autentycznie coś wyczuwa, ale dorabia do tego new-ageową otoczkę.',
    ideology: 'Wszystko we wszechświecie wibruje, a my możemy dostroić te wibracje.',
    significantPerson: 'Zamożna pacjentka, sponsorująca jego najdroższe warsztaty duchowe.',
    meaningfulLocation: 'Zasnuty kadzidłami pokój przyjęć, pełen kryształów górskich.',
    treasuredPossession: 'Duży, rzekomo stary kryształ kwarcu na rzemyku.',
    traits: ['Empatyczny', 'Charyzmatyczny', 'Ekscentryczny'],
    description: 'Ubiera się swobodnie w lniane koszule, nosi długie włosy związane w kucyk.',
    backstory: 'Gabinet Andrzeja w centrum Lublina na przełomie wieków przyciągał setki ludzi, dla których oficjalna służba zdrowia nie miała już ratunku. Długowłosy, ubrany w lniane koszule i otoczony dymem szałwiowych kadzideł, Andrzej uchodzi za charyzmatycznego mistrza bioterpaii i uzdrawiania kryształami. Za tą kolorową, new-ageową fasadą kryje się jednak człowiek noszący w sobie autentyczny, niewytłumaczalny dar odczuwania anomalii energetycznych. Jego życie pękło na pół podczas prywatnego seansu z dawnym pacjentem z okolic Traszyna. Kiedy dotknął dłońmi skroni mężczyzny, w ułamku sekundy ujrzał czarne, pulsujące niebo i bezkształtną obecność czającą się pod fundamentami wiejskich zabudowań. Złote wahadełko w jego rękach rozgrzało się do czerwoności, a fala obezwładniającego chłodu na zawsze zmieniła jego postrzeganie świata. Przyjechał do Traszyna na prośbę znajomego duchownego, wiedząc, że to nie zabawa w bioenergię, lecz walka o przetrwanie. Mimo że wciąż posługuje się żargonem o czakrach i wibracjach, Andrzej panicznie boi się chwili, w której jego własna wrażliwość przyciągnie uwagę bytu czuwającego w traszyńskich lasach.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skuteczny w niekonwencjonalnym leczeniu (pierwsza pomoc / psychologia) oraz wykrywaniu anomalii magicznych.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 65, 'Pierwsza Pomoc': 60, 'Okultyzm': 55, 'Urok osobisty': 70, 'Spostrzegawczość': 60 },
    equipment: [{ id: 'eq_andrzej_crystal', name: 'Wahadełko z kryształem', category: 'tool' }, { id: 'eq_andrzej_incense', name: 'Kadzidła szałwiowe', category: 'tool' }]
  },
  {
    id: 'traszyn_psycholog',
    scenarioIds: ['tajemnica-dzieci-z-traszyna'],
    era: '1990s',
    archetype: 'scholar',
    name: 'Marta Kamińska',
    occupation: 'Psycholog',
    age: 36,
    gender: 'female',
    portraitUrl: '/portraits/predefined/marta_kaminska.webp',
    str: 40, dex: 55, con: 55, app: 65, pow: 70, edu: 80, siz: 50, int: 75, luck: 60,
    hp: 10, maxHp: 10, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Ekspertka od traum dziecięcych pracująca dla opieki społecznej. Szuka racjonalnego wytłumaczenia w wypartych wspomnieniach i paraliżach sennych dzieci.',
    birthplace: 'Radom, Polska',
    residence: 'Lublin, Polska',
    characterConcept: 'Anioł stróż straumatyzowanych dzieci, twardo stąpająca po ziemi.',
    ideology: 'Demonom można nadać racjonalne nazwy: to po prostu ukryte w podświadomości traumy i lęki.',
    significantPerson: 'Jej sześcioletnia córka, dla której bardzo mało ma czasu przez nadmiar spraw.',
    meaningfulLocation: 'Pokój do terapii przez zabawę, pełen zabawek i kredek.',
    treasuredPossession: 'Mały, porysowany rysunek "potwora" podarowany przez uratowanego pacjenta.',
    traits: ['Cierpliwa', 'Analityczna', 'Empatyczna'],
    description: 'Spokojny głos, ciepły uśmiech, ubiera się w stonowane barwy, aby nie przerażać dzieci.',
    backstory: 'Jako psycholog dziecięcy pracująca w lubelskich placówkach opieki społecznej, Marta poświęciła życie ratowaniu najmłodszych przed traumą i przemocą domową. Jest osobą twardo stąpającą po ziemi, dla której każde ludzkie zachowanie, nawet najbardziej skrajne, ma źródło w neurobiologii lub środowiskowych ranach. Wszystkie te racjonalne założenia stanęły pod znakiem zapytania, gdy na jej biurko trafiły akta trójki dzieci z Traszyna. Mali pacjenci cierpieli na identyczne ataki paniki nocnej, opisując wspólnie postać bez twarzy stojącą w progu starej stodoły. Największym wstrząsem był dla Marty podarunek od siedmioletniego chłopca, który po miesiącach milczenia narysował istotę o nieludzkich proporcjach, otoczoną geometrycznymi symbolami sprzed wieków. Prowadząc dochodzenie w odciętej od świata wsi, Marta każdego dnia walczy z poczuciem winy wobec własnej córeczki zostawionej pod opieką rodziny w Lublinie. Zawsze spokojna i metodyczna, z notesem pełnym zapisków klinicznych, próbuje znaleźć naukowe wytłumaczenie koszmaru, zanim obłęd pochłonie kolejne dzieci i jej własny, uporządkowany umysł.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonała do "zbierania rozumu" w momentach grozy. Potrafi bezbłędnie ocenić ludzkie emocje.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 80, 'Psychologia': 75, 'Medycyna': 45, 'Perswazja': 60, 'Ukrywanie': 40 },
    equipment: [{ id: 'eq_marta_notebook', name: 'Zeszyt do notatek psychologicznych', category: 'document' }]
  },
  {
    id: 'traszyn_etnografka',
    scenarioIds: ['tajemnica-dzieci-z-traszyna'],
    era: '1990s',
    archetype: 'investigator',
    name: 'Zofia "Zosia" Sadowska',
    occupation: 'Etnograf / Bibliotekarz',
    age: 29,
    gender: 'female',
    portraitUrl: '/portraits/predefined/zofia_sadowska.webp',
    str: 45, dex: 65, con: 55, app: 70, pow: 65, edu: 70, siz: 55, int: 70, luck: 55,
    hp: 11, maxHp: 11, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Pracuje w małej gminnej bibliotece, a hobbystycznie spisuje ludowe legendy i pieśni okolicznych wiosek.',
    birthplace: 'Traszyn, Polska',
    residence: 'Traszyn, Polska',
    characterConcept: 'Wścibska dziewczyna z sąsiedztwa, która wie, kogo na wsi zapytać o stare plotki i legendy.',
    ideology: 'Dawne legendy to przestrogi, których nie wolno lekceważyć.',
    significantPerson: 'Jej starsza ciotka, która znała wszystkie lokalne znachorki.',
    meaningfulLocation: 'Zakurzone, ciemne sekcje archiwum w starej bibliotece.',
    treasuredPossession: 'Prababci oprawiony w skórę śpiewnik z kilkoma bardzo starymi zaklęciami szeptuch.',
    traits: ['Wścibska', 'Towarzyska', 'Przesądna'],
    description: 'Nosi wełniane kardigany i szale. Zawsze jest w centrum lokalnych wydarzeń.',
    backstory: 'Zofia spędziła całe życie w Traszynie, pracując w skromnej gminnej bibliotece i opiekując się schorowaną ciotką, która uchodziła za ostatnią wiejską zielarkę i szeptuchę. Od najmłodszych lat Zosia chłonęła lokalne podania, spisując w grubych zeszytach legendy o utopcach, biesach i zapomnianych mogiłach w okolicznych zagajnikach. Pamięta szepty starszych mieszkańców o tragedii w starej stodole z lat 80., gdy zabawa trójki dzieci zakończyła się śmiercią jednego z nich i głuchym milczeniem pozostałych. Kiedy na polu za wsią znaleziono zbezczeszczony, odwrócony krzyż, a wśród zwierząt gospodarskich wybuchła niewytłumaczalna zaraza, Zosia zrozumiała, że stare przestrogi prababki nie były tylko ludowymi bajkami. Wyposażona w skórzany śpiewnik pełen archaicznych formuł ochronnych i niezrównaną znajomość wiejskich koneksji, Zofia stanowi dla przyjezdnych badaczy jedyny przewodnik po zamkniętej społeczności Traszyna. Za jej dziewczęcym urokiem i ciepłym uśmiechem kryje się jednak nieustanny strach przed zmrokiem i skrzypieniem desek w opuszczonych domostwach.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skupiona na researchu i szukaniu powiązań z mitami. Doskonały zmysł orientacji w plotkach.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Korzystanie z Bibliotek': 75, 'Antropologia': 65, 'Historia': 60, 'Spostrzegawczość': 55, 'Urok osobisty': 60 },
    equipment: [{ id: 'eq_zosia_book', name: 'Zeszyt z legendami i baśniami', category: 'document' }]
  },

  // ==========================================================================
  // 4. PRZYBYSZ Z MATRIKSA: GŁOGÓW
  // ==========================================================================
  {
    id: 'glogow_detektyw',
    scenarioIds: ['przybysz-z-matriksa-glogow'],
    era: '2000s',
    archetype: 'investigator',
    name: 'Artur "Stary" Majchrzak',
    occupation: 'Prywatny Detektyw',
    age: 51,
    gender: 'male',
    portraitUrl: '/portraits/predefined/artur_majchrzak.webp',
    str: 65, dex: 55, con: 70, app: 45, pow: 60, edu: 65, siz: 70, int: 65, luck: 50,
    hp: 14, maxHp: 14, san: 60, maxSan: 99, mp: 12, maxMp: 12,
    background: 'Wyblakły eks-policjant prowadzący biuro detektywistyczne. Zajmuje się głównie szukaniem młodzieży uciekającej po dyskotekach.',
    birthplace: 'Wrocław, Polska',
    residence: 'Głogów, Polska',
    characterConcept: 'Zmęczony życiem glina, który zaczyna wątpić we własne zmysły po dziwnych zaginięciach.',
    ideology: 'Prawda jest często brzydsza, niż jakiekolwiek dziwaczne wytłumaczenia.',
    significantPerson: 'Jego były partner z milicji, który popadł w alkoholizm po sprawie sprzed 10 lat.',
    meaningfulLocation: 'Jego zagracone, pachnące starym tytoniem biuro.',
    treasuredPossession: 'Srebrna piersiówka, zawsze lekko wypełniona.',
    traits: ['Zgorzkniały', 'Cyniczny', 'Twardy'],
    description: 'Pognieciony trencz i głębokie worki pod oczami, wygląda jak relikt innej epoki.',
    backstory: 'Artur to relikt dawno minionej epoki, zgorzkniały eks-milicjant, który po transformacji ustrojowej otworzył jednoosobowe biuro detektywistyczne w dusznej kamienicy w Legnicy. Przez dekady służby na Dolnym Śląsku widział najgorsze przejawy ludzkiej podłości, korupcji i zbrodni. Jego kariera w policji załamała się w 1991 roku po niewyjaśnionej tragedii w głogowskich podziemiach, gdzie wysłany patrol zniknął bez śladu, a jedyny ocalały funkcjonariusz wpadł w nieodwracalny obłęd. Od tamtej pory Artur żyje głównie z poszukiwań zaginionej młodzieży i drobnych spraw rozwodowych, topiąc wspomnienia w srebrnej piersiówce z żytnią i wypalając paczkę papierosów za paczką. Przyjęcie zlecenia odnalezienia chłopaka powiązanego z głogowskimi kafejkami internetowymi miało być prostą robotą za dobre pieniądze. Kiedy jednak na miejscu odnalazł notatki o wielkiej symulacji i ślady po istotach, których kule się nie imają, stary glina musiał odbezpieczyć swojego nielegalnego rewolweru. W pogniecionym trenczu i z papierosem w kąciku ust, Artur staje do ostatniego śledztwa, gotów spojrzeć w twarz prawdzie gorszej niż jakiekolwiek zbrodnie z milicyjnych kartotek.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Skuteczny w przesłuchaniach, szukaniu śladów fizycznych i twardym starciu z bandytami.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Prawo': 50, 'Zastraszanie': 65, 'Broń palna (krótka)': 60, 'Spostrzegawczość': 70, 'Ukrywanie': 55 },
    equipment: [{ id: 'eq_artur_revolver', name: 'Rewolwer kieszonkowy (bez zezwolenia)', category: 'weapon' }, { id: 'eq_artur_flask', name: 'Srebrna piersiówka', category: 'tool' }]
  },
  {
    id: 'glogow_haker',
    scenarioIds: ['przybysz-z-matriksa-glogow'],
    era: '2000s',
    archetype: 'trickster',
    name: 'Piotr "Kabel" Wójcicki',
    occupation: 'Programista / Haker',
    age: 26,
    gender: 'male',
    portraitUrl: '/portraits/predefined/piotr_wojcicki.webp',
    str: 40, dex: 70, con: 50, app: 50, pow: 65, edu: 75, siz: 55, int: 85, luck: 70,
    hp: 10, maxHp: 10, san: 65, maxSan: 99, mp: 13, maxMp: 13,
    background: 'Samouk, który noce spędza na wczesnych forach internetowych BBS. Wierzy, że system, w którym żyjemy, to symulacja.',
    birthplace: 'Legnica, Polska',
    residence: 'Głogów, Polska',
    characterConcept: 'Zafascynowany komputerami paranoik, gotów uwierzyć, że maszyny przejmą kontrolę.',
    ideology: 'Informacja musi być wolna, ale nikt nie jest bezpieczny w sieci.',
    significantPerson: 'Użytkownik o nicku "Oracle", z którym koresponduje od dwóch lat, nie znając go osobiście.',
    meaningfulLocation: 'Piwnica z kilkoma połączonymi w sieć PC-tami na Windowsie 95.',
    treasuredPossession: 'Twardy dysk wypełniony zaszyfrowanymi logami z forów o zjawiskach paranormalnych.',
    traits: ['Paranoiczny', 'Błyskotliwy', 'Introwertyk'],
    description: 'Blady, pije dużo tanich napojów energetycznych. Ubrany w za dużą bluzę z kapturem.',
    backstory: 'Dla Piotra świat zewnętrzny zawsze był zbyt głośny, chaotyczny i pozbawiony logiki. Jako samouk spędził młodość w piwnicach rodzinnego bloku w Legnicy, otoczony starymi monitorami CRT, kablami sieciowymi i szumem modemów dial-up. W świecie forów BBS i kanałów IRC uchodził za legendę podziemnego hackingu, łamiąc zabezpieczenia systemów telekomunikacyjnych i uczelnianych serwerów. Wszystko zmieniło się pamiętnej nocy, gdy w ramach sieciowej przepychanki włamał się na serwer powiązany z głogowską infrastrukturą przemysłową. Zamiast standardowych baz danych przechwycił nieskończony strumień obcych, fraktalnych ciągów znaków, które po zdekodowaniu układały się w logi błędów w fizycznej strukturze otaczającego nas świata. Chwilę później jego tajemniczy rozmówca o nicku Oracle zniknął z sieci, a w mieszkaniu Piotra padło zasilanie. Blady, wiecznie niewyspany i uzależniony od tanich napojów energetycznych, Piotr nie rozstaje się z ciężkim laptopem i zaszyfrowanym dyskiem. Jest święcie przekonany, że Głogów stał się epicentrum usterki w kosmicznym kodzie, a błędy renderowania rzeczywistości wkrótce doprowadzą do całkowitego restartu naszego świata.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Doskonale porusza się po komputerach, technologii, umie ominąć cyfrowe zabezpieczenia.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Korzystanie z Komputerów': 85, 'Elektronika': 60, 'Języki obce (Angielski)': 65, 'Spostrzegawczość': 50, 'Gadanina': 40 },
    equipment: [{ id: 'eq_piotr_laptop', name: 'Ciężki laptop z wczesnym Wi-Fi', category: 'tool' }, { id: 'eq_piotr_cables', name: 'Zestaw narzędzi do elektroniki', category: 'tool' }]
  },
  {
    id: 'glogow_psychiatra',
    scenarioIds: ['przybysz-z-matriksa-glogow'],
    era: '2000s',
    archetype: 'healer',
    name: 'Dr Krystyna Zawada',
    occupation: 'Psychiatra',
    age: 49,
    gender: 'female',
    portraitUrl: '/portraits/predefined/krystyna_zawada.webp',
    str: 40, dex: 50, con: 55, app: 55, pow: 70, edu: 85, siz: 50, int: 80, luck: 55,
    hp: 10, maxHp: 10, san: 70, maxSan: 99, mp: 14, maxMp: 14,
    background: 'Pracuje w szpitalu psychiatrycznym w Legnicy. Spotkała się niedawno z wieloma przypadkami nagłej derealizacji u młodzieży.',
    birthplace: 'Szczecin, Polska',
    residence: 'Legnica, Polska',
    characterConcept: 'Współczująca, lecz zmęczona lekarka, której naukowe fundamenty powoli kruszeją pod naporem niewyjaśnionego.',
    ideology: 'Każdy ból umysłu ma chemiczne podłoże - dopóki nie dowiedzie się, że to wpływ koszmarów z zewnątrz.',
    significantPerson: 'Jej pacjent "Zerowy", który przed zapadnięciem w śpiączkę mówił o "siatce na niebie".',
    meaningfulLocation: 'Sterroryzowany, duszny oddział zamknięty, w którym spędza dnie i noce.',
    treasuredPossession: 'Notes z zapiskami z terapii najbardziej uciążliwych przypadków.',
    traits: ['Spokojna', 'Chłodna', 'Wnikliwa'],
    description: 'Nosi elegancki biały kitel na prostej bluzce, jej postawa sugeruje ogromne zmęczenie stresem.',
    backstory: 'Dr Krystyna Zawada przez niemal trzy dekady kierowała oddziałem zamkniętym szpitala psychiatrycznego w Legnicy. Jako wytrawny klinicysta zawsze uważała, że każdy omam, halucynacja czy urojenie mają swoje twarde podłoże w neurochemii mózgu. Ta niezłomna pewność legła w gruzach jednej nocy przełomu tysiącleci, kiedy na jej oddział przywieziono trójkę zupełnie obcych sobie nastolatków z Głogowa. Młodzi ludzie znajdowali się w stanie głębokiego szoku, powtarzając w transie te same matematyczne sekwencje i mówiąc o gasnącym niebie nad miastem. Co gorsza, na ciele każdego z nich Krystyna odkryła identyczne, geometryczne oparzenia przypominające ślady po układach scalonych. Próby konwencjonalnej terapii zawiodły, a jeden z pacjentów przed zapadnięciem w śpiączkę ostrzegł lekarkę przed nadchodzącym rozpadem materii. Zawsze opanowana, ubrana w nieskazitelny biały kitel i z notesem klinicznym pod pachą, Krystyna postanowiła osobiście udać się do Głogowa. Za jej chłodnym profesjonalizmem kryje się rosnące przerażenie i determinacja, by ocalić swoich pacjentów przed koszmarem wykraczającym poza ramy współczesnej medycyny.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Pierwsza pomoc, stabilizowanie Poczytalności u drużyny, dogłębna psychoanaliza świadków.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Psychoanaliza': 80, 'Medycyna': 75, 'Psychologia': 70, 'Perswazja': 50, 'Nauka (Biologia)': 60 },
    equipment: [{ id: 'eq_krys_medkit', name: 'Zestaw pierwszej pomocy z środkami uspokajającymi', category: 'tool' }]
  },
  {
    id: 'glogow_ufolog',
    scenarioIds: ['przybysz-z-matriksa-glogow'],
    era: '2000s',
    archetype: 'scholar',
    name: 'Karolina "Luna" Maj',
    occupation: 'Ufolog / Badacz anomalii',
    age: 33,
    gender: 'female',
    portraitUrl: '/portraits/predefined/karolina_maj.webp',
    str: 45, dex: 60, con: 60, app: 65, pow: 75, edu: 70, siz: 55, int: 70, luck: 65,
    hp: 11, maxHp: 11, san: 75, maxSan: 99, mp: 15, maxMp: 15,
    background: 'Redaktorka niszowego magazynu "Czwarty Wymiar". Podróżuje po Polsce z wykrywaczami anomalii magnetycznych w poszukiwaniu śladów kosmitów.',
    birthplace: 'Gdynia, Polska',
    residence: 'Nomada (żyje w wozie typu kamper)',
    characterConcept: 'Niezrażona, pełna pasji kobieta wierząca, że rząd ukrywa przed nami istnienie obcych cywilizacji.',
    ideology: 'Zarówno bogowie, jak i demony, to po prostu przybysze z innych gwiazd, których nasz umysł jeszcze nie ogarnia.',
    significantPerson: 'Jej partner, z którym kiedyś prowadzili kanał, dopóki nie zniknął podczas poszukiwań kręgów w zbożu.',
    meaningfulLocation: 'Jej zagracony kamper, obwieszony folią aluminiową i mapami piktogramów.',
    treasuredPossession: 'Nietypowy kryształ rzekomo odnaleziony na miejscu katastrofy pod Wylatowem.',
    traits: ['Egzaltowana', 'Uparta', 'Otwarta'],
    description: 'Nosi hipisowskie ubrania, dużą ilość bransolet i zawsze z kamerą pod ręką.',
    backstory: 'Karolina to niestrudzona poszukiwaczka prawdy o pozaziemskich cywilizacjach i zjawiskach anomalnych w Polsce lat 90. Od czasu tajemniczego zaginięcia jej partnera podczas wyprawy do słynnych kręgów zbożowych pod Wylatowem w 1997 roku, jej domem stał się rozklekotany kamper obwieszony folią aluminiową i mapami piktogramów. Jako niezależna publicystka magazynu Czwarty Wymiar przemierzyła cały kraj z aparatami do zdjęć nocnych i domowej roboty wykrywaczami pól elektromagnetycznych. Kiedy jej sensory zarejestrowały gigantyczne zaburzenia radiacyjne i mikrofale emanujące z opuszczonych korytarzy pod Głogowem, natychmiast skierowała tam swój wóz. Karolina uważa, że to, co dawni ludzie nazywali bogami i demonami, a współcześni biorą za gości z kosmosu, to pradawna inteligencja operująca na wyższych częstotliwościach wszechświata. Uparta, pełna pasji i nieustraszona w obliczu nieznanego, z nieodłączną kamerą w dłoniach, Luna jest gotowa wejść w najgłębsze podziemia, by zdobyć twardy dowód na to, że ludzkość nigdy nie była sama na tej planecie.',
    playerName: '',
    isActive: false,
    lastUsed: new Date(),
    notes: '',
    tacticalNotes: 'Jako badaczka terenowa z dużą MOC-ą jest świetna w operowaniu na styku mitów, okultyzmu i obserwacji.',
    experience: { totalXP: 0, availableXP: 0, earnedThisSession: 0, maxEarnedThisSession: 0 },
    developmentHistory: [],
    skills: { 'Okultyzm': 70, 'Nawigacja': 60, 'Spostrzegawczość': 65, 'Korzystanie z Bibliotek': 50, 'Fotografia': 65 },
    equipment: [{ id: 'eq_luna_camera', name: 'Zestaw do zdjęć nocnych', category: 'tool' }, { id: 'eq_luna_detector', name: 'Wykrywacz pól elektromagnetycznych domowej roboty', category: 'tool' }]
  }
];

export const STREFA_11_CHARACTERS: PredefinedCharacter[] =
  BASE_STREFA_11_CHARACTERS.map((character) => ({
    ...character,
    equipment: character.equipment?.map((item) => ({
      ...item,
      source: 'starting',
      imageUrl: CATEGORY_FALLBACK_ASSETS[item.category],
      visualSource: 'fallback',
    })),
  }));

export function getStrefa11CharactersForAdventure(adventureId: string): PredefinedCharacter[] {
  return STREFA_11_CHARACTERS.filter((character) =>
    character.scenarioIds?.includes(adventureId)
  );
}
