import { NextRequest, NextResponse } from 'next/server';
import { googleCloudStorageService } from '@/lib/google-cloud-storage-service-fixed';
import { resolveUserId } from '@/lib/auth-user';

interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  dateCompleted?: string;
  gameDay?: number;
  gameHour?: number;
}

interface JournalEntry {
  id: string;
  date: string;
  title: string;
  content: string;
  category: string;
  tags: string[];
  isAutoGenerated: boolean;
  sessionId?: string;
  type?: string;
  gameDay?: number;
  gameHour?: number;
  questStatus?: string;
  objectives?: QuestObjective[];
}

interface CloudJournal {
  id: string;
  name: string;
  date: string;
  entries: JournalEntry[];
  userId: string;
  lastUpdated: string;
  version: string;
  size: number;
}

// Generowanie unikalnego ID użytkownika (na podstawie IP i user agent)
function generateUserId(request: NextRequest): string {
  const ip = request.headers.get('x-forwarded-for') || 'unknown';
  const userAgent = request.headers.get('user-agent') || 'unknown';
  const combined = `${ip}-${userAgent}`;

  // Prosta funkcja hash
  let hash = 0;
  for (let i = 0; i < combined.length; i++) {
    const char = combined.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  return `user_${Math.abs(hash)}`;
}

// POST - Zapisywanie dziennika do chmury
export async function POST(request: NextRequest) {
  try {
    const { journalData, journalId, userId } = await request.json();

    if (!journalData) {
      return NextResponse.json(
        { error: 'Journal data is required' },
        { status: 400 }
      );
    }

    const finalUserId = await resolveUserId(userId || generateUserId(request));
    const finalJournalId = journalId || `journal_${Date.now()}`;

    // Przygotowanie danych dziennika
    const cloudJournal: CloudJournal = {
      ...journalData,
      id: finalJournalId,
      userId: finalUserId,
      lastUpdated: new Date().toISOString(),
      version: '1.0',
      size: JSON.stringify(journalData).length,
    };

    // Nazwa pliku w Google Cloud Storage
    const fileName = `journals/${finalUserId}/${finalJournalId}.json`;

    // Upload do Google Cloud Storage
    const url = await googleCloudStorageService.uploadJSON(
      cloudJournal,
      fileName
    );

    return NextResponse.json({
      success: true,
      message: 'Journal saved to cloud successfully',
      journalId: finalJournalId,
      userId: finalUserId,
      url: url,
      size: cloudJournal.size,
      lastUpdated: cloudJournal.lastUpdated,
    });
  } catch (error) {
    console.error('Error saving journal to cloud:', error);

    if (error instanceof Error) {
      if (
        error.message.includes('GOOGLE_CLOUD') ||
        error.message.includes('key') ||
        error.message.includes('credentials')
      ) {
        return NextResponse.json(
          {
            error:
              'Błąd konfiguracji Google Cloud Storage. Skontaktuj się z pomocą techniczną',
            details: 'See IMPLEMENTATION_GUIDE.md for instructions',
          },
          { status: 500 }
        );
      }
    }

    return NextResponse.json(
      {
        error: 'Failed to save journal to cloud',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

// GET - Ładowanie dziennika z chmury
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const userId = searchParams.get('userId');
    const journalId = searchParams.get('journalId');
    const listAll = searchParams.get('listAll') === 'true';
    const test = searchParams.get('test') === 'true';

    // Test endpoint - sprawdź czy API jest dostępne
    if (test) {
      return NextResponse.json({
        status: 'available',
        message: 'Journal API is configured and ready',
      });
    }

    const finalUserId = await resolveUserId(userId || generateUserId(request));

    if (listAll) {
      // Lista wszystkich dzienników użytkownika
      return await listUserJournals(finalUserId);
    } else if (journalId) {
      // Pojedynczy dziennik
      return await getSingleJournal(finalUserId, journalId);
    } else {
      // Domyślnie zwróć najnowszy dziennik użytkownika
      return await getLatestJournal(finalUserId);
    }
  } catch (error) {
    console.error('Error loading journal from cloud:', error);
    return NextResponse.json(
      {
        error: 'Failed to load journal from cloud',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

// PUT - Aktualizacja dziennika
export async function PUT(request: NextRequest) {
  try {
    const { journalData, journalId, userId } = await request.json();

    if (!journalData || !journalId) {
      return NextResponse.json(
        { error: 'Journal data and journalId are required' },
        { status: 400 }
      );
    }

    const finalUserId = await resolveUserId(userId || generateUserId(request));

    // Przygotowanie danych dziennika
    const cloudJournal: CloudJournal = {
      ...journalData,
      id: journalId,
      userId: finalUserId,
      lastUpdated: new Date().toISOString(),
      version: '1.0',
      size: JSON.stringify(journalData).length,
    };

    // Nazwa pliku w Google Cloud Storage
    const fileName = `journals/${finalUserId}/${journalId}.json`;

    // Upload do Google Cloud Storage (nadpisuje istniejący)
    const url = await googleCloudStorageService.uploadJSON(
      cloudJournal,
      fileName
    );

    return NextResponse.json({
      success: true,
      message: 'Journal updated successfully',
      journalId,
      userId: finalUserId,
      url: url,
      size: cloudJournal.size,
      lastUpdated: cloudJournal.lastUpdated,
    });
  } catch (error) {
    console.error('Error updating journal:', error);
    return NextResponse.json(
      {
        error: 'Failed to update journal',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

// DELETE - Usuwanie dziennika z chmury
export async function DELETE(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    const { journalId, userId } = body;

    if (!journalId) {
      // Jeśli brak ID, uznajemy to za prośbę o wyczyszczenie (lub sukces bez akcji)
      // W przypadku GCS nie chcemy usuwać wszystkiego bez potwierdzenia, ale
      // zwrócenie sukcesu uciszy błędy na froncie.
      return NextResponse.json({
        success: true,
        message: 'Journal clear requested (no specific ID provided)',
      });
    }

    const finalUserId = await resolveUserId(userId || generateUserId(request));
    const fileName = `journals/${finalUserId}/${journalId}.json`;

    // Usunięcie z Google Cloud Storage
    await googleCloudStorageService.deleteFile(fileName);

    return NextResponse.json({
      success: true,
      message: 'Journal deleted from cloud successfully',
      journalId,
    });
  } catch (error) {
    console.error('Error deleting journal from cloud:', error);
    return NextResponse.json(
      {
        error: 'Failed to delete journal from cloud',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

// Funkcje pomocnicze
async function listUserJournals(userId: string) {
  try {
    const files = await googleCloudStorageService.listFiles(
      `journals/${userId}/`
    );

    const journals = await Promise.all(
      files.map(async (file) => {
        try {
          const buffer = await googleCloudStorageService.downloadFile(
            file.name
          );
          const journalData = JSON.parse(buffer.toString());
          return {
            id: journalData.id,
            name: journalData.name,
            date: journalData.date,
            lastUpdated: journalData.lastUpdated,
            size: journalData.size,
            entriesCount: journalData.entries?.length || 0,
            url: file.publicUrl,
          };
        } catch (error) {
          console.error(`Error loading journal ${file.name}:`, error);
          return null;
        }
      })
    );

    const validJournals = journals.filter((journal) => journal !== null);

    return NextResponse.json({
      success: true,
      journals: validJournals,
      totalCount: validJournals.length,
      userId,
    });
  } catch (error) {
    console.error('Error listing user journals:', error);
    return NextResponse.json(
      { error: 'Failed to list journals' },
      { status: 500 }
    );
  }
}

async function getSingleJournal(userId: string, journalId: string) {
  try {
    const fileName = `journals/${userId}/${journalId}.json`;

    try {
      const buffer = await googleCloudStorageService.downloadFile(fileName);
      const journalData = JSON.parse(buffer.toString());

      return NextResponse.json({
        success: true,
        journal: journalData,
        url: `https://storage.googleapis.com/${process.env.GOOGLE_CLOUD_STORAGE_BUCKET}/${fileName}`,
      });
    } catch {
      return NextResponse.json({ error: 'Journal not found' }, { status: 404 });
    }
  } catch (error) {
    console.error('Error getting single journal:', error);
    return NextResponse.json(
      { error: 'Failed to get journal' },
      { status: 500 }
    );
  }
}

async function getLatestJournal(userId: string) {
  try {
    const files = await googleCloudStorageService.listFiles(
      `journals/${userId}/`
    );

    if (files.length === 0) {
      // Jeśli nie ma dzienników, zwróć pusty dziennik
      return NextResponse.json({
        success: true,
        journal: {
          id: `journal_${Date.now()}`,
          name: 'Mój Dziennik',
          date: new Date().toISOString(),
          entries: [],
          userId,
          lastUpdated: new Date().toISOString(),
          version: '1.0',
          size: 0,
        },
        isNew: true,
      });
    }

    // Znajdź najnowszy dziennik
    const latestFile = files.reduce((latest, current) => {
      return new Date(current.updated) > new Date(latest.updated)
        ? current
        : latest;
    });

    const buffer = await googleCloudStorageService.downloadFile(
      latestFile.name
    );
    const journalData = JSON.parse(buffer.toString());

    return NextResponse.json({
      success: true,
      journal: journalData,
      url: latestFile.publicUrl,
    });
  } catch (error) {
    console.error('Error getting latest journal:', error);
    return NextResponse.json(
      { error: 'Failed to get latest journal' },
      { status: 500 }
    );
  }
}
